## Funding analysis (2020-2025)

Computes the standard breakdowns needed for reporting, exported as CSVs sized to paste directly
into the existing Google Sheets template (`raw_data/Funding analysis 2026.xlsx`, 'Europe wide'
tab) - keeps chart formatting consistent with prior reports while the underlying numbers are
computed in code.

Methodology confirmed against that template rather than assumed:
- Funding figure throughout = `'Gov & NP contribution (EUR)'`.
- Excludes any grant whose `'Award purpose'` is *exactly* `'Equipment and infrastructure'` (not
  combined with anything else).
- "Country" = `'Funder Country'` (whose money it is), not `'PI organisation country'`.
- Multi-value cells (countries, pillars, end products) split the grant's funding evenly across
  the **distinct** values listed.
- Growth rate = simple year-over-year % change.
- Population/GDP from the World Bank, R&D spend from OECD - fetched live (see
  `Funding_analysis_helpers.py`).

In [48]:
import re
from pathlib import Path

import numpy as np
import pandas as pd

from Funding_analysis_helpers import (
    split_multi_value, fetch_worldbank_indicator, fetch_oecd_gerd, fetch_usd_to_eur_rate,
    lookup_country_value, COUNTRY_NAME_TO_OECD, yoy_growth, YEAR_COLS, COI
)

FINAL_FILE = Path('data_output/20260930_funding_data_cleaned.csv')
OUTPUT_DIR = Path('data_output/analysis')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FUNDING_COL = 'Gov & NP contribution (EUR)'
YEAR_COL_STRS = [str(y) for y in YEAR_COLS]
ALL_TIME_YEARS = [str(y) for y in range(2020, 2026)]  # 2020-2025, matching the template's "All time" window

# Tied to FINAL_FILE's own run-timestamp prefix, not "now" - change FINAL_FILE above to analyze a
# different run and this follows automatically. Reruns of this notebook overwrite the same CSVs
# instead of piling up a fresh timestamped copy every time.
#RUN_TIMESTAMP = re.match(r'(\d{6}_\d{4})', FINAL_FILE.name).group(1)


def save(df_or_series, name, **to_csv_kwargs):
    path = OUTPUT_DIR / f'{name}.csv'
    df_or_series.to_csv(path, **to_csv_kwargs)
    print(f"Saved {name} -> {path}")

### Load and filter

Loads the curated dataset and applies the pipeline-wide filtering rules below - every analysis in
this notebook operates on the filtered `df`, not the raw `FINAL_FILE` export directly. Three filters:

1. Drop grants whose `'Award purpose'` is *only* `'Equipment and infrastructure'`.
2. Drop grants whose `'Funding decision'` is not `'Awarded'` (pledged, not yet decided, unfunded, or blank).
3. Drop grants whose `'Year project started'` is outside 2020-2025 - the reporting window every
   analysis below is labelled with.

In [49]:
df = pd.read_csv(FINAL_FILE)
print(f"Loaded {len(df)} rows from '{FINAL_FILE.name}'.")

# Filter 1: exclude grants whose Award purpose is ONLY 'Equipment and infrastructure' - a grant
# combining it with something else (e.g. 'Research and development; Equipment and infrastructure')
# stays in. Confirmed against the colleagues' own 'Europe wide' template, which applies the same rule.
award_purpose_mask = df['Award purpose'].astype(str).str.strip() == 'Equipment and infrastructure'
df = df[~award_purpose_mask].reset_index(drop=True)
print(f"Excluded {award_purpose_mask.sum()} grants whose Award purpose is ONLY 'Equipment and infrastructure'.")

# Filter 2: keep ONLY grants whose Funding decision is 'Awarded' - money that's been pledged
# ('Committed'), not yet decided ('No decision yet'), turned down ('Unfunded'), or simply unknown
# (blank) shouldn't count in a funding-received analysis. Switched from excluding just 'Committed'
# to this whitelist since several blank/'Unfunded'/'No decision yet' grants turned out to carry
# real funding amounts too (~€15M combined) - not just Committed. This also still removes the
# €162.5M Danish government commitment the colleagues' template excludes from every total
# (confirmed its own Funding decision is 'Committed').
awarded_mask = df['Funding decision'].astype(str).str.strip() == 'Awarded'
df = df[awarded_mask].reset_index(drop=True)
print(f"Excluded {(~awarded_mask).sum()} grants whose Funding decision is not 'Awarded' "
      f"(Committed/Unfunded/No decision yet/blank).")

# Filter 3: restrict to the 2020-2025 reporting window. Applied here, once, rather than at each
# aggregation - previously only SOME cells filtered on year, so grants outside the window leaked
# into totals whose titles said "2020-2025" (1c, 3a, 3b, 4, 4b, 7 and 9). Doing it globally is
# what keeps every analysis in this notebook comparable to every other.
# Two consequences worth knowing:
#  - 1b (funding by FUNDING year) still spreads over 2020-2035, but now only for grants that
#    STARTED in the window. That's the intended reading: "grants started 2020-2025, paid out over time".
#  - Analysis 5's 'Total' column is now window-scoped too (see the note in that cell).
# .between() also drops blank years; there are currently none, so the count below is the whole story.
year_mask = df['Year project started'].between(2020, 2025)
df = df[year_mask].reset_index(drop=True)
print(f"Excluded {(~year_mask).sum()} grants whose start year falls outside 2020-2025.")

# Curation correction: 3 European Commission grants carry Funder Country 'Belgium' (the EC's seat in
# Brussels) instead of 'EU'. Uncorrected they put EUR 12,245,242 of EU-level money into Belgium's
# total - 77% of Belgium's entire figure - and make the by-funder-name and by-country views of EU
# funding disagree by that amount (464.5M vs 452.8M). Funder region is already 'Europe' on all three,
# so only the country needs changing. Targeted on purpose: it only fires on rows that are exactly
# 'European Commission' + 'Belgium', so it becomes a no-op once the source data is fixed.
_ec_belgium = ((df['Funder name'].astype(str).str.strip() == 'European Commission') &
               (df['Funder Country'].astype(str).str.strip() == 'Belgium'))
if _ec_belgium.any():
    print(f"Recoded {_ec_belgium.sum()} European Commission grants from Funder Country 'Belgium' to "
          f"'EU' (EUR {df.loc[_ec_belgium, FUNDING_COL].sum():,.0f}).")
    df.loc[_ec_belgium, 'Funder Country'] = 'EU'

print(f"{len(df)} grants remain for analysis.")

Loaded 2520 rows from '20260930_funding_data_cleaned.csv'.
Excluded 27 grants whose Award purpose is ONLY 'Equipment and infrastructure'.
Excluded 33 grants whose Funding decision is not 'Awarded' (Committed/Unfunded/No decision yet/blank).
Excluded 4 grants whose start year falls outside 2020-2025.
2456 grants remain for analysis.

In [50]:
# Excluding grants from non-profit/NGO funders.
# NOTE: distinct variable names (*_np) on purpose
NON_PROFIT_FUNDER_TYPES = {'nonprofit', 'ngo'}  # matched after lowercasing and stripping -/spaces

funder_type_norm = (df['Funder type'].astype(str)
                    .str.strip().str.lower()
                    .str.replace(r'[-\s]', '', regex=True))
non_profit_mask = funder_type_norm.isin(NON_PROFIT_FUNDER_TYPES)

df_np = df[~non_profit_mask].reset_index(drop=True)
print(f"Excluded {non_profit_mask.sum()} grants with a non-profit/NGO Funder type "
      f"(EUR {df.loc[non_profit_mask, FUNDING_COL].sum():,.0f}). {len(df_np)} grants remain.")

Excluded 213 grants with a non-profit/NGO Funder type (EUR 248,673,492). 2243 grants remain.

### 1. Total funding by start year, and by funding year

In [51]:
by_start_year = df[df['Year project started'].between(2020, 2025)].groupby('Year project started')[FUNDING_COL].sum()
by_start_year.index = by_start_year.index.astype(int)
by_start_year.name = 'Total funding (EUR)'
save(by_start_year, '1a_funding_by_start_year')
print(by_start_year)

by_funding_year = df[YEAR_COL_STRS].sum()
by_funding_year.name = 'Total funding (EUR)'
save(by_funding_year, '1b_funding_by_funding_year')
print()
print(by_funding_year)

Saved 1a_funding_by_start_year -> data_output\analysis\1a_funding_by_start_year.csv
Year project started
2020    1.351691e+08
2021    2.385229e+08
2022    3.021175e+08
2023    4.415752e+08
2024    5.314605e+08
2025    3.116437e+08
Name: Total funding (EUR), dtype: float64
Saved 1b_funding_by_funding_year -> data_output\analysis\1b_funding_by_funding_year.csv

2020    900000750000700000535302.53395647.333311476701...
2021    11170801038142.857480240649371.93751040170.261...
2022    4333333.33311170801038142.857480240649371.9375...
2023    4333333.3334333333.33311170801038142.857480240...
2024    4333333.3334333333.33311170801038142.857317360...
2025                                     342240823.437231
2026    4333333.3331038142.8573173601.4835000001829938...
2027                                     177413772.414257
2028    3173601.481829938.714202136.22722505923.618138...
2029                                      69382592.663147
2030                                      18348727.346157
2031                                        12172753.1108
2032                                          5454545.455
2033                                          5454545.455
2034
2035                                                  0.0
Name: Total funding (EUR), dtype: object

### 1c. Total funding by region (2020-2025), plus an EU / EU+ / Europe comparison

The second table isn't a partition like the first - EU and EU+ are subsets of Europe, so their
totals are nested (EU <= EU+ <= Europe), not additive alongside the other regions.

In [52]:
from Funding_analysis_helpers import europe_tier_split

# Uses the Totals column directly (not the 2020-2035 per-year split) - many grants lack enough
# public info to know their duration, which would otherwise silently drop them from a "total".
region_split = split_multi_value(df, 'Funder region', delimiter=',')
region_split['weighted_funding'] = region_split[FUNDING_COL] * region_split['_weight']
by_region = region_split.groupby('Funder region_split')['weighted_funding'].sum().sort_values(ascending=False)
by_region.name = 'Total funding (2020-2025, EUR)'
save(by_region, '1c_funding_by_region')
print(by_region)

tier_split = europe_tier_split(df)
tier_split['weighted_funding'] = tier_split[FUNDING_COL] * tier_split['_weight']
by_tier = tier_split.groupby('_tiers')['weighted_funding'].sum().reindex(['EU', 'EU+', 'Europe'])
by_tier.name = 'Total funding (2020-2025, EUR)'
save(by_tier, '1c_funding_by_eu_tier')
print()
print(by_tier)

Saved 1c_funding_by_region -> data_output\analysis\1c_funding_by_region.csv
Funder region_split
Europe               1.272965e+09
North America        3.721569e+08
Asia/Asia Pacific    2.813736e+08
Middle East          2.745611e+07
Global               3.338193e+06
South America        2.639045e+06
Africa               5.599000e+05
Name: Total funding (2020-2025, EUR), dtype: float64
Saved 1c_funding_by_eu_tier -> data_output\analysis\1c_funding_by_eu_tier.csv

_tiers
EU        1.038998e+09
EU+       1.272815e+09
Europe    1.272965e+09
Name: Total funding (2020-2025, EUR), dtype: float64

### 2. Total funding by year x AP pillar, plus growth rates

In [53]:
# By START year (2020-2025), not the calculated per-year split stretching out to 2035 - each
# grant's full funding figure counts entirely toward the year it started, matching analysis 1a's
# methodology exactly but split by AP pillar.
by_start_year_pillar = df[df['Year project started'].between(2020, 2025)].pivot_table(
    index='AP pillar', columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
by_start_year_pillar.columns = by_start_year_pillar.columns.astype(int)
by_start_year_pillar = by_start_year_pillar[sorted(by_start_year_pillar.columns)]
by_start_year_pillar.loc['Total'] = by_start_year_pillar.sum()
save(by_start_year_pillar, '2a_funding_by_year_and_pillar')
print(by_start_year_pillar)

# YoY growth rate (matches the template's own formula: (year_N - year_N-1) / year_N-1)
growth_rates = by_start_year_pillar.apply(yoy_growth, axis=1)
growth_rates['Average growth rate (2021-2025)'] = growth_rates.iloc[:, 1:].mean(axis=1)
save(growth_rates, '2b_growth_rates_by_pillar')
print()
print(growth_rates)

Saved 2a_funding_by_year_and_pillar -> data_output\analysis\2a_funding_by_year_and_pillar.csv
Year project started          2020          2021          2022          2023  \
AP pillar
Cross-cutting         1.082863e+07  5.153889e+07  5.808985e+07  9.767319e+07
Cultivated            1.646469e+07  4.050796e+07  4.915279e+07  6.472893e+07
Fermentation          2.175219e+07  4.266925e+07  4.716501e+07  1.166055e+08
Plant-based           8.612357e+07  1.038068e+08  1.477098e+08  1.625676e+08
Total                 1.351691e+08  2.385229e+08  3.021175e+08  4.415752e+08

Year project started          2024          2025
AP pillar
Cross-cutting         1.731158e+08  3.267131e+07
Cultivated            7.069326e+07  2.978128e+07
Fermentation          1.665243e+08  1.456873e+08
Plant-based           1.211271e+08  1.035038e+08
Total                 5.314605e+08  3.116437e+08
Saved 2b_growth_rates_by_pillar -> data_output\analysis\2b_growth_rates_by_pillar.csv

Year project started  2020      2021      2022      2023      2024      2025  \
AP pillar
Cross-cutting          NaN  3.759503  0.127107  0.681416  0.772399 -0.811275
Cultivated             NaN  1.460292  0.213411  0.316892  0.092143 -0.578725
Fermentation           NaN  0.961607  0.105363  1.472288  0.428100 -0.125129
Plant-based            NaN  0.205324  0.422930  0.100587 -0.254912 -0.145495
Total                  NaN  0.764626  0.266618  0.461601  0.203556 -0.413609

Year project started  Average growth rate (2021-2025)
AP pillar
Cross-cutting                                0.905830
Cultivated                                   0.300803
Fermentation                                 0.568446
Plant-based                                  0.065687
Total                                        0.256559

### 2c/2d. Funding by year x region, and by EU / EU+ / Europe, with growth rates

In [54]:
# By START year (2020-2025), not the funding-year spread - matches 1a/2a's methodology,
# split by region. 1b is the one deliberate exception that stays funding-year-based.
by_year_region = region_split[region_split['Year project started'].between(2020, 2025)].pivot_table(
    index='Funder region_split', columns='Year project started', values='weighted_funding', aggfunc='sum', fill_value=0
)
by_year_region.columns = by_year_region.columns.astype(int)
by_year_region = by_year_region[sorted(by_year_region.columns)]
by_year_region.loc['Total'] = by_year_region.sum()
save(by_year_region, '2c_funding_by_year_and_region')
print(by_year_region)

growth_region = by_year_region.apply(yoy_growth, axis=1)
growth_region['Average growth rate (2021-2025)'] = growth_region.iloc[:, 1:].mean(axis=1)
save(growth_region, '2d_growth_rates_by_region')
print()
print(growth_region)

Saved 2c_funding_by_year_and_region -> data_output\analysis\2c_funding_by_year_and_region.csv
Year project started          2020          2021          2022          2023  \
Funder region_split
Africa                0.000000e+00  0.000000e+00  0.000000e+00  5.599000e+05
Asia/Asia Pacific     1.304494e+07  7.278290e+07  3.753042e+07  2.870742e+07
Europe                8.792323e+07  1.213803e+08  2.083944e+08  3.395904e+08
Global                1.309406e+06  6.024936e+05  8.956450e+05  5.306482e+05
Middle East           0.000000e+00  8.149300e+06  1.666206e+07  2.271742e+06
North America         3.288723e+07  3.559801e+07  3.859720e+07  6.821811e+07
South America         4.269000e+03  9.929000e+03  3.773600e+04  1.696999e+06
Total                 1.351691e+08  2.385229e+08  3.021175e+08  4.415752e+08

Year project started          2024          2025
Funder region_split
Africa                0.000000e+00  0.000000e+00
Asia/Asia Pacific     7.861785e+07  5.069005e+07
Europe                2.892173e+08  2.264595e+08
Global                0.000000e+00  0.000000e+00
Middle East           0.000000e+00  3.730060e+05
North America         1.633679e+08  3.348845e+07
South America         2.574205e+05  6.326920e+05
Total                 5.314605e+08  3.116437e+08
Saved 2d_growth_rates_by_region -> data_output\analysis\2d_growth_rates_by_region.csv

Year project started  2020      2021      2022       2023      2024      2025  \
Funder region_split
Africa                 NaN       NaN       NaN        inf -1.000000       NaN
Asia/Asia Pacific      NaN  4.579395 -0.484351  -0.235089  1.738590 -0.355235
Europe                 NaN  0.380526  0.716872   0.629556 -0.148335 -0.216992
Global                 NaN -0.539873  0.486564  -0.407524 -1.000000       NaN
Middle East            NaN       inf  1.044600  -0.863658 -1.000000       inf
North America          NaN  0.082426  0.084252   0.767437  1.394788 -0.795012
South America          NaN  1.325837  2.800584  43.970283 -0.848308  1.457815
Total                  NaN  0.764626  0.266618   0.461601  0.203556 -0.413609

Year project started  Average growth rate (2021-2025)
Funder region_split
Africa                                            inf
Asia/Asia Pacific                            1.048662
Europe                                       0.272325
Global                                      -0.365208
Middle East                                       inf
North America                                0.306778
South America                                9.741242
Total                                        0.256559

In [55]:
by_year_tier = tier_split[tier_split['Year project started'].between(2020, 2025)].pivot_table(
    index='_tiers', columns='Year project started', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
by_year_tier.columns = by_year_tier.columns.astype(int)
by_year_tier = by_year_tier[sorted(by_year_tier.columns)]
save(by_year_tier, '2c_funding_by_year_and_eu_tier')
print(by_year_tier)

growth_tier = by_year_tier.apply(yoy_growth, axis=1)
growth_tier['Average growth rate (2021-2025)'] = growth_tier.iloc[:, 1:].mean(axis=1)
save(growth_tier, '2d_growth_rates_by_eu_tier')
print()
print(growth_tier)

Saved 2c_funding_by_year_and_eu_tier -> data_output\analysis\2c_funding_by_year_and_eu_tier.csv
Year project started          2020          2021          2022          2023  \
_tiers
EU                    7.272313e+07  7.502605e+07  1.842130e+08  2.814545e+08
EU+                   8.792323e+07  1.213803e+08  2.083944e+08  3.394404e+08
Europe                8.792323e+07  1.213803e+08  2.083944e+08  3.395904e+08

Year project started          2024          2025
_tiers
EU                    2.199877e+08  2.055937e+08
EU+                   2.892173e+08  2.264595e+08
Europe                2.892173e+08  2.264595e+08
Saved 2d_growth_rates_by_eu_tier -> data_output\analysis\2d_growth_rates_by_eu_tier.csv

Year project started  2020      2021      2022      2023      2024      2025  \
_tiers
EU                     NaN  0.031667  1.455320  0.527876 -0.218390 -0.065431
EU+                    NaN  0.380526  0.716872  0.628836 -0.147958 -0.216992
Europe                 NaN  0.380526  0.716872  0.629556 -0.148335 -0.216992

Year project started  Average growth rate (2021-2025)
_tiers
EU                                           0.346208
EU+                                          0.272257
Europe                                       0.272325

### 3a. Total funding by country (2020-2025), with per-capita/GDP/R&D-spend

Fetches World Bank population/GDP and OECD R&D spend live, plus a live USD->EUR rate (Frankfurter)
to convert them - reused by analyses 4 and 8 below, so this cell's variables stay in scope.

In [56]:
# No year filter needed here - `df` is already restricted to 2020-2025 by Filter 3 in the load
# cell. `country_split` is reused by analyses 4, 6 and 9 below, so it inherits that window too.
country_split = split_multi_value(df, 'Funder Country', delimiter=',')
country_split['weighted_funding'] = country_split[FUNDING_COL] * country_split['_weight']

by_country = country_split.groupby('Funder Country_split')['weighted_funding'].sum().sort_values(ascending=False)
by_country.name = 'Total funding (2020-2025, EUR)'

print("Fetching World Bank population/GDP, OECD R&D spend, and a USD->EUR rate...")
POP_GDP_YEAR = 2023  # most recent year with broad World Bank/OECD coverage
pop = fetch_worldbank_indicator('SP.POP.TOTL', POP_GDP_YEAR)
gdp_usd = fetch_worldbank_indicator('NY.GDP.MKTP.CD', POP_GDP_YEAR)
gerd_usd = fetch_oecd_gerd(POP_GDP_YEAR)
usd_to_eur = fetch_usd_to_eur_rate(f'{POP_GDP_YEAR}-12-29')
print(f"USD->EUR rate ({POP_GDP_YEAR}-12-29): {usd_to_eur}")

by_country_df = by_country.reset_index().rename(columns={'Funder Country_split': 'Country'})
by_country_df['Population'] = by_country_df['Country'].apply(lambda c: lookup_country_value(c, pop))
by_country_df['GDP (EUR)'] = by_country_df['Country'].apply(lambda c: lookup_country_value(c, gdp_usd)) * usd_to_eur
by_country_df['R&D spend (EUR)'] = by_country_df['Country'].apply(
    lambda c: lookup_country_value(c, gerd_usd, COUNTRY_NAME_TO_OECD)
) * usd_to_eur
by_country_df['Funding per capita'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['Population']
by_country_df['Funding per GDP'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['GDP (EUR)']
by_country_df['GDP per capita'] = by_country_df['GDP (EUR)'] / by_country_df['Population']
by_country_df['Funding per R&D spend'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['R&D spend (EUR)']

n_no_population = by_country_df['Population'].isna().sum()
print(f"{n_no_population} entries have no population match (expected for non-country entities like 'EU'/'Global').")

save(by_country_df, '3a_funding_by_country', index=False)
print(by_country_df.head(15).to_string())

Fetching World Bank population/GDP, OECD R&D spend, and a USD->EUR rate...

c:\Users\Viola Hollek\Documents\SHEEP_Pipeline\Funding\Funding_analysis_helpers.py:150: DtypeWarning: Columns (0: OBS_STATUS, 1: Observation status, 2: OBS_STATUS_2, 3: Observation status 2, 4: OBS_STATUS_3, 5: Observation status 3, 6: AUX_OBS_STATUS, 7: Aux observation status, 8: CONF_STATUS, 9: Confidentiality status) have mixed types. Specify dtype option on import or set low_memory=False.
  raw = pd.read_csv(io.StringIO(text))

USD->EUR rate (2023-12-29): 0.90498
2 entries have no population match (expected for non-country entities like 'EU'/'Global').
Saved 3a_funding_by_country -> data_output\analysis\3a_funding_by_country.csv
           Country  Total funding (2020-2025, EUR)   Population     GDP (EUR)  R&D spend (EUR)  Funding per capita  Funding per GDP  GDP per capita  Funding per R&D spend
0               EU                    4.544506e+08          NaN           NaN              NaN                 NaN              NaN             NaN                    NaN
1    United States                    3.093985e+08  336755052.0  2.516887e+13     8.616450e+11            0.918764         0.000012    74739.388482               0.000359
2          Denmark                    1.642351e+08    5946952.0  3.662017e+11     1.277912e+10           27.616682         0.000448    61578.048890               0.012852
3   United Kingdom                    1.495972e+08   68526000.0  3.095753e+12     1.037927e+11            2.183072         0.000048    45176.320750               0.001441
4      South Korea                    1.411758e+08   51712619.0  1.669508e+12     1.328646e+11            2.730007         0.000085    32284.343394               0.001063
5      Netherlands                    9.488457e+07   17877117.0  1.027583e+12     2.997770e+10            5.307599         0.000092    57480.350474               0.003165
6        Singapore                    8.313929e+07    5917648.0  4.626093e+11     1.559697e+10           14.049381         0.000180    78174.516343               0.005330
7          Germany                    8.197689e+07   83287273.0  4.128707e+12     1.704072e+11            0.984267         0.000020    49571.878440               0.000481
8          Finland                    7.776410e+07    5583911.0  2.671426e+11     9.914299e+09           13.926457         0.000291    47841.490014               0.007844
9           Canada                    6.275840e+07   40049088.0  1.987873e+12     4.557030e+10            1.567037         0.000032    49635.924044               0.001377
10          Norway                    5.935346e+07    5519601.0  4.544788e+11     9.584503e+09           10.753216         0.000131    82339.070198               0.006193
11          Sweden                    5.073370e+07   10536632.0  5.239752e+11     2.376228e+10            4.814982         0.000097    49728.907537               0.002135
12           Spain                    3.512625e+07   48352528.0  1.465599e+12     3.639257e+10            0.726461         0.000024    30310.696535               0.000965
13          France                    3.326737e+07   68372286.0  2.765846e+12     8.200142e+10            0.486562         0.000012    40452.731265               0.000406
14     New Zealand                    2.800436e+07    5200000.0  2.320117e+11     3.985797e+09            5.385454         0.000121    44617.633351               0.007026

### 3b. Total funding by country (2020-2025) excl. non-profit funding, with per-capita/GDP/R&D-spend

Same breakdown as 3a with grants from non-profit/NGO funders removed, i.e. `'Funder type'` not in
`'Non-profit'` / `'Nonprofit'` / `'NGO'`. Compared case/hyphen/whitespace-insensitively because the
curated data carries both `'Non-profit'` and `'Nonprofit'` as separate labels for the same thing.

`'Non-profit/Gov'` (4 grants) is deliberately **kept** - mixed public/non-profit funders count as
partly governmental. `'For profit'`, `'Research Institute'`, `'Joint public/private partnership'`,
`'Unknown'` and blank Funder types are also kept; this filter only removes purely non-profit/NGO money.

In [57]:
# Same breakdown as 3a, but excluding grants from non-profit/NGO funders using the dataframe df_np

country_split_np = split_multi_value(df_np, 'Funder Country', delimiter=',')
country_split_np['weighted_funding'] = country_split_np[FUNDING_COL] * country_split_np['_weight']

by_country_np = (country_split_np.groupby('Funder Country_split')['weighted_funding']
                 .sum().sort_values(ascending=False))
# Same column header as 3a so this CSV pastes into the same template columns.
by_country_np.name = 'Total funding (2020-2025, EUR)'

# pop / gdp_usd / gerd_usd / usd_to_eur were fetched in 3a and are still in scope - deliberately
# not refetched here (4 extra network round-trips that can fail). Run 3a before 3b.
by_country_np_df = by_country_np.reset_index().rename(columns={'Funder Country_split': 'Country'})
by_country_np_df['Population'] = by_country_np_df['Country'].apply(lambda c: lookup_country_value(c, pop))
by_country_np_df['GDP (EUR)'] = by_country_np_df['Country'].apply(lambda c: lookup_country_value(c, gdp_usd)) * usd_to_eur
by_country_np_df['R&D spend (EUR)'] = by_country_np_df['Country'].apply(
    lambda c: lookup_country_value(c, gerd_usd, COUNTRY_NAME_TO_OECD)
) * usd_to_eur
by_country_np_df['Funding per capita'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['Population']
by_country_np_df['Funding per GDP'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['GDP (EUR)']
by_country_np_df['GDP per capita'] = by_country_np_df['GDP (EUR)'] / by_country_np_df['Population']
by_country_np_df['Funding per R&D spend'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['R&D spend (EUR)']

n_no_population = by_country_np_df['Population'].isna().sum()
print(f"{n_no_population} entries have no population match (expected for non-country entities like 'EU'/'Global').")

save(by_country_np_df, '3b_funding_by_country_excl_nonprofit', index=False)
print(by_country_np_df.head(15).to_string())

1 entries have no population match (expected for non-country entities like 'EU'/'Global').
Saved 3b_funding_by_country_excl_nonprofit -> data_output\analysis\3b_funding_by_country_excl_nonprofit.csv
           Country  Total funding (2020-2025, EUR)   Population     GDP (EUR)  R&D spend (EUR)  Funding per capita  Funding per GDP  GDP per capita  Funding per R&D spend
0               EU                    4.544506e+08          NaN           NaN              NaN                 NaN              NaN             NaN                    NaN
1    United States                    1.910789e+08  336755052.0  2.516887e+13     8.616450e+11            0.567412         0.000008    74739.388482               0.000222
2   United Kingdom                    1.480611e+08   68526000.0  3.095753e+12     1.037927e+11            2.160656         0.000048    45176.320750               0.001427
3      South Korea                    1.411758e+08   51712619.0  1.669508e+12     1.328646e+11            2.730007         0.000085    32284.343394               0.001063
4      Netherlands                    9.488457e+07   17877117.0  1.027583e+12     2.997770e+10            5.307599         0.000092    57480.350474               0.003165
5        Singapore                    8.313929e+07    5917648.0  4.626093e+11     1.559697e+10           14.049381         0.000180    78174.516343               0.005330
6          Germany                    8.197689e+07   83287273.0  4.128707e+12     1.704072e+11            0.984267         0.000020    49571.878440               0.000481
7          Finland                    7.770410e+07    5583911.0  2.671426e+11     9.914299e+09           13.915712         0.000291    47841.490014               0.007838
8           Norway                    5.935346e+07    5519601.0  4.544788e+11     9.584503e+09           10.753216         0.000131    82339.070198               0.006193
9           Canada                    5.929110e+07   40049088.0  1.987873e+12     4.557030e+10            1.480461         0.000030    49635.924044               0.001301
10          Sweden                    5.073370e+07   10536632.0  5.239752e+11     2.376228e+10            4.814982         0.000097    49728.907537               0.002135
11         Denmark                    4.353424e+07    5946952.0  3.662017e+11     1.277912e+10            7.320429         0.000119    61578.048890               0.003407
12           Spain                    3.512625e+07   48352528.0  1.465599e+12     3.639257e+10            0.726461         0.000024    30310.696535               0.000965
13          France                    3.326737e+07   68372286.0  2.765846e+12     8.200142e+10            0.486562         0.000012    40452.731265               0.000406
14     New Zealand                    2.800436e+07    5200000.0  2.320117e+11     3.985797e+09            5.385454         0.000121    44617.633351               0.007026

### 4. Total funding by country x AP pillar (2020-2025)

In [58]:
country_pillar = country_split.pivot_table(
    index='Funder Country_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
country_pillar['Total'] = country_pillar.sum(axis=1)
country_pillar = country_pillar.sort_values('Total', ascending=False)
save(country_pillar, '4_funding_by_country_and_pillar')
print(country_pillar)

Saved 4_funding_by_country_and_pillar -> data_output\analysis\4_funding_by_country_and_pillar.csv
AP pillar             Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder Country_split
EU                     3.877506e+07  2.641055e+07  1.778421e+08  2.114229e+08
United States          9.470778e+07  3.277099e+07  1.341277e+08  4.779206e+07
Denmark                6.085037e+06  2.890231e+06  6.443271e+07  9.082711e+07
United Kingdom         4.117117e+07  2.742822e+07  3.991223e+07  4.108559e+07
South Korea            6.666517e+07  6.371271e+07  5.987246e+06  4.810685e+06
Netherlands            6.164645e+07  1.452487e+07  2.305151e+06  1.640810e+07
Singapore              1.285894e+07  1.798270e+07  3.960247e+07  1.269518e+07
Germany                4.181583e+06  9.593932e+06  7.620307e+06  6.058107e+07
Finland                3.864689e+07  4.899000e+05  2.682890e+07  1.179841e+07
Canada                 3.339732e+05  9.152549e+06  1.379242e+06  5.189263e+07
Norway                 1.689705e+07  1.606977e+06  1.082230e+07  3.002714e+07
Sweden                 1.064234e+06  2.549047e+05  5.186524e+06  4.422803e+07
Spain                  8.428214e+06  1.020059e+07  3.845675e+06  1.265177e+07
France                 2.418290e+05  0.000000e+00  3.000000e+06  3.002554e+07
New Zealand            6.712255e+06  5.954930e+06  5.152576e+06  1.018460e+07
Israel                 9.491092e+06  1.750923e+07  4.557900e+05  0.000000e+00
Switzerland            2.663368e+06  4.187049e+06  2.938837e+06  1.507707e+07
Japan                  1.105109e+06  1.328473e+07  2.657010e+05  3.317074e+06
Poland                 1.017403e+05  4.189125e+06  2.040675e+05  1.013188e+07
Portugal               3.859768e+06  1.008026e+06  3.497930e+05  2.297318e+06
Australia              3.580585e+06  3.159440e+05  6.817100e+05  2.768026e+06
Ireland                7.725970e+05  0.000000e+00  0.000000e+00  5.173310e+06
Austria                8.979060e+05  0.000000e+00  3.200000e+06  1.112695e+06
Estonia                2.430000e+04  0.000000e+00  2.602796e+06  2.004573e+06
Czechia                0.000000e+00  5.873048e+05  0.000000e+00  3.731505e+06
China                  2.559000e+06  8.008800e+04  4.004400e+04  1.056127e+06
Belgium                0.000000e+00  3.600000e+06  0.000000e+00  0.000000e+00
Global                 0.000000e+00  1.880443e+06  6.630000e+05  7.947500e+05
Brazil                 4.465736e+05  1.562936e+06  9.673755e+04  0.000000e+00
South Africa           0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00
Slovakia               0.000000e+00  0.000000e+00  3.000000e+05  2.371710e+05
Uruguay                0.000000e+00  0.000000e+00  0.000000e+00  5.327980e+05
Serbia                 0.000000e+00  1.499950e+05  0.000000e+00  0.000000e+00
Croatia                0.000000e+00  0.000000e+00  0.000000e+00  1.312388e+05
Latvia                 0.000000e+00  0.000000e+00  0.000000e+00  4.235000e+04
Chile                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Iceland                0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Malaysia               0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Italy                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Russia                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Turkey                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00

AP pillar                    Total
Funder Country_split
EU                    4.544506e+08
United States         3.093985e+08
Denmark               1.642351e+08
United Kingdom        1.495972e+08
South Korea           1.411758e+08
Netherlands           9.488457e+07
Singapore             8.313929e+07
Germany               8.197689e+07
Finland               7.776410e+07
Canada                6.275840e+07
Norway                5.935346e+07
Sweden                5.073370e+07
Spain                 3.512625e+07
France                3.326737e+07
New Zealand           2.800436e+07
Israel                2.745611e+07
Switzerland           2.486632e+07
Japan                 1.797262e+07
Poland                1.462682e+07
Portugal              7.514905e+06
Australia             7.346265e+06
Ireland               5.945907e+06
Austria               5.210601e+06
Estonia               4.631669e+06
Czechia               4.318810e+06
China                 3.735259e+06
Belgium               3.600000e+06
Global                3.338193e+06
Brazil                2.106247e+06
South Africa          5.599000e+05
Slovakia              5.371710e+05
Uruguay               5.327980e+05
Serbia                1.499950e+05
Croatia               1.312388e+05
Latvia                4.235000e+04
Chile                 0.000000e+00
Iceland               0.000000e+00
Malaysia              0.000000e+00
Italy                 0.000000e+00
Russia                0.000000e+00
Turkey                0.000000e+00

### 4a. Total funding by country x AP pillar excl. non-profit funding

Same breakdown as 4, restricted to the same non-profit/NGO-excluded set as 3b (see 3b's note for
exactly which `'Funder type'` values are dropped and which are kept). Reuses 3b's
`country_split_np`, so **3b must have been run first**.

In [59]:
# Same pivot as 4, but off 3b's non-profit-excluded split rather than re-deriving the filter -
# guarantees 4a and 3b always agree on which grants are in scope. `country_split_np` already
# carries the weighted_funding column, so this is a pure re-pivot.
# NOTE: *_np naming again on purpose - analyses 6 and 9 below read 3a's `country_split`.
country_pillar_np = country_split_np.pivot_table(
    index='Funder Country_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
country_pillar_np['Total'] = country_pillar_np.sum(axis=1)
country_pillar_np = country_pillar_np.sort_values('Total', ascending=False)

# Reindex onto 4's country list so 4a has the SAME rows in the same order-ish as 4, making the two
# CSVs directly comparable side by side in the template. A country whose funding was entirely
# non-profit drops out of country_split_np and would otherwise vanish from this table; showing it
# as an explicit 0 row says "assessed, nothing left" rather than silently omitting it.
# In the current data that applies to 'Global' only. ('Chile', 'Iceland', 'Malaysia', 'Italy',
# 'Russia' and 'Turkey' also read 0 here, but they are already 0 in 4 - grants with no funding
# amount recorded, not an artefact of this filter.)
country_pillar_np = country_pillar_np.reindex(
    country_pillar.index.union(country_pillar_np.index, sort=False), fill_value=0
).fillna(0).sort_values('Total', ascending=False)

save(country_pillar_np, '4a_funding_by_country_and_pillar_excl_nonprofit')
print(country_pillar_np)

Saved 4a_funding_by_country_and_pillar_excl_nonprofit -> data_output\analysis\4a_funding_by_country_and_pillar_excl_nonprofit.csv
AP pillar             Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder Country_split
EU                     3.877506e+07  2.641055e+07  1.778421e+08  2.114229e+08
United States          1.375888e+07  2.467003e+07  1.170682e+08  3.558181e+07
United Kingdom         4.117117e+07  2.742822e+07  3.961206e+07  3.984964e+07
South Korea            6.666517e+07  6.371271e+07  5.987246e+06  4.810685e+06
Netherlands            6.164645e+07  1.452487e+07  2.305151e+06  1.640810e+07
Singapore              1.285894e+07  1.798270e+07  3.960247e+07  1.269518e+07
Germany                4.181583e+06  9.593932e+06  7.620307e+06  6.058107e+07
Finland                3.858689e+07  4.899000e+05  2.682890e+07  1.179841e+07
Norway                 1.689705e+07  1.606977e+06  1.082230e+07  3.002714e+07
Canada                 3.339732e+05  8.548564e+06  1.379242e+06  4.902932e+07
Sweden                 1.064234e+06  2.549047e+05  5.186524e+06  4.422803e+07
Denmark                2.842624e+06  5.991436e+05  7.752327e+06  3.234015e+07
Spain                  8.428214e+06  1.020059e+07  3.845675e+06  1.265177e+07
France                 2.418290e+05  0.000000e+00  3.000000e+06  3.002554e+07
New Zealand            6.712255e+06  5.954930e+06  5.152576e+06  1.018460e+07
Israel                 9.491092e+06  1.713622e+07  4.557900e+05  0.000000e+00
Switzerland            2.663368e+06  4.187049e+06  2.938837e+06  1.425375e+07
Japan                  1.105109e+06  1.325399e+07  2.657010e+05  3.317074e+06
Poland                 1.017403e+05  4.189125e+06  2.040675e+05  1.013188e+07
Portugal               3.859768e+06  1.008026e+06  3.497930e+05  2.297318e+06
Australia              3.580585e+06  3.159440e+05  6.817100e+05  2.768026e+06
Ireland                7.725970e+05  0.000000e+00  0.000000e+00  5.173310e+06
Austria                8.979060e+05  0.000000e+00  3.200000e+06  1.112695e+06
Estonia                0.000000e+00  0.000000e+00  2.602796e+06  2.004573e+06
Czechia                0.000000e+00  5.873048e+05  0.000000e+00  3.731505e+06
China                  2.559000e+06  8.008800e+04  4.004400e+04  1.056127e+06
Belgium                0.000000e+00  3.600000e+06  0.000000e+00  0.000000e+00
Brazil                 4.465736e+05  1.562936e+06  9.673755e+04  0.000000e+00
South Africa           0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00
Slovakia               0.000000e+00  0.000000e+00  3.000000e+05  2.371710e+05
Uruguay                0.000000e+00  0.000000e+00  0.000000e+00  5.327980e+05
Serbia                 0.000000e+00  1.499950e+05  0.000000e+00  0.000000e+00
Croatia                0.000000e+00  0.000000e+00  0.000000e+00  1.312388e+05
Latvia                 0.000000e+00  0.000000e+00  0.000000e+00  4.235000e+04
Global                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Chile                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Iceland                0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Malaysia               0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Italy                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Russia                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Turkey                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00

AP pillar                    Total
Funder Country_split
EU                    4.544506e+08
United States         1.910789e+08
United Kingdom        1.480611e+08
South Korea           1.411758e+08
Netherlands           9.488457e+07
Singapore             8.313929e+07
Germany               8.197689e+07
Finland               7.770410e+07
Norway                5.935346e+07
Canada                5.929110e+07
Sweden                5.073370e+07
Denmark               4.353424e+07
Spain                 3.512625e+07
France                3.326737e+07
New Zealand           2.800436e+07
Israel                2.708310e+07
Switzerland           2.404300e+07
Japan                 1.794187e+07
Poland                1.462682e+07
Portugal              7.514905e+06
Australia             7.346265e+06
Ireland               5.945907e+06
Austria               5.210601e+06
Estonia               4.607369e+06
Czechia               4.318810e+06
China                 3.735259e+06
Belgium               3.600000e+06
Brazil                2.106247e+06
South Africa          5.599000e+05
Slovakia              5.371710e+05
Uruguay               5.327980e+05
Serbia                1.499950e+05
Croatia               1.312388e+05
Latvia                4.235000e+04
Global                0.000000e+00
Chile                 0.000000e+00
Iceland               0.000000e+00
Malaysia              0.000000e+00
Italy                 0.000000e+00
Russia                0.000000e+00
Turkey                0.000000e+00

### 4b. Total funding by region x AP pillar (2020-2025), and by EU / EU+ / Europe x AP pillar

In [60]:
region_pillar = region_split.pivot_table(
    index='Funder region_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
region_pillar['Total'] = region_pillar.sum(axis=1)
region_pillar = region_pillar.sort_values('Total', ascending=False)
save(region_pillar, '4b_funding_by_region_and_pillar')
print(region_pillar)

tier_pillar = tier_split.pivot_table(
    index='_tiers', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
tier_pillar['Total'] = tier_pillar.sum(axis=1)
save(tier_pillar, '4b_funding_by_eu_tier_and_pillar')
print()
print(tier_pillar)

Saved 4b_funding_by_region_and_pillar -> data_output\analysis\4b_funding_by_region_and_pillar.csv

AP pillar            Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder region_split
Europe                2.254572e+08  1.071217e+08  3.513914e+08  5.889948e+08
North America         9.504176e+07  4.192354e+07  1.355070e+08  9.968469e+07
Asia/Asia Pacific     9.348106e+07  1.013311e+08  5.172974e+07  3.483169e+07
Middle East           9.491092e+06  1.750923e+07  4.557900e+05  0.000000e+00
Global                0.000000e+00  1.880443e+06  6.630000e+05  7.947500e+05
South America         4.465736e+05  1.562936e+06  9.673755e+04  5.327980e+05
Africa                0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00

AP pillar                   Total
Funder region_split
Europe               1.272965e+09
North America        3.721569e+08
Asia/Asia Pacific    2.813736e+08
Middle East          2.745611e+07
Global               3.338193e+06
South America        2.639045e+06
Africa               5.599000e+05
Saved 4b_funding_by_eu_tier_and_pillar -> data_output\analysis\4b_funding_by_eu_tier_and_pillar.csv

AP pillar  Cross-cutting    Cultivated  Fermentation   Plant-based  \
_tiers
EU          1.647256e+08  7.374943e+07  2.977180e+08  5.028050e+08
EU+         2.254572e+08  1.069717e+08  3.513914e+08  5.889948e+08
Europe      2.254572e+08  1.071217e+08  3.513914e+08  5.889948e+08

AP pillar         Total
_tiers
EU         1.038998e+09
EU+        1.272815e+09
Europe     1.272965e+09

### 4c. Total funding by region x AP pillar excl. non-profit funding, and by EU / EU+ / Europe x AP pillar

Region- and tier-level twins of 4a, on the same non-profit/NGO-excluded set as 3b (see 3b's note for
which `'Funder type'` values are dropped). Also defines `region_split_np` / `tier_split_np`, which 9c
reuses - so **3b must have been run first**, and this cell before 9c.

In [61]:
# Region/tier equivalents of 4a. Built from `df_np` (defined once in 3b) rather than re-deriving the
# funder-type filter, so 3b, 4a, 4c and 9c can never disagree about which grants are in scope.
# NOTE: *_np naming again - analyses 5-9 read the unfiltered `region_split` / `tier_split`.
region_split_np = split_multi_value(df_np, 'Funder region', delimiter=',')
region_split_np['weighted_funding'] = region_split_np[FUNDING_COL] * region_split_np['_weight']

tier_split_np = europe_tier_split(df_np)
tier_split_np['weighted_funding'] = tier_split_np[FUNDING_COL] * tier_split_np['_weight']

region_pillar_np = region_split_np.pivot_table(
    index='Funder region_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
region_pillar_np['Total'] = region_pillar_np.sum(axis=1)
# Reindexed onto 4b's region list for the same reason 4a is reindexed onto 4's - keeps the two CSVs
# row-for-row comparable in the template. 'Global' funding is 100% non-profit, so it appears here as
# an explicit 0 row rather than silently vanishing.
region_pillar_np = region_pillar_np.reindex(
    region_pillar.index.union(region_pillar_np.index, sort=False), fill_value=0
).fillna(0).sort_values('Total', ascending=False)
save(region_pillar_np, '4c_funding_by_region_and_pillar_excl_nonprofit')
print(region_pillar_np)

tier_pillar_np = tier_split_np.pivot_table(
    index='_tiers', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
tier_pillar_np['Total'] = tier_pillar_np.sum(axis=1)
save(tier_pillar_np, '4c_funding_by_eu_tier_and_pillar_excl_nonprofit')
print()
print(tier_pillar_np)

Saved 4c_funding_by_region_and_pillar_excl_nonprofit -> data_output\analysis\4c_funding_by_region_and_pillar_excl_nonprofit.csv
AP pillar            Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder region_split
Europe                2.221305e+08  1.048306e+08  2.944108e+08  5.284485e+08
Asia/Asia Pacific     9.348106e+07  1.013004e+08  5.172974e+07  3.483169e+07
North America         1.409286e+07  3.321859e+07  1.184474e+08  8.461114e+07
Middle East           9.491092e+06  1.713622e+07  4.557900e+05  0.000000e+00
South America         4.465736e+05  1.562936e+06  9.673755e+04  5.327980e+05
Africa                0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00
Global                0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00

AP pillar                   Total
Funder region_split
Europe               1.149820e+09
Asia/Asia Pacific    2.813429e+08
North America        2.503700e+08
Middle East          2.708310e+07
South America        2.639045e+06
Africa               5.599000e+05
Global               0.000000e+00
Saved 4c_funding_by_eu_tier_and_pillar_excl_nonprofit -> data_output\analysis\4c_funding_by_eu_tier_and_pillar_excl_nonprofit.csv

AP pillar  Cross-cutting    Cultivated  Fermentation   Plant-based  \
_tiers
EU          1.613989e+08  7.145834e+07  2.410376e+08  4.443180e+08
EU+         2.221305e+08  1.046806e+08  2.944108e+08  5.284485e+08
Europe      2.221305e+08  1.048306e+08  2.944108e+08  5.284485e+08

AP pillar         Total
_tiers
EU         9.182129e+08
EU+        1.149670e+09
Europe     1.149820e+09

### 5. Top 20 funder institutions, with yearly split (no pillar split)

In [62]:
# Yearly breakdown by START year, not the funding-year spread - same default as everywhere
# else except 1b. 'Total' is the funder's sum across the 2020-2025 window: since Filter 3 now
# scopes `df` to that window globally, this Total is window-scoped too (it previously spanned
# all start years). Only NSERC was affected in the current data: 137,862 -> 96,985 EUR.
by_funder_year = df[df['Year project started'].between(2020, 2025)].pivot_table(
    index='Funder name', columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
by_funder_year.columns = by_funder_year.columns.astype(int)
by_funder_year = by_funder_year[sorted(by_funder_year.columns)]
by_funder_year['Total'] = df.groupby('Funder name')[FUNDING_COL].sum()
by_funder_year = by_funder_year.fillna(0)
top20_funders = by_funder_year.sort_values('Total', ascending=False).head(20)
save(top20_funders, '5_top20_funders')
print(top20_funders)

Saved 5_top20_funders -> data_output\analysis\5_top20_funders.csv
Year project started                                        2020  \
Funder name
European Commission                                 3.468856e+07
UK Research and Innovation (UKRI)                   2.992053e+06
Novo Nordisk Foundation                             3.345500e+04
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    3.272000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          1.022493e+07
"Agency for Science, Technology, and Research (...  0.000000e+00
Protein Industries Canada                           1.955580e+07
Federal Ministry of Food and Agriculture (BMEL)     1.552889e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  8.730389e+06
MAFRA,IPET                                          0.000000e+00
NSF                                                 3.020116e+06
Israel Innovation Authority's Generic Technolog...  0.000000e+00
National Institute of Food and Agriculture          1.207839e+06
Federal Ministry for Economic Affairs and Energ...  8.166190e+05
Ministry of Oceans and Fisheries                    0.000000e+00
Singapore Food Agency                               0.000000e+00

Year project started                                        2021  \
Funder name
European Commission                                 2.500890e+07
UK Research and Innovation (UKRI)                   7.417615e+06
Novo Nordisk Foundation                             1.356960e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    1.017000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          2.488350e+07
"Agency for Science, Technology, and Research (...  4.218251e+07
Protein Industries Canada                           7.631638e+06
Federal Ministry of Food and Agriculture (BMEL)     8.060830e+05
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  3.662148e+06
MAFRA,IPET                                          1.395225e+07
NSF                                                 0.000000e+00
Israel Innovation Authority's Generic Technolog...  8.149300e+06
National Institute of Food and Agriculture          8.462400e+06
Federal Ministry for Economic Affairs and Energ...  2.195042e+06
Ministry of Oceans and Fisheries                    0.000000e+00
Singapore Food Agency                               0.000000e+00

Year project started                                        2022  \
Funder name
European Commission                                 1.017730e+08
UK Research and Innovation (UKRI)                   1.246470e+07
Novo Nordisk Foundation                             3.514565e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    5.766000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          9.229815e+05
"Agency for Science, Technology, and Research (...  0.000000e+00
Protein Industries Canada                           3.795336e+06
Federal Ministry of Food and Agriculture (BMEL)     3.488063e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  4.040993e+06
MAFRA,IPET                                          8.028260e+06
NSF                                                 1.255051e+06
Israel Innovation Authority's Generic Technolog...  1.666206e+07
National Institute of Food and Agriculture          8.765550e+05
Federal Ministry for Economic Affairs and Energ...  5.100692e+06
Ministry of Oceans and Fisheries                    0.000000e+00
Singapore Food Agency                               0.000000e+00

Year project started                                        2023  \
Funder name
European Commission                                 1.017476e+08
UK Research and Innovation (UKRI)                   4.356962e+07
Novo Nordisk Foundation                             2.027661e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    4.882900e+06
Dutch National Growth Fund                          6.000000e+07
Department of Commerce (DoC)                        4.718300e+05
Research Council of Norway                          2.239901e+06
"Agency for Science, Technology, and Research (...  3.188250e+05
Protein Industries Canada                           3.029490e+06
Federal Ministry of Food and Agriculture (BMEL)     2.050728e+07
Defense Advanced Research Projects Agency (DARPA)   3.708478e+07
Swedish Research Council for Environment Agricu...  4.121009e+06
MAFRA,IPET                                          0.000000e+00
NSF                                                 5.426400e+05
Israel Innovation Authority's Generic Technolog...  1.341792e+06
National Institute of Food and Agriculture          4.382728e+06
Federal Ministry for Economic Affairs and Energ...  6.631378e+06
Ministry of Oceans and Fisheries                    2.777775e+05
Singapore Food Agency                               0.000000e+00

Year project started                                        2024  \
Funder name
European Commission                                 7.813586e+07
UK Research and Innovation (UKRI)                   6.320059e+07
Novo Nordisk Foundation                             2.180884e+07
Bezos Earth Fund (BEF)                              8.077890e+07
Business Finland                                    4.678500e+07
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        4.746417e+07
Research Council of Norway                          5.253050e+05
"Agency for Science, Technology, and Research (...  0.000000e+00
Protein Industries Canada                           3.838650e+06
Federal Ministry of Food and Agriculture (BMEL)     9.741771e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  5.988906e+06
MAFRA,IPET                                          6.930000e+06
NSF                                                 1.747786e+07
Israel Innovation Authority's Generic Technolog...  0.000000e+00
National Institute of Food and Agriculture          5.713368e+06
Federal Ministry for Economic Affairs and Energ...  3.990763e+06
Ministry of Oceans and Fisheries                    2.002000e+07
Singapore Food Agency                               0.000000e+00

Year project started                                        2025         Total
Funder name
European Commission                                 1.125967e+08  4.539506e+08
UK Research and Innovation (UKRI)                   4.680803e+06  1.343254e+08
Novo Nordisk Foundation                             2.398031e+07  1.148145e+08
Bezos Earth Fund (BEF)                              3.841188e+06  8.462009e+07
Business Finland                                    1.123707e+07  7.295997e+07
Dutch National Growth Fund                          0.000000e+00  6.000000e+07
Department of Commerce (DoC)                        0.000000e+00  4.793600e+07
Research Council of Norway                          6.259273e+06  4.505590e+07
"Agency for Science, Technology, and Research (...  0.000000e+00  4.250134e+07
Protein Industries Canada                           2.758304e+06  4.060921e+07
Federal Ministry of Food and Agriculture (BMEL)     4.084547e+06  4.018063e+07
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00  3.708478e+07
Swedish Research Council for Environment Agricu...  5.333470e+06  3.187691e+07
MAFRA,IPET                                          1.950000e+06  3.086051e+07
NSF                                                 3.882711e+06  2.617838e+07
Israel Innovation Authority's Generic Technolog...  0.000000e+00  2.615315e+07
National Institute of Food and Agriculture          3.407436e+06  2.405033e+07
Federal Ministry for Economic Affairs and Energ...  3.078532e+06  2.181303e+07
Ministry of Oceans and Fisheries                    0.000000e+00  2.029778e+07
Singapore Food Agency                               2.025035e+07  2.025035e+07

### 6. Top 20 country rankings per year, 2020-2025 (non-cumulative)

Two shapes: (a) rank 1-20 x year, country name per cell (for a table); (b) country x year, rank
number per cell (for graphing a ranked-line/bump chart). Distinct from analysis #8's cumulative
ranking below - confirmed via the template these are two different things, not variants of one.

In [63]:
# By START year (2020-2025), not the funding-year spread - same default as everywhere else in
# this notebook except 1b.
annual_country = country_split[country_split['Year project started'].between(2020, 2025)]
year_country_totals = {}
for y in range(2020, 2026):
    year_country_totals[y] = annual_country[annual_country['Year project started'] == y].groupby(
        'Funder Country_split'
    )['weighted_funding'].sum().sort_values(ascending=False)

# Shape A: rank (1-20) x year, country name per cell
rank_table = pd.DataFrame({y: year_country_totals[y].head(20).index.tolist() for y in range(2020, 2026)})
rank_table.index = pd.RangeIndex(1, 21, name='Rank')
save(rank_table, '6a_country_rank_table')
print(rank_table)

# Shape B: country x year, rank number per cell (for graphing)
all_countries_ranked = sorted(set().union(*[year_country_totals[y].head(10).index for y in range(2020, 2026)]))
country_rank_grid = pd.DataFrame(index=all_countries_ranked, columns=range(2020, 2026), dtype='float')
for y in range(2020, 2026):
    ranks = {c: i + 1 for i, c in enumerate(year_country_totals[y].index)}
    for c in all_countries_ranked:
        country_rank_grid.loc[c, y] = ranks.get(c, np.nan)
save(country_rank_grid, '6b_country_rank_grid')
print()
print(country_rank_grid)

Saved 6a_country_rank_table -> data_output\analysis\6a_country_rank_table.csv
                2020            2021            2022            2023  \
Rank
1                 EU       Singapore              EU              EU
2             Canada          Norway         Denmark     Netherlands
3             Norway   United States     South Korea   United States
4            Germany              EU   United States  United Kingdom
5             Sweden         Denmark  United Kingdom         Germany
6      United States     South Korea          Israel         Denmark
7        New Zealand           Spain         Germany          France
8            Denmark          Canada           Spain          Canada
9            Belgium          Israel         Finland           Japan
10           Finland  United Kingdom     Switzerland           Spain
11    United Kingdom          Sweden          Sweden          Sweden
12           Ireland       Australia          Canada     South Korea
13             Japan         Germany     Netherlands     New Zealand
14             China     Switzerland          France     Switzerland
15             Spain     Netherlands       Australia         Finland
16       Switzerland         Finland          Norway         Austria
17            Global        Portugal          Global         Ireland
18           Estonia           Japan           Japan          Israel
19       Netherlands          Global         Austria          Norway
20       South Korea           China           China          Brazil

                2024            2025
Rank
1      United States              EU
2                 EU         Denmark
3     United Kingdom   United States
4        South Korea     South Korea
5            Finland       Singapore
6            Denmark         Finland
7            Germany          Sweden
8             Poland     Netherlands
9        Netherlands         Germany
10         Singapore          Norway
11            Sweden     New Zealand
12            Canada  United Kingdom
13            France     Switzerland
14       New Zealand        Portugal
15             Spain          Canada
16           Estonia         Czechia
17           Czechia         Austria
18            Norway           Japan
19       Switzerland          France
20             Japan           Spain
Saved 6b_country_rank_grid -> data_output\analysis\6b_country_rank_grid.csv

                2020  2021  2022  2023  2024  2025
Belgium          9.0  26.0  28.0  32.0  26.0  29.0
Canada           2.0   8.0  12.0   8.0  12.0  15.0
Denmark          8.0   5.0   2.0   6.0   6.0   2.0
EU               1.0   4.0   1.0   1.0   2.0   1.0
Finland         10.0  16.0   9.0  15.0   5.0   6.0
France           NaN   NaN  14.0   7.0  13.0  19.0
Germany          4.0  13.0   7.0   5.0   7.0   9.0
Israel           NaN   9.0   6.0  18.0   NaN  23.0
Japan           13.0  18.0  18.0   9.0  20.0  18.0
Netherlands     19.0  15.0  13.0   2.0   9.0   8.0
New Zealand      7.0   NaN  24.0  13.0  14.0  11.0
Norway           3.0   2.0  16.0  19.0  18.0  10.0
Poland          22.0  21.0  21.0  24.0   8.0  27.0
Singapore        NaN   1.0   NaN  23.0  10.0   5.0
South Korea     20.0   6.0   3.0  12.0   4.0   4.0
Spain           15.0   7.0   8.0  10.0  15.0  20.0
Sweden           5.0  11.0  11.0  11.0  11.0   7.0
Switzerland     16.0  14.0  10.0  14.0  19.0  13.0
United Kingdom  11.0  10.0   5.0   4.0   3.0  12.0
United States    6.0   3.0   4.0   3.0   1.0   3.0

### 7. Total funding 2020-2025 by AP pillar x End product type, plus a separate Dairy sub-split

In [64]:
ep_split = split_multi_value(df, 'End product type', delimiter=';')
ep_split['weighted_funding'] = ep_split[FUNDING_COL] * ep_split['_weight']
pillar_end_product = ep_split.pivot_table(
    index='End product type_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
pillar_end_product['Total'] = pillar_end_product.sum(axis=1)
save(pillar_end_product, '7a_funding_by_pillar_and_end_product')
print(pillar_end_product)

# Dairy's own constituents, not cross-tabulated with pillar. Starts from ep_split's Dairy share
# (not df directly) so a 'Meat; Dairy' grant contributes the same weighted share here as it does
# to 7a's Dairy total, then splits that share further across sub-end products. 'sub-end product'
# is exclusively populated for Dairy rows (confirmed: no non-Dairy row has one) - Dairy rows
# missing a sub-end product are labelled 'Agnostic' here, for this breakdown only, so their
# funding isn't silently dropped. Not written back to the underlying data: 'Agnostic' is already a
# distinct End product type value, and reusing it as a sub-end product value there would be confusing.
dairy_ep = ep_split[ep_split['End product type_split'] == 'Dairy'].copy()
dairy_ep['sub-end product'] = dairy_ep['sub-end product'].fillna('Agnostic')
dairy_ep = dairy_ep.rename(columns={'weighted_funding': 'dairy_weighted_funding'})
sub_ep_split = split_multi_value(dairy_ep, 'sub-end product', delimiter=';')
sub_ep_split['weighted_funding'] = sub_ep_split['dairy_weighted_funding'] * sub_ep_split['_weight']
dairy_breakdown = sub_ep_split.groupby('sub-end product_split')['weighted_funding'].sum().sort_values(ascending=False)
dairy_breakdown.name = 'Total funding (2020-2025, EUR)'
save(dairy_breakdown, '7b_dairy_sub_breakdown')
print()
print(dairy_breakdown)

Saved 7a_funding_by_pillar_and_end_product -> data_output\analysis\7a_funding_by_pillar_and_end_product.csv
AP pillar                               Cross-cutting    Cultivated  \
End product type_split
Agnostic                                 3.201466e+08  5.267538e+07
Chocolate, desserts, and confectionery   0.000000e+00  3.597543e+05
Dairy                                    5.628772e+06  1.185138e+06
Eggs and egg proteins                    5.498261e+06  0.000000e+00
Fish and seafood                         2.018002e+07  2.719244e+07
Meat                                     7.246404e+07  1.897692e+08
Spreads, sauces, and condiments          0.000000e+00  0.000000e+00

AP pillar                               Fermentation   Plant-based  \
End product type_split
Agnostic                                4.536600e+08  5.169338e+08
Chocolate, desserts, and confectionery  1.053143e+06  6.477531e+06
Dairy                                   3.658074e+07  6.262193e+07
Eggs and egg proteins                   7.166210e+06  8.009521e+06
Fish and seafood                        8.217224e+06  2.018518e+07
Meat                                    2.624262e+07  1.099061e+08
Spreads, sauces, and condiments         7.483568e+06  7.046046e+05

AP pillar                                      Total
End product type_split
Agnostic                                1.343416e+09
Chocolate, desserts, and confectionery  7.890428e+06
Dairy                                   1.060166e+08
Eggs and egg proteins                   2.067399e+07
Fish and seafood                        7.577486e+07
Meat                                    3.983820e+08
Spreads, sauces, and condiments         8.188172e+06
Saved 7b_dairy_sub_breakdown -> data_output\analysis\7b_dairy_sub_breakdown.csv

sub-end product_split
Milk and milk proteins         2.859118e+07
Cheese                         2.815509e+07
Agnostic                       2.616505e+07
Yoghurt and fermented dairy    1.841982e+07
Infant formula                 3.581390e+06
Cream and ice cream            1.104044e+06
Name: Total funding (2020-2025, EUR), dtype: float64

### 7c/7d. End product type by country, and the Dairy sub-split by country (2020-2025)

Country columns restricted to `COI` from `Funding_analysis_helpers` (13 funders of interest).

Funding is split **twice**: once across a grant's end product types, then again across its funder
countries - so a `'Meat; Dairy'` grant funded by `'Sweden, EU'` puts 1/4 of its amount in each of
the four cells. Same nesting the Dairy sub-split in 7 already uses.

Reuses `ep_split` and `sub_ep_split` from 7, so **run 7 first**. Row totals cover the COI columns
only and are therefore lower than 7a/7b's world totals - the coverage line reports by how much.

In [65]:
from Funding_analysis_helpers import COI

# 'EU' is treated as a country here, on purpose: it is its own 'Funder Country' value
# (supranational EU-level funding) and the single largest funder in the data, so it needs its own
# column. Unioned in explicitly rather than trusting COI alone, because a Jupyter kernel caches
# Funding_analysis_helpers - a COI edited after the module was first imported stays stale until the
# kernel restarts, which is exactly how the EU column went missing on the first run of this cell.
COUNTRIES_OF_INTEREST = set(COI) | {'EU'}
if 'EU' not in COI:
    print("Note: the imported COI has no 'EU' (stale cached module?) - added it here. "
          "Restart the kernel if you expect other COI edits to be picked up.")


def _by_country(base_split, value_col, index_col):
    """Split an already-end-product-weighted frame across funder countries and pivot to
    index_col x country, keeping only COI columns. Renames the incoming weight column first because
    split_multi_value overwrites '_weight' - the new weight must multiply the OLD share, not replace it."""
    base = base_split.rename(columns={value_col: '_carried'}).copy()
    exploded = split_multi_value(base, 'Funder Country', delimiter=',')
    exploded['weighted_funding'] = exploded['_carried'] * exploded['_weight']
    table = exploded.pivot_table(
        index=index_col, columns='Funder Country_split', values='weighted_funding',
        aggfunc='sum', fill_value=0,
    )
    # Reindex onto the full COI list so the column set is stable even if a country funded nothing.
    table = table.reindex(columns=sorted(COUNTRIES_OF_INTEREST), fill_value=0).fillna(0)
    table['Total (COI)'] = table.sum(axis=1)
    return table.sort_values('Total (COI)', ascending=False), exploded


# 7c: end product type x country
end_product_country, _ep_country_exploded = _by_country(
    ep_split, 'weighted_funding', 'End product type_split')
save(end_product_country, '7c_funding_by_end_product_and_country')
print(end_product_country.to_string(float_format=lambda v: f'{v:,.0f}'))

_coi_total = end_product_country['Total (COI)'].sum()
_world_total = _ep_country_exploded['weighted_funding'].sum()
print(f"\nCOI columns cover EUR {_coi_total:,.0f} of EUR {_world_total:,.0f} "
      f"({100 * _coi_total / _world_total:.1f}%) of end-product-attributed funding.")

# 7d: Dairy sub-end product x country. sub_ep_split already carries the Dairy share split across
# sub-end products, so this only adds the country dimension.
dairy_sub_country, _dairy_country_exploded = _by_country(
    sub_ep_split, 'weighted_funding', 'sub-end product_split')
save(dairy_sub_country, '7d_dairy_sub_breakdown_by_country')
print()
print(dairy_sub_country.to_string(float_format=lambda v: f'{v:,.0f}'))

_coi_dairy = dairy_sub_country['Total (COI)'].sum()
_world_dairy = _dairy_country_exploded['weighted_funding'].sum()
print(f"\nCOI columns cover EUR {_coi_dairy:,.0f} of EUR {_world_dairy:,.0f} "
      f"({100 * _coi_dairy / _world_dairy:.1f}%) of Dairy funding.")

Saved 7c_funding_by_end_product_and_country -> data_output\analysis\7c_funding_by_end_product_and_country.csv
Funder Country_split                       Canada     Denmark          EU    Finland    Germany     Israel      Japan     Norway  Singapore  South Korea     Sweden  United Kingdom  United States   Total (COI)
End product type_split
Agnostic                               36,898,279 127,152,571 342,365,677 66,271,407 49,815,854  9,864,098 16,117,455 28,715,067 68,006,710   15,855,117 34,624,436     101,384,072    257,144,988 1,154,215,731
Meat                                   16,793,923  20,741,230  38,046,270  6,264,900 15,173,276 16,662,060  1,645,839 28,436,206 14,035,169   92,875,390  9,046,537      38,814,428     42,584,673   341,119,900
Dairy                                   5,077,559  11,602,651  42,195,271    727,790  8,658,480          0     67,958    604,161          0    3,705,000  4,498,201       5,213,837      2,738,057    85,088,965
Fish and seafood                        3,872,666     408,192  19,712,666          0  6,683,690    929,950    115,698  1,015,855  1,097,410   24,363,163  2,321,114       1,459,657      5,445,721    67,425,783
Eggs and egg proteins                      88,509   3,435,605   4,635,513  4,500,000    766,318          0     12,833    582,175          0    4,230,136    203,856       1,317,091        901,956    20,673,993
Spreads, sauces, and condiments            13,730     894,836   6,588,732          0    225,110          0          0          0          0            0          0         118,426        176,323     8,017,156
Chocolate, desserts, and confectionery     13,730           0     906,492          0    654,164          0     12,833          0          0            0     39,554       1,289,700        406,828     3,323,300

COI columns cover EUR 1,679,864,828 of EUR 1,960,341,822 (85.7%) of end-product-attributed funding.
Saved 7d_dairy_sub_breakdown_by_country -> data_output\analysis\7d_dairy_sub_breakdown_by_country.csv

Funder Country_split           Canada   Denmark         EU  Finland   Germany  Israel  Japan  Norway  Singapore  South Korea    Sweden  United Kingdom  United States  Total (COI)
sub-end product_split
Milk and milk proteins        567,762 4,613,219 13,585,050        0 3,051,954       0 67,958 580,725          0            0   181,727         856,699        728,883   24,233,978
Agnostic                       58,622 1,852,996  7,873,039  727,790 1,021,291       0      0  13,286          0    3,705,000 2,767,210       1,554,098        932,297   20,505,629
Cheese                      4,098,897 3,672,313  4,007,933        0 3,958,888       0      0   9,425          0            0   643,875       2,273,756        482,500   19,147,586
Yoghurt and fermented dairy   143,262 1,149,582 14,229,250        0   403,287       0      0     725          0            0   668,171               0        520,009   17,114,286
Infant formula                 46,503         0  2,499,999        0         0       0      0       0          0            0         0         529,285              0    3,075,787
Cream and ice cream           162,513   314,541          0        0   223,060       0      0       0          0            0   237,219               0         74,367    1,011,700

COI columns cover EUR 85,088,965 of EUR 106,016,582 (80.3%) of Dairy funding.

### 8. Investment and cumulative investment by country, 2020-2025, with cumulative rank

Reuses `year_country_totals` computed for analysis #6 above.

In [66]:
investment_by_year = pd.DataFrame({y: year_country_totals[y] for y in range(2020, 2026)}).fillna(0)
save(investment_by_year, '8a_investment_by_country_and_year')

cumulative_by_year = investment_by_year.cumsum(axis=1)
save(cumulative_by_year, '8b_cumulative_investment_by_country_and_year')

# Rank 1 = highest cumulative total-to-date that year
cumulative_rank = cumulative_by_year.rank(axis=0, ascending=False, method='min')
save(cumulative_rank, '8c_cumulative_investment_rank')

print(investment_by_year.head(10))
print()
print(cumulative_by_year.head(10))
print()
print(cumulative_rank.head(10))

Saved 8a_investment_by_country_and_year -> data_output\analysis\8a_investment_by_country_and_year.csv
Saved 8b_cumulative_investment_by_country_and_year -> data_output\analysis\8b_cumulative_investment_by_country_and_year.csv
Saved 8c_cumulative_investment_rank -> data_output\analysis\8c_cumulative_investment_rank.csv
                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.828994e+06  1.328364e+06  6.063202e+05
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.200000e+06
Belgium               3.600000e+06  0.000000e+00  0.000000e+00  0.000000e+00
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.343843e+07  9.612336e+06  5.661477e+06  1.334250e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.328890e+05  4.717510e+05  3.254220e+05
Croatia               1.312388e+05  0.000000e+00  0.000000e+00  0.000000e+00
Czechia               0.000000e+00  3.755200e+04  0.000000e+00  0.000000e+00
Denmark               4.621640e+06  2.212959e+07  3.844566e+07  2.879998e+07

                              2024          2025
Funder Country_split
Australia             1.279530e+05  4.340292e+05
Austria               0.000000e+00  1.345167e+06
Belgium               0.000000e+00  0.000000e+00
Brazil                2.179625e+05  4.144000e+05
Canada                6.939440e+06  3.764216e+06
Chile                 0.000000e+00  0.000000e+00
China                 0.000000e+00  0.000000e+00
Croatia               0.000000e+00  0.000000e+00
Czechia               1.689872e+06  2.591386e+06
Denmark               3.362960e+07  3.660860e+07

                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.849598e+06  6.177962e+06  6.784282e+06
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.865434e+06
Belgium               3.600000e+06  3.600000e+06  3.600000e+06  3.600000e+06
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.343843e+07  3.305076e+07  3.871224e+07  5.205474e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.938086e+06  3.409837e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05  1.312388e+05  1.312388e+05
Czechia               0.000000e+00  3.755200e+04  3.755200e+04  3.755200e+04
Denmark               4.621640e+06  2.675123e+07  6.519690e+07  9.399688e+07

                              2024          2025
Funder Country_split
Australia             6.912235e+06  7.346265e+06
Austria               3.865434e+06  5.210601e+06
Belgium               3.600000e+06  3.600000e+06
Brazil                1.691847e+06  2.106247e+06
Canada                5.899418e+07  6.275840e+07
Chile                 0.000000e+00  0.000000e+00
China                 3.735259e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05
Czechia               1.727424e+06  4.318810e+06
Denmark               1.276265e+08  1.642351e+08

                      2020  2021  2022  2023  2024  2025
Funder Country_split
Australia             23.0  15.0  17.0  19.0  20.0  21.0
Austria               25.0  29.0  26.0  21.0  23.0  23.0
Belgium                9.0  18.0  19.0  23.0  25.0  27.0
Brazil                25.0  29.0  31.0  27.0  29.0  29.0
Canada                 2.0   5.0   7.0   9.0  10.0  10.0
Chile                 25.0  29.0  31.0  35.0  36.0  36.0
China                 14.0  21.0  20.0  22.0  24.0  26.0
Croatia               21.0  26.0  28.0  33.0  34.0  34.0
Czechia               25.0  27.0  30.0  34.0  28.0  25.0
Denmark                8.0   6.0   3.0   3.0   4.0   3.0

### 8d. Investment and cumulative investment by country excl. non-profit funding, 2020-2025

Non-profit/NGO-excluded twin of 8a-8c. It rebuilds the per-year country totals from
`country_split_np` (the weighted country split defined once in 3b) rather than reusing
`year_country_totals`, which is all-funders. Run 3b before this cell.

In [67]:
# Non-profit-excluded twin of 8a-8c. Built from `country_split_np` (defined once in 3b) so the
# weights come from the same frame the non-profit mask was applied to - masks are never reindexed
# across frames here, because 3b calls reset_index(drop=True) and the row labels no longer line up.
annual_country_np = country_split_np[country_split_np['Year project started'].between(2020, 2025)]
year_country_totals_np = {
    y: (annual_country_np[annual_country_np['Year project started'] == y]
        .groupby('Funder Country_split')['weighted_funding'].sum()
        .sort_values(ascending=False))
    for y in range(2020, 2026)
}

investment_by_year_np = pd.DataFrame(
    {y: year_country_totals_np[y] for y in range(2020, 2026)}
).fillna(0)
save(investment_by_year_np, '8d_investment_by_country_and_year_excl_nonprofit')

cumulative_by_year_np = investment_by_year_np.cumsum(axis=1)
save(cumulative_by_year_np, '8d_cumulative_investment_by_country_and_year_excl_nonprofit')

# Rank 1 = highest cumulative total-to-date that year. Countries funded ONLY by non-profits drop
# out of the index entirely, so these ranks are not directly comparable to 8c's row-for-row.
cumulative_rank_np = cumulative_by_year_np.rank(axis=0, ascending=False, method='min')
save(cumulative_rank_np, '8d_cumulative_investment_rank_excl_nonprofit')

# Tripwire: the excl.-non-profit total can never exceed the all-funders total of 8a.
_total_all = investment_by_year.to_numpy().sum()
_total_np = investment_by_year_np.to_numpy().sum()
assert _total_np <= _total_all + 1e-6, f"excl.-non-profit total {_total_np:,.0f} exceeds all-funders {_total_all:,.0f}"
_dropped = sorted(set(investment_by_year.index) - set(investment_by_year_np.index))
print(f"2020-2025 total: EUR {_total_all:,.0f} all funders vs EUR {_total_np:,.0f} excl. non-profit "
      f"({_total_np / _total_all:.1%}).")
print(f"{len(_dropped)} countries drop out entirely (non-profit money only): {_dropped}")

print(investment_by_year_np.head(10))
print()
print(cumulative_by_year_np.head(10))
print()
print(cumulative_rank_np.head(10))

Saved 8d_investment_by_country_and_year_excl_nonprofit -> data_output\analysis\8d_investment_by_country_and_year_excl_nonprofit.csv
Saved 8d_cumulative_investment_by_country_and_year_excl_nonprofit -> data_output\analysis\8d_cumulative_investment_by_country_and_year_excl_nonprofit.csv
Saved 8d_cumulative_investment_rank_excl_nonprofit -> data_output\analysis\8d_cumulative_investment_rank_excl_nonprofit.csv
2020-2025 total: EUR 1,960,488,822 all funders vs EUR 1,711,815,330 excl. non-profit (87.3%).
1 countries drop out entirely (non-profit money only): ['Global']
                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.828994e+06  1.328364e+06  6.063202e+05
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.200000e+06
Belgium               3.600000e+06  0.000000e+00  0.000000e+00  0.000000e+00
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.343843e+07  9.612336e+06  5.661477e+06  1.263351e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.328890e+05  4.717510e+05  3.254220e+05
Croatia               1.312388e+05  0.000000e+00  0.000000e+00  0.000000e+00
Czechia               0.000000e+00  3.755200e+04  0.000000e+00  0.000000e+00
Denmark               4.588185e+06  5.962510e+06  1.311116e+06  8.523374e+06

                              2024          2025
Funder Country_split
Australia             1.279530e+05  4.340292e+05
Austria               0.000000e+00  1.345167e+06
Belgium               0.000000e+00  0.000000e+00
Brazil                2.179625e+05  4.144000e+05
Canada                6.939440e+06  1.005912e+06
Chile                 0.000000e+00  0.000000e+00
China                 0.000000e+00  0.000000e+00
Croatia               0.000000e+00  0.000000e+00
Czechia               1.689872e+06  2.591386e+06
Denmark               1.052076e+07  1.262829e+07

                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.849598e+06  6.177962e+06  6.784282e+06
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.865434e+06
Belgium               3.600000e+06  3.600000e+06  3.600000e+06  3.600000e+06
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.343843e+07  3.305076e+07  3.871224e+07  5.134575e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.938086e+06  3.409837e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05  1.312388e+05  1.312388e+05
Czechia               0.000000e+00  3.755200e+04  3.755200e+04  3.755200e+04
Denmark               4.588185e+06  1.055070e+07  1.186181e+07  2.038519e+07

                              2024          2025
Funder Country_split
Australia             6.912235e+06  7.346265e+06
Austria               3.865434e+06  5.210601e+06
Belgium               3.600000e+06  3.600000e+06
Brazil                1.691847e+06  2.106247e+06
Canada                5.828519e+07  5.929110e+07
Chile                 0.000000e+00  0.000000e+00
China                 3.735259e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05
Czechia               1.727424e+06  4.318810e+06
Denmark               3.090595e+07  4.353424e+07

                      2020  2021  2022  2023  2024  2025
Funder Country_split
Australia             22.0  15.0  17.0  19.0  20.0  21.0
Austria               24.0  28.0  25.0  21.0  23.0  23.0
Belgium                9.0  18.0  19.0  23.0  25.0  27.0
Brazil                24.0  28.0  30.0  26.0  28.0  28.0
Canada                 2.0   4.0   6.0   8.0   9.0  10.0
Chile                 24.0  28.0  30.0  34.0  35.0  35.0
China                 14.0  21.0  20.0  22.0  24.0  26.0
Croatia               20.0  25.0  27.0  32.0  33.0  33.0
Czechia               24.0  26.0  29.0  33.0  27.0  25.0
Denmark                8.0  11.0  13.0  14.0  14.0  12.0

### 9a. Research category as a % of total funding, by region (+ EU / EU+ / Europe) - overall, and by AP pillar

`'Research category'` is multi-value like `'Funder Country'`/`'Funder region'`, so it gets the
same fractional split - a grant tagged with 3 categories has each get 1/3 of its (region- or
country-weighted) share. Grants with no `'Research category'` at all are excluded entirely, so
`'Total (EUR)'` here is the classified-funding total, not the full region/country total from
1c/3 - percentages are a share of classified funding only.

In [68]:
def category_pct_table(base_split, index_col, weighted_col_name):
    # Grants with no Research category are dropped entirely (not labelled 'Unclassified') -
    # percentages here are a share of classified funding only, so Total (EUR) will be less than
    # the region/country's true total wherever some grants lack a category.
    base = base_split.rename(columns={'weighted_funding': weighted_col_name}).copy()
    exploded = split_multi_value(base, 'Research category', delimiter=',')
    exploded['weighted_funding'] = exploded[weighted_col_name] * exploded['_weight']
    eur = exploded.pivot_table(
        index=index_col, columns='Research category_split', values='weighted_funding', aggfunc='sum', fill_value=0
    )
    eur['Total (EUR)'] = eur.sum(axis=1)
    pct = eur.drop(columns='Total (EUR)').div(eur['Total (EUR)'], axis=0) * 100
    pct['Total (EUR)'] = eur['Total (EUR)']
    return pct.sort_values('Total (EUR)', ascending=False)


def category_pct_by_pillar(base_split, index_col, weighted_col_name):
    pillars = sorted(base_split['AP pillar'].dropna().unique())
    return pd.concat(
        {p: category_pct_table(base_split[base_split['AP pillar'] == p], index_col, weighted_col_name) for p in pillars},
        names=['AP pillar']
    )

In [69]:
region_category_pct = category_pct_table(region_split, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct, '9a_research_category_pct_by_region')
print(region_category_pct)

region_category_pct_by_pillar = category_pct_by_pillar(region_split, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_by_pillar, '9a_research_category_pct_by_region_and_pillar')
print()
print(region_category_pct_by_pillar)

Saved 9a_research_category_pct_by_region -> data_output\analysis\9a_research_category_pct_by_region.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder region_split
Europe                           10.244087            2.304391
North America                     5.066339            2.416803
Asia/Asia Pacific                16.124989            8.850165
Middle East                       0.000000            0.000000
Global                           26.362429           12.716364
South America                     0.359001            4.593517
Africa                           20.000000            0.000000

Research category_split  Cell line development  Consumer & market research  \
Funder region_split
Europe                                1.297469                    6.114026
North America                         1.647925                    0.901654
Asia/Asia Pacific                     4.323574                    2.706964
Middle East                           0.000000                    0.000000
Global                                5.077501                    0.000000
South America                        15.702649                    0.616795
Africa                                0.000000                    0.000000

Research category_split  Crop development  End product formulation  \
Funder region_split
Europe                           4.697446                11.925927
North America                    3.511752                 8.662913
Asia/Asia Pacific                0.282924                 9.006473
Middle East                      0.000000                 1.416843
Global                           0.000000                14.025801
South America                    1.265451                26.134035
Africa                           0.000000                20.000000

Research category_split  Feedstocks  Food safety & quality  \
Funder region_split
Europe                     4.984994               3.367723
North America              7.191904               0.969761
Asia/Asia Pacific          2.915269               6.566697
Middle East                0.000000               0.553356
Global                     0.000000               0.000000
South America              0.000000               1.074559
Africa                     0.000000               0.000000

Research category_split  Health & nutrition  Impact Assessments  \
Funder region_split
Europe                             6.840850            6.061811
North America                      2.670363            1.350419
Asia/Asia Pacific                  3.810167            1.168139
Middle East                        0.000000            0.000000
Global                             0.000000            3.942926
South America                      1.396833            1.087041
Africa                             0.000000            0.000000

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder region_split
Europe                                 17.460195  12.326114     1.650598
North America                           9.771159  47.283614     2.429039
Asia/Asia Pacific                       9.825882  19.205867     3.709559
Middle East                             0.000000  96.612958     0.863487
Global                                 19.436663   9.523116     4.437976
South America                           5.639082  40.694112     0.000000
Africa                                 20.000000   0.000000     0.000000

Research category_split  Strain development  Target molecule selection  \
Funder region_split
Europe                             6.050798                   1.872645
North America                      3.266500                   0.587144
Asia/Asia Pacific                  4.780057                   3.403618
Middle East                        0.000000                   0.000000
Global                             0.000000                   0.000000
South America                      0.714526                   0.000000
Africa                            20.000000                  20.000000

Research category_split  Texturization methods   Total (EUR)
Funder region_split
Europe                                2.800924  1.272965e+09
North America                         2.272713  3.721569e+08
Asia/Asia Pacific                     3.319655  2.811636e+08
Middle East                           0.553356  2.745611e+07
Global                                4.477223  3.338193e+06
South America                         0.722398  2.639045e+06
Africa                                0.000000  5.599000e+05
Saved 9a_research_category_pct_by_region_and_pillar -> data_output\analysis\9a_research_category_pct_by_region_and_pillar.csv

Research category_split            Bioprocess design  Cell culture media  \
AP pillar     Funder region_split
Cross-cutting Europe                        6.971188            1.939140
              North America                 1.409992            0.883320
              Asia/Asia Pacific             7.085718           10.876473
              Middle East                   0.000000            0.000000
              South America                 0.000000            0.000000
Cultivated    Europe                       23.436837           23.302620
              Asia/Asia Pacific            25.922480           14.552847
              North America                15.346484           19.451552
              Middle East                   0.000000            0.000000
              Global                       41.148748           22.574296
              South America                 0.000000            7.756236
Fermentation  Europe                       25.493132                 NaN
              North America                 8.177337                 NaN
              Asia/Asia Pacific            24.165397                 NaN
              Global                       16.025641                 NaN
              Africa                       20.000000                 NaN
              Middle East                   0.000000                 NaN
              South America                 9.793715                 NaN
Plant-based   Europe                             NaN                 NaN
              North America                      NaN                 NaN
              Asia/Asia Pacific                  NaN                 NaN
              Global                             NaN                 NaN
              South America                      NaN                 NaN

Research category_split            Cell line development  \
AP pillar     Funder region_split
Cross-cutting Europe                            1.939140
              North America                     0.464250
              Asia/Asia Pacific                 6.631795
              Middle East                       0.000000
              South America                     0.000000
Cultivated    Europe                           11.337010
              Asia/Asia Pacific                 5.890802
              North America                    13.576225
              Middle East                       0.000000
              Global                            9.013663
              South America                    26.514201
Fermentation  Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              Global                                 NaN
              Africa                                 NaN
              Middle East                            NaN
              South America                          NaN
Plant-based   Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              Global                                 NaN
              South America                          NaN

Research category_split            Consumer & market research  \
AP pillar     Funder region_split
Cross-cutting Europe                                 1.746183
              North America                          0.323891
              Asia/Asia Pacific                      2.484506
              Middle East                            0.000000
              South America                          0.000000
Cultivated    Europe                                 2.694817
              Asia/Asia Pacific                      1.962577
              North America                          5.509458
              Middle East                            0.000000
              Global                                 0.000000
              South America                          0.000000
Fermentation  Europe                                 2.696141
              North America                          0.145464
              Asia/Asia Pacific                      0.000000
              Global                                 0.000000
              Africa                                 0.000000
              Middle East                            0.000000
              South America                          0.000000
Plant-based   Europe                                10.446915
              North America                          0.542573
              Asia/Asia Pacific                      9.485258
              Global                                 0.000000
              South America                          3.055098

Research category_split            Crop development  End product formulation  \
AP pillar     Funder region_split
Cross-cutting Europe                       0.708598                 3.224800
              North America                0.337592                 0.856361
              Asia/Asia Pacific            0.475141                11.325525
              Middle East                  0.000000                 0.000000
              South America                0.000000               100.000000
Cultivated    Europe                            NaN                 7.444316
              Asia/Asia Pacific                 NaN                 5.150460
              North America                     NaN                10.825417
              Middle East                       NaN                 1.354029
              Global                            NaN                 0.000000
              South America                     NaN                 0.000000
Fermentation  Europe                            NaN                 8.927312
              North America                     NaN                 3.308521
              Asia/Asia Pacific                 NaN                 6.003958
              Global                            NaN                26.709402
              Africa                            NaN                20.000000
              Middle East                       NaN                33.333333
              South America                     NaN                11.210719
Plant-based   Europe                       9.881117                17.860609
              North America               12.788701                22.474922
              Asia/Asia Pacific            1.008604                18.436282
              Global                       0.000000                36.631016
              South America                6.268010                43.594458

Research category_split            Feedstocks  Food safety & quality  \
AP pillar     Funder region_split
Cross-cutting Europe                 4.912811               5.634170
              North America          0.640067               0.276549
              Asia/Asia Pacific      2.996236               8.757283
              Middle East            0.000000               0.000000
              South America          0.000000               0.000000
Cultivated    Europe                      NaN               3.265166
              Asia/Asia Pacific           NaN               8.639630
              North America               NaN               3.755245
              Middle East                 NaN               0.000000
              Global                      NaN               0.000000
              South America               NaN               0.000000
Fermentation  Europe                14.906724               1.621662
              North America         19.302947               0.342643
              Asia/Asia Pacific     10.430676               2.792682
              Global                 0.000000               0.000000
              Africa                 0.000000               0.000000
              Middle East            0.000000              33.333333
              South America          0.000000               9.793715
Plant-based   Europe                      NaN               3.560510
              North America               NaN               1.311694
              Asia/Asia Pacific           NaN               0.274534
              Global                      NaN               0.000000
              South America               NaN               3.544289

Research category_split            Health & nutrition  Impact Assessments  \
AP pillar     Funder region_split
Cross-cutting Europe                         3.581136            3.568633
              North America                  0.483633            0.878540
              Asia/Asia Pacific              0.927017            0.612017
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Cultivated    Europe                         0.314254            9.326361
              Asia/Asia Pacific              1.260408            0.000000
              North America                  0.391042            6.949685
              Middle East                    0.000000            0.000000
              Global                         0.000000            2.479336
              South America                  0.000000            0.000000
Fermentation  Europe                         2.694331            6.429439
              North America                  2.078380            0.239060
              Asia/Asia Pacific              4.384194            0.000000
              Global                         0.000000            0.000000
              Africa                         0.000000            0.000000
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Plant-based   Europe                        11.749412            6.203103
              North America                  6.518554            0.956215
              Asia/Asia Pacific             18.097730            7.786768
              Global                         0.000000           10.695187
              South America                  6.918770            5.384311

Research category_split            Ingredient optimisation       Other  \
AP pillar     Funder region_split
Cross-cutting Europe                              5.006310   52.933919
              North America                       0.941440   89.575569
              Asia/Asia Pacific                  11.288481   13.607779
              Middle East                         0.000000  100.000000
              South America                       0.000000    0.000000
Cultivated    Europe                                   NaN    3.215269
              Asia/Asia Pacific                        NaN   31.420913
              North America                            NaN    4.140555
              Middle East                              NaN   97.291942
              Global                                   NaN   16.905590
              South America                            NaN   65.729563
Fermentation  Europe                             12.140707    3.686489
              North America                       4.475349   52.671283
              Asia/Asia Pacific                   9.481102   18.021547
              Global                             46.581197    0.000000
              Africa                             20.000000    0.000000
              Middle East                         0.000000    0.000000
              South America                      21.004434   48.197417
Plant-based   Europe                             28.576433    3.593502
              North America                      29.497885   17.782005
              Asia/Asia Pacific                  34.938469    0.526931
              Global                             42.780749    0.000000
              South America                      24.117721    0.000000

Research category_split            Scaffolding  Strain development  \
AP pillar     Funder region_split
Cross-cutting Europe                  1.877382            3.217339
              North America           0.665340            1.055032
              Asia/Asia Pacific       5.532405            7.327915
              Middle East             0.000000            0.000000
              South America           0.000000            0.000000
Cultivated    Europe                 15.663351                 NaN
              Asia/Asia Pacific       5.199883                 NaN
              North America          20.054338                 NaN
              Middle East             1.354029                 NaN
              Global                  7.878367                 NaN
              South America           0.000000                 NaN
Fermentation  Europe                       NaN           13.694201
              North America                NaN            7.023641
              Asia/Asia Pacific            NaN           12.437247
              Global                       NaN            0.000000
              Africa                       NaN           20.000000
              Middle East                  NaN            0.000000
              South America                NaN            0.000000
Plant-based   Europe                       NaN            3.675853
              North America                NaN            1.641440
              Asia/Asia Pacific            NaN            0.447330
              Global                       NaN            0.000000
              South America                NaN            3.539177

Research category_split            Target molecule selection  \
AP pillar     Funder region_split
Cross-cutting Europe                                1.299401
              North America                         0.878032
              Asia/Asia Pacific                     3.439915
              Middle East                           0.000000
              South America                         0.000000
Cultivated    Europe                                     NaN
              Asia/Asia Pacific                          NaN
              North America                              NaN
              Middle East                                NaN
              Global                                     NaN
              South America                              NaN
Fermentation  Europe                                5.950210
              North America                         0.996700
              Asia/Asia Pacific                    12.283197
              Global                                0.000000
              Africa                               20.000000
              Middle East                           0.000000
              South America                         0.000000
Plant-based   Europe                                     NaN
              North America                              NaN
              Asia/Asia Pacific                          NaN
              Global                                     NaN
              South America                              NaN

Research category_split            Texturization methods   Total (EUR)
AP pillar     Funder region_split
Cross-cutting Europe                            1.439851  2.254572e+08
              North America                     0.330391  9.504176e+07

In [70]:
tier_category_pct = category_pct_table(tier_split, '_tiers', 'tier_weighted_funding').reindex(['EU', 'EU+', 'Europe'])
save(tier_category_pct, '9a_research_category_pct_by_eu_tier')
print(tier_category_pct)

tier_category_pct_by_pillar = category_pct_by_pillar(tier_split, '_tiers', 'tier_weighted_funding')
save(tier_category_pct_by_pillar, '9a_research_category_pct_by_eu_tier_and_pillar')
print()
print(tier_category_pct_by_pillar)

Saved 9a_research_category_pct_by_eu_tier -> data_output\analysis\9a_research_category_pct_by_eu_tier.csv
Research category_split  Bioprocess design  Cell culture media  \
_tiers
EU                                9.900253            1.466121
EU+                              10.245295            2.292878
Europe                           10.244087            2.304391

Research category_split  Cell line development  Consumer & market research  \
_tiers
EU                                    0.864438                    6.236502
EU+                                   1.297622                    6.114747
Europe                                1.297469                    6.114026

Research category_split  Crop development  End product formulation  \
_tiers
EU                               4.542430                12.590099
EU+                              4.698000                11.927332
Europe                           4.697446                11.925927

Research category_split  Feedstocks  Food safety & quality  \
_tiers
EU                         4.714571               3.293937
EU+                        4.985581               3.368120
Europe                     4.984994               3.367723

Research category_split  Health & nutrition  Impact Assessments  \
_tiers
EU                                 6.348176            6.632445
EU+                                6.841656            6.062526
Europe                             6.840850            6.061811

Research category_split  Ingredient optimisation      Other  Scaffolding  \
_tiers
EU                                     18.270553  14.412992     1.120896
EU+                                    17.462253  12.327567     1.650793
Europe                                 17.460195  12.326114     1.650598

Research category_split  Strain development  Target molecule selection  \
_tiers
EU                                 5.674872                   1.492705
EU+                                6.051511                   1.872866
Europe                             6.050798                   1.872645

Research category_split  Texturization methods   Total (EUR)
_tiers
EU                                    2.439009  1.038998e+09
EU+                                   2.801254  1.272815e+09
Europe                                2.800924  1.272965e+09
Saved 9a_research_category_pct_by_eu_tier_and_pillar -> data_output\analysis\9a_research_category_pct_by_eu_tier_and_pillar.csv

Research category_split  Bioprocess design  Cell culture media  \
AP pillar     _tiers
Cross-cutting EU+                 6.971188            1.939140
              Europe              6.971188            1.939140
              EU                  4.719343            0.107617
Cultivated    Europe             23.436837           23.302620
              EU+                23.469700           23.195075
              EU                 20.480126           20.414659
Fermentation  EU+                25.493132                 NaN
              Europe             25.493132                 NaN
              EU                 26.866192                 NaN
Plant-based   EU+                      NaN                 NaN
              Europe                   NaN                 NaN
              EU                       NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
AP pillar     _tiers
Cross-cutting EU+                     1.939140                    1.746183
              Europe                  1.939140                    1.746183
              EU                      0.107617                    0.177639
Cultivated    Europe                 11.337010                    2.694817
              EU+                    11.352907                    2.698595
              EU                     11.938013                    3.752887
Fermentation  EU+                          NaN                    2.696141
              Europe                       NaN                    2.696141
              EU                           NaN                    3.067562
Plant-based   EU+                          NaN                   10.446915
              Europe                       NaN                   10.446915
              EU                           NaN                   10.462127

Research category_split  Crop development  End product formulation  \
AP pillar     _tiers
Cross-cutting EU+                0.708598                 3.224800
              Europe             0.708598                 3.224800
              EU                 0.008406                 3.087630
Cultivated    Europe                  NaN                 7.444316
              EU+                     NaN                 7.454754
              EU                      NaN                 9.315331
Fermentation  EU+                     NaN                 8.927312
              Europe                  NaN                 8.927312
              EU                      NaN                 9.136014
Plant-based   EU+                9.881117                17.860609
              Europe             9.881117                17.860609
              EU                 9.383740                18.228778

Research category_split  Feedstocks  Food safety & quality  \
AP pillar     _tiers
Cross-cutting EU+          4.912811               5.634170
              Europe       4.912811               5.634170
              EU           2.053565               4.671681
Cultivated    Europe            NaN               3.265166
              EU+               NaN               3.269744
              EU                NaN               3.038503
Fermentation  EU+         14.906724               1.621662
              Europe      14.906724               1.621662
              EU          15.317029               1.816992
Plant-based   EU+               NaN               3.560510
              Europe            NaN               3.560510
              EU                NaN               3.754555

Research category_split  Health & nutrition  Impact Assessments  \
AP pillar     _tiers
Cross-cutting EU+                  3.581136            3.568633
              Europe               3.581136            3.568633
              EU                   3.599283            4.595673
Cultivated    Europe               0.314254            9.326361
              EU+                  0.314694            9.339438
              EU                   0.456456           11.095333
Fermentation  EU+                  2.694331            6.429439
              Europe               2.694331            6.429439
              EU                   2.087828            7.338063
Plant-based   EU+                 11.749412            6.203103
              Europe              11.749412            6.203103
              EU                  10.635537            6.227313

Research category_split  Ingredient optimisation      Other  Scaffolding  \
AP pillar     _tiers
Cross-cutting EU+                       5.006310  52.933919     1.877382
              Europe                    5.006310  52.933919     1.877382
              EU                        3.693323  69.561090     0.199140
Cultivated    Europe                         NaN   3.215269    15.663351
              EU+                            NaN   3.219777    15.685314
              EU                             NaN   4.162055    15.346637
Fermentation  EU+                      12.140707   3.686489          NaN
              Europe                   12.140707   3.686489          NaN
              EU                       12.490527   3.929243          NaN
Plant-based   EU+                      28.576433   3.593502          NaN
              Europe                   28.576433   3.593502          NaN
              EU                       29.148537   4.056886          NaN

Research category_split  Strain development  Target molecule selection  \
AP pillar     _tiers
Cross-cutting EU+                  3.217339                   1.299401
              Europe               3.217339                   1.299401
              EU                   1.729722                   0.665396
Cultivated    Europe                    NaN                        NaN
              EU+                       NaN                        NaN
              EU                        NaN                        NaN
Fermentation  EU+                 13.694201                   5.950210
              Europe              13.694201                   5.950210
              EU                  12.035561                   4.841192
Plant-based   EU+                  3.675853                        NaN
              Europe               3.675853                        NaN
              EU                   4.033468                        NaN

Research category_split  Texturization methods   Total (EUR)
AP pillar     _tiers
Cross-cutting EU+                     1.439851  2.254572e+08
              Europe                  1.439851  2.254572e+08
              EU                      1.022875  1.647256e+08
Cultivated    Europe                       NaN  1.071217e+08
              EU+                          NaN  1.069717e+08
              EU                           NaN  7.374943e+07
Fermentation  EU+                     1.759653  3.513914e+08
              Europe                  1.759653  3.513914e+08
              EU                      1.073798  2.977180e+08
Plant-based   EU+                     4.452546  5.889948e+08
              Europe                  4.452546  5.889948e+08
              EU                      4.069059  5.028050e+08

### 9b. Research category as a % of total funding, by country - overall, and by AP pillar

In [71]:
country_category_pct = category_pct_table(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct, '9b_research_category_pct_by_country')
print(country_category_pct)

country_category_pct_by_pillar = category_pct_by_pillar(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_by_pillar, '9b_research_category_pct_by_country_and_pillar')
print()
print(country_category_pct_by_pillar)

Saved 9b_research_category_pct_by_country -> data_output\analysis\9b_research_category_pct_by_country.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder Country_split
EU                               11.737117            1.478546
United States                     5.558337            2.316493
Denmark                          12.662765            0.522068
United Kingdom                   12.609021            8.600747
South Korea                      17.444499            9.342214
Netherlands                       4.777105            2.669911
Singapore                        15.089249            3.764120
Germany                           5.062017            0.710331
Finland                          14.454670            0.314991
Canada                            2.640789            2.911334
Norway                           10.121437            1.736356
Sweden                            1.736568            0.230849
Spain                             6.719447            4.375153
France                            3.005948            0.000000
New Zealand                       7.295102            8.140037
Israel                            0.000000            0.000000
Switzerland                      10.737583            0.217401
Japan                            34.044760           35.081630
Poland                           10.064336            9.434726
Portugal                          6.809871            2.055218
Australia                         0.000000            0.000000
Ireland                          12.993763            0.000000
Austria                          17.272480            0.000000
Estonia                           4.029116            0.000000
Czechia                           0.000000            8.967859
China                             1.072054            0.000000
Belgium                          20.000000           20.000000
Global                           26.362429           12.716364
Brazil                            0.449814            5.755497
South Africa                     20.000000            0.000000
Slovakia                          0.000000            0.000000
Uruguay                           0.000000            0.000000
Serbia                            0.000000          100.000000
Croatia                           0.000000            0.000000
Latvia                            0.000000            0.000000
Chile                                  NaN                 NaN
Iceland                                NaN                 NaN
Malaysia                               NaN                 NaN
Italy                                  NaN                 NaN
Russia                                 NaN                 NaN
Turkey                                 NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
Funder Country_split
EU                                    0.218016                    8.774040
United States                         1.541134                    1.034693
Denmark                               0.443447                    3.181475
United Kingdom                        4.800849                    3.258684
South Korea                           6.065584                    0.000000
Netherlands                           3.462910                    3.809717
Singapore                             2.256169                    2.803278
Germany                               1.711609                    4.498287
Finland                               0.314991                    2.767671
Canada                                2.174402                    0.245773
Norway                                0.594575                   10.206345
Sweden                                0.000000                    9.540901
Spain                                 4.139731                    1.006515
France                                0.000000                    5.743470
New Zealand                           5.808940                   15.247091
Israel                                0.000000                    0.000000
Switzerland                           0.000000                    8.443429
Japan                                 0.352501                    3.979293
Poland                                0.000000                    0.695574
Portugal                              2.055218                    1.161203
Australia                             0.000000                    4.020274
Ireland                               0.000000                   12.613720
Austria                               0.000000                    0.000000
Estonia                               0.000000                    0.000000
Czechia                               0.000000                   50.939958
China                                 1.072054                    0.000000
Belgium                              20.000000                    0.000000
Global                                5.077501                    0.000000
Brazil                               19.674804                    0.000000
South Africa                          0.000000                    0.000000
Slovakia                              0.000000                    0.000000
Uruguay                               0.000000                    3.055098
Serbia                                0.000000                    0.000000
Croatia                               0.000000                    0.000000
Latvia                                0.000000                    0.000000
Chile                                      NaN                         NaN
Iceland                                    NaN                         NaN
Malaysia                                   NaN                         NaN
Italy                                      NaN                         NaN
Russia                                     NaN                         NaN
Turkey                                     NaN                         NaN

Research category_split  Crop development  End product formulation  \
Funder Country_split
EU                               2.738675                13.582692
United States                    3.247576                 4.235815
Denmark                          4.513992                 9.948399
United Kingdom                   7.189054                 7.807557
South Korea                      0.315088                 9.374280
Netherlands                      1.560073                 2.938007
Singapore                        0.000000                 7.548412
Germany                         16.689909                13.262198
Finland                          1.107567                10.068663
Canada                           4.814142                30.488479
Norway                           1.707581                 9.853148
Sweden                           4.719720                15.945495
Spain                            6.033096                11.352648
France                          18.861266                26.191180
New Zealand                      0.000000                 7.975960
Israel                           0.000000                 1.416843
Switzerland                      3.349743                13.970398
Japan                            0.000000                 0.361932
Poland                           0.000000                41.847084
Portugal                         1.771524                16.177895
Australia                        4.782213                45.551112
Ireland                          0.000000                21.826909
Austria                          0.000000                 3.198607
Estonia                          0.000000                15.108344
Czechia                          9.062357                 1.861896
China                            0.000000                 5.025836
Belgium                          0.000000                20.000000
Global                           0.000000                14.025801
Brazil                           0.000000                21.717232
South Africa                     0.000000                20.000000
Slovakia                         0.000000                27.924069
Uruguay                          6.268010                43.594458
Serbia                           0.000000                 0.000000
Croatia                          0.000000                 0.000000
Latvia                           0.000000                33.333333
Chile                                 NaN                      NaN
Iceland                               NaN                      NaN
Malaysia                              NaN                      NaN
Italy                                 NaN                      NaN
Russia                                NaN                      NaN
Turkey                                NaN                      NaN

Research category_split  Feedstocks  Food safety & quality  \
Funder Country_split
EU                         5.781346               4.607575
United States              8.557516               1.129449
Denmark                   11.343831               3.341095
United Kingdom             5.489184               2.880944
South Korea                1.735291               5.518654
Netherlands                0.269622               1.765040
Singapore                  4.280558              11.002779
Germany                    0.657566               1.652671
Finland                    1.835021               0.727166
Canada                     0.459442               0.182497
Norway                     9.847553               6.336612
Sweden                     1.714531               4.029783
Spain                      2.111453               3.538663
France                     0.000000               0.000000
New Zealand                4.902813               3.279324
Israel                     0.000000               0.553356
Switzerland                1.674534               2.313117
Japan                      0.762109               2.984571
Poland                     0.367135               0.367135
Portugal                   0.132627               3.324087
Australia                  9.279682               0.000000
Ireland                    0.000000               0.000000
Austria                    0.000000               0.000000
Estonia                    0.719683              13.016388
Czechia                    0.000000               0.000000
China                      0.000000               2.178042
Belgium                    0.000000               0.000000
Global                     0.000000               0.000000
Brazil                     0.000000               0.449814
South Africa               0.000000               0.000000
Slovakia                  27.924069               1.613515
Uruguay                    0.000000               3.544289
Serbia                     0.000000               0.000000
Croatia                    0.000000               0.000000
Latvia                     0.000000               0.000000
Chile                           NaN                    NaN
Iceland                         NaN                    NaN
Malaysia                        NaN                    NaN
Italy                           NaN                    NaN
Russia                          NaN                    NaN
Turkey                          NaN                    NaN

Research category_split  Health & nutrition  Impact Assessments  \
Funder Country_split
EU                                 7.743235           11.974782
United States                      2.619520            1.528322
Denmark                            6.818564            3.174690
United Kingdom                     7.923459            3.199083
South Korea                        0.095114            0.315088
Netherlands                        2.790457            2.218842
Singapore                          7.811373            0.000000
Germany                            2.798419            1.692598
Finland                            1.465537            1.509929
Canada                             2.921020            0.473358
Norway                            12.516152            2.963911
Sweden                            12.339342            5.657249
Spain                              4.837425            1.018734
France                            11.322818            0.000000
New Zealand                       14.284079            7.416242
Israel                             0.000000            0.000000
Switzerland                        7.408260            6.872136
Japan                              0.280073            0.000000
Poland                             2.378054            0.000000
Portugal                           0.332586            6.097294
Australia                          0.000000           10.390926
Ireland                           21.131753            0.000000
Austria                            0.000000           17.272480
Estonia                            0.000000            0.524649
Czechia                            1.861896            0.000000
China                              0.907648            0.000000
Belgium                            0.000000            0.000000
Global                             0.000000            3.942926
Brazil                             0.000000            0.000000
South Africa                       0.000000            0.000000
Slovakia                           1.613515            0.000000
Uruguay                            6.918770            5.384311
Serbia                             0.000000            0.000000
Croatia                           33.333333            0.000000
Latvia                             0.000000            0.000000
Chile                                   NaN                 NaN
Iceland                                 NaN                 NaN
Malaysia                                NaN                 NaN
Italy                                   NaN                 NaN
Russia                                  NaN                 NaN
Turkey                                  NaN                 NaN

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder Country_split
EU                                     20.163993   3.446606     0.734551
United States                           5.205341  54.657805     2.434372
Denmark                                19.738344   1.414765     0.443447
United Kingdom                         10.166643   4.079753     5.077504
South Korea                             9.104529  22.296692     4.824943
Netherlands                             3.038857  63.637390     3.751927
Singapore                               7.017653  22.885570     3.103563
Germany                                30.614440   8.035141     1.802324
Finland                                10.230779  46.079953     0.000000
Canada                                 32.280615  10.928892     2.402750
Norway                                 22.218513   1.774488     0.105977
Sweden                                 20.849494  17.440435     0.297164
Spain                                  11.086548  31.108330     4.320772
France                                 20.260609   8.091802     0.000000
New Zealand                            14.732951   0.000000     3.049145
Israel                                  0.000000  96.612958     0.863487
Switzerland                            16.226836   0.000000     6.863654
Japan                                  16.083000   3.585789     1.080741
Poland                                 34.442129   0.000000     0.000000
Portugal                                5.452568  52.452666     2.044617
Australia                              18.409355   4.612358     0.000000
Ireland                                22.023787   0.000000     0.000000
Austria                                 3.198607  38.586739     0.000000
Estonia                                18.809321   0.000000     0.000000
Czechia                                12.901331  12.542807     0.000000
China                                  15.776644  68.509306     0.000000
Belgium                                 0.000000   0.000000    20.000000
Global                                 19.436663   9.523116     4.437976
Brazil                                  0.964710  50.988128     0.000000
South Africa                           20.000000   0.000000     0.000000
Slovakia                               40.924833   0.000000     0.000000
Uruguay                                24.117721   0.000000     0.000000
Serbia                                  0.000000   0.000000     0.000000
Croatia                                33.333333   0.000000     0.000000
Latvia                                 33.333333   0.000000     0.000000
Chile                                        NaN        NaN          NaN
Iceland                                      NaN        NaN          NaN
Malaysia                                     NaN        NaN          NaN
Italy                                        NaN        NaN          NaN
Russia                                       NaN        NaN          NaN
Turkey                                       NaN        NaN          NaN

Research category_split  Strain development  Target molecule selection  \
Funder Country_split
EU                                 4.469171                   1.331183
United States                      3.447266                   0.678545
Denmark                           14.508244                   2.233868
United Kingdom                     9.592805                   3.838401
South Korea                        5.274613                   2.585765
Netherlands                        2.676339                   0.280498
Singapore                          5.838059                   5.838059
Germany                            3.822264                   0.797671
Finland                            4.448731                   3.891194
Canada                             2.375325                   0.136536
Norway                             5.037609                   4.358296
Sweden                             1.995732                   0.624950
Spain                              3.242455                   0.648358
France                             0.000000                   3.005948
New Zealand                        3.679838                   3.679838
Israel                             0.000000                   0.000000
Switzerland                        2.904241                   0.000000
Japan                              0.557088                   0.113691
Poland                             0.293754                   0.000000
Portugal                           0.132627                   0.000000
Australia                          0.000000                   0.000000
Ireland                            9.410068                   0.000000
Austria                           17.272480                   0.000000
Estonia                           41.099986                   6.477147
Czechia                            1.861896                   0.000000
China                              0.536027                   0.536027
Belgium                            0.000000                   0.000000
Global                             0.000000                   0.000000
Brazil                             0.000000                   0.000000
South Africa                      20.000000                  20.000000
Slovakia                           0.000000                   0.000000
Uruguay                            3.539177                   0.000000
Serbia                             0.000000                   0.000000
Croatia                           33.333333                   0.000000
Latvia                             0.000000                   0.000000
Chile                                   NaN                        NaN
Iceland                                 NaN                        NaN
Malaysia                                NaN                        NaN
Italy                                   NaN                        NaN

### 9c. Research category as a % of total funding, excl. non-profit funding

Non-profit-excluded twin of 9a/9b, for region, EU / EU+ / Europe, and country. Reuses
`region_split_np` / `tier_split_np` from 4c and `country_split_np` from 3b.

Named **9c**, not 9b - `9b_*` is already the by-country cut of the unfiltered analysis above.

Unlike 4a/4c these tables are **not** reindexed onto 9a/9b's row list. Every figure here is a
percentage of that row's own classified total, and a row left with no funding has no meaningful
percentage (0/0); a row that disappears did so because 100% of its money was non-profit. In the
current data that is `'Global'` in the region cut.

In [72]:
region_category_pct_np = category_pct_table(region_split_np, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_np, '9c_research_category_pct_by_region_excl_nonprofit')
print(region_category_pct_np)

region_category_pct_by_pillar_np = category_pct_by_pillar(region_split_np, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_by_pillar_np, '9c_research_category_pct_by_region_and_pillar_excl_nonprofit')
print()
print(region_category_pct_by_pillar_np)

Saved 9c_research_category_pct_by_region_excl_nonprofit -> data_output\analysis\9c_research_category_pct_by_region_excl_nonprofit.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder region_split
Europe                            9.746582            2.495920
Asia/Asia Pacific                16.126752            8.851132
North America                     6.234931            2.620023
Middle East                       0.000000            0.000000
South America                     0.359001            4.593517
Africa                           20.000000            0.000000

Research category_split  Cell line development  Consumer & market research  \
Funder region_split
Europe                                1.381158                    6.467449
Asia/Asia Pacific                     4.313112                    2.707260
North America                         1.960065                    1.340244
Middle East                           0.000000                    0.000000
South America                        15.702649                    0.616795
Africa                                0.000000                    0.000000

Research category_split  Crop development  End product formulation  \
Funder region_split
Europe                           4.597609                12.526630
Asia/Asia Pacific                0.282955                 9.007458
North America                    3.819744                11.120832
Middle East                      0.000000                 1.436357
South America                    1.265451                26.134035
Africa                           0.000000                20.000000

Research category_split  Feedstocks  Food safety & quality  \
Funder region_split
Europe                     4.099526               3.366287
Asia/Asia Pacific          2.915588               6.567415
North America              6.151515               1.300304
Middle East                0.000000               0.560977
South America              0.000000               1.074559
Africa                     0.000000               0.000000

Research category_split  Health & nutrition  Impact Assessments  \
Funder region_split
Europe                             7.168217            6.264115
Asia/Asia Pacific                  3.810583            1.168267
North America                      3.366756            1.924869
Middle East                        0.000000            0.000000
South America                      1.396833            1.087041
Africa                             0.000000            0.000000

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder region_split
Europe                                 17.462140  13.618328     1.772107
Asia/Asia Pacific                       9.826956  19.207968     3.709965
North America                          13.012118  36.127374     2.938336
Middle East                             0.000000  96.566309     0.875380
South America                           5.639082  40.694112     0.000000
Africa                                 20.000000   0.000000     0.000000

Research category_split  Strain development  Target molecule selection  \
Funder region_split
Europe                             4.780816                   1.787485
Asia/Asia Pacific                  4.780580                   3.403990
North America                      4.733986                   0.804439
Middle East                        0.000000                   0.000000
South America                      0.714526                   0.000000
Africa                            20.000000                  20.000000

Research category_split  Texturization methods   Total (EUR)
Funder region_split
Europe                                2.465633  1.149820e+09
Asia/Asia Pacific                     3.320018  2.811329e+08
North America                         2.544463  2.503700e+08
Middle East                           0.560977  2.708310e+07
South America                         0.722398  2.639045e+06
Africa                                0.000000  5.599000e+05
Saved 9c_research_category_pct_by_region_and_pillar_excl_nonprofit -> data_output\analysis\9c_research_category_pct_by_region_and_pillar_excl_nonprofit.csv

Research category_split            Bioprocess design  Cell culture media  \
AP pillar     Funder region_split
Cross-cutting Europe                        6.801844            1.888375
              Asia/Asia Pacific             7.085718           10.876473
              North America                 9.508942            5.957079
              Middle East                   0.000000            0.000000
              South America                 0.000000            0.000000
Cultivated    Europe                       23.511950           23.374799
              Asia/Asia Pacific            25.930363           14.557273
              North America                14.435523           17.219959
              Middle East                   0.000000            0.000000
              South America                 0.000000            7.756236
Fermentation  Europe                       24.561428                 NaN
              North America                 7.999362                 NaN
              Asia/Asia Pacific            24.165397                 NaN
              Africa                       20.000000                 NaN
              Middle East                   0.000000                 NaN
              South America                 9.793715                 NaN
Plant-based   Europe                             NaN                 NaN
              North America                      NaN                 NaN
              Asia/Asia Pacific                  NaN                 NaN
              South America                      NaN                 NaN

Research category_split            Cell line development  \
AP pillar     Funder region_split
Cross-cutting Europe                            1.888375
              Asia/Asia Pacific                 6.631795
              North America                     3.130888
              Middle East                       0.000000
              South America                     0.000000
Cultivated    Europe                           11.147679
              Asia/Asia Pacific                 5.862183
              North America                    13.444832
              Middle East                       0.000000
              South America                    26.514201
Fermentation  Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              Africa                                 NaN
              Middle East                            NaN
              South America                          NaN
Plant-based   Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              South America                          NaN

Research category_split            Consumer & market research  \
AP pillar     Funder region_split
Cross-cutting Europe                                 1.764231
              Asia/Asia Pacific                      2.484506
              North America                          2.184312
              Middle East                            0.000000
              South America                          0.000000
Cultivated    Europe                                 2.753712
              Asia/Asia Pacific                      1.963174
              North America                          6.953214
              Middle East                            0.000000
              South America                          0.000000
Fermentation  Europe                                 3.217955
              North America                          0.166415
              Asia/Asia Pacific                      0.000000
              Africa                                 0.000000
              Middle East                            0.000000
              South America                          0.000000
Plant-based   Europe                                10.991500
              North America                          0.639233
              Asia/Asia Pacific                      9.485258
              South America                          3.055098

Research category_split            Crop development  End product formulation  \
AP pillar     Funder region_split
Cross-cutting Europe                       0.719210                 2.999349
              Asia/Asia Pacific            0.475141                11.325525
              North America                2.276709                 5.775268
              Middle East                  0.000000                 0.000000
              South America                0.000000               100.000000
Cultivated    Europe                            NaN                 7.169909
              Asia/Asia Pacific                 NaN                 5.152027
              North America                     NaN                11.370232
              Middle East                       NaN                 1.383502
              South America                     NaN                 0.000000
Fermentation  Europe                            NaN                10.619457
              North America                     NaN                 3.668955
              Asia/Asia Pacific                 NaN                 6.003958
              Africa                            NaN                20.000000
              Middle East                       NaN                33.333333
              South America                     NaN                11.210719
Plant-based   Europe                       9.701355                18.656536
              North America               10.923667                22.345181
              Asia/Asia Pacific            1.008604                18.436282
              South America                6.268010                43.594458

Research category_split            Feedstocks  Food safety & quality  \
AP pillar     Funder region_split
Cross-cutting Europe                 4.906582               5.444802
              Asia/Asia Pacific      2.996236               8.757283
              North America          4.316594               1.865040
              Middle East            0.000000               0.000000
              South America          0.000000               0.000000
Cultivated    Europe                      NaN               3.336526
              Asia/Asia Pacific           NaN               8.642258
              North America               NaN               4.461870
              Middle East                 NaN               0.000000
              South America               NaN               0.000000
Fermentation  Europe                12.308710               1.929838
              North America         12.489269               0.295366
              Asia/Asia Pacific     10.430676               2.792682
              Africa                 0.000000               0.000000
              Middle East            0.000000              33.333333
              South America          0.000000               9.793715
Plant-based   Europe                      NaN               3.298776
              North America               NaN               1.371818
              Asia/Asia Pacific           NaN               0.274534
              South America               NaN               3.544289

Research category_split            Health & nutrition  Impact Assessments  \
AP pillar     Funder region_split
Cross-cutting Europe                         3.554962            3.592231
              Asia/Asia Pacific              0.927017            0.612017
              North America                  3.261602            5.924848
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Cultivated    Europe                         0.321122            9.530190
              Asia/Asia Pacific              1.260791            0.000000
              North America                  0.493515            8.739384
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Fermentation  Europe                         3.185820            7.673799
              North America                  1.219425            0.234402
              Asia/Asia Pacific              4.384194            0.000000
              Africa                         0.000000            0.000000
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Plant-based   Europe                        12.264001            5.953955
              North America                  7.518370            0.949723
              Asia/Asia Pacific             18.097730            7.786768
              South America                  6.918770            5.384311

Research category_split            Ingredient optimisation       Other  \
AP pillar     Funder region_split
Cross-cutting Europe                              5.001480   53.726678
              Asia/Asia Pacific                  11.288481   13.607779
              North America                       6.349043   29.697981
              Middle East                         0.000000  100.000000
              South America                       0.000000    0.000000
Cultivated    Europe                                   NaN    3.285539
              Asia/Asia Pacific                        NaN   31.430468
              North America                            NaN    2.638705
              Middle East                              NaN   97.232995
              South America                            NaN   65.729563
Fermentation  Europe                             13.585477    4.291009
              North America                       3.556397   60.257346
              Asia/Asia Pacific                   9.481102   18.021547
              Africa                             20.000000    0.000000
              Middle East                         0.000000    0.000000
              South America                      21.004434   48.197417
Plant-based   Europe                             28.323728    4.005222
              North America                      32.467613   16.566387
              Asia/Asia Pacific                  34.938469    0.526931
              South America                      24.117721    0.000000

Research category_split            Scaffolding  Strain development  \
AP pillar     Funder region_split
Cross-cutting Europe                  1.825693            3.185717
              Asia/Asia Pacific       5.532405            7.327915
              North America           4.487029            7.115098
              Middle East             0.000000            0.000000
              South America           0.000000            0.000000
Cultivated    Europe                 15.568573                 NaN
              Asia/Asia Pacific       5.201464                 NaN
              North America          20.242767                 NaN
              Middle East             1.383502                 NaN
              South America           0.000000                 NaN
Fermentation  Europe                       NaN           10.540345
              North America                NaN            7.778554
              Asia/Asia Pacific            NaN           12.437247
              Africa                       NaN           20.000000
              Middle East                  NaN            0.000000
              South America                NaN            0.000000
Plant-based   Europe                       NaN            3.190931
              North America                NaN            1.933864
              Asia/Asia Pacific            NaN            0.447330
              South America                NaN            3.539177

Research category_split            Target molecule selection  \
AP pillar     Funder region_split
Cross-cutting Europe                                1.318861
              Asia/Asia Pacific                     3.439915
              North America                         5.921420
              Middle East                           0.000000
              South America                         0.000000
Cultivated    Europe                                     NaN
              Asia/Asia Pacific                          NaN
              North America                              NaN
              Middle East                                NaN
              South America                              NaN
Fermentation  Europe                                5.985945
              North America                         0.995865
              Asia/Asia Pacific                    12.283197
              Africa                               20.000000
              Middle East                           0.000000
              South America                         0.000000
Plant-based   Europe                                     NaN
              North America                              NaN
              Asia/Asia Pacific                          NaN
              South America                              NaN

Research category_split            Texturization methods   Total (EUR)
AP pillar     Funder region_split
Cross-cutting Europe                            1.381609  2.221305e+08
              Asia/Asia Pacific                 6.631795  9.348106e+07
              North America                     2.228148  1.409286e+07
              Middle East                       0.000000  9.491092e+06
              South America                     0.000000  4.465736e+05
Cultivated    Europe                                 NaN  1.048306e+08
              Asia/Asia Pacific                      NaN  1.010904e+08
              North America                          NaN  3.321859e+07
              Middle East                            NaN  1.713622e+07
              South America                          NaN  1.562936e+06
Fermentation  Europe                            2.100217  2.944108e+08
              North America                     1.338643  1.184474e+08
              Asia/Asia Pacific                 0.000000  5.172974e+07
              Africa                            0.000000  5.599000e+05
              Middle East                      33.333333  4.557900e+05
              South America                     0.000000  9.673755e+04
Plant-based   Europe                            3.613996  5.284485e+08
              North America                     5.284145  8.461114e+07
              Asia/Asia Pacific                 8.998093  3.483169e+07
              South America                     3.578167  5.327980e+05

In [73]:
tier_category_pct_np = category_pct_table(tier_split_np, '_tiers', 'tier_weighted_funding').reindex(['EU', 'EU+', 'Europe'])
save(tier_category_pct_np, '9c_research_category_pct_by_eu_tier_excl_nonprofit')
print(tier_category_pct_np)

tier_category_pct_by_pillar_np = category_pct_by_pillar(tier_split_np, '_tiers', 'tier_weighted_funding')
save(tier_category_pct_by_pillar_np, '9c_research_category_pct_by_eu_tier_and_pillar_excl_nonprofit')
print()
print(tier_category_pct_by_pillar_np)

Saved 9c_research_category_pct_by_eu_tier_excl_nonprofit -> data_output\analysis\9c_research_category_pct_by_eu_tier_excl_nonprofit.csv
Research category_split  Bioprocess design  Cell culture media  \
_tiers
EU                                9.205706            1.589770
EU+                               9.747853            2.483199
Europe                            9.746582            2.495920

Research category_split  Cell line development  Consumer & market research  \
_tiers
EU                                    0.908939                    6.740293
EU+                                   1.381338                    6.468293
Europe                                1.381158                    6.467449

Research category_split  Crop development  End product formulation  \
_tiers
EU                               4.466874                13.399045
EU+                              4.598209                12.528264
Europe                           4.597609                12.526630

Research category_split  Feedstocks  Food safety & quality  \
_tiers
EU                         3.557374               3.273778
EU+                        4.100061               3.366726
Europe                     4.099526               3.366287

Research category_split  Health & nutrition  Impact Assessments  \
_tiers
EU                                 6.680050            7.006085
EU+                                7.169152            6.264932
Europe                             7.168217            6.264115

Research category_split  Ingredient optimisation      Other  Scaffolding  \
_tiers
EU                                     18.351100  16.306683     1.199134
EU+                                    17.464418  13.620104     1.772338
Europe                                 17.462140  13.618328     1.772107

Research category_split  Strain development  Target molecule selection  \
_tiers
EU                                 4.019553                   1.331273
EU+                                4.781439                   1.787718
Europe                             4.780816                   1.787485

Research category_split  Texturization methods   Total (EUR)
_tiers
EU                                    1.964341  9.182129e+08
EU+                                   2.465954  1.149670e+09
Europe                                2.465633  1.149820e+09
Saved 9c_research_category_pct_by_eu_tier_and_pillar_excl_nonprofit -> data_output\analysis\9c_research_category_pct_by_eu_tier_and_pillar_excl_nonprofit.csv

Research category_split  Bioprocess design  Cell culture media  \
AP pillar     _tiers
Cross-cutting EU+                 6.801844            1.888375
              Europe              6.801844            1.888375
              EU                  4.439862            0.000000
Cultivated    Europe             23.511950           23.374799
              EU+                23.545640           23.265004
              EU                 20.495520           20.427954
Fermentation  EU+                24.561428                 NaN
              Europe             24.561428                 NaN
              EU                 26.019310                 NaN
Plant-based   EU+                      NaN                 NaN
              Europe                   NaN                 NaN
              EU                       NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
AP pillar     _tiers
Cross-cutting EU+                     1.888375                    1.764231
              Europe                  1.888375                    1.764231
              EU                      0.000000                    0.170148
Cultivated    Europe                 11.147679                    2.753712
              EU+                    11.163653                    2.757658
              EU                     11.679530                    3.873212
Fermentation  EU+                          NaN                    3.217955
              Europe                       NaN                    3.217955
              EU                           NaN                    3.788904
Plant-based   EU+                          NaN                   10.991500
              Europe                       NaN                   10.991500
              EU                           NaN                   11.189104

Research category_split  Crop development  End product formulation  \
AP pillar     _tiers
Cross-cutting EU+                0.719210                 2.999349
              Europe             0.719210                 2.999349
              EU                 0.008579                 2.774517
Cultivated    Europe                  NaN                 7.169909
              EU+                     NaN                 7.180183
              EU                      NaN                 8.972761
Fermentation  EU+                     NaN                10.619457
              Europe                  NaN                10.619457
              EU                      NaN                11.240811
Plant-based   EU+                9.701355                18.656536
              Europe             9.701355                18.656536
              EU                 9.227978                19.141097

Research category_split  Feedstocks  Food safety & quality  \
AP pillar     _tiers
Cross-cutting EU+          4.906582               5.444802
              Europe       4.906582               5.444802
              EU           1.986058               4.391218
Cultivated    Europe            NaN               3.336526
              EU+               NaN               3.341307
              EU                NaN               3.135923
Fermentation  EU+         12.308710               1.929838
              Europe      12.308710               1.929838
              EU          12.221654               2.237321
Plant-based   EU+               NaN               3.298776
              Europe            NaN               3.298776
              EU                NaN               3.452305

Research category_split  Health & nutrition  Impact Assessments  \
AP pillar     _tiers
Cross-cutting EU+                  3.554962            3.592231
              Europe               3.554962            3.592231
              EU                   3.563635            4.649319
Cultivated    Europe               0.321122            9.530190
              EU+                  0.321582            9.543846
              EU                   0.471091           11.451069
Fermentation  EU+                  3.185820            7.673799
              Europe               3.185820            7.673799
              EU                   2.542173            9.063620
Plant-based   EU+                 12.264001            5.953955
              Europe              12.264001            5.953955
              EU                  11.055412            6.031119

Research category_split  Ingredient optimisation      Other  Scaffolding  \
AP pillar     _tiers
Cross-cutting EU+                       5.001480  53.726678     1.825693
              Europe                    5.001480  53.726678     1.825693
              EU                        3.659614  70.994865     0.093410
Cultivated    Europe                         NaN   3.285539    15.568573
              EU+                            NaN   3.290247    15.590881
              EU                             NaN   4.295498    15.197441
Fermentation  EU+                      13.585477   4.291009          NaN
              Europe                   13.585477   4.291009          NaN
              EU                       14.322355   4.844649          NaN
Plant-based   EU+                      28.323728   4.005222          NaN
              Europe                   28.323728   4.005222          NaN
              EU                       28.824699   4.590906          NaN

Research category_split  Strain development  Target molecule selection  \
AP pillar     _tiers
Cross-cutting EU+                  3.185717                   1.318861
              Europe               3.185717                   1.318861
              EU                   1.655539                   0.679111
Cultivated    Europe                    NaN                        NaN
              EU+                       NaN                        NaN
              EU                        NaN                        NaN
Fermentation  EU+                 10.540345                   5.985945
              Europe              10.540345                   5.985945
              EU                   7.776258                   4.616642
Plant-based   EU+                  3.190931                        NaN
              Europe               3.190931                        NaN
              EU                   3.486764                        NaN

Research category_split  Texturization methods   Total (EUR)
AP pillar     _tiers
Cross-cutting EU+                     1.381609  2.221305e+08
              Europe                  1.381609  2.221305e+08
              EU                      0.934123  1.613989e+08
Cultivated    Europe                       NaN  1.048306e+08
              EU+                          NaN  1.046806e+08
              EU                           NaN  7.145834e+07
Fermentation  EU+                     2.100217  2.944108e+08
              Europe                  2.100217  2.944108e+08
              EU                      1.326303  2.410376e+08
Plant-based   EU+                     3.613996  5.284485e+08
              Europe                  3.613996  5.284485e+08
              EU                      3.000616  4.443180e+08

In [74]:
country_category_pct_np = category_pct_table(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_np, '9c_research_category_pct_by_country_excl_nonprofit')
print(country_category_pct_np)

country_category_pct_by_pillar_np = category_pct_by_pillar(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_by_pillar_np, '9c_research_category_pct_by_country_and_pillar_excl_nonprofit')
print()
print(country_category_pct_by_pillar_np)

Saved 9c_research_category_pct_by_country_excl_nonprofit -> data_output\analysis\9c_research_category_pct_by_country_excl_nonprofit.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder Country_split
EU                               11.737117            1.478546
United States                     7.302261            2.476801
United Kingdom                   12.739839            8.689979
South Korea                      17.444499            9.342214
Netherlands                       4.777105            2.669911
Singapore                        15.089249            3.764120
Germany                           5.062017            0.710331
Finland                          14.465832            0.315234
Norway                           10.121437            1.736356
Canada                            2.795220            3.081586
Sweden                            1.736568            0.230849
Denmark                           5.653579            0.509780
Spain                             6.719447            4.375153
France                            3.005948            0.000000
New Zealand                       7.295102            8.140037
Israel                            0.000000            0.000000
Switzerland                      11.105277            0.224845
Japan                            34.103094           35.141740
Poland                           10.064336            9.434726
Portugal                          6.809871            2.055218
Australia                         0.000000            0.000000
Ireland                          12.993763            0.000000
Austria                          17.272480            0.000000
Estonia                           4.050367            0.000000
Czechia                           0.000000            8.967859
China                             1.072054            0.000000
Belgium                          20.000000           20.000000
Brazil                            0.449814            5.755497
South Africa                     20.000000            0.000000
Slovakia                          0.000000            0.000000
Uruguay                           0.000000            0.000000
Serbia                            0.000000          100.000000
Croatia                           0.000000            0.000000
Latvia                            0.000000            0.000000
Chile                                  NaN                 NaN
Iceland                                NaN                 NaN
Malaysia                               NaN                 NaN
Italy                                  NaN                 NaN
Russia                                 NaN                 NaN
Turkey                                 NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
Funder Country_split
EU                                    0.218016                    8.774040
United States                         1.854101                    1.675394
United Kingdom                        4.850657                    2.915301
South Korea                           6.065584                    0.000000
Netherlands                           3.462910                    3.809717
Singapore                             2.256169                    2.803278
Germany                               1.711609                    4.498287
Finland                               0.315234                    2.746643
Norway                                0.594575                   10.206345
Canada                                2.301560                    0.260146
Sweden                                0.000000                    9.540901
Denmark                               0.213177                    5.366374
Spain                                 4.139731                    1.006515
France                                0.000000                    5.743470
New Zealand                           5.808940                   15.247091
Israel                                0.000000                    0.000000
Switzerland                           0.000000                    8.732562
Japan                                 0.181761                    3.986111
Poland                                0.000000                    0.695574
Portugal                              2.055218                    1.161203
Australia                             0.000000                    4.020274
Ireland                               0.000000                   12.613720
Austria                               0.000000                    0.000000
Estonia                               0.000000                    0.000000
Czechia                               0.000000                   50.939958
China                                 1.072054                    0.000000
Belgium                              20.000000                    0.000000
Brazil                               19.674804                    0.000000
South Africa                          0.000000                    0.000000
Slovakia                              0.000000                    0.000000
Uruguay                               0.000000                    3.055098
Serbia                                0.000000                    0.000000
Croatia                               0.000000                    0.000000
Latvia                                0.000000                    0.000000
Chile                                      NaN                         NaN
Iceland                                    NaN                         NaN
Malaysia                                   NaN                         NaN
Italy                                      NaN                         NaN
Russia                                     NaN                         NaN
Turkey                                     NaN                         NaN

Research category_split  Crop development  End product formulation  \
Funder Country_split
EU                               2.738675                13.582692
United States                    3.905010                 5.039060
United Kingdom                   7.236849                 7.888559
South Korea                      0.315088                 9.374280
Netherlands                      1.560073                 2.938007
Singapore                        0.000000                 7.548412
Germany                         16.689909                13.262198
Finland                          1.108422                10.076437
Norway                           1.707581                 9.853148
Canada                           3.544956                30.720706
Sweden                           4.719720                15.945495
Denmark                          2.832740                19.661842
Spain                            6.033096                11.352648
France                          18.861266                26.191180
New Zealand                      0.000000                 7.975960
Israel                           0.000000                 1.436357
Switzerland                      0.500665                14.448796
Japan                            0.000000                 0.362552
Poland                           0.000000                41.847084
Portugal                         1.771524                16.177895
Australia                        4.782213                45.551112
Ireland                          0.000000                21.826909
Austria                          0.000000                 3.198607
Estonia                          0.000000                15.188028
Czechia                          9.062357                 1.861896
China                            0.000000                 5.025836
Belgium                          0.000000                20.000000
Brazil                           0.000000                21.717232
South Africa                     0.000000                20.000000
Slovakia                         0.000000                27.924069
Uruguay                          6.268010                43.594458
Serbia                           0.000000                 0.000000
Croatia                          0.000000                 0.000000
Latvia                           0.000000                33.333333
Chile                                 NaN                      NaN
Iceland                               NaN                      NaN
Malaysia                              NaN                      NaN
Italy                                 NaN                      NaN
Russia                                NaN                      NaN
Turkey                                NaN                      NaN

Research category_split  Feedstocks  Food safety & quality  \
Funder Country_split
EU                         5.781346               4.607575
United States              7.909408               1.643845
United Kingdom             5.546134               2.910833
South Korea                1.735291               5.518654
Netherlands                0.269622               1.765040
Singapore                  4.280558              11.002779
Germany                    0.657566               1.652671
Finland                    1.836438               0.727727
Norway                     9.847553               6.336612
Canada                     0.486310               0.193169
Sweden                     1.714531               4.029783
Denmark                    5.307338               3.040290
Spain                      2.111453               3.538663
France                     0.000000               0.000000
New Zealand                4.902813               3.279324
Israel                     0.000000               0.560977
Switzerland                1.731876               2.392326
Japan                      0.763415               2.989685
Poland                     0.367135               0.367135
Portugal                   0.132627               3.324087
Australia                  9.279682               0.000000
Ireland                    0.000000               0.000000
Austria                    0.000000               0.000000
Estonia                    0.723479              13.085038
Czechia                    0.000000               0.000000
China                      0.000000               2.178042
Belgium                    0.000000               0.000000
Brazil                     0.000000               0.449814
South Africa               0.000000               0.000000
Slovakia                  27.924069               1.613515
Uruguay                    0.000000               3.544289
Serbia                     0.000000               0.000000
Croatia                    0.000000               0.000000
Latvia                     0.000000               0.000000
Chile                           NaN                    NaN
Iceland                         NaN                    NaN
Malaysia                        NaN                    NaN
Italy                           NaN                    NaN
Russia                          NaN                    NaN
Turkey                          NaN                    NaN

Research category_split  Health & nutrition  Impact Assessments  \
Funder Country_split
EU                                 7.743235           11.974782
United States                      3.466749            2.366679
United Kingdom                     7.978873            2.855082
South Korea                        0.095114            0.315088
Netherlands                        2.790457            2.218842
Singapore                          7.811373            0.000000
Germany                            2.798419            1.692598
Finland                            1.466668            1.457044
Norway                            12.516152            2.963911
Canada                             3.044508            0.501040
Sweden                            12.339342            5.657249
Denmark                           15.110250            1.608083
Spain                              4.837425            1.018734
France                            11.322818            0.000000
New Zealand                       14.284079            7.416242
Israel                             0.000000            0.000000
Switzerland                        7.661946            7.107463
Japan                              0.280553            0.000000
Poland                             2.378054            0.000000
Portugal                           0.332586            6.097294
Australia                          0.000000           10.390926
Ireland                           21.131753            0.000000
Austria                            0.000000           17.272480
Estonia                            0.000000            0.000000
Czechia                            1.861896            0.000000
China                              0.907648            0.000000
Belgium                            0.000000            0.000000
Brazil                             0.000000            0.000000
South Africa                       0.000000            0.000000
Slovakia                           1.613515            0.000000
Uruguay                            6.918770            5.384311
Serbia                             0.000000            0.000000
Croatia                           33.333333            0.000000
Latvia                             0.000000            0.000000
Chile                                   NaN                 NaN
Iceland                                 NaN                 NaN
Malaysia                                NaN                 NaN
Italy                                   NaN                 NaN
Russia                                  NaN                 NaN
Turkey                                  NaN                 NaN

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder Country_split
EU                                     20.163993   3.446606     0.734551
United States                           6.487678  44.064152     3.060927
United Kingdom                         10.245330   3.919345     5.130183
South Korea                             9.104529  22.296692     4.824943
Netherlands                             3.038857  63.637390     3.751927
Singapore                               7.017653  22.885570     3.103563
Germany                                30.614440   8.035141     1.802324
Finland                                10.238679  46.115534     0.000000
Norway                                 22.218513   1.774488     0.105977
Canada                                 34.038590  10.549327     2.543261
Sweden                                 20.849494  17.440435     0.297164
Denmark                                25.471366   5.289871     0.213177
Spain                                  11.086548  31.108330     4.320772
France                                 20.260609   8.091802     0.000000
New Zealand                            14.732951   0.000000     3.049145
Israel                                  0.000000  96.566309     0.875380
Switzerland                            16.321923   0.000000     7.098690
Japan                                  16.110558   3.591933     1.082593
Poland                                 34.442129   0.000000     0.000000
Portugal                                5.452568  52.452666     2.044617
Australia                              18.409355   4.612358     0.000000
Ireland                                22.023787   0.000000     0.000000
Austria                                 3.198607  38.586739     0.000000
Estonia                                18.908525   0.000000     0.000000
Czechia                                12.901331  12.542807     0.000000
China                                  15.776644  68.509306     0.000000
Belgium                                 0.000000   0.000000    20.000000
Brazil                                  0.964710  50.988128     0.000000
South Africa                           20.000000   0.000000     0.000000
Slovakia                               40.924833   0.000000     0.000000
Uruguay                                24.117721   0.000000     0.000000
Serbia                                  0.000000   0.000000     0.000000
Croatia                                33.333333   0.000000     0.000000
Latvia                                 33.333333   0.000000     0.000000
Chile                                        NaN        NaN          NaN
Iceland                                      NaN        NaN          NaN
Malaysia                                     NaN        NaN          NaN
Italy                                        NaN        NaN          NaN
Russia                                       NaN        NaN          NaN
Turkey                                       NaN        NaN          NaN

Research category_split  Strain development  Target molecule selection  \
Funder Country_split
EU                                 4.469171                   1.331183
United States                      5.422768                   1.009209
United Kingdom                     9.692329                   3.878225
South Korea                        5.274613                   2.585765
Netherlands                        2.676339                   0.280498
Singapore                          5.838059                   5.838059
Germany                            3.822264                   0.797671
Finland                            4.452166                   3.894199
Norway                             5.037609                   4.358296
Canada                             2.514232                   0.144521
Sweden                             1.995732                   0.624950
Denmark                            4.074663                   0.881007
Spain                              3.242455                   0.648358
France                             0.000000                   3.005948
New Zealand                        3.679838                   3.679838
Israel                             0.000000                   0.000000
Switzerland                        3.003693                   0.000000
Japan                              0.558043                   0.113886
Poland                             0.293754                   0.000000
Portugal                           0.132627                   0.000000
Australia                          0.000000                   0.000000
Ireland                            9.410068                   0.000000
Austria                           17.272480                   0.000000
Estonia                           41.316754                   6.511308
Czechia                            1.861896                   0.000000
China                              0.536027                   0.536027
Belgium                            0.000000                   0.000000
Brazil                             0.000000                   0.000000
South Africa                      20.000000                  20.000000
Slovakia                           0.000000                   0.000000
Uruguay                            3.539177                   0.000000
Serbia                             0.000000                   0.000000
Croatia                           33.333333                   0.000000
Latvia                             0.000000                   0.000000
Chile                                   NaN                        NaN
Iceland                                 NaN                        NaN
Malaysia                                NaN                        NaN
Italy                                   NaN                        NaN
Russia                                  NaN                        NaN
Turkey                                  NaN                        NaN

Research category_split  Texturization methods   Total (EUR)
Funder Country_split
EU                                    1.218473  4.544506e+08
United States                         2.315959  1.910789e+08
United Kingdom                        3.522483  1.480611e+08
South Korea                           5.707648  1.409658e+08

### 9d. Research category by country in EUR (2020-2025)

Same split as 9b, in absolute amounts instead of row percentages. Five CSVs: one overall, plus one
per AP pillar carrying only the categories that occur in that pillar, and every country funded in it.

In [75]:
def category_eur_table(base_split, index_col, weighted_col_name):
    """EUR twin of category_pct_table - identical split logic, absolute amounts instead of row shares."""
    base = base_split.rename(columns={'weighted_funding': weighted_col_name}).copy()
    exploded = split_multi_value(base, 'Research category', delimiter=',')
    exploded['weighted_funding'] = exploded[weighted_col_name] * exploded['_weight']
    eur = exploded.pivot_table(
        index=index_col, columns='Research category_split', values='weighted_funding', aggfunc='sum', fill_value=0
    )
    eur = eur.loc[:, eur.sum() > 0]  # drop categories with no funding in this slice
    eur['Total (EUR)'] = eur.sum(axis=1)
    return eur.sort_values('Total (EUR)', ascending=False)


country_category_eur = category_eur_table(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_eur, '9d_research_category_eur_by_country')
print(country_category_eur.to_string(float_format=lambda v: f'{v:,.0f}'))

# One CSV per AP pillar. Subsetting BEFORE the pivot is what keeps each file to the categories that
# actually occur in that pillar - pivoting first and filtering after would leave all-zero columns.
for pillar in sorted(country_split['AP pillar'].dropna().unique()):
    pillar_eur = category_eur_table(
        country_split[country_split['AP pillar'] == pillar],
        'Funder Country_split', 'country_weighted_funding',
    )
    slug = re.sub(r'[^a-z0-9]+', '-', pillar.lower()).strip('-')
    save(pillar_eur, f'9d_research_category_eur_by_country_{slug}')
    print(f"\n--- {pillar}: {len(pillar_eur)} countries x {len(pillar_eur.columns) - 1} categories, "
          f"EUR {pillar_eur['Total (EUR)'].sum():,.0f} ---")
    print(pillar_eur.to_string(float_format=lambda v: f'{v:,.0f}'))

Saved 9d_research_category_eur_by_country -> data_output\analysis\9d_research_category_eur_by_country.csv
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation       Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
EU                              53,339,400           6,719,260                990,773                  39,873,679        12,445,924               61,726,629  26,273,365             20,939,153          35,189,180          54,419,473               91,635,389  15,663,122    3,338,170          20,310,176                  6,049,571              5,537,357  454,450,622
United States                   17,197,415           7,167,195              4,768,245                   3,201,324        10,047,952               13,105,551  26,476,830              3,494,499           8,104,756           4,728,605               16,105,249 169,110,454    7,531,911          10,665,791                  2,099,408              5,593,361  309,398,547
Denmark                         20,796,702             857,419                728,295                   5,225,099         7,413,558               16,338,761  18,630,551              5,487,251          11,198,474           5,213,955               32,417,286   2,323,541      728,295          23,827,627                  3,668,796              9,379,472  164,235,084
United Kingdom                  18,862,744          12,866,478              7,181,936                   4,874,900        10,754,624               11,679,887   8,211,667              4,309,811          11,853,273           4,785,739               15,209,015   6,103,197    7,595,805          14,350,569                  5,742,142              5,215,427  149,597,212
South Korea                     24,590,779          13,169,327              8,550,399                           0           444,167               13,214,529   2,446,167              7,779,415             134,078             444,167               12,834,272  31,430,711    6,801,519           7,435,400                  3,645,044              8,045,832  140,965,806
Netherlands                      4,532,735           2,533,333              3,285,767                   3,614,833         1,480,268                2,787,715     255,830              1,674,751           2,647,713           2,105,339                2,883,406  60,382,061    3,560,000           2,539,432                    266,150                335,232   94,884,566
Singapore                       12,545,095           3,129,462              1,875,762                   2,330,625                 0                6,275,696   3,558,826              9,147,632           6,494,320                   0                5,834,427  19,026,900    2,580,280           4,853,721                  4,853,721                632,824   83,139,290
Germany                          4,149,684             582,307              1,403,124                   3,687,556        13,681,869               10,871,938     539,052              1,354,808           2,294,057           1,387,539               25,096,767   6,586,959    1,477,489           3,133,373                    653,906              5,076,463   81,976,892
Finland                         11,240,544             244,950                244,950                   2,152,254           861,289                7,829,805   1,426,987                565,474           1,139,661           1,174,183                7,955,873  35,833,659            0           3,459,515                  3,025,952                609,000   77,764,097
Canada                           1,657,317           1,827,106              1,364,620                     154,244         3,021,278               19,134,080     288,338                114,532           1,833,185             297,072               20,258,796   6,858,797    1,507,928           1,490,716                     85,688              2,864,698   62,758,395
Norway                           6,007,423           1,030,587                352,901                   6,057,819         1,013,508                5,848,185   5,844,864              3,760,999           7,428,770           1,759,184               13,187,457   1,053,220       62,901           2,989,995                  2,586,800                368,850   59,353,463
Sweden                             881,025             117,118                      0                   4,840,452         2,394,489                8,089,739     869,845              2,044,458           6,260,205           2,870,131               10,577,719   8,848,177      150,762           1,012,508                    317,060              1,460,008   50,733,697
Spain                            2,360,290           1,536,827              1,454,132                     353,551         2,119,200                3,987,759     741,674              1,242,999           1,699,206             357,843                3,894,288  10,927,189    1,517,725           1,138,953                    227,744              1,566,866   35,126,248
France                           1,000,000                   0                      0                   1,910,702         6,274,648                8,713,118           0                      0           3,766,804                   0                6,740,173   2,691,930            0                   0                  1,000,000              1,170,000   33,267,374
New Zealand                      2,042,947           2,279,565              1,626,756                   4,269,850                 0                2,233,617   1,373,001                918,354           4,000,165           2,076,871                4,125,869           0      853,894           1,030,515                  1,030,515                142,441   28,004,360
Israel                                   0                   0                      0                           0                 0                  389,010           0                151,930                   0                   0                        0  26,526,158      237,080                   0                          0                151,930   27,456,108
Switzerland                      2,670,042              54,060                      0                   2,099,570           832,958                3,473,924     416,395                575,187           1,842,162           1,708,848                4,035,017           0    1,706,738             722,178                          0              4,729,244   24,866,323
Japan                            6,118,734           6,305,086                 63,354                     715,183                 0                   65,049     136,971                536,405              50,336                   0                2,890,536     644,460      194,237             100,123                     20,433                131,707   17,972,616
Poland                           1,472,092           1,380,000                      0                     101,740                 0                6,120,896      53,700                 53,700             347,834                   0                5,037,787           0            0              42,967                          0                 16,100   14,626,815
Portugal                           511,755             154,448                154,448                      87,263           133,128                1,215,753       9,967                249,802              24,994             458,206                  409,755   3,941,768      153,651               9,967                          0                      0    7,514,905
Australia                                0                   0                      0                     295,340           351,314                3,346,305     681,710                      0                   0             763,345                1,352,400     338,836            0                   0                          0                217,015    7,346,265
Ireland                            772,597                   0                      0                     750,000                 0                1,297,808           0                      0           1,256,474                   0                1,309,514           0            0             559,514                          0                      0    5,945,907
Austria                            900,000                   0                      0                           0                 0                  166,667           0                      0                   0             900,000                  166,667   2,010,601            0             900,000                          0                166,667    5,210,601
Estonia                            186,615                   0                      0                           0                 0                  699,768      33,333                602,876                   0              24,300                  871,186           0            0           1,903,615                    300,000                  9,975    4,631,669
Czechia                                  0             387,305                      0                   2,200,000           391,386                   80,412           0                      0              80,412                   0                  557,184     541,700            0              80,412                          0                      0    4,318,810
China                               40,044                   0                 40,044                           0                 0                  187,728           0                 81,356              33,903                   0                  589,298   2,559,000            0              20,022                     20,022                163,842    3,735,259
Belgium                            720,000             720,000                720,000                           0                 0                  720,000           0                      0                   0                   0                        0           0      720,000                   0                          0                      0    3,600,000
Global                             880,029             424,497                169,497                           0                 0                  468,208           0                      0                   0             131,622                  648,833     317,900      148,148                   0                          0                149,458    3,338,193
Brazil                               9,474             121,225                414,400                           0                 0                  457,419           0                  9,474                   0                   0                   20,319   1,073,936            0                   0                          0                      0    2,106,247
South Africa                       111,980                   0                      0                           0                 0                  111,980           0                      0                   0                   0                  111,980           0            0             111,980                    111,980                      0      559,900
Slovakia                                 0                   0                      0                           0                 0                  150,000     150,000                  8,667               8,667                   0                  219,836           0            0                   0                          0                      0      537,171
Uruguay                                  0                   0                      0                      16,278            33,396                  232,270           0                 18,884              36,863              28,688                  128,499           0            0              18,857                          0                 19,064      532,798
Serbia                                   0             149,995                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0      149,995
Croatia                                  0                   0                      0                           0                 0                        0           0                      0              43,746                   0                   43,746           0            0              43,746                          0                      0      131,239
Latvia                                   0                   0                      0                           0                 0                   14,117           0                      0                   0                   0                   14,117           0            0                   0                          0                 14,117       42,350
Chile                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Iceland                                  0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Malaysia                                 0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Italy                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Russia                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Turkey                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Saved 9d_research_category_eur_by_country_cross-cutting -> data_output\analysis\9d_research_category_eur_by_country_cross-cutting.csv

--- Cross-cutting: 29 countries x 16 categories, EUR 423,917,682 ---
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
United States                    1,340,081             839,523                441,232                     274,312           320,853                  797,784     608,331                262,837             384,250             822,722                  828,818 85,019,577      632,351             986,605                    834,497                314,010   94,707,783
South Korea                      5,864,658           9,514,634              6,199,472                           0           444,167                6,363,448   2,446,167              4,693,620              87,536             444,167                9,947,956          0    4,861,429           6,694,400                  2,904,044              6,199,472   66,665,168
Netherlands                        266,150                   0                      0                           0                 0                  266,150           0                266,150             266,150                   0                  266,150 60,049,554            0                   0                    266,150                      0   61,646,452
United Kingdom                   4,410,911           3,904,657              3,904,657                   1,314,593         1,583,739                1,847,660   3,963,383              1,755,553           1,894,603             233,807                1,763,081  3,718,234    3,904,657           3,963,383                  1,543,515              1,464,739   41,171,173
EU                               1,565,059                   0                      0                           0                 0                2,390,008   1,565,059              6,701,490           5,280,243           6,999,521                3,861,255  8,847,362            0           1,565,059                          0                      0   38,775,058
Finland                          3,828,954                   0                      0                      18,000                 0                  756,050     838,954                      0                   0             546,429                  765,050 30,000,000            0           1,063,525                    829,929                      0   38,646,890
Norway                           3,242,344             290,000                290,000                   2,088,000                 0                  101,414   3,343,758              2,858,906               8,700                   0                3,053,758  1,040,170            0             290,000                    290,000                      0   16,897,050
Singapore                                0                   0                      0                           0                 0                        0           0              2,531,294                   0                   0                  155,812  9,704,400            0             155,812                    311,625                      0   12,858,944
Israel                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0  9,491,092            0                   0                          0                      0    9,491,092
Spain                               71,354                   0                      0                      43,438                 0                  253,294     139,688                119,738             191,429                   0                  239,341  7,240,850            0              43,438                          0                 85,645    8,428,214

### 9e. Research category by country in EUR, excl. non-profit funding (2020-2025)

9d with non-profit/NGO funders removed - i.e. government money only. Reuses `country_split_np` from
3b and `category_eur_table` from 9d, so both must have been run. Five CSVs, same shapes as 9d.

In [76]:
country_category_eur_np = category_eur_table(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_eur_np, '9e_research_category_eur_by_country_excl_nonprofit')
print(country_category_eur_np.to_string(float_format=lambda v: f'{v:,.0f}'))

# Pillar list taken from country_split (not country_split_np) so the same four files are always
# written even if a pillar's funding were entirely non-profit in some future dataset.
for pillar in sorted(country_split['AP pillar'].dropna().unique()):
    pillar_eur_np = category_eur_table(
        country_split_np[country_split_np['AP pillar'] == pillar],
        'Funder Country_split', 'country_weighted_funding',
    )
    slug = re.sub(r'[^a-z0-9]+', '-', pillar.lower()).strip('-')
    save(pillar_eur_np, f'9e_research_category_eur_by_country_{slug}_excl_nonprofit')
    print(f"\n--- {pillar}: {len(pillar_eur_np)} countries x {len(pillar_eur_np.columns) - 1} categories, "
          f"EUR {pillar_eur_np['Total (EUR)'].sum():,.0f} ---")
    print(pillar_eur_np.to_string(float_format=lambda v: f'{v:,.0f}'))

assert country_category_eur_np['Total (EUR)'].sum() <= country_category_eur['Total (EUR)'].sum() + 1

Saved 9e_research_category_eur_by_country_excl_nonprofit -> data_output\analysis\9e_research_category_eur_by_country_excl_nonprofit.csv
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
EU                              53,339,400           6,719,260                990,773                  39,873,679        12,445,924               61,726,629  26,273,365             20,939,153          35,189,180          54,419,473               91,635,389 15,663,122    3,338,170          20,310,176                  6,049,571              5,537,357  454,450,622
United States                   13,953,078           4,732,644              3,542,795                   3,201,324         7,461,649                9,628,578  15,113,207              3,141,040           6,624,225           4,522,223               12,396,582 84,197,285    5,848,784          10,361,764                  1,928,386              4,425,309  191,078,872
United Kingdom                  18,862,744          12,866,478              7,181,936                   4,316,427        10,714,957               11,679,887   8,211,667              4,309,811          11,813,606           4,227,265               15,169,348  5,803,025    7,595,805          14,350,569                  5,742,142              5,215,427  148,061,093
South Korea                     24,590,779          13,169,327              8,550,399                           0           444,167               13,214,529   2,446,167              7,779,415             134,078             444,167               12,834,272 31,430,711    6,801,519           7,435,400                  3,645,044              8,045,832  140,965,806
Netherlands                      4,532,735           2,533,333              3,285,767                   3,614,833         1,480,268                2,787,715     255,830              1,674,751           2,647,713           2,105,339                2,883,406 60,382,061    3,560,000           2,539,432                    266,150                335,232   94,884,566
Singapore                       12,545,095           3,129,462              1,875,762                   2,330,625                 0                6,275,696   3,558,826              9,147,632           6,494,320                   0                5,834,427 19,026,900    2,580,280           4,853,721                  4,853,721                632,824   83,139,290
Germany                          4,149,684             582,307              1,403,124                   3,687,556        13,681,869               10,871,938     539,052              1,354,808           2,294,057           1,387,539               25,096,767  6,586,959    1,477,489           3,133,373                    653,906              5,076,463   81,976,892
Finland                         11,240,544             244,950                244,950                   2,134,254           861,289                7,829,805   1,426,987                565,474           1,139,661           1,132,183                7,955,873 35,833,659            0           3,459,515                  3,025,952                609,000   77,704,097
Norway                           6,007,423           1,030,587                352,901                   6,057,819         1,013,508                5,848,185   5,844,864              3,760,999           7,428,770           1,759,184               13,187,457  1,053,220       62,901           2,989,995                  2,586,800                368,850   59,353,463
Canada                           1,657,317           1,827,106              1,364,620                     154,244         2,101,843               18,214,645     288,338                114,532           1,805,122             297,072               20,181,855  6,254,812    1,507,928           1,490,716                     85,688              1,945,263   59,291,102
Sweden                             881,025             117,118                      0                   4,840,452         2,394,489                8,089,739     869,845              2,044,458           6,260,205           2,870,131               10,577,719  8,848,177      150,762           1,012,508                    317,060              1,460,008   50,733,697
Denmark                          2,461,243             221,929                 92,805                   2,336,210         1,233,212                8,559,634   2,310,509              1,323,567           6,578,133             700,067               11,088,766  2,302,905       92,805           1,773,874                    383,540              2,075,044   43,534,241
Spain                            2,360,290           1,536,827              1,454,132                     353,551         2,119,200                3,987,759     741,674              1,242,999           1,699,206             357,843                3,894,288 10,927,189    1,517,725           1,138,953                    227,744              1,566,866   35,126,248
France                           1,000,000                   0                      0                   1,910,702         6,274,648                8,713,118           0                      0           3,766,804                   0                6,740,173  2,691,930            0                   0                  1,000,000              1,170,000   33,267,374
New Zealand                      2,042,947           2,279,565              1,626,756                   4,269,850                 0                2,233,617   1,373,001                918,354           4,000,165           2,076,871                4,125,869          0      853,894           1,030,515                  1,030,515                142,441   28,004,360
Israel                                   0                   0                      0                           0                 0                  389,010           0                151,930                   0                   0                        0 26,153,152      237,080                   0                          0                151,930   27,083,102
Switzerland                      2,670,042              54,060                      0                   2,099,570           120,375                3,473,924     416,395                575,187           1,842,162           1,708,848                3,924,280          0    1,706,738             722,178                          0              4,729,244   24,043,003
Japan                            6,118,734           6,305,086                 32,611                     715,183                 0                   65,049     136,971                536,405              50,336                   0                2,890,536    644,460      194,237             100,123                     20,433                131,707   17,941,873
Poland                           1,472,092           1,380,000                      0                     101,740                 0                6,120,896      53,700                 53,700             347,834                   0                5,037,787          0            0              42,967                          0                 16,100   14,626,815
Portugal                           511,755             154,448                154,448                      87,263           133,128                1,215,753       9,967                249,802              24,994             458,206                  409,755  3,941,768      153,651               9,967                          0                      0    7,514,905
Australia                                0                   0                      0                     295,340           351,314                3,346,305     681,710                      0                   0             763,345                1,352,400    338,836            0                   0                          0                217,015    7,346,265
Ireland                            772,597                   0                      0                     750,000                 0                1,297,808           0                      0           1,256,474                   0                1,309,514          0            0             559,514                          0                      0    5,945,907
Austria                            900,000                   0                      0                           0                 0                  166,667           0                      0                   0             900,000                  166,667  2,010,601            0             900,000                          0                166,667    5,210,601
Estonia                            186,615                   0                      0                           0                 0                  699,768      33,333                602,876                   0                   0                  871,186          0            0           1,903,615                    300,000                  9,975    4,607,369
Czechia                                  0             387,305                      0                   2,200,000           391,386                   80,412           0                      0              80,412                   0                  557,184    541,700            0              80,412                          0                      0    4,318,810
China                               40,044                   0                 40,044                           0                 0                  187,728           0                 81,356              33,903                   0                  589,298  2,559,000            0              20,022                     20,022                163,842    3,735,259
Belgium                            720,000             720,000                720,000                           0                 0                  720,000           0                      0                   0                   0                        0          0      720,000                   0                          0                      0    3,600,000
Brazil                               9,474             121,225                414,400                           0                 0                  457,419           0                  9,474                   0                   0                   20,319  1,073,936            0                   0                          0                      0    2,106,247
South Africa                       111,980                   0                      0                           0                 0                  111,980           0                      0                   0                   0                  111,980          0            0             111,980                    111,980                      0      559,900
Slovakia                                 0                   0                      0                           0                 0                  150,000     150,000                  8,667               8,667                   0                  219,836          0            0                   0                          0                      0      537,171
Uruguay                                  0                   0                      0                      16,278            33,396                  232,270           0                 18,884              36,863              28,688                  128,499          0            0              18,857                          0                 19,064      532,798
Serbia                                   0             149,995                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0      149,995
Croatia                                  0                   0                      0                           0                 0                        0           0                      0              43,746                   0                   43,746          0            0              43,746                          0                      0      131,239
Latvia                                   0                   0                      0                           0                 0                   14,117           0                      0                   0                   0                   14,117          0            0                   0                          0                 14,117       42,350
Chile                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Iceland                                  0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Malaysia                                 0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Italy                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Russia                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Turkey                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Saved 9e_research_category_eur_by_country_cross-cutting_excl_nonprofit -> data_output\analysis\9e_research_category_eur_by_country_cross-cutting_excl_nonprofit.csv

--- Cross-cutting: 28 countries x 16 categories, EUR 339,642,069 ---
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
South Korea                      5,864,658           9,514,634              6,199,472                           0           444,167                6,363,448   2,446,167              4,693,620              87,536             444,167                9,947,956          0    4,861,429           6,694,400                  2,904,044              6,199,472   66,665,168
Netherlands                        266,150                   0                      0                           0                 0                  266,150           0                266,150             266,150                   0                  266,150 60,049,554            0                   0                    266,150                      0   61,646,452
United Kingdom                   4,410,911           3,904,657              3,904,657                   1,314,593         1,583,739                1,847,660   3,963,383              1,755,553           1,894,603             233,807                1,763,081  3,718,234    3,904,657           3,963,383                  1,543,515              1,464,739   41,171,173
EU                               1,565,059                   0                      0                           0                 0                2,390,008   1,565,059              6,701,490           5,280,243           6,999,521                3,861,255  8,847,362            0           1,565,059                          0                      0   38,775,058
Finland                          3,828,954                   0                      0                           0                 0                  756,050     838,954                      0                   0             504,429                  765,050 30,000,000            0           1,063,525                    829,929                      0   38,586,890
Norway                           3,242,344             290,000                290,000                   2,088,000                 0                  101,414   3,343,758              2,858,906               8,700                   0                3,053,758  1,040,170            0             290,000                    290,000                      0   16,897,050
United States                    1,340,081             839,523                441,232                     274,312           320,853                  797,784     608,331                262,837             384,250             822,722                  828,818  4,070,677      632,351             986,605                    834,497                314,010   13,758,883
Singapore                                0                   0                      0                           0                 0                        0           0              2,531,294                   0                   0                  155,812  9,704,400            0             155,812                    311,625                      0   12,858,944
Israel                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0  9,491,092            0                   0                          0                      0    9,491,092
Spain                               71,354                   0                      0                      43,438                 0                  253,294     139,688                119,738             191,429                   0                  239,341  7,240,850            0              43,438                          0                 85,645    8,428,214
New Zealand                        746,886             652,809                      0                   1,701,956                 0                1,089,373     342,486                652,809             779,050                   0                  436,564          0      310,323                   0                          0                      0    6,712,255

### 10. Total funding by sub-production pillar (2020-2025)

Total funding per `'Sub-production pillar'` value, across all AP pillars. Mutually exclusive rows
summing to the grand total, with `(no sub-pillar assigned)` shown explicitly since it is the
majority of funding (Cultivated has no sub-pillar scheme, and most Plant-based grants have none).

In [77]:
SUBPILLAR_COL = 'Sub-production pillar'
total_funding = df[FUNDING_COL].sum()

# Single-valued today, so a plain groupby is correct - no split_multi_value weighting needed.
# Guard in case curation starts packing two values into one cell.
_multi = df[SUBPILLAR_COL].dropna().astype(str).str.contains(r'[;,]')
if _multi.any():
    print(f"WARNING: {_multi.sum()} '{SUBPILLAR_COL}' cells contain ';' or ',' - this analysis "
          f"assumes one value per grant. Switch to split_multi_value before trusting these totals.")

subpillar = df[SUBPILLAR_COL].astype(str).str.strip().where(df[SUBPILLAR_COL].notna())
subpillar_np = df_np[SUBPILLAR_COL].astype(str).str.strip().where(df_np[SUBPILLAR_COL].notna())

by_subpillar = pd.DataFrame({
    'Grants': df.groupby(subpillar)[FUNDING_COL].size(),
    'Total funding (2020-2025, EUR)': df.groupby(subpillar)[FUNDING_COL].sum(),
})
# excl. non-profit column comes from 3b's df_np - run 3b first. Derived from df_np's own column,
# NOT by reindexing a df-based mask: 3b resets df_np's index, so the labels don't line up.
by_subpillar['Total funding excl. non-profit (EUR)'] = df_np.groupby(subpillar_np)[FUNDING_COL].sum()
by_subpillar['% of all funding'] = 100 * by_subpillar['Total funding (2020-2025, EUR)'] / total_funding
by_subpillar = by_subpillar.sort_values('Total funding (2020-2025, EUR)', ascending=False)
by_subpillar.index.name = SUBPILLAR_COL

_blank, _blank_np = df[SUBPILLAR_COL].isna(), df_np[SUBPILLAR_COL].isna()
by_subpillar.loc['(no sub-pillar assigned)'] = [
    int(_blank.sum()), df.loc[_blank, FUNDING_COL].sum(),
    df_np.loc[_blank_np, FUNDING_COL].sum(),
    100 * df.loc[_blank, FUNDING_COL].sum() / total_funding,
]
by_subpillar.loc['ALL GRANTS'] = [len(df), total_funding, df_np[FUNDING_COL].sum(), 100.0]

save(by_subpillar, '10a_funding_by_subpillar')
print(by_subpillar.to_string(float_format=lambda v: f'{v:,.1f}'))

Saved 10a_funding_by_subpillar -> data_output\analysis\10a_funding_by_subpillar.csv
                          Grants  Total funding (2020-2025, EUR)  Total funding excl. non-profit (EUR)  % of all funding
Sub-production pillar
Broad R&D                  107.0                   299,079,390.6                         270,859,390.6              15.3
Mixed                       72.0                   222,087,099.7                         178,252,191.7              11.3
BF                         232.0                   220,532,980.6                         199,901,311.5              11.2
PF                         124.0                    96,534,976.6                          86,827,970.5               4.9
TF                         105.0                    70,521,864.5                          61,781,461.8               3.6
Socioeconomic               60.0                    16,941,237.4                          16,856,937.4               0.9
Technical research          29.0                    10,435,295.3                           9,142,882.4               0.5
(no sub-pillar assigned) 1,727.0                 1,024,355,977.3                         888,193,184.4              52.3
ALL GRANTS               2,456.0                 1,960,488,822.0                       1,711,815,330.3             100.0

### 11. Fermentation-pillar funding by start year x sub-pillar (2020-2025)

Fermentation-pillar grants only, split by `BF` / `PF` / `Mixed`. By START year, same as 1a/2a.

In [78]:
ferment = df[df['AP pillar'] == 'Fermentation']

ferment_year_subpillar = ferment.pivot_table(
    index=SUBPILLAR_COL, columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
ferment_year_subpillar.columns = ferment_year_subpillar.columns.astype(int)
ferment_year_subpillar = ferment_year_subpillar[sorted(ferment_year_subpillar.columns)]
ferment_year_subpillar.loc['Total'] = ferment_year_subpillar.sum()

save(ferment_year_subpillar, '11_funding_fermentation_by_year_and_subpillar')
print(ferment_year_subpillar.to_string(float_format=lambda v: f'{v:,.0f}'))

# pivot_table drops rows with a blank sub-pillar, so the table total falls short of the pillar total.
_gap = ferment[ferment[SUBPILLAR_COL].isna()]
print(f"\nFermentation pillar total: EUR {ferment[FUNDING_COL].sum():,.0f}. Table covers "
      f"EUR {ferment_year_subpillar.loc['Total'].sum():,.0f}; {len(_gap)} grants "
      f"(EUR {_gap[FUNDING_COL].sum():,.0f}) have no sub-pillar and are excluded.")

Saved 11_funding_fermentation_by_year_and_subpillar -> data_output\analysis\11_funding_fermentation_by_year_and_subpillar.csv
Year project started        2020       2021       2022        2023        2024        2025
Sub-production pillar
BF                    10,304,279 25,600,180 38,092,226  56,856,521  18,863,122  70,816,653
Mixed                  9,940,951 14,324,124  2,573,474  41,001,060 115,585,366  38,662,125
PF                     1,506,957  2,744,946  6,454,392  18,331,093  32,075,818  35,421,770
Total                 21,752,187 42,669,250 47,120,092 116,188,673 166,524,305 144,900,549

Fermentation pillar total: EUR 540,403,526. Table covers EUR 539,155,057; 7 grants (EUR 1,248,469) have no sub-pillar and are excluded.

### 12. Funding by start year x AP pillar x country, for a fixed country set (2020-2025)

Same methodology and growth-rate formula as 2c/2d, with a (Country, AP pillar) row index instead of
region. Country set = EU-27 + Norway / UK / Switzerland (EU+), plus US, Canada, Australia,
New Zealand, Brazil, Israel, Japan, South Korea, Singapore, `Global`, and `EU` (supranational
EU-level funding, kept as its own row - it is the largest single funder value in the data).

Every requested country gets a row per pillar even at zero, so the row set is stable across reruns
and pastes into a fixed template. Nine EU-27 members currently have no funding at all
(Bulgaria, Cyprus, Greece, Hungary, Lithuania, Luxembourg, Malta, Romania, Slovenia), as does Italy.

In [79]:
from Funding_analysis_helpers import EU_27

# 'EU' = supranational EU-level funding, kept as its own row (not folded into the member states) -
# same treatment europe_tier_split gives it.
REPORT_COUNTRIES = sorted(EU_27) + [
    'Norway', 'United Kingdom', 'Switzerland',
    'United States', 'Canada', 'Australia', 'New Zealand', 'Brazil',
    'Israel', 'Japan', 'South Korea', 'Singapore',
    'EU', 'Global',
]
YEARS = list(range(2020, 2026))
AP_PILLARS = sorted(df['AP pillar'].dropna().unique())

_unknown = [c for c in REPORT_COUNTRIES if c not in set(country_split['Funder Country_split'])]
if _unknown:
    print(f"No funding found for: {_unknown} - kept as zero rows. Check spelling against "
          f"'Funder Country' if any of these were expected to have grants.")

country_pillar_year = country_split[country_split['Funder Country_split'].isin(REPORT_COUNTRIES)].pivot_table(
    index=['Funder Country_split', 'AP pillar'], columns='Year project started',
    values='weighted_funding', aggfunc='sum', fill_value=0,
)
country_pillar_year.columns = country_pillar_year.columns.astype(int)

# Reindex onto the full (country x pillar) grid so absent combinations read as 0 rather than vanishing.
_grid = pd.MultiIndex.from_product([REPORT_COUNTRIES, AP_PILLARS], names=['Funder Country', 'AP pillar'])
country_pillar_year = country_pillar_year.reindex(index=_grid, columns=YEARS, fill_value=0).fillna(0)
country_pillar_year['Total'] = country_pillar_year[YEARS].sum(axis=1)

save(country_pillar_year, '12a_funding_by_year_country_and_pillar')
print(country_pillar_year.to_string(float_format=lambda v: f'{v:,.0f}'))

# Growth rates, same formula as 2b/2d. yoy_growth needs the year columns only, not 'Total'.
growth_country_pillar = country_pillar_year[YEARS].apply(yoy_growth, axis=1)
growth_country_pillar['Average growth rate (2021-2025)'] = growth_country_pillar.iloc[:, 1:].mean(axis=1)
save(growth_country_pillar, '12b_growth_rates_by_country_and_pillar')
print()
print(growth_country_pillar.to_string(float_format=lambda v: f'{v:,.2f}'))

print(f"\nTable covers EUR {country_pillar_year['Total'].sum():,.0f} of "
      f"EUR {country_split['weighted_funding'].sum():,.0f} total "
      f"({100 * country_pillar_year['Total'].sum() / country_split['weighted_funding'].sum():.1f}%) - "
      f"the remainder sits in countries outside REPORT_COUNTRIES.")

No funding found for: ['Bulgaria', 'Cyprus', 'Greece', 'Hungary', 'Lithuania', 'Luxembourg', 'Malta', 'Romania', 'Slovenia'] - kept as zero rows. Check spelling against 'Funder Country' if any of these were expected to have grants.
Saved 12a_funding_by_year_country_and_pillar -> data_output\analysis\12a_funding_by_year_country_and_pillar.csv
Year project started               2020       2021       2022       2023       2024       2025       Total
Funder Country AP pillar
Austria        Cross-cutting          0          0          0          0          0    897,906     897,906
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0  3,200,000          0          0   3,200,000
               Plant-based            0          0    665,434          0          0    447,261   1,112,695
Belgium        Cross-cutting          0          0          0          0          0          0           0
               Cultivated     3,600,000          0          0          0          0          0   3,600,000
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Bulgaria       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Croatia        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based      131,239          0          0          0          0          0     131,239
Cyprus         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Czechia        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0     37,552          0          0    549,753          0     587,305
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0  1,140,119  2,591,386   3,731,505
Denmark        Cross-cutting          0  1,292,413  1,950,000  2,373,887    343,008    125,729   6,085,037
               Cultivated             0          0          0  2,890,231          0          0   2,890,231
               Fermentation     964,149  4,984,719  1,178,426 15,792,355 20,742,871 20,770,189  64,432,708
               Plant-based    3,657,491 15,852,462 35,317,239  7,743,507 12,543,726 15,712,683  90,827,108
Estonia        Cross-cutting          0          0          0          0     24,300          0      24,300
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0      6,000    759,846  1,817,000     19,950   2,602,796
               Plant-based    1,091,457     49,620    181,978     56,376    526,526     98,616   2,004,573
Finland        Cross-cutting     36,000     36,100  1,266,000     56,000 36,521,000    731,790  38,646,890
               Cultivated             0          0          0    489,900          0          0     489,900
               Fermentation     800,000    944,900  4,500,000          0  9,346,927 11,237,070  26,828,897
               Plant-based    2,436,000    735,814  2,416,526  4,393,000    917,070    900,000  11,798,410
France         Cross-cutting          0          0          0          0    241,829          0     241,829
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0  3,000,000          0   3,000,000
               Plant-based            0          0  3,302,803 22,943,999  2,993,732    785,011  30,025,545
Germany        Cross-cutting  2,273,642    549,500          0     45,645          0  1,312,796   4,181,583
               Cultivated     1,251,942    226,812  1,748,286  6,366,892          0          0   9,593,932
               Fermentation     934,702     57,525  1,244,760  2,530,964  1,882,916    969,440   7,620,307
               Plant-based    5,298,483  3,806,425  9,088,858 22,301,895 12,024,598  8,060,811  60,581,070
Greece         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Hungary        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Ireland        Cross-cutting          0          0          0    772,597          0          0     772,597
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based    3,000,000          0          0  2,173,310          0          0   5,173,310
Italy          Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Latvia         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0     42,350          0      42,350
Lithuania      Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Luxembourg     Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Malta          Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Netherlands    Cross-cutting          0          0  1,596,898 60,000,000          0     49,554  61,646,452
               Cultivated             0          0  1,280,000  3,750,000  7,900,000  1,594,867  14,524,867
               Fermentation           0          0          0    720,194     49,978  1,534,979   2,305,151
               Plant-based      958,406  2,166,950  1,028,663    839,762  3,735,695  7,678,620  16,408,096
Poland         Cross-cutting          0    101,740          0          0          0          0     101,740
               Cultivated             0          0          0          0  4,189,125          0   4,189,125
               Fermentation           0          0          0    204,068          0          0     204,068
               Plant-based       44,629    124,586    344,609    449,758  9,120,000     48,300  10,131,883
Portugal       Cross-cutting          0          0          0          0          0  3,859,768   3,859,768
               Cultivated             0          0     45,427    497,610    164,000    300,989   1,008,026
               Fermentation           0          0    249,991     49,834          0     49,968     349,793
               Plant-based            0  1,194,205      4,000    799,552          0    299,561   2,297,318
Romania        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Slovakia       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0    300,000     300,000
               Plant-based            0          0          0    211,169          0     26,002     237,171
Slovenia       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Spain          Cross-cutting    243,174    199,307    111,758  7,000,000    873,975          0   8,428,214
               Cultivated             0  5,521,700  3,615,350    154,515    909,026          0  10,200,591
               Fermentation     450,445  1,277,964    722,874    541,250    383,142    470,000   3,845,675
               Plant-based    1,261,850  3,579,116  4,342,395  1,159,682  2,308,725          0  12,651,768
Sweden         Cross-cutting          0    162,257          0    772,568    129,409          0   1,064,234
               Cultivated             0          0      1,287     27,300    226,318          0     254,905
               Fermentation     512,913    112,930  1,202,058  1,585,192    474,494  1,298,937   5,186,524
               Plant-based    9,088,049  7,002,557  5,028,372  5,554,098  6,730,200 10,824,758  44,228,034
Norway         Cross-cutting      8,700 12,475,794          0  2,020,313    304,243  2,088,000  16,897,050
               Cultivated             0          0          0          0          0  1,606,977   1,606,977
               Fermentation   8,963,974     43,500    442,830          0    323,647  1,048,349  10,822,300
               Plant-based    1,298,734 23,799,834    480,152    232,874    658,055  3,557,488  30,027,137
United Kingdom Cross-cutting          0    119,000  4,201,830 15,592,467 19,826,308  1,431,569  41,171,173
               Cultivated       653,680  3,952,365  3,275,443 11,071,815  6,078,099  2,396,823  27,428,224
               Fermentation     724,398    577,667  4,675,561  6,751,092 25,323,755  1,859,754  39,912,227
               Plant-based    1,647,560  2,914,392  4,630,149 15,095,069 16,056,614    741,803  41,085,587
Switzerland    Cross-cutting          0          0  1,721,954          0          0    941,414   2,663,368
               Cultivated             0    611,394          0  3,413,477    162,179          0   4,187,049
               Fermentation           0          0    462,352    328,447          0  2,148,038   2,938,837
               Plant-based    1,903,055  1,860,276  4,291,153  3,480,264    496,736  3,045,586  15,077,069
United States  Cross-cutting    241,358    260,526    312,888  3,218,605 85,825,457  4,848,948  94,707,783
               Cultivated     5,147,022 12,038,918  3,356,120  4,121,446  4,327,248  3,780,236  32,770,989
               Fermentation     905,398  4,370,162 12,176,573 39,742,145 62,654,125 14,279,317 134,127,718
               Plant-based    3,155,025  9,316,069 17,090,147  7,793,417  3,621,664  6,815,736  47,792,057
Canada         Cross-cutting     12,258     50,728     14,387    147,485     99,655      9,460     333,973
               Cultivated        15,818    198,320    127,955  7,587,463    244,293    978,700   9,152,549
               Fermentation     152,077    488,691     28,055    327,893    382,526          0   1,379,242
               Plant-based   23,258,275  8,874,597  5,491,080  5,279,657  6,212,966  2,776,056  51,892,631
Australia      Cross-cutting          0  3,134,400          0    318,232    127,953          0   3,580,585
               Cultivated        20,604          0    295,340          0          0          0     315,944
               Fermentation           0          0    681,710          0          0          0     681,710
               Plant-based            0  1,694,594    351,314    288,088          0    434,029   2,768,026
New Zealand    Cross-cutting  5,160,642          0          0          0          0  1,551,613   6,712,255
               Cultivated             0          0          0  1,074,661  4,880,269          0   5,954,930
               Fermentation           0          0          0          0          0  5,152,576   5,152,576
               Plant-based    1,686,976          0    181,995  6,230,613    569,765  1,515,250  10,184,599
Brazil         Cross-cutting          0          0          0    446,574          0          0     446,574
               Cultivated             0          0          0  1,027,311    121,225    414,400   1,562,936
               Fermentation           0          0          0          0     96,738          0      96,738
               Plant-based            0          0          0          0          0          0           0
Israel         Cross-cutting          0  8,149,300          0  1,341,792          0          0   9,491,092
               Cultivated             0          0 16,662,060    474,160          0    373,006  17,509,226
               Fermentation           0          0          0    455,790          0          0     455,790
               Plant-based            0          0          0          0          0          0           0
Japan          Cross-cutting          0    727,925     23,097     68,165     78,601    207,321   1,105,109
               Cultivated        93,799          0    538,136 12,054,230    280,678    317,889  13,284,732
               Fermentation      32,524          0          0     12,497          0    220,680     265,701
               Plant-based    2,747,742     28,363    109,047     46,307    180,681    204,934   3,317,074
South Korea    Cross-cutting          0 13,952,250 19,917,158          0 27,711,128  5,084,632  66,665,168
               Cultivated       462,711  1,125,569 14,563,750  7,100,128 29,172,406 11,288,143  63,712,707
               Fermentation           0          0          0          0  2,235,121  3,752,125   5,987,246
               Plant-based      134,750          0    397,125    396,092  3,172,210    710,508   4,810,685
Singapore      Cross-cutting          0 10,327,650          0          0          0  2,531,294  12,858,944
               Cultivated             0 12,127,125          0    792,985          0  5,062,588  17,982,698
               Fermentation           0 19,268,250          0          0 10,209,040 10,125,176  39,602,466
               Plant-based            0 10,163,888          0          0          0  2,531,294  12,695,182
EU             Cross-cutting    293,854          0 26,973,875  3,498,858  1,008,950  6,999,521  38,775,058
               Cultivated     4,406,961  4,065,712  3,305,404  1,477,162 11,488,644  1,666,667  26,410,550
               Fermentation   7,311,607 10,542,943 19,128,777 42,806,039 27,602,026 70,450,720 177,842,111
               Plant-based   22,676,135 10,400,243 52,364,944 54,465,529 38,036,241 33,479,810 211,422,902
Global         Cross-cutting          0          0          0          0          0          0           0
               Cultivated       812,156    602,494    258,145    207,648          0          0   1,880,443
               Fermentation           0          0    425,000    238,000          0          0     663,000
               Plant-based      497,250          0    212,500     85,000          0          0     794,750
Saved 12b_growth_rates_by_country_and_pillar -> data_output\analysis\12b_growth_rates_by_country_and_pillar.csv

Year project started          2020     2021  2022   2023   2024  2025  Average growth rate (2021-2025)
Funder Country AP pillar
Austria        Cross-cutting   NaN      NaN   NaN    NaN    NaN   inf                              inf
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    inf  -1.00   NaN                              inf
               Plant-based     NaN      NaN   inf  -1.00    NaN   inf                              inf
Belgium        Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN    -1.00   NaN    NaN    NaN   NaN                            -1.00
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN      NaN   NaN    NaN    NaN   NaN                              NaN
Bulgaria       Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN      NaN   NaN    NaN    NaN   NaN                              NaN
Croatia        Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN    -1.00   NaN    NaN    NaN   NaN                            -1.00

### 13. Research Question No. 18

Evaluate how public R&I grants act as a catalyst for private investment by correlating specific public grants to private investment data. This analysis aims to build on the previous section by describing the link between public support and downstream private capital investment and IP generation activity. Depending on data availability, it will also analyse the degree to which not receiving public funding support has been a hindrance to companies in relation to intellectual property generation and commercial activity.

In [80]:
# Read in private investment data that was collected by other GFI colleagues
# private investment was collected by year of deal
private2025 = pd.read_csv('data_output/private_investment_2025.csv')
private2024 = pd.read_csv('data_output/private_investment_2024.csv')
private2023 = pd.read_csv('data_output/private_investment_2023.csv')
private2022 = pd.read_csv('data_output/private_investment_2022.csv')
private2021 = pd.read_csv('data_output/private_investment_2021.csv')
private2020 = pd.read_csv('data_output/private_investment_2020.csv')

In [81]:
# combine all private investment tables in one
private = pd.concat([private2025, private2024, private2023, private2022, private2021, private2020])
private = private[private["Net0i Organisation ID"].notna()]
private["Net0i Organisation ID"] = private["Net0i Organisation ID"].astype(int)

In [82]:
# Check whether the names and organisation ID's match (= if one ID corresponds to one name only)
private.drop_duplicates(['Organisation name', 'Net0i Organisation ID'])['Net0i Organisation ID'].value_counts()

# after cleaning up some names, all ID's are unique except for two ID's that correspond to companies that changed their name
# Nutrumami -> SUMM Ingredients (ID: 153164); Re:Meat -> Curve (ID: 124873)

Net0i Organisation ID
153164    2
124873    2
31814     1
486       1
55931     1
         ..
179082    1
496       1
128227    1
43723     1
73048     1
Name: count, Length: 279, dtype: int64

In [83]:
df_np

,Title,Abstract,Original title,Database,Total amount,Gov & NP contribution,Currency,Total amount (USD),Gov & NP contribution (USD),Total amount (EUR),...,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104
0,"Precision Technology: Biotechnology, smart sen...",The project has three sub-goals:\n\nDeveloping...,NaN,airtable,64200000,64200000,NOK,7524240,7524240.00,5.585400e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,National Alternative Proteins Innovation and K...,"To secure a continued supply of safe, tasty, a...",NAPIC: National Alternative Protein Innovation...,airtable,38000000,16001352,GBP,48859450,18697500.00,4.522000e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Green technology for plant-based food (GreenPl...,To maintain national food self-sufficiency and...,GreenPlantFood - Green technology for plant-ba...,airtable,27600000,27600000,NOK,2604048,2604048.00,2.401200e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SYLPLANT,"Arbiom, an agricultural-biotech company develo...",NaN,airtable,23000000,14000000,EUR,25829000,15722000.00,2.300000e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,University of Bath Cellular Agriculture Manufa...,Imagine being able to manufacture food anywher...,Cellular Agriculture Manufacturing Hub,airtable,21214469,12302109,GBP,26130285,15655848.00,2.524522e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2238,Establishment of a process-specific risk facto...,NaN,NaN,GFI public investment database,40000000,40000000,KRW,28452,28452.00,2.600000e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2239,Study on the Safety Assessment Methods for Nov...,"[machine translated] ""Applying precision ferme...",NaN,GFI public investment database,60000001,60000001,KRW,41400,41400.00,3.900000e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2240,2025 High Value-Added Food Technology Developm...,"1,500,000,000 KRW each on the research topics ...",NaN,GFI public investment database,3000000000,3000000000,KRW,2063400,2063400.00,1.950000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2241,Research on improving safety assessment of foo...,"식품등안전관리 - 4) 선제적 위해요인 안전관리 (""Food and Product ...",NaN,GFI public investment database,200000000,200000000,KRW,154380,154380.00,1.400000e+05,...,3.0,NaN,False,False,False,False,ok,tool_use,260930.0,manual_review
2242,Development of food colloidal structures utili...,개인기초연구 - 우수연구-신진연구/우수신진 (Individual Basic Rese...,NaN,GFI public investment database,504860000,166603800,KRW,372233,122836.89,3.534020e+05,...,3.0,NaN,False,False,False,False,ok,tool_use,260930.0,manual_review

#### 13a. Normalise organisation names and generate match candidates

Matches **from** the curated private-investment company list **into** the funding data's
organisation text, rather than trying to resolve every funding org name into a canonical entity -
201 targeted lookups instead of ~1,200 messy names, and every candidate stays reviewable.

Matching and fractional weighting are deliberately decoupled: matching searches the *unsplit* text
(so a name shredded by a comma inside it is still found), while the recipient split is used only
for the 1/n denominator.

Tiers: `exact` (normalised equal, or equal ignoring spaces) and `contains` on a multi-token name
are auto-accepted; `contains` on a **single-token** name and anything `fuzzy` go to a review file.
Single-token names are the false-positive risk - 95 of the 201 companies have one-word names, and
e.g. `Multus` legitimately matches `Multus Biotechnology Limited` but not `Multus Media`.

The review file is written **without a run timestamp** so hand edits survive re-runs. Edit the
`accept` column (True/False) and re-run 13b to pick the decisions up.

In [84]:
import unicodedata
from rapidfuzz import fuzz

REVIEW_FILE = Path('data_output/company_match_review.csv')  # deliberately NOT timestamped
FUZZ_MIN = 88

# LEGAL FORMS ONLY. Descriptive words ('technologies', 'labs', 'group') are deliberately NOT
# stripped: removing them reduced 'Roslin Technologies' to the generic token 'roslin', which then
# matched 'Instytut Genetyki Roslin Polskiej Akademii Nauk'.
LEGAL_FORMS = (r'(ltd|limited|inc|incorporated|llc|plc|gmbh|mbh|ug|ag|bv|nv|ab|oyj|oy|as|asa|aps|'
               r'sa|sl|slu|srl|sas|sarl|spa|kg|kft|doo|ou|ehf|sia|pte|pty|co|corp|corporation|company)')


def normalise_org(name):
    """Lowercase, de-accent, drop parentheticals/punctuation, strip legal forms. '' if unusable."""
    if pd.isna(name):
        return ''
    s = str(name).replace('&amp;', '&').replace('&', ' and ')
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()  # 'Sophie’s' -> "sophie's"
    s = s.lower()
    s = re.sub(r'\(.*?\)', ' ', s)
    s = re.sub(r'[^a-z0-9]+', ' ', s)
    for _ in range(2):  # handles stacked forms like 'foo bv ltd'
        s = re.sub(rf'\b{LEGAL_FORMS}\b', ' ', s)
    s = re.sub(r'\bthe\b', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()


def _despace(s):
    return s.replace(' ', '')  # 'onego bio' == 'onegobio'


def split_collaborators(value):
    """Best-effort split of 'Collaborator institutions'. Delimiters are inconsistent (';' 109 rows,
    ',' 159, ' and ' 72, '&' 26) and commas also occur INSIDE names, so prefer ';' when present and
    only fall back to ','. Used for the 1/n denominator only - never for matching."""
    if pd.isna(value):
        return []
    t = str(value).replace('&amp;', '&')
    if ';' in t or '\n' in t:
        parts = re.split(r';|\n', t)
    elif ',' in t:
        parts = re.split(r',', t)
    else:
        parts = re.split(r'\s+and\s+|\s*/\s*', t)
    return [x.strip() for x in parts if x.strip()]


# --- recipients per grant, from df_np (non-profit funders already excluded) ---
# 'Multiple organisation recipients' is NOT used as a gate: it is 2,166 NaN / 133 No / 104 Yes plus
# ~19 rows holding country lists, and 396 grants list collaborators while it is not 'Yes'.
_recip_rows = []
for _idx, _r in df_np.iterrows():
    _pi = _r['PI organisation']
    _raw_collab = _r['Collaborator institutions']
    _recips = ([_pi] if pd.notna(_pi) else []) + split_collaborators(_raw_collab)
    # norm_blob is built from the UNSPLIT text on purpose - it is the fallback that catches a name
    # the split damaged, so it must not itself go through the split. Rejoining the split parts would
    # nearly work (delimiters collapse to spaces either way), but the ' and ' / '/' fallback branch
    # CONSUMES its delimiter: 'Flour Milling and Baking Research Association' loses its 'and', so a
    # company whose real name contains 'and' could not be recovered here. 6 grants differ.
    _blob_parts = ([str(_pi)] if pd.notna(_pi) else []) + ([str(_raw_collab)] if pd.notna(_raw_collab) else [])
    _recip_rows.append({
        'grant_idx': _idx,
        'recipients': _recips,
        'norm_recipients': [normalise_org(x) for x in _recips],
        'norm_blob': normalise_org(' ; '.join(_blob_parts)),
        'n_recipients': max(len(_recips), 1),
    })
grant_recipients = pd.DataFrame(_recip_rows)
print(f"{len(grant_recipients)} grants; {(grant_recipients['recipients'].map(len) > 0).sum()} name at "
      f"least one recipient. Recipients per grant: median "
      f"{int(grant_recipients['n_recipients'].median())}, max {grant_recipients['n_recipients'].max()}.")

# --- fuzzy engine: rapidfuzz if available, stdlib difflib otherwise (different scores, same tiers) ---

def _ratio(a, b): return fuzz.token_set_ratio(a, b)
FUZZ_ENGINE = 'rapidfuzz.token_set_ratio'

print(f'Fuzzy engine: {FUZZ_ENGINE}')

# --- company search list: EVERY name an ID has ever carried, not one row per ID ---
# Companies get renamed (e.g. 124873 Re:Meat -> Curve, 153164 Nutrumami -> SUMM Ingredients) and in
# both of those cases only the OLD name appears in the funding data - the grant predates the rename.
# Searching just the current name loses the match, so every (id, name) pair is searched and results
# attributed back to the id. 13b de-duplicates on (org_id, grant_idx), so an alias cannot double-count.
companies = (private[['Net0i Organisation ID', 'Organisation name']]
             .drop_duplicates()
             .rename(columns={'Net0i Organisation ID': 'org_id', 'Organisation name': 'org_name'}))
companies['org_norm'] = companies['org_name'].map(normalise_org)
companies['n_tokens'] = companies['org_norm'].str.split().str.len()
companies = (companies[companies['org_norm'] != '']
             .drop_duplicates(['org_id', 'org_norm']).reset_index(drop=True))
_n_ids = companies['org_id'].nunique()
_aliases = len(companies) - _n_ids
print(f"{_n_ids} private-investment companies searched under {len(companies)} name variants "
      f"({_aliases} renamed/alias); {(companies['n_tokens'] == 1).sum()} variants are single-token "
      f"(never auto-accepted).")

_cands = []
for _c in companies.itertuples(index=False):
    _cn, _cd = _c.org_norm, _despace(_c.org_norm)
    _pat = re.compile(rf'(?<![a-z0-9]){re.escape(_cn)}(?![a-z0-9])')
    for _g in grant_recipients.itertuples(index=False):
        _best = None
        for _rn, _raw in zip(_g.norm_recipients, _g.recipients):
            if not _rn:
                continue
            if _rn == _cn or _despace(_rn) == _cd:
                _best = ('exact', 100.0, _raw)
                break
            if _best is None and _pat.search(_rn):
                _best = ('contains', 100.0, _raw)
        if _best is None and _pat.search(_g.norm_blob):
            # name survived only in the unsplit text - a comma inside it shredded the split
            _best = ('contains_blob', 100.0, ' ; '.join(str(x) for x in _g.recipients)[:140])
        if _best is None:
            for _rn, _raw in zip(_g.norm_recipients, _g.recipients):
                if not _rn:
                    continue
                _sc = _ratio(_cn, _rn)
                if _sc >= FUZZ_MIN and (_best is None or _sc > _best[1]):
                    _best = ('fuzzy', _sc, _raw)
        if _best:
            _tier, _score, _matched = _best
            _cands.append({
                'org_id': _c.org_id, 'org_name': _c.org_name, 'org_norm': _cn,
                'n_tokens': _c.n_tokens, 'grant_idx': _g.grant_idx, 'tier': _tier,
                'score': round(_score, 1), 'matched_text': _matched,
                'n_recipients': _g.n_recipients,
                'accept': _tier == 'exact' or (_tier in ('contains', 'contains_blob') and _c.n_tokens >= 2),
            })

match_candidates = pd.DataFrame(_cands)
match_candidates['needs_review'] = ~match_candidates['accept']
print()
print(match_candidates.groupby(['tier', 'accept']).size().to_string())
print(f"\n{match_candidates['org_id'].nunique()} of {_n_ids} companies have at least one "
      f"candidate; {match_candidates.loc[match_candidates['accept'], 'org_id'].nunique()} are "
      f"auto-accepted. {int(match_candidates['needs_review'].sum())} pairs need review.")

if REVIEW_FILE.exists():
    print(f"\n{REVIEW_FILE} already exists - NOT overwritten. Delete it to regenerate from scratch.")
else:
    match_candidates.to_csv(REVIEW_FILE, index=False)
    print(f"\nWrote {REVIEW_FILE}. Edit the 'accept' column for the rows where needs_review is True, "
          f"then re-run 13b.")

print()
print(match_candidates[match_candidates['needs_review']]
      [['org_name', 'n_tokens', 'tier', 'score', 'matched_text']].to_string())

2243 grants; 2109 name at least one recipient. Recipients per grant: median 1, max 159.
Fuzzy engine: rapidfuzz.token_set_ratio
279 private-investment companies searched under 281 name variants (2 renamed/alias); 129 variants are single-token (never auto-accepted).

tier      accept
contains  False      29
          True       16
exact     True      165
fuzzy     False      27

106 of 279 companies have at least one candidate; 84 are auto-accepted. 56 pairs need review.

data_output\company_match_review.csv already exists - NOT overwritten. Delete it to regenerate from scratch.

                       org_name  n_tokens      tier  score                                                                                                                                                                                            matched_text
26          Roslin Technologies         2     fuzzy  100.0                                                                                                                                                                                                  Roslin
32                       Mewery         1  contains  100.0                                                                                                                                                                                           Mewery s.r.o.
33         Finnish Food Factory         3     fuzzy  100.0                                                                                                                                                                                                   "Food
34                 Vanetta Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food
35                     Uncommon         1  contains  100.0                                                                                                                                                                                        Uncommon Bio Ltd
40                  Quorn Foods         2     fuzzy  100.0                                                                                                                                                                                                   Quorn
41                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
42                       Multus         1  contains  100.0                                                                                                                                                                                            Multus Media
43                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
44                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
45                       Multus         1  contains  100.0                                                                                                                                                                            MULTUS BIOTECHNOLOGY LIMITED
46                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
47                       Multus         1  contains  100.0                                                                                                                                               University College London; Multus\n Biotechnology Limited
48                       Multus         1  contains  100.0                                                                                                                                                                                Multus Biotechnology Ltd
50                       Multus         1  contains  100.0                                                                                                                                                                                Multus Biotechnology Ltd
59             Clean Food Group         3     fuzzy  100.0                                                                                                                                                                                                   "Food
65                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
66                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
67                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
68                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
73                    Poseidona         1     fuzzy   90.0                                                                                                                                                                                          POSEIDONADA SL
84                      Planeat         1     fuzzy   93.3                                                                                                                                                                                            The PlantEat
90                        Formo         1  contains  100.0                                                                                                                                                                                          Formo Bio GmbH
91                        Formo         1  contains  100.0                                                                                                                                                                                        Formo Foods GmbH
101                  Greenforce         1  contains  100.0                                                                                                                                                                               GREENFORCE FUTURE FOOD AG
111              Ironic Biotech         2     fuzzy  100.0                                                                                                                                                                                               IRONIC AB
116                    Novameat         1  contains  100.0                                                                                                                                 Hooked Foods AB / Novameat / Sunny side / Solymeyea / ITC MURSKA SOBOTA
117                    Novameat         1  contains  100.0                                                                                                                                                                                        NOVAMEAT TECH SL
118                    Novameat         1  contains  100.0                                                                                                                                                                                     NOVAMEAT TECH, S.L.
120  The Mediterranean Food Lab         3     fuzzy  100.0                                                                                                                                                                                                   "Food
124                    Meatable         1  contains  100.0  National University of Singapore, A*STAR, Singapore Food Agency, TissUse, United States Food and Drug Administration (US-FDA), Meatable, Vireo Advisors, Asia-Pacific Society for Cellular Agriculture
127                   Planetary         1     fuzzy   90.0                                                                                                                                                                                         PlanetDairy ApS
128                   Planetary         1     fuzzy   90.0                                                                                                                                                                                         PlanetDairy ApS
129               Innocent Meat         2     fuzzy  100.0                                                                                                                                                                                            Innocent Ltd
132               Innocent Meat         2     fuzzy  100.0                                                                                                                                                                                        INNOCENT LIMITED
133                      Sallea         1  contains  100.0                                                                                                                                                 Simple Planet, Dongguk University, Sallea (Switzerland)
134                   Cultimate         1  contains  100.0                                                                                                                                                                                      CULTIMATE FOODS UG
138            The Very Food Co         2     fuzzy  100.0                                                                                                                                                                                                   "Food
142                       Vacka         1  contains  100.0                                                                                                                                                                                       VACKA QUESERIA SL
148                      Innomy         1  contains  100.0                                                                                                                                                                                       INNOMY BIOTECH SL
150                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
151                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
152                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
153                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
166                  Renew Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food
195                   Havredals         1  contains  100.0                                                                                                                                                                                 Havredals Biodevelop Ab
197                BLUU Seafood         2     fuzzy  100.0                                                                                                                                                                                               Bluu GmbH
198                BLUU Seafood         2     fuzzy  100.0                                                                                                                                                                                               Bluu GmbH
200        The Vegan Food Group         3     fuzzy  100.0                                                                                                                                                                                                   "Food
201                       Oatly         1  contains  100.0                                                                                                                                                                                                Oatly UK
202                       Oatly         1  contains  100.0                                                                                                                                                                                                Oatly UK
204                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                          Matr Foods ApS
205                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                              Matr Foods
206                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                          Matr Foods ApS
226               BioTech Foods         2     fuzzy  100.0                                                                                                                                                              NEW WAVE BIOTECH LTD; FORMIDABLE FOODS LTD
233                  Gosh! Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food

#### 13b. Public funding per matched company, by year

Applies the accepted matches with fractional counting: a grant's amount is split evenly across its
recipients (`1 / n_recipients`), and the matched company takes one share. If a company matched a
grant more than once (e.g. named as both PI and collaborator) it is de-duplicated to one share.

Reads `company_match_review.csv` if it exists so hand decisions win; otherwise falls back to the
auto-accepted tiers.

In [85]:
if REVIEW_FILE.exists():
    _decisions = pd.read_csv(REVIEW_FILE)
    _decisions['accept'] = _decisions['accept'].astype(str).str.strip().str.lower().isin(['true', '1', 'yes'])
    print(f'Using hand-reviewed decisions from {REVIEW_FILE}.')
else:
    _decisions = match_candidates.copy()
    print('No review file found - using auto-accepted tiers only.')

# Canonical name per Net0i ID, taken from the most recent deal. Two IDs carry two names because the
# company was renamed (Re:Meat -> Curve, Nutrumami -> SUMM Ingredients), so org_id is the ONLY safe
# join key - joining on the name as well would split those companies into separate rows.
ORG_NAME = (private.sort_values('Deal year')
            .drop_duplicates('Net0i Organisation ID', keep='last')
            .set_index('Net0i Organisation ID')['Organisation name'])


def _org_attribute(column):
    """Per-COMPANY lookup of a company-level attribute, from the most recent deal that records one.
    HQ country/continent belong to the company, not to a (company, year) pair, so a year in which a
    company has public funding but no private deal must still carry them - carrying them through the
    groupby alone leaves those rows NA (e.g. Bruno Cell: Italy on its 2020 deal, blank on its 2024
    grant-only row)."""
    have = private[private[column].notna()]
    return (have.sort_values('Deal year')
            .drop_duplicates('Net0i Organisation ID', keep='last')
            .set_index('Net0i Organisation ID')[column])


ORG_COUNTRY = _org_attribute('Organisation HQ country')
ORG_CONTINENT = _org_attribute('Organisation continent')

accepted = _decisions[_decisions['accept']].copy()
# One share per (company, grant): a company named as both PI and collaborator must not double-count.
accepted = accepted.drop_duplicates(['org_id', 'grant_idx'])
print(f"{len(accepted)} accepted (company, grant) pairs covering "
      f"{accepted['org_id'].nunique()} companies and {accepted['grant_idx'].nunique()} grants.")

_grant_cols = df_np[[FUNDING_COL, 'Year project started']].copy()
public_matched = accepted.merge(_grant_cols, left_on='grant_idx', right_index=True, how='left')
public_matched['company_share_eur'] = public_matched[FUNDING_COL] / public_matched['n_recipients']
public_matched['Year'] = public_matched['Year project started'].astype(int)

public_by_company_year = (public_matched.groupby(['org_id', 'Year'])
                          .agg(public_funding_eur=('company_share_eur', 'sum'),
                               grants=('grant_idx', 'nunique'))
                          .reset_index())
print(f"\nPublic funding attributed to matched companies: "
      f"EUR {public_by_company_year['public_funding_eur'].sum():,.0f} "
      f"({100 * public_by_company_year['public_funding_eur'].sum() / df_np[FUNDING_COL].sum():.1f}% of df_np).")
print(public_by_company_year.assign(org_name=lambda d: d['org_id'].map(ORG_NAME))
      .sort_values('public_funding_eur', ascending=False).head(15).to_string(index=False))

Using hand-reviewed decisions from data_output\company_match_review.csv.
222 accepted (company, grant) pairs covering 98 companies and 181 grants.

Public funding attributed to matched companies: EUR 110,958,752 (6.5% of df_np).
 org_id  Year  public_funding_eur  grants                     org_name
 165558  2024        9.605077e+06       2                      Labfarm
  56605  2022        8.507457e+06       1                  Melt&Marble
  31687  2020        8.352000e+06       1          The Protein Brewery
 104301  2022        5.999858e+06       1                   Herlab Ltd
  29755  2022        5.440049e+06       5                       Multus
  88765  2020        5.140274e+06       1                Extracellular
  31807  2024        4.499428e+06       1      Time-Travelling Milkman
 101471  2025        4.373420e+06       2             New Wave Biotech
   8777  2025        2.784086e+06       3                BioTech Foods
  40342  2023        2.695038e+06       4          Roslin Technologies
    489  2023        2.561608e+06       1                     Novameat
  88542  2022        2.380000e+06       1             Standing Ovation
 124872  2022        1.833124e+06       2                   Quest Meat
  40415  2025        1.746916e+06       2 Cellular Agriculture Limited
  29755  2023        1.391856e+06       3                       Multus

In [86]:
public_by_company_year

     org_id  Year  public_funding_eur  grants
0       486  2023        3.004208e+05       1
1       486  2024        1.060667e+06       2
2       489  2021        4.351890e+05       2
3       489  2023        2.561608e+06       1
4       489  2024        7.972200e+04       1
..      ...   ...                 ...     ...
161  124873  2024        3.000000e+05       1
162  127895  2023        9.984700e+04       1
163  153164  2021        3.116250e+05       1
164  153339  2024        1.992960e+05       1
165  165558  2024        9.605077e+06       2

[166 rows x 4 columns]

#### 13c. Public vs private investment by company and year

Private deal amounts are USD; converted to EUR with a year-end rate per deal year (same
Frankfurter source as 3a). Deals with no recorded amount are counted in `deals` but contribute 0 to
`private_investment_eur` - check the coverage line before using the ratio.

Rows are the union of (company, year) seen in either dataset, so a company with public funding but
no private deal that year appears with a zero, and vice versa.

In [87]:
# --- private side: USD -> EUR per deal year ---
private_deals = private.copy()
def _to_number(series):
    return pd.to_numeric(series.astype(str).str.replace(',', '', regex=False), errors='coerce')

private_deals['deal_amount_usd'] = _to_number(private_deals['Deal amount USD'])
private_deals['deal_amount_orig'] = _to_number(private_deals['Deal amount original currency'])
private_deals['Year'] = private_deals['Deal year'].astype(int)

# A deal already denominated in EUR is taken at its ORIGINAL amount - no conversion. The vendor's
# USD figure was converted at the deal-date rate (implied USD/EUR ranges 1.09-1.22 within 2020
# alone), so round-tripping it back through one year-end rate would inject error into a number that
# is already exact. Everything else converts from USD at a year-end rate, as elsewhere in this
# notebook.
_orig_ccy = private_deals['Deal original currency'].astype(str).str.strip().str.upper()
_is_eur = _orig_ccy.eq('EUR') & private_deals['deal_amount_orig'].notna()

_rates = {int(y): fetch_usd_to_eur_rate(f'{int(y)}-12-29') for y in sorted(private_deals['Year'].unique())}
print('USD->EUR year-end rates (used only for non-EUR deals):', _rates)

private_deals['deal_amount_eur'] = np.where(
    _is_eur,
    private_deals['deal_amount_orig'],
    private_deals['deal_amount_usd'] * private_deals['Year'].map(_rates),
)
private_deals['amount_source'] = np.where(
    _is_eur, 'original EUR',
    np.where(private_deals['deal_amount_usd'].notna(), 'converted from USD', 'no amount'))

print(private_deals['amount_source'].value_counts().to_string())
_missing = (private_deals['amount_source'] == 'no amount').sum()
print(f"{_missing} of {len(private_deals)} deals ({100 * _missing / len(private_deals):.0f}%) have no "
      f"recorded amount and contribute 0 EUR - treat the ratio as a lower bound on private capital.")

private_by_company_year = (private_deals.groupby(['Net0i Organisation ID', 'Year', 'Organisation HQ country', 'Organisation continent'])
                           .agg(private_investment_eur=('deal_amount_eur', 'sum'),
                                deals=('Net0i Organisation ID', 'size'),
                                deals_with_amount=('deal_amount_eur', 'count'))
                           .reset_index()
                           .rename(columns={'Net0i Organisation ID': 'org_id', 
                                            'Organisation HQ country': 'country',
                                            'Organisation continent': 'continent'}))

# Outer join on org_id + Year ONLY (see ORG_NAME note in 13b), so public-only and private-only
# (company, year) rows both survive; the name is attached afterwards.
public_vs_private = (public_by_company_year
                     .merge(private_by_company_year, on=['org_id', 'Year'], how='outer')
                     .fillna({'public_funding_eur': 0, 'grants': 0,
                              'private_investment_eur': 0, 'deals': 0, 'deals_with_amount': 0}))
public_vs_private.insert(1, 'org_name', public_vs_private['org_id'].map(ORG_NAME))
# Backfill company-level attributes on rows that came only from the public side (no deal that year).
for _col, _lookup in (('country', ORG_COUNTRY), ('continent', ORG_CONTINENT)):
    _before = public_vs_private[_col].isna().sum()
    public_vs_private[_col] = public_vs_private[_col].fillna(public_vs_private['org_id'].map(_lookup))
    _after = public_vs_private[_col].isna().sum()
    print(f"{_col}: filled {_before - _after} of {_before} blank rows from the company's other rows"
          f"{f'; {_after} still blank' if _after else ''}.")
public_vs_private[['grants', 'deals', 'deals_with_amount']] = \
    public_vs_private[['grants', 'deals', 'deals_with_amount']].astype(int)
public_vs_private = public_vs_private.sort_values(['org_name', 'Year']).reset_index(drop=True)

assert public_vs_private['org_name'].notna().all(), 'org_id present in funding matches but not in private data'
assert not public_vs_private.duplicated(['org_id', 'Year']).any(), 'duplicate (company, year) rows'

save(public_vs_private, 'Q18_public_vs_private_by_company_and_year', index=False)
print()
print(public_vs_private.to_string(index=False, float_format=lambda v: f'{v:,.0f}'))

_yr = public_vs_private.groupby('Year')[['public_funding_eur', 'private_investment_eur']].sum()
_yr['private_per_public_eur'] = _yr['private_investment_eur'] / _yr['public_funding_eur']
print()
_pub_yrs = sorted(public_by_company_year['Year'].unique())
_prv_yrs = sorted(private_by_company_year['Year'].unique())
print(f'Year totals across matched companies. NOT a causal ratio - public and private are')
print(f'contemporaneous here, with no lag applied. Public years {_pub_yrs[0]}-{_pub_yrs[-1]}, '
      f'private years {_prv_yrs[0]}-{_prv_yrs[-1]};')
print(f'any year present in only one of the two gives a meaningless ratio.')
print(_yr.to_string(float_format=lambda v: f'{v:,.2f}'))

USD->EUR year-end rates (used only for non-EUR deals): {2020: 0.81573, 2021: 0.88472, 2022: 0.93906, 2023: 0.90498, 2024: 0.95831, 2025: 0.84991}
amount_source
no amount             468
original EUR          347
converted from USD    275
468 of 1090 deals (43%) have no recorded amount and contribute 0 EUR - treat the ratio as a lower bound on private capital.
country: filled 68 of 68 blank rows from the company's other rows.
continent: filled 68 of 68 blank rows from the company's other rows.
Saved Q18_public_vs_private_by_company_and_year -> data_output\analysis\Q18_public_vs_private_by_company_and_year.csv

 org_id                       org_name  Year  public_funding_eur  grants        country continent  private_investment_eur  deals  deals_with_amount
  68536                       21St.Bio  2021                   0       0        Denmark    Europe              86,000,000      1                  1
 179045                          5Yes!  2021                   0       0         Russia    Europe                       0      1                  0
 179046                            Aak  2021                   0       0         Sweden    Europe             400,000,000      1                  1
 179046                            Aak  2022                   0       0         Sweden    Europe             253,990,741      3                  3
  42893                        Aberyne  2022                   0       0         France    Europe                       0      1                  0
  88658                    Adamo Foods  2022                   0       0 United Kingdom    Europe                 950,713      3                  2
  88658                    Adamo Foods  2023           1,250,224       4 United Kingdom    Europe               2,495,281      6                  3
  88658                    Adamo Foods  2024             205,018       1 United Kingdom    Europe               2,466,864      2                  1
  88658                    Adamo Foods  2025              59,500       1 United Kingdom    Europe                 359,813      2                  1
  97369                            Aio  2022                   0       0        Estonia    Europe                 210,000      3                  2
  97369                            Aio  2023                   0       0        Estonia    Europe               1,180,000      4                  3
  97369                            Aio  2024                   0       0        Estonia    Europe              12,500,000      6                  4
  97369                            Aio  2025                   0       0        Estonia    Europe               2,200,000      2                  2
  31768                         Algama  2020                   0       0         France    Europe                       0      1                  0
  31768                         Algama  2021                   0       0         France    Europe               2,000,000      2                  1
  31768                         Algama  2022             133,124       1         France    Europe                       0      0                  0
  31768                         Algama  2023              13,221       1         France    Europe              13,000,000      1                  1
 110921                      Alt Atlas  2022                   0       0 United Kingdom    Europe                       0      2                  0
 110921                      Alt Atlas  2023                   0       0 United Kingdom    Europe                       0      2                  0
 111102        Apollo Roslinny Qurczak  2020                   0       0         Poland    Europe                       0      1                  0
 110927                         Arivia  2020                   0       0         Greece    Europe             500,000,000      1                  1
  57032                         Arkeon  2022                   0       0        Austria    Europe               9,756,240      2                  2
  57032                         Arkeon  2023                   0       0        Austria    Europe               2,750,000      1                  1
 179066                    Awevo Foods  2023                   0       0          Spain    Europe                       0      1                  0
  41330                   BLUU Seafood  2020             178,434       1        Germany    Europe                       0      0                  0
  41330                   BLUU Seafood  2021              45,500       1        Germany    Europe               7,000,000      2                  1
  41330                   BLUU Seafood  2023                   0       0        Germany    Europe              16,000,000      1                  1
  41330                   BLUU Seafood  2024             288,733       2        Germany    Europe                       0      0                  0
  55628                      Bene Meat  2023                   0       0 Czech Republic    Europe                       0      1                  0
  39666                      BettaF!sh  2020                   0       0        Germany    Europe                       0      1                  0
  39666                      BettaF!sh  2021                   0       0        Germany    Europe                       0      2                  0
  39666                      BettaF!sh  2023                   0       0        Germany    Europe                       0      1                  0
  39666                      BettaF!sh  2024             457,630       1        Germany    Europe                       0      4                  0
  39666                      BettaF!sh  2025                   0       0        Germany    Europe                 248,562      2                  1
  31611                   Better Dairy  2020                   0       0 United Kingdom    Europe               1,774,498      3                  1
  31611                   Better Dairy  2022                   0       0 United Kingdom    Europe              20,683,089      1                  1
  31611                   Better Dairy  2024             620,943       2 United Kingdom    Europe                       0      1                  0
  31611                   Better Dairy  2025             448,953       1 United Kingdom    Europe                       0      0                  0
 109256         BioCraft Pet Nutrition  2021                   0       0        Austria    Europe                       0      1                  0
 133326                         BioGNR  2022                   0       0      Lithuania    Europe                  20,000      1                  1
   8777                  BioTech Foods  2020                   0       0          Spain    Europe               1,906,961      1                  1
   8777                  BioTech Foods  2021                   0       0          Spain    Europe              41,200,000      2                  2
   8777                  BioTech Foods  2022              62,500       2          Spain    Europe                 753,000      1                  1
   8777                  BioTech Foods  2023           1,220,974       3          Spain    Europe                       0      0                  0
   8777                  BioTech Foods  2024             349,753       1          Spain    Europe                       0      0                  0
   8777                  BioTech Foods  2025           2,784,086       3          Spain    Europe                       0      0                  0
 110938                         Biolab  2025                   0       0          Italy    Europe                       0      1                  0
 101359                         Bluana  2022                   0       0        Romania    Europe                 317,382      4                  2
 101359                         Bluana  2023                   0       0        Romania    Europe                       0      2                  0
 101359                         Bluana  2024                   0       0        Romania    Europe                 100,000      2                  2
 101359                         Bluana  2025                   0       0        Romania    Europe                       0      2                  0
  42545                      Blue Farm  2020                   0       0        Germany    Europe                       0      1                  0
  42545                      Blue Farm  2021                   0       0        Germany    Europe                       0      2                  0
  42545                      Blue Farm  2022                   0       0        Germany    Europe               3,000,000      1                  1
  42545                      Blue Farm  2023                   0       0        Germany    Europe                       0      1                  0
  42545                      Blue Farm  2025                   0       0        Germany    Europe               1,334,070      1                  1
 110942                   Bolder Foods  2022                   0       0        Belgium    Europe                       0      1                  0
 110942                   Bolder Foods  2023                   0       0        Belgium    Europe                       0      1                  0
  60154                     Bon Vivant  2022                   0       0         France    Europe               5,500,000      2                  2
  60154                     Bon Vivant  2023                   0       0         France    Europe              15,000,000      1                  1
  60154                     Bon Vivant  2024                   0       0         France    Europe              10,000,000      6                  2
  55667                   Bosque Foods  2021             465,722       1        Germany    Europe                 442,360      3                  1
  55667                   Bosque Foods  2022                   0       0        Germany    Europe               2,817,180      2                  1
  55667                   Bosque Foods  2023                   0       0        Germany    Europe                   5,000      2                  1
  55667                   Bosque Foods  2024                   0       0        Germany    Europe                       0      2                  0
 192677                     Brew Bites  2025                   0       0        Germany    Europe                 254,973      2                  1
  72243                 Bright Biotech  2021                   0       0 United Kingdom    Europe                  12,452      2                  1
  72243                 Bright Biotech  2022                   0       0 United Kingdom    Europe               6,187,034      3                  2
  72243                 Bright Biotech  2025                   0       0 United Kingdom    Europe               1,143,692      1                  1
  26553                     Bruno Cell  2020                   0       0          Italy    Europe                       0      1                  0
  26553                     Bruno Cell  2023                 502       1          Italy    Europe                       0      0                  0
 179082                   Bunte Burger  2020                   0       0        Germany    Europe                       0      1                  0
  31823              Bute Island Foods  2021                   0       0 United Kingdom    Europe             135,738,467      1                  1
  84466                   Calidris Bio  2022             292,675       1        Belgium    Europe                       0      1                  0
  84466                   Calidris Bio  2024                   0       1        Belgium    Europe                       0      0                  0
 172465                      Catchfree  2023                   0       0    Switzerland    Europe                  34,274      2                  2
 172465                      Catchfree  2024                   0       0    Switzerland    Europe                       0      2                  0
 172465                      Catchfree  2025                   0       0    Switzerland    Europe               1,247,745      2                  2
  45908                     Cell Craft  2020                   0       0 United Kingdom    Europe                       0      1                  0
  45908                     Cell Craft  2021                   0       0 United Kingdom    Europe                 176,944      2                  1
  45908                     Cell Craft  2023             609,200       2 United Kingdom    Europe                 504,270      2                  1
  45908                     Cell Craft  2024                   0       0 United Kingdom    Europe                 423,131      1                  1
 127895                      Cell4Food  2022                   0       0       Portugal    Europe                       0      1                  0
 127895                      Cell4Food  2023              99,847       1       Portugal    Europe                       0      0                  0
 127895                      Cell4Food  2024                   0       0       Portugal    Europe                       0      2                  0
 127895                      Cell4Food  2025                   0       0       Portugal    Europe               1,500,000      3                  1
 110949                        CellRev  2020                   0       0 United Kingdom    Europe                  90,862      1                  1
 110949                        CellRev  2021                   0       0 United Kingdom    Europe               1,227,445      2                  1
 110949                        CellRev  2022                   0       0 United Kingdom    Europe               2,223,977      2                  1
 110949                        CellRev  2024                   0       0 United Kingdom    Europe                       0      1                  0
  40415   Cellular Agriculture Limited  2020                   0       1 United Kingdom    Europe                  44,865      1                  1
  40415   Cellular Agriculture Limited  2021                   0       0 United Kingdom    Europe                 176,944      2                  2
  40415   Cellular Agriculture Limited  2022              82,264       3 United Kingdom    Europe                       0      1                  0
  40415   Cellular Agriculture Limited  2023           1,103,870       3 United Kingdom    Europe                 794,868      2                  2
  40415   Cellular Agriculture Limited  2024              26,573       1 United Kingdom    Europe                       0      0                  0
  40415   Cellular Agriculture Limited  2025           1,746,916       2 United Kingdom    Europe                       0      0                  0
  73048                    Chunk Foods  2020                   0       0         Turkey    Europe                       0      1                  0
  89432               Clean Food Group  2022                   0       0 United Kingdom    Europe               1,855,290      2                  1
  89432               Clean Food Group  2023           1,103,369       2 United Kingdom    Europe               3,253,976      2                  2
  89432               Clean Food Group  2024                   0       0 United Kingdom    Europe               3,050,278      2                  1
  89432               Clean Food Group  2025                   0       0 United Kingdom    Europe                       0      1                  0
  47781          Cocuus System Iberica  2020             771,372       1          Spain    Europe                       0      0                  0
  47781          Cocuus System Iberica  2021                   0       0          Spain    Europe                       0      1                  0
  47781          Cocuus System Iberica  2022                   0       0          Spain    Europe               2,500,000      1                  1
 103324                Connectomix Bio  2022                   0       0     Luxembourg    Europe                       0      1                  0
   8746                    Cubiq Foods  2020                   0       0          Spain    Europe               5,000,000      1                  1
   8746                    Cubiq Foods  2022             503,920       1          Spain    Europe               5,750,000      1                  1
   8746                    Cubiq Foods  2023                   0       0          Spain    Europe               2,262,450      1                  1
  88766                      Cultimate  2022                   0       0        Germany    Europe                 900,000      4                  2
  88766                      Cultimate  2023                 502       1        Germany    Europe                       0      2                  0
  88766                      Cultimate  2024                   0       0        Germany    Europe               4,600,000      2                  2
  84645         Cultivated Biosciences  2021                   0       0    Switzerland    Europe                   9,643      3                  1
  84645         Cultivated Biosciences  2022                   0       0    Switzerland    Europe               1,641,067      5                  5
  84645         Cultivated Biosciences  2023                   0       0    Switzerland    Europe                       0      2                  0
  84645         Cultivated Biosciences  2024                   0       0    Switzerland    Europe               9,583,100      6                  2
 124609                 Cultured Foods  2023             268,124       1         Poland    Europe                 484,164      1                  1
 124609                 Cultured Foods  2024             119,759       1         Poland    Europe                       0      0                  0
 124873                          Curve  2023                   0       0         Sweden    Europe                 284,042      3                  2
 124873                          Curve  2024             300,000       1         Sweden    Europe                 322,742     10                  4
 124873                          Curve  2025                   0       0         Sweden    Europe               1,001,254      2                  2
  30602                           DRYK  2021                   0       0        Denmark    Europe                       0      1                  0
  30602                           DRYK  2022                   0       0        Denmark    Europe                       0      1                  0
 113569                   DUG Foodtech  2020                   0       0         Sweden    Europe                       0      1                  0
 113569                   DUG Foodtech  2022                   0       0         Sweden    Europe               1,497,825      1                  1
 113569                   DUG Foodtech  2023                   0       0         Sweden    Europe               1,487,359      1                  1
 113569                   DUG Foodtech  2024                   0       0         Sweden    Europe                 324,208      2                  2
  39907             Devon Garden Foods  2020                   0       0 United Kingdom    Europe                  20,000      1                  1
  31884                   Dr. Mannah's  2023                   0       0        Germany    Europe                       0      1                  0
 124265                      Dreamfarm  2023                   0       0          Italy    Europe               5,000,000      1                  1

In [88]:
public_vs_private

,org_id,org_name,Year,public_funding_eur,grants,country,continent,private_investment_eur,deals,deals_with_amount
0,68536,21St.Bio,2021,0.0,0,Denmark,Europe,8.600000e+07,1,1
1,179045,5Yes!,2021,0.0,0,Russia,Europe,0.000000e+00,1,0
2,179046,Aak,2021,0.0,0,Sweden,Europe,4.000000e+08,1,1
3,179046,Aak,2022,0.0,0,Sweden,Europe,2.539907e+08,3,3
4,42893,Aberyne,2022,0.0,0,France,Europe,0.000000e+00,1,0
...,...,...,...,...,...,...,...,...,...,...
687,102467,YOFI,2021,0.0,0,France,Europe,1.105900e+05,1,1
688,128294,Yeastup,2022,0.0,0,Switzerland,Europe,8.188603e+05,1,1
689,128294,Yeastup,2024,0.0,0,Switzerland,Europe,1.916627e+07,2,2
690,12254,Yumgo,2022,0.0,0,France,Europe,1.500000e+06,1,1
691,12254,Yumgo,2024,0.0,0,France,Europe,6.000000e+06,2,2

### 14. HORIZON money

In [89]:
horizon = pd.read_csv("data_output/HORIZON_funding.csv")

In [90]:
horizon

,Title,Abstract,Total amount,Gov & NP contribution,Currency,Funding decision,URL for announcement,Identification code,Project start date,Funder name,...,microalgae,Award purpose,End product type,sub-end product,Research category,Year project started,End date,recipient_institutions,recipient_countries,recipient_funding_amount
0,Like-A-Pro: From niche to mainstream - alterna...,The interest of Europeans in alternative prote...,13909093.00,11999660.00,EUR,Awarded,https://cordis.europa.eu/project/id/101083961,grant.13029417,2022-11-01 0:00:00,European Commission,...,NaN,Research and development; Education and traini...,Agnostic,NaN,"End product formulation, Consumer & market res...",2022.0,2026.0,CENTRO NACIONAL DE TECNOLOGIA Y SEGURIDAD ALIM...,Spain; Norway; Germany; Denmark; Belgium; Belg...,1 341 092.05; 978 201.25; 809 937.50; 551 775....
1,HealthFerm: Innovative pulse and cereal-based ...,Food fermentation is a natural process in whic...,11303944.75,11303944.75,EUR,Awarded,https://cordis.europa.eu/project/id/101060247/...,grant.12941144,2022-09-01 0:00:00,European Commission,...,NaN,Research and development,Agnostic,NaN,"Strain development, Ingredient optimisation, E...",2022.0,2026.0,KATHOLIEKE UNIVERSITEIT LEUVEN; VIB VZW; CHALM...,Belgium; Belgium; Sweden; Finland; Belgium; Fi...,2 046 148.42; 987 750.00; 826 475.00; 754 206....
2,Harnessing the microbial potential of fermente...,Food and beverage fermentation dates back 7 00...,10815148.00,10815148.00,EUR,Awarded,https://cordis.europa.eu/project/id/101060218,NaN,2023-03-01 0:00:00,European Commission,...,NaN,Research and development,Dairy,Yoghurt and fermented dairy,"End product formulation, Health & nutrition",2023.0,2028.0,INSTITUT NATIONAL DE RECHERCHE POUR L'AGRICULT...,France; Ireland; Italy; Spain; Italy; Italy; B...,2 848 336.25; 1 277 277.50; 1 072 187.50; 919 ...
3,"Gap resolutIon in sAfety, NuTritional, alLerge...",NaN,10347863.00,10272862.00,EUR,Awarded,https://cordis.europa.eu/project/id/101059632,grant.12960620,2022-09-01 0:00:00,European Commission,...,NaN,Research and development,Agnostic,NaN,"Food safety & quality, Health & nutrition",2022.0,2026.0,STICHTING WAGENINGEN RESEARCH; TEKNOLOGIAN TUT...,Netherlands; Finland; Germany; Netherlands; Fr...,1 724 397.50; 759 389.00; 736 000.00; 719 825....
4,new VALue landscapes for plant PROtein Pathway...,The current European plant-protein landscape i...,9580339.88,8658160.51,EUR,Awarded,https://cordis.europa.eu/project/id/101059824,grant.12960983,2022-09-01 0:00:00,European Commission,...,NaN,Research and development; Networking,Agnostic,NaN,Impact Assessments,2022.0,2026.0,TEAGASC - AGRICULTURE AND FOOD DEVELOPMENT AUT...,Ireland; Denmark; Italy; Serbia; Netherlands; ...,1 623 293.63; 1 201 237.50; 697 750.00; 606 95...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,FunSea,One of our most pressing societal challenges t...,NaN,NaN,NaN,Awarded,https://bluepartnership.eu/projects/functional...,need to check,2024-04-01 0:00:00,European Commission,...,NaN,Research and development,Agnostic,NaN,"Ingredient optimisation, End product formulati...",2024.0,2027.0,NaN,NaN,NaN
163,AlgFlavor: Enhancing algal biomass consumer ac...,As society shifts away from animal-based diets...,1666667.00,1666667.00,EUR,Awarded,https://bluepartnership.eu/news/24-projects-re...,NaN,2025-05-01 0:00:00,European Commission,...,NaN,Research and development,Fish and seafood,NaN,"Bioprocess design, Ingredient optimisation, En...",2025.0,2028.0,NaN,NaN,NaN
164,SEANERGIES: Cell-cultured octopus production t...,The world’s population is projected to surpass...,1666667.00,1666667.00,EUR,Awarded,https://bluepartnership.eu/news/24-projects-re...,NaN,2025-05-01 0:00:00,European Commission,...,NaN,Research and development,Fish and seafood,NaN,"Cell line development, Cell culture media, Bio...",2025.0,2028.0,NaN,NaN,NaN
165,BIOVAL: Microalgal biomass valorization for su...,The main aim of this proposal is the developme...,1666667.00,1666667.00,EUR,Awarded,https://bluepartnership.eu/news/24-projects-re...,NaN,2025-05-01 0:00:00,European Commission,...,NaN,Research and development,Agnostic,NaN,"Bioprocess design, Ingredient optimisation, He...",2025.0,2028.0,NaN,NaN,NaN
166,Topic: Holistic chia and oyster mushroom syste...,NaN,86826.00,86826.00,EUR,Awarded,NaN,NaN,2021-06-01 0:00:00,European Commission,...,NaN,Research and development,Agnostic,NaN,Other,2021.0,2021.0,NaN,NaN,NaN

#### 14a. HORIZON funding by sub-funder and recipient country

`recipient_institutions`, `recipient_countries` and `recipient_funding_amount` are three parallel
`;`-separated lists - position *i* in each refers to the same recipient - so they are zipped
positionally rather than split independently. No fractional counting: each recipient's exact
amount is used.

Amounts use a space as the thousands separator (`1 341 092.05`), so the spaces are stripped before
parsing. Rows whose three lists disagree in length are reported and skipped rather than silently
mis-zipped.

In [91]:
def _split_semicolon(value):
    """'A; B; C' -> ['A', 'B', 'C']. Empty list for a blank cell."""
    if pd.isna(value):
        return []
    return [x.strip() for x in str(value).split(';') if x.strip() != '']


def _parse_amount(value):
    """'1 341 092.05' -> 1341092.05. Space (incl. non-breaking) is the thousands separator here,
    '.' the decimal point."""
    return pd.to_numeric(re.sub(r'[\s\u00a0\u202f]', '', str(value)), errors='coerce')


RECIPIENT_COLS = ['recipient_institutions', 'recipient_countries', 'recipient_funding_amount']

_recipient_rows = []
_no_breakdown = 0
_misaligned = []
for _idx, _r in horizon.iterrows():
    _inst = _split_semicolon(_r['recipient_institutions'])
    _ctry = _split_semicolon(_r['recipient_countries'])
    _amts = _split_semicolon(_r['recipient_funding_amount'])
    if not _ctry:
        _no_breakdown += 1
        continue
    # The three lists are positionally aligned, so a length mismatch would silently pair the wrong
    # country with the wrong amount - skip and report instead of zipping to the shortest list.
    if not (len(_inst) == len(_ctry) == len(_amts)):
        _misaligned.append((_idx, len(_inst), len(_ctry), len(_amts)))
        continue
    for _i, (_institution, _country, _amount) in enumerate(zip(_inst, _ctry, _amts)):
        _recipient_rows.append({
            'grant_idx': _idx,
            'Title': _r['Title'],
            'Sub-funder': _r['Sub-funder'],
            'recipient_institution': _institution,
            'recipient_country': _country,
            'recipient_funding_eur': _parse_amount(_amount),
        })

horizon_recipients = pd.DataFrame(_recipient_rows)
horizon_recipients['Sub-funder'] = horizon_recipients['Sub-funder'].fillna('NA')

print(f"{len(horizon)} HORIZON grants -> {len(horizon_recipients)} recipient entries "
      f"across {horizon_recipients['recipient_country'].nunique()} countries and "
      f"{horizon_recipients['Sub-funder'].nunique()} sub-funders.")
print(f"{_no_breakdown} grants have no recipient breakdown and are excluded.")
if _misaligned:
    print(f"WARNING: {len(_misaligned)} grants skipped - the three lists disagree in length "
          f"(grant_idx, n_inst, n_country, n_amount): {_misaligned}")
_unparsed = int(horizon_recipients['recipient_funding_eur'].isna().sum())
if _unparsed:
    print(f'WARNING: {_unparsed} recipient amounts could not be parsed and count as 0.')

# One number per sub-funder per country.
horizon_subfunder_country = horizon_recipients.pivot_table(
    index='Sub-funder', columns='recipient_country', values='recipient_funding_eur',
    aggfunc='sum', fill_value=0,
)
horizon_subfunder_country['Total'] = horizon_subfunder_country.sum(axis=1)
horizon_subfunder_country = horizon_subfunder_country.sort_values('Total', ascending=False)
horizon_subfunder_country.loc['Total'] = horizon_subfunder_country.sum()
horizon_subfunder_country = horizon_subfunder_country[horizon_subfunder_country.columns[horizon_subfunder_country.loc["Total"] != 0]]

# One number per grant per country.
horizon_grant_country = horizon_recipients.pivot_table(
    index='Title', columns='recipient_country', values='recipient_funding_eur',
    aggfunc='sum', fill_value=0,
)
horizon_grant_country['Total'] = horizon_grant_country.sum(axis=1)
horizon_grant_country = horizon_grant_country.sort_values('Total', ascending=False)
horizon_grant_country.loc['Total'] = horizon_grant_country.sum()
horizon_grant_country = horizon_grant_country[horizon_grant_country.columns[horizon_grant_country.loc["Total"] != 0]]

save(horizon_subfunder_country, '14a_horizon_funding_by_subfunder_and_country')
save(horizon_grant_country, '14a_horizon_funding_by_grant_and_country')
print()
print(horizon_subfunder_country.to_string(float_format=lambda v: f'{v:,.0f}'))

print(f"\nTotal allocated to recipients: EUR "
      f"{horizon_recipients['recipient_funding_eur'].sum():,.2f}.")

167 HORIZON grants -> 944 recipient entries across 47 countries and 8 sub-funders.
74 grants have no recipient breakdown and are excluded.
Saved 14a_horizon_funding_by_subfunder_and_country -> data_output\analysis\14a_horizon_funding_by_subfunder_and_country.csv
Saved 14a_horizon_funding_by_grant_and_country -> data_output\analysis\14a_horizon_funding_by_grant_and_country.csv

recipient_country                                                                                                                          Argentina   Austria    Belgium  Bulgaria    Canada  Croatia  Cyprus   Czechia    Denmark   Estonia    Finland     France    Germany     Greece   Hungary   Iceland    Ireland    Israel      Italy    Latvia  Lebanon  Lithuania  Luxembourg   Malta  Netherlands  North Macedonia    Norway    Poland   Portugal   Romania    Serbia  Slovenia      Spain     Sweden  Switzerland  Thailand    Turkey  Ukraine  United Kingdom       Total
Sub-funder
Cluster 6: Food, Bioeconomy Natural Resources, Agriculture and Environment                                                                         0 2,709,888 12,615,583   412,695 1,025,093  424,520 146,250   377,280 12,009,678 3,119,950 10,279,220 23,938,042 16,855,279  8,738,259   506,750   821,146  6,602,025   180,486 10,188,393 1,698,336        0    669,466      88,348 288,698   13,569,869                0 8,329,298 3,400,836  8,532,340   650,520 1,487,341   927,950 28,703,454 11,826,463            0         0   242,000        0       3,579,172 194,944,627
European Innovation Council (EIC)                                                                                                                  0 4,949,999    620,829         0         0        0       0         0    698,002         0  4,828,824  2,474,938  4,160,555  2,442,728         0         0          0 2,432,030    479,061         0        0          0           0       0    1,879,851                0         0         0  4,677,135         0         0         0  6,139,408  6,354,840            0         0         0        0       1,772,210  43,910,410
SOCIETAL CHALLENGES - Food security, sustainable agriculture and forestry, marine, maritime and inland water research, and the bioeconomy     40,435    74,738    776,575         0         0        0       0 1,062,219  1,607,754         0          0  4,309,307  6,728,880          0   927,375 2,500,000  3,435,586   143,325  4,729,851         0  250,000          0           0       0    3,490,688                0   481,766   429,954  6,404,106   245,000         0   176,999  4,412,679    370,064      501,685    97,562         0        0         659,619  43,856,166
Marie Skłodowska-Curie Actions (MSCA)                                                                                                              0   528,414  1,489,020   207,295         0        0       0         0  1,225,824         0          0  3,439,057  1,221,030    488,498         0         0  1,385,838   271,433    880,215         0        0          0           0       0    2,318,189                0         0   519,800    237,720   322,000         0         0  1,918,720    293,710            0         0         0        0               0  16,746,764
Widening participation and spreading excellence                                                                                                    0         0    609,500         0         0        0       0         0    460,056         0          0          0    304,106  2,415,951         0         0          0         0    457,594         0        0          0           0 205,148            0          122,988         0   327,012          0         0         0         0     89,800    122,321            0         0 4,308,058  897,812         122,944  10,443,290
European Research Council (ERC)                                                                                                                    0         0          0         0         0        0       0         0          0         0          0          0  1,499,961          0         0         0  2,076,770   300,000          0         0        0          0           0       0            0                0         0         0  1,499,791         0         0         0  2,355,741    150,000            0         0         0        0               0   7,882,263
Horizon 2020 Framework Programme                                                                                                                   0         0          0         0         0        0       0         0          0         0          0    496,038          0          0         0         0          0         0          0         0        0          0           0       0            0                0         0         0    225,050         0         0         0  1,185,874          0            0         0         0        0               0   1,906,961
European innovation ecosystems                                                                                                                     0         0    120,325         0         0        0       0         0          0   131,500    138,967    370,238    150,000          0         0         0    109,375         0    152,098   159,438        0    129,750           0       0      121,354                0         0         0          0         0         0         0          0    150,531            0         0         0        0               0   1,733,575
Total                                                                                                                                         40,435 8,263,040 16,231,832   619,990 1,025,093  424,520 146,250 1,439,499 16,001,314 3,251,450 15,247,011 35,027,618 30,919,810 14,085,437 1,434,125 3,321,146 13,609,594 3,327,274 16,887,213 1,857,774  250,000    799,216      88,348 493,845   21,379,951          122,988 8,811,065 4,677,602 21,576,142 1,217,520 1,487,341 1,104,949 44,805,675 19,267,929      501,685    97,562 4,550,058  897,812       6,133,944 321,424,056

Total allocated to recipients: EUR 321,424,056.11.

In [92]:
horizon_subfunder_country[horizon_subfunder_country.columns[horizon_subfunder_country.loc["Total"] != 0]]

recipient_country,Argentina,Austria,Belgium,Bulgaria,Canada,Croatia,Cyprus,Czechia,Denmark,Estonia,...,Serbia,Slovenia,Spain,Sweden,Switzerland,Thailand,Turkey,Ukraine,United Kingdom,Total
Sub-funder,,,,,,,,,,,,,,,,,,,,,
"Cluster 6: Food, Bioeconomy Natural Resources, Agriculture and Environment",0.00,2709888.48,12615583.00,412695.0,1025093.25,424520.0,146250.0,377280.00,12009677.66,3119949.5,...,1487341.0,927949.93,28703453.53,11826462.68,0.0,0.0,242000.0,0.0,3579171.75,1.949446e+08
European Innovation Council (EIC),0.00,4949999.00,620829.24,0.0,0.00,0.0,0.0,0.00,698002.13,0.0,...,0.0,0.00,6139407.81,6354840.00,0.0,0.0,0.0,0.0,1772209.50,4.391041e+07
"SOCIETAL CHALLENGES - Food security, sustainable agriculture and forestry, marine, maritime and inland water research, and the bioeconomy",40435.49,74738.13,776575.00,0.0,0.00,0.0,0.0,1062219.38,1607753.89,0.0,...,0.0,176998.75,4412679.03,370063.75,501685.0,97562.5,0.0,0.0,659618.75,4.385617e+07
Marie Skłodowska-Curie Actions (MSCA),0.00,528414.48,1489020.00,207295.2,0.00,0.0,0.0,0.00,1225824.48,0.0,...,0.0,0.00,1918719.68,293709.60,0.0,0.0,0.0,0.0,0.00,1.674676e+07
Widening participation and spreading excellence,0.00,0.00,609500.00,0.0,0.00,0.0,0.0,0.00,460056.25,0.0,...,0.0,0.00,89800.00,122321.25,0.0,0.0,4308057.5,897812.5,122943.75,1.044329e+07
European Research Council (ERC),0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,...,0.0,0.00,2355741.00,150000.00,0.0,0.0,0.0,0.0,0.00,7.882263e+06
Horizon 2020 Framework Programme,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,...,0.0,0.00,1185873.50,0.00,0.0,0.0,0.0,0.0,0.00,1.906961e+06
European innovation ecosystems,0.00,0.00,120325.00,0.0,0.00,0.0,0.0,0.00,0.00,131500.0,...,0.0,0.00,0.00,150531.25,0.0,0.0,0.0,0.0,0.00,1.733575e+06
Total,40435.49,8263040.09,16231832.24,619990.2,1025093.25,424520.0,146250.0,1439499.38,16001314.41,3251449.5,...,1487341.0,1104948.68,44805674.55,19267928.53,501685.0,97562.5,4550057.5,897812.5,6133943.75,3.214241e+08

#### 14b. Reconciliation: `Gov & NP contribution` vs the sum of recipient amounts

One row per grant that has a recipient breakdown, comparing the grant-level
`'Gov & NP contribution'` against the sum of its `recipient_funding_amount` entries, sorted by the
size of the gap.

`'Gov & NP contribution'` is parsed with the same space-thousands-separator rule as the recipient
amounts - at least one row is written `'11 303 944.75'`, which a plain `float()` would reject.

14a is built purely from the recipient amounts, so a gap here does **not** affect it: it flags a
problem in the grant-level column (or a genuine amendment / withdrawn partner).

In [93]:
TOLERANCE_EUR = 1.0  # at or below this, treat as rounding

_recip_sums = (horizon_recipients.groupby('grant_idx')
               .agg(n_recipients=('recipient_country', 'size'),
                    recipient_sum_eur=('recipient_funding_eur', 'sum')))

_grant_cols = ['Title', 'Sub-funder', 'Identification code', 'Year project started',
               'Gov & NP contribution', 'Total amount', 'URL for announcement']
horizon_reconciliation = horizon[_grant_cols].join(_recip_sums, how='inner')
horizon_reconciliation['gov_np_eur'] = horizon_reconciliation['Gov & NP contribution'].map(_parse_amount)
horizon_reconciliation['difference_eur'] = (horizon_reconciliation['recipient_sum_eur']
                                            - horizon_reconciliation['gov_np_eur'])
# Sort by size of gap; a missing Gov & NP sorts first rather than vanishing to the bottom as NaN.
horizon_reconciliation = (horizon_reconciliation
                          .assign(_abs=lambda d: d['difference_eur'].abs())
                          .sort_values('_abs', ascending=False, na_position='first')
                          .drop(columns='_abs'))
horizon_reconciliation.index.name = 'grant_idx'

save(horizon_reconciliation, '14b_horizon_recipient_sum_vs_gov_np')

_missing_gov = horizon_reconciliation['gov_np_eur'].isna()
_mismatch = horizon_reconciliation['difference_eur'].abs() > TOLERANCE_EUR
print(f"{len(horizon_reconciliation)} grants have a recipient breakdown "
      f"({len(horizon) - len(horizon_reconciliation)} have none and cannot be reconciled).")
print(f"{int(_mismatch.sum())} differ by more than EUR {TOLERANCE_EUR:,.0f}; "
      f"{int((~_mismatch & ~_missing_gov).sum())} agree within rounding; "
      f"{int(_missing_gov.sum())} have no 'Gov & NP contribution' to compare against.")

_show = ['Sub-funder', 'Identification code', 'Year project started', 'n_recipients',
         'gov_np_eur', 'recipient_sum_eur', 'difference_eur']
print()
print('Grants that do not reconcile:')
print(horizon_reconciliation.loc[_mismatch | _missing_gov, _show]
      .to_string(float_format=lambda v: f'{v:,.2f}'))

Saved 14b_horizon_recipient_sum_vs_gov_np -> data_output\analysis\14b_horizon_recipient_sum_vs_gov_np.csv
93 grants have a recipient breakdown (74 have none and cannot be reconciled).
0 differ by more than EUR 1; 93 agree within rounding; 0 have no 'Gov & NP contribution' to compare against.

Grants that do not reconcile:
Empty DataFrame
Columns: [Sub-funder, Identification code, Year project started, n_recipients, gov_np_eur, recipient_sum_eur, difference_eur]
Index: []

In [94]:
horizon_recipients

,grant_idx,Title,Sub-funder,recipient_institution,recipient_country,recipient_funding_eur
0,0,Like-A-Pro: From niche to mainstream - alterna...,"Cluster 6: Food, Bioeconomy Natural Resources,...",CENTRO NACIONAL DE TECNOLOGIA Y SEGURIDAD ALIM...,Spain,1341092.05
1,0,Like-A-Pro: From niche to mainstream - alterna...,"Cluster 6: Food, Bioeconomy Natural Resources,...",MOREFORSKING AS,Norway,978201.25
2,0,Like-A-Pro: From niche to mainstream - alterna...,"Cluster 6: Food, Bioeconomy Natural Resources,...",COLLABORATING CENTRE ON SUSTAINABLE CONSUMPTIO...,Germany,809937.50
3,0,Like-A-Pro: From niche to mainstream - alterna...,"Cluster 6: Food, Bioeconomy Natural Resources,...",FBCD AS,Denmark,551775.00
4,0,Like-A-Pro: From niche to mainstream - alterna...,"Cluster 6: Food, Bioeconomy Natural Resources,...",CELABOR SCRL,Belgium,531580.00
...,...,...,...,...,...,...
939,92,APRISE - Alternative Proteins Research and Inn...,Widening participation and spreading excellence,INSTITUT DE RECERCA I TECNOLOGIA AGROALIMENTARIES,Spain,89800.00
940,92,APRISE - Alternative Proteins Research and Inn...,Widening participation and spreading excellence,NUTRI BIOTECH SERVICES LTD,Malta,73243.75
941,92,APRISE - Alternative Proteins Research and Inn...,Widening participation and spreading excellence,SUTAS SUT URUNLERI AS,Turkey,59641.25
942,92,APRISE - Alternative Proteins Research and Inn...,Widening participation and spreading excellence,TURKIYE TEKNOLOJI GELISTIRME VAKFI,Turkey,40468.75
943,93,The Oater develops a compact machine for hyper...,European innovation ecosystems,OIY SOLUTIONS GMBH,Germany,75000.00