## Funding analysis (2020-2025)

Computes the standard breakdowns needed for reporting, exported as CSVs sized to paste directly
into the existing Google Sheets template (`raw_data/Funding analysis 2026.xlsx`, 'Europe wide'
tab) - keeps chart formatting consistent with prior reports while the underlying numbers are
computed in code.

Methodology confirmed against that template rather than assumed:
- Funding figure throughout = `'Gov & NP contribution (EUR)'`.
- Excludes any grant whose `'Award purpose'` is *exactly* `'Equipment and infrastructure'` (not
  combined with anything else).
- "Country" = `'Funder Country'` (whose money it is), not `'PI organisation country'`.
- Multi-value cells (countries, pillars, end products) split the grant's funding evenly across
  the **distinct** values listed.
- Growth rate = simple year-over-year % change.
- Population/GDP from the World Bank, R&D spend from OECD - fetched live (see
  `Funding_analysis_helpers.py`).

In [4]:
import re
from pathlib import Path

import numpy as np
import pandas as pd

from Funding_analysis_helpers import (
    split_multi_value, fetch_worldbank_indicator, fetch_oecd_gerd, fetch_usd_to_eur_rate,
    lookup_country_value, COUNTRY_NAME_TO_OECD, yoy_growth, YEAR_COLS,
)

FINAL_FILE = Path('data_output/260727_0922_ap_pillar_backfill_funding_curated_FINAL.xlsx')
OUTPUT_DIR = Path('data_output/analysis')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FUNDING_COL = 'Gov & NP contribution (EUR)'
YEAR_COL_STRS = [str(y) for y in YEAR_COLS]
ALL_TIME_YEARS = [str(y) for y in range(2020, 2026)]  # 2020-2025, matching the template's "All time" window

# Tied to FINAL_FILE's own run-timestamp prefix, not "now" - change FINAL_FILE above to analyze a
# different run and this follows automatically. Reruns of this notebook overwrite the same CSVs
# instead of piling up a fresh timestamped copy every time.
RUN_TIMESTAMP = re.match(r'(\d{6}_\d{4})', FINAL_FILE.name).group(1)


def save(df_or_series, name, **to_csv_kwargs):
    path = OUTPUT_DIR / f'{RUN_TIMESTAMP}_{name}.csv'
    df_or_series.to_csv(path, **to_csv_kwargs)
    print(f"Saved {name} -> {path}")

### Load and filter

Loads the curated dataset and applies the pipeline-wide filtering rules below - every analysis in
this notebook operates on the filtered `df`, not the raw `FINAL_FILE` export directly. Three filters:

1. Drop grants whose `'Award purpose'` is *only* `'Equipment and infrastructure'`.
2. Drop grants whose `'Funding decision'` is not `'Awarded'` (pledged, not yet decided, unfunded, or blank).
3. Drop grants whose `'Year project started'` is outside 2020-2025 - the reporting window every
   analysis below is labelled with.

In [5]:
df = pd.read_excel(FINAL_FILE)
print(f"Loaded {len(df)} rows from '{FINAL_FILE.name}'.")

# Filter 1: exclude grants whose Award purpose is ONLY 'Equipment and infrastructure' - a grant
# combining it with something else (e.g. 'Research and development; Equipment and infrastructure')
# stays in. Confirmed against the colleagues' own 'Europe wide' template, which applies the same rule.
award_purpose_mask = df['Award purpose'].astype(str).str.strip() == 'Equipment and infrastructure'
df = df[~award_purpose_mask].reset_index(drop=True)
print(f"Excluded {award_purpose_mask.sum()} grants whose Award purpose is ONLY 'Equipment and infrastructure'.")

# Filter 2: keep ONLY grants whose Funding decision is 'Awarded' - money that's been pledged
# ('Committed'), not yet decided ('No decision yet'), turned down ('Unfunded'), or simply unknown
# (blank) shouldn't count in a funding-received analysis. Switched from excluding just 'Committed'
# to this whitelist since several blank/'Unfunded'/'No decision yet' grants turned out to carry
# real funding amounts too (~€15M combined) - not just Committed. This also still removes the
# €162.5M Danish government commitment the colleagues' template excludes from every total
# (confirmed its own Funding decision is 'Committed').
awarded_mask = df['Funding decision'].astype(str).str.strip() == 'Awarded'
df = df[awarded_mask].reset_index(drop=True)
print(f"Excluded {(~awarded_mask).sum()} grants whose Funding decision is not 'Awarded' "
      f"(Committed/Unfunded/No decision yet/blank).")

# Filter 3: restrict to the 2020-2025 reporting window. Applied here, once, rather than at each
# aggregation - previously only SOME cells filtered on year, so grants outside the window leaked
# into totals whose titles said "2020-2025" (1c, 3a, 3b, 4, 4b, 7 and 9). Doing it globally is
# what keeps every analysis in this notebook comparable to every other.
# Two consequences worth knowing:
#  - 1b (funding by FUNDING year) still spreads over 2020-2035, but now only for grants that
#    STARTED in the window. That's the intended reading: "grants started 2020-2025, paid out over time".
#  - Analysis 5's 'Total' column is now window-scoped too (see the note in that cell).
# .between() also drops blank years; there are currently none, so the count below is the whole story.
year_mask = df['Year project started'].between(2020, 2025)
df = df[year_mask].reset_index(drop=True)
print(f"Excluded {(~year_mask).sum()} grants whose start year falls outside 2020-2025.")

print(f"{len(df)} grants remain for analysis.")

Loaded 2481 rows from '260727_0922_ap_pillar_backfill_funding_curated_FINAL.xlsx'.
Excluded 27 grants whose Award purpose is ONLY 'Equipment and infrastructure'.
Excluded 30 grants whose Funding decision is not 'Awarded' (Committed/Unfunded/No decision yet/blank).
Excluded 2 grants whose start year falls outside 2020-2025.
2422 grants remain for analysis.

In [9]:
# Excluding grants from non-profit/NGO funders.
# NOTE: distinct variable names (*_np) on purpose
NON_PROFIT_FUNDER_TYPES = {'nonprofit', 'ngo'}  # matched after lowercasing and stripping -/spaces

funder_type_norm = (df['Funder type'].astype(str)
                    .str.strip().str.lower()
                    .str.replace(r'[-\s]', '', regex=True))
non_profit_mask = funder_type_norm.isin(NON_PROFIT_FUNDER_TYPES)

df_np = df[~non_profit_mask].reset_index(drop=True)
print(f"Excluded {non_profit_mask.sum()} grants with a non-profit/NGO Funder type "
      f"(EUR {df.loc[non_profit_mask, FUNDING_COL].sum():,.0f}). {len(df_np)} grants remain.")

Excluded 213 grants with a non-profit/NGO Funder type (EUR 248,673,492). 2209 grants remain.

### 1. Total funding by start year, and by funding year

In [39]:
by_start_year = df[df['Year project started'].between(2020, 2025)].groupby('Year project started')[FUNDING_COL].sum()
by_start_year.index = by_start_year.index.astype(int)
by_start_year.name = 'Total funding (EUR)'
save(by_start_year, '1a_funding_by_start_year')
print(by_start_year)

by_funding_year = df[YEAR_COL_STRS].sum()
by_funding_year.name = 'Total funding (EUR)'
save(by_funding_year, '1b_funding_by_funding_year')
print()
print(by_funding_year)

Saved 1a_funding_by_start_year -> data_output\analysis\260727_0922_1a_funding_by_start_year.csv
Year project started
2020    1.374401e+08
2021    2.320233e+08
2022    2.817690e+08
2023    4.247723e+08
2024    4.892599e+08
2025    3.178548e+08
Name: Total funding (EUR), dtype: float64
Saved 1b_funding_by_funding_year -> data_output\analysis\260727_0922_1b_funding_by_funding_year.csv

2020    5.051815e+07
2021    1.011812e+08
2022    1.501645e+08
2023    2.362088e+08
2024    3.544032e+08
2025    3.319381e+08
2026    2.328084e+08
2027    1.684541e+08
2028    9.821652e+07
2029    7.119121e+07
2030    1.829727e+07
2031    1.217275e+07
2032    5.454545e+06
2033    5.454545e+06
2034    0.000000e+00
2035    0.000000e+00
Name: Total funding (EUR), dtype: float64

### 1c. Total funding by region (2020-2025), plus an EU / EU+ / Europe comparison

The second table isn't a partition like the first - EU and EU+ are subsets of Europe, so their
totals are nested (EU <= EU+ <= Europe), not additive alongside the other regions.

In [12]:
from Funding_analysis_helpers import europe_tier_split

# Uses the Totals column directly (not the 2020-2035 per-year split) - many grants lack enough
# public info to know their duration, which would otherwise silently drop them from a "total".
region_split = split_multi_value(df, 'Funder region', delimiter=',')
region_split['weighted_funding'] = region_split[FUNDING_COL] * region_split['_weight']
by_region = region_split.groupby('Funder region_split')['weighted_funding'].sum().sort_values(ascending=False)
by_region.name = 'Total funding (2020-2025, EUR)'
save(by_region, '1c_funding_by_region')
print(by_region)

tier_split = europe_tier_split(df)
tier_split['weighted_funding'] = tier_split[FUNDING_COL] * tier_split['_weight']
by_tier = tier_split.groupby('_tiers')['weighted_funding'].sum().reindex(['EU', 'EU+', 'Europe'])
by_tier.name = 'Total funding (2020-2025, EUR)'
save(by_tier, '1c_funding_by_eu_tier')
print()
print(by_tier)

Saved 1c_funding_by_region -> data_output\analysis\260727_0922_1c_funding_by_region.csv
Funder region_split
Europe               1.297971e+09
North America        3.806738e+08
Asia/Asia Pacific    1.706996e+08
Middle East          2.745611e+07
Global               3.338193e+06
South America        2.421083e+06
Africa               5.599000e+05
Name: Total funding (2020-2025, EUR), dtype: float64
Saved 1c_funding_by_eu_tier -> data_output\analysis\260727_0922_1c_funding_by_eu_tier.csv

_tiers
EU        1.055625e+09
EU+       1.297821e+09
Europe    1.297971e+09
Name: Total funding (2020-2025, EUR), dtype: float64

### 2. Total funding by year x AP pillar, plus growth rates

In [13]:
# By START year (2020-2025), not the calculated per-year split stretching out to 2035 - each
# grant's full funding figure counts entirely toward the year it started, matching analysis 1a's
# methodology exactly but split by AP pillar.
by_start_year_pillar = df[df['Year project started'].between(2020, 2025)].pivot_table(
    index='AP pillar', columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
by_start_year_pillar.columns = by_start_year_pillar.columns.astype(int)
by_start_year_pillar = by_start_year_pillar[sorted(by_start_year_pillar.columns)]
by_start_year_pillar.loc['Total'] = by_start_year_pillar.sum()
save(by_start_year_pillar, '2a_funding_by_year_and_pillar')
print(by_start_year_pillar)

# YoY growth rate (matches the template's own formula: (year_N - year_N-1) / year_N-1)
growth_rates = by_start_year_pillar.apply(yoy_growth, axis=1)
growth_rates['Average growth rate (2021-2025)'] = growth_rates.iloc[:, 1:].mean(axis=1)
save(growth_rates, '2b_growth_rates_by_pillar')
print()
print(growth_rates)

Saved 2a_funding_by_year_and_pillar -> data_output\analysis\260727_0922_2a_funding_by_year_and_pillar.csv
Year project started          2020          2021          2022          2023  \
AP pillar
Cross-cutting         1.082863e+07  3.758664e+07  3.817269e+07  9.770968e+07
Cultivated            1.887046e+07  4.785970e+07  4.831153e+07  5.762773e+07
Fermentation          2.175219e+07  4.266925e+07  4.716501e+07  1.166636e+08
Plant-based           8.598882e+07  1.039077e+08  1.481198e+08  1.527712e+08
Total                 1.374401e+08  2.320233e+08  2.817690e+08  4.247723e+08

Year project started          2024          2025
AP pillar
Cross-cutting         1.456454e+08  2.754990e+07
Cultivated            5.125342e+07  2.767294e+07
Fermentation          1.652358e+08  1.499915e+08
Plant-based           1.271253e+08  1.126404e+08
Total                 4.892599e+08  3.178548e+08
Saved 2b_growth_rates_by_pillar -> data_output\analysis\260727_0922_2b_growth_rates_by_pillar.csv

Year project started  2020      2021      2022      2023      2024      2025  \
AP pillar
Cross-cutting          NaN  2.471044  0.015592  1.559675  0.490593 -0.810843
Cultivated             NaN  1.536224  0.009441  0.192836 -0.110612 -0.460076
Fermentation           NaN  0.961607  0.105363  1.473521  0.416344 -0.092258
Plant-based            NaN  0.208386  0.425494  0.031403 -0.167872 -0.113942
Total                  NaN  0.688177  0.214400  0.507519  0.151817 -0.350336

Year project started  Average growth rate (2021-2025)
AP pillar
Cross-cutting                                0.745212
Cultivated                                   0.233563
Fermentation                                 0.572915
Plant-based                                  0.076694
Total                                        0.242316

### 2c/2d. Funding by year x region, and by EU / EU+ / Europe, with growth rates

In [40]:
# By START year (2020-2025), not the funding-year spread - matches 1a/2a's methodology,
# split by region. 1b is the one deliberate exception that stays funding-year-based.
by_year_region = region_split[region_split['Year project started'].between(2020, 2025)].pivot_table(
    index='Funder region_split', columns='Year project started', values='weighted_funding', aggfunc='sum', fill_value=0
)
by_year_region.columns = by_year_region.columns.astype(int)
by_year_region = by_year_region[sorted(by_year_region.columns)]
by_year_region.loc['Total'] = by_year_region.sum()
save(by_year_region, '2c_funding_by_year_and_region')
print(by_year_region)

growth_region = by_year_region.apply(yoy_growth, axis=1)
growth_region['Average growth rate (2021-2025)'] = growth_region.iloc[:, 1:].mean(axis=1)
save(growth_region, '2d_growth_rates_by_region')
print()
print(growth_region)

Saved 2c_funding_by_year_and_region -> data_output\analysis\260727_0922_2c_funding_by_year_and_region.csv
Year project started          2020          2021          2022          2023  \
Funder region_split
Africa                0.000000e+00  0.000000e+00  0.000000e+00  5.599000e+05
Asia/Asia Pacific     1.244748e+07  5.770508e+07  1.684614e+07  2.121120e+07
Europe                9.076646e+07  1.214811e+08  2.087149e+08  3.302847e+08
Global                1.309406e+06  6.024936e+05  8.956450e+05  5.306482e+05
Middle East           0.000000e+00  8.149300e+06  1.666206e+07  2.271742e+06
North America         3.291247e+07  4.407532e+07  3.861254e+07  6.821704e+07
South America         4.269000e+03  9.929000e+03  3.773600e+04  1.696999e+06
Total                 1.374401e+08  2.320233e+08  2.817690e+08  4.247723e+08

Year project started          2024          2025
Funder region_split
Africa                0.000000e+00  0.000000e+00
Asia/Asia Pacific     2.372379e+07  3.876595e+07
Europe                3.021287e+08  2.445947e+08
Global                0.000000e+00  0.000000e+00
Middle East           0.000000e+00  3.730060e+05
North America         1.633679e+08  3.348845e+07
South America         3.945800e+04  6.326920e+05
Total                 4.892599e+08  3.178548e+08
Saved 2d_growth_rates_by_region -> data_output\analysis\260727_0922_2d_growth_rates_by_region.csv

Year project started  2020      2021      2022       2023      2024  \
Funder region_split
Africa                 NaN       NaN       NaN        inf -1.000000
Asia/Asia Pacific      NaN  3.635883 -0.708065   0.259113  0.118456
Europe                 NaN  0.338392  0.718085   0.582468 -0.085248
Global                 NaN -0.539873  0.486564  -0.407524 -1.000000
Middle East            NaN       inf  1.044600  -0.863658 -1.000000
North America          NaN  0.339168 -0.123942   0.766707  1.394826
South America          NaN  1.325837  2.800584  43.970283 -0.976748
Total                  NaN  0.688177  0.214400   0.507519  0.151817

Year project started       2025  Average growth rate (2021-2025)
Funder region_split
Africa                      NaN                              inf
Asia/Asia Pacific      0.634054                         0.787888
Europe                -0.190429                         0.272654
Global                      NaN                        -0.365208
Middle East                 inf                              inf
North America         -0.795012                         0.316349
South America         15.034568                        12.430905
Total                 -0.350336                         0.242316

In [41]:
by_year_tier = tier_split[tier_split['Year project started'].between(2020, 2025)].pivot_table(
    index='_tiers', columns='Year project started', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
by_year_tier.columns = by_year_tier.columns.astype(int)
by_year_tier = by_year_tier[sorted(by_year_tier.columns)]
save(by_year_tier, '2c_funding_by_year_and_eu_tier')
print(by_year_tier)

growth_tier = by_year_tier.apply(yoy_growth, axis=1)
growth_tier['Average growth rate (2021-2025)'] = growth_tier.iloc[:, 1:].mean(axis=1)
save(growth_tier, '2d_growth_rates_by_eu_tier')
print()
print(growth_tier)

Saved 2c_funding_by_year_and_eu_tier -> data_output\analysis\260727_0922_2c_funding_by_year_and_eu_tier.csv
Year project started          2020          2021          2022          2023  \
_tiers
EU                    7.544736e+07  7.512691e+07  1.842527e+08  2.721124e+08
EU+                   9.076646e+07  1.214811e+08  2.087149e+08  3.301348e+08
Europe                9.076646e+07  1.214811e+08  2.087149e+08  3.302847e+08

Year project started          2024          2025
_tiers
EU                    2.249562e+08  2.237289e+08
EU+                   3.021287e+08  2.445947e+08
Europe                3.021287e+08  2.445947e+08
Saved 2d_growth_rates_by_eu_tier -> data_output\analysis\260727_0922_2d_growth_rates_by_eu_tier.csv

Year project started  2020      2021      2022      2023      2024      2025  \
_tiers
EU                     NaN -0.004247  1.452553  0.476843 -0.173297 -0.005456
EU+                    NaN  0.338392  0.718085  0.581750 -0.084832 -0.190429
Europe                 NaN  0.338392  0.718085  0.582468 -0.085248 -0.190429

Year project started  Average growth rate (2021-2025)
_tiers
EU                                           0.349279
EU+                                          0.272593
Europe                                       0.272654

### 3a. Total funding by country (2020-2025), with per-capita/GDP/R&D-spend

Fetches World Bank population/GDP and OECD R&D spend live, plus a live USD->EUR rate (Frankfurter)
to convert them - reused by analyses 4 and 8 below, so this cell's variables stay in scope.

In [7]:
# No year filter needed here - `df` is already restricted to 2020-2025 by Filter 3 in the load
# cell. `country_split` is reused by analyses 4, 6 and 9 below, so it inherits that window too.
country_split = split_multi_value(df, 'Funder Country', delimiter=',')
country_split['weighted_funding'] = country_split[FUNDING_COL] * country_split['_weight']

by_country = country_split.groupby('Funder Country_split')['weighted_funding'].sum().sort_values(ascending=False)
by_country.name = 'Total funding (2020-2025, EUR)'

print("Fetching World Bank population/GDP, OECD R&D spend, and a USD->EUR rate...")
POP_GDP_YEAR = 2023  # most recent year with broad World Bank/OECD coverage
pop = fetch_worldbank_indicator('SP.POP.TOTL', POP_GDP_YEAR)
gdp_usd = fetch_worldbank_indicator('NY.GDP.MKTP.CD', POP_GDP_YEAR)
gerd_usd = fetch_oecd_gerd(POP_GDP_YEAR)
usd_to_eur = fetch_usd_to_eur_rate(f'{POP_GDP_YEAR}-12-29')
print(f"USD->EUR rate ({POP_GDP_YEAR}-12-29): {usd_to_eur}")

by_country_df = by_country.reset_index().rename(columns={'Funder Country_split': 'Country'})
by_country_df['Population'] = by_country_df['Country'].apply(lambda c: lookup_country_value(c, pop))
by_country_df['GDP (EUR)'] = by_country_df['Country'].apply(lambda c: lookup_country_value(c, gdp_usd)) * usd_to_eur
by_country_df['R&D spend (EUR)'] = by_country_df['Country'].apply(
    lambda c: lookup_country_value(c, gerd_usd, COUNTRY_NAME_TO_OECD)
) * usd_to_eur
by_country_df['Funding per capita'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['Population']
by_country_df['Funding per GDP'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['GDP (EUR)']
by_country_df['GDP per capita'] = by_country_df['GDP (EUR)'] / by_country_df['Population']
by_country_df['Funding per R&D spend'] = by_country_df['Total funding (2020-2025, EUR)'] / by_country_df['R&D spend (EUR)']

n_no_population = by_country_df['Population'].isna().sum()
print(f"{n_no_population} entries have no population match (expected for non-country entities like 'EU'/'Global').")

save(by_country_df, '3a_funding_by_country', index=False)
print(by_country_df.head(15).to_string())

Fetching World Bank population/GDP, OECD R&D spend, and a USD->EUR rate...

c:\Users\Viola Hollek\Documents\SHEEP_Pipeline\Funding\Funding_analysis_helpers.py:146: DtypeWarning: Columns (0: OBS_STATUS, 1: Observation status, 2: OBS_STATUS_2, 3: Observation status 2, 4: OBS_STATUS_3, 5: Observation status 3, 6: AUX_OBS_STATUS, 7: Aux observation status, 8: CONF_STATUS, 9: Confidentiality status) have mixed types. Specify dtype option on import or set low_memory=False.
  raw = pd.read_csv(io.StringIO(text))

USD->EUR rate (2023-12-29): 0.90498
2 entries have no population match (expected for non-country entities like 'EU'/'Global').
Saved 3a_funding_by_country -> data_output\analysis\260727_0922_3a_funding_by_country.csv
           Country  Total funding (2020-2025, EUR)   Population     GDP (EUR)  R&D spend (EUR)  Funding per capita  Funding per GDP  GDP per capita  Funding per R&D spend
0               EU                    4.527810e+08          NaN           NaN              NaN                 NaN              NaN             NaN                    NaN
1    United States                    3.178609e+08  336755052.0  2.516887e+13     8.616450e+11            0.943894         0.000013    74739.388482               0.000369
2          Denmark                    1.661546e+08    5946952.0  3.662017e+11     1.277912e+10           27.939458         0.000454    61578.048890               0.013002
3   United Kingdom                    1.545517e+08   68526000.0  3.095753e+12     1.037927e+11            2.255374         0.000050    45176.320750               0.001489
4      Netherlands                    9.488457e+07   17877117.0  1.027583e+12     2.997770e+10            5.307599         0.000092    57480.350474               0.003165
5          Germany                    8.500092e+07   83287273.0  4.128707e+12     1.704072e+11            1.020575         0.000021    49571.878440               0.000499
6        Singapore                    8.313929e+07    5917648.0  4.626093e+11     1.559697e+10           14.049381         0.000180    78174.516343               0.005330
7          Finland                    7.776410e+07    5583911.0  2.671426e+11     9.914299e+09           13.926457         0.000291    47841.490014               0.007844
8           Canada                    6.281281e+07   40049088.0  1.987873e+12     4.557030e+10            1.568396         0.000032    49635.924044               0.001378
9           Norway                    5.935346e+07    5519601.0  4.544788e+11     9.584503e+09           10.753216         0.000131    82339.070198               0.006193
10          Sweden                    5.263569e+07   10536632.0  5.239752e+11     2.376228e+10            4.995495         0.000100    49728.907537               0.002215
11           Spain                    3.522711e+07   48352528.0  1.465599e+12     3.639257e+10            0.728547         0.000024    30310.696535               0.000968
12          France                    3.237181e+07   68372286.0  2.765846e+12     8.200142e+10            0.473464         0.000012    40452.731265               0.000395
13     South Korea                    3.109875e+07   51712619.0  1.669508e+12     1.328646e+11            0.601376         0.000019    32284.343394               0.000234
14     Switzerland                    2.829096e+07    8888822.0  8.402154e+11     2.345421e+10            3.182757         0.000034    94524.938843               0.001206

### 3b. Total funding by country (2020-2025) excl. non-profit funding, with per-capita/GDP/R&D-spend

Same breakdown as 3a with grants from non-profit/NGO funders removed, i.e. `'Funder type'` not in
`'Non-profit'` / `'Nonprofit'` / `'NGO'`. Compared case/hyphen/whitespace-insensitively because the
curated data carries both `'Non-profit'` and `'Nonprofit'` as separate labels for the same thing.

`'Non-profit/Gov'` (4 grants) is deliberately **kept** - mixed public/non-profit funders count as
partly governmental. `'For profit'`, `'Research Institute'`, `'Joint public/private partnership'`,
`'Unknown'` and blank Funder types are also kept; this filter only removes purely non-profit/NGO money.

In [ ]:
# Same breakdown as 3a, but excluding grants from non-profit/NGO funders using the dataframe df_np

country_split_np = split_multi_value(df_np, 'Funder Country', delimiter=',')
country_split_np['weighted_funding'] = country_split_np[FUNDING_COL] * country_split_np['_weight']

by_country_np = (country_split_np.groupby('Funder Country_split')['weighted_funding']
                 .sum().sort_values(ascending=False))
# Same column header as 3a so this CSV pastes into the same template columns.
by_country_np.name = 'Total funding (2020-2025, EUR)'

# pop / gdp_usd / gerd_usd / usd_to_eur were fetched in 3a and are still in scope - deliberately
# not refetched here (4 extra network round-trips that can fail). Run 3a before 3b.
by_country_np_df = by_country_np.reset_index().rename(columns={'Funder Country_split': 'Country'})
by_country_np_df['Population'] = by_country_np_df['Country'].apply(lambda c: lookup_country_value(c, pop))
by_country_np_df['GDP (EUR)'] = by_country_np_df['Country'].apply(lambda c: lookup_country_value(c, gdp_usd)) * usd_to_eur
by_country_np_df['R&D spend (EUR)'] = by_country_np_df['Country'].apply(
    lambda c: lookup_country_value(c, gerd_usd, COUNTRY_NAME_TO_OECD)
) * usd_to_eur
by_country_np_df['Funding per capita'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['Population']
by_country_np_df['Funding per GDP'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['GDP (EUR)']
by_country_np_df['GDP per capita'] = by_country_np_df['GDP (EUR)'] / by_country_np_df['Population']
by_country_np_df['Funding per R&D spend'] = by_country_np_df['Total funding (2020-2025, EUR)'] / by_country_np_df['R&D spend (EUR)']

n_no_population = by_country_np_df['Population'].isna().sum()
print(f"{n_no_population} entries have no population match (expected for non-country entities like 'EU'/'Global').")

save(by_country_np_df, '3b_funding_by_country_excl_nonprofit', index=False)
print(by_country_np_df.head(15).to_string())

Excluded 213 grants with a non-profit/NGO Funder type (EUR 248,673,492). 2209 grants remain.
1 entries have no population match (expected for non-country entities like 'EU'/'Global').
Saved 3b_funding_by_country_excl_nonprofit -> data_output\analysis\260727_0922_3b_funding_by_country_excl_nonprofit.csv
           Country  Total funding (2020-2025, EUR)   Population     GDP (EUR)  R&D spend (EUR)  Funding per capita  Funding per GDP  GDP per capita  Funding per R&D spend
0               EU                    4.527810e+08          NaN           NaN              NaN                 NaN              NaN             NaN                    NaN
1    United States                    1.995413e+08  336755052.0  2.516887e+13     8.616450e+11            0.592541         0.000008    74739.388482               0.000232
2   United Kingdom                    1.530156e+08   68526000.0  3.095753e+12     1.037927e+11            2.232957         0.000049    45176.320750               0.001474
3      Netherlands                    9.488457e+07   17877117.0  1.027583e+12     2.997770e+10            5.307599         0.000092    57480.350474               0.003165
4          Germany                    8.500092e+07   83287273.0  4.128707e+12     1.704072e+11            1.020575         0.000021    49571.878440               0.000499
5        Singapore                    8.313929e+07    5917648.0  4.626093e+11     1.559697e+10           14.049381         0.000180    78174.516343               0.005330
6          Finland                    7.770410e+07    5583911.0  2.671426e+11     9.914299e+09           13.915712         0.000291    47841.490014               0.007838
7           Norway                    5.935346e+07    5519601.0  4.544788e+11     9.584503e+09           10.753216         0.000131    82339.070198               0.006193
8           Canada                    5.934552e+07   40049088.0  1.987873e+12     4.557030e+10            1.481819         0.000030    49635.924044               0.001302
9           Sweden                    5.263569e+07   10536632.0  5.239752e+11     2.376228e+10            4.995495         0.000100    49728.907537               0.002215
10         Denmark                    4.545377e+07    5946952.0  3.662017e+11     1.277912e+10            7.643204         0.000124    61578.048890               0.003557
11           Spain                    3.522711e+07   48352528.0  1.465599e+12     3.639257e+10            0.728547         0.000024    30310.696535               0.000968
12          France                    3.237181e+07   68372286.0  2.765846e+12     8.200142e+10            0.473464         0.000012    40452.731265               0.000395
13     South Korea                    3.109875e+07   51712619.0  1.669508e+12     1.328646e+11            0.601376         0.000019    32284.343394               0.000234
14     New Zealand                    2.800436e+07    5200000.0  2.320117e+11     3.985797e+09            5.385454         0.000121    44617.633351               0.007026

### 4. Total funding by country x AP pillar (2020-2025)

In [18]:
country_pillar = country_split.pivot_table(
    index='Funder Country_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
country_pillar['Total'] = country_pillar.sum(axis=1)
country_pillar = country_pillar.sort_values('Total', ascending=False)
save(country_pillar, '4_funding_by_country_and_pillar')
print(country_pillar)

Saved 4_funding_by_country_and_pillar -> data_output\analysis\260727_0922_4_funding_by_country_and_pillar.csv
AP pillar             Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder Country_split
EU                     3.877506e+07  3.108022e+07  1.853421e+08  1.975836e+08
United States          9.470778e+07  4.123339e+07  1.341277e+08  4.779206e+07
Denmark                6.085037e+06  2.890231e+06  6.449083e+07  9.268851e+07
United Kingdom         4.169018e+07  2.754722e+07  4.095560e+07  4.435874e+07
Netherlands            6.164645e+07  1.452487e+07  2.305151e+06  1.640810e+07
Germany                4.181583e+06  9.593932e+06  7.620307e+06  6.360510e+07
Singapore              1.285894e+07  1.798270e+07  3.960247e+07  1.269518e+07
Finland                3.864689e+07  4.899000e+05  2.682890e+07  1.179841e+07
Canada                 3.339732e+05  9.206964e+06  1.379242e+06  5.189263e+07
Norway                 1.689705e+07  1.606977e+06  1.082230e+07  3.002714e+07
Sweden                 1.064234e+06  2.549047e+05  5.963613e+06  4.535294e+07
Spain                  8.428214e+06  1.020059e+07  3.845675e+06  1.275263e+07
France                 0.000000e+00  0.000000e+00  3.000000e+06  2.937181e+07
South Korea            0.000000e+00  3.109875e+07  0.000000e+00  0.000000e+00
Switzerland            2.663368e+06  4.187049e+06  2.938837e+06  1.850170e+07
New Zealand            6.712255e+06  5.954930e+06  5.152576e+06  1.018460e+07
Israel                 9.491092e+06  1.750923e+07  4.557900e+05  0.000000e+00
Japan                  1.068329e+06  1.298129e+07  4.502100e+04  3.281080e+06
Belgium                0.000000e+00  3.600000e+06  0.000000e+00  1.224524e+07
Poland                 1.017403e+05  4.189125e+06  2.040675e+05  1.013188e+07
Portugal               3.859768e+06  1.008026e+06  3.497930e+05  2.297318e+06
Australia              3.580585e+06  3.159440e+05  6.817100e+05  2.768026e+06
Ireland                7.725970e+05  0.000000e+00  0.000000e+00  5.173310e+06
Austria                8.979060e+05  0.000000e+00  3.200000e+06  1.112695e+06
Estonia                2.430000e+04  0.000000e+00  2.602796e+06  2.004573e+06
Czechia                0.000000e+00  5.873048e+05  0.000000e+00  3.731505e+06
China                  2.559000e+06  8.008800e+04  4.004400e+04  1.056127e+06
Global                 0.000000e+00  1.880443e+06  6.630000e+05  7.947500e+05
Brazil                 4.465736e+05  1.441711e+06  0.000000e+00  0.000000e+00
South Africa           0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00
Slovakia               0.000000e+00  0.000000e+00  3.000000e+05  2.371710e+05
Uruguay                0.000000e+00  0.000000e+00  0.000000e+00  5.327980e+05
Serbia                 0.000000e+00  1.499950e+05  0.000000e+00  0.000000e+00
Croatia                0.000000e+00  0.000000e+00  0.000000e+00  1.312388e+05
Latvia                 0.000000e+00  0.000000e+00  0.000000e+00  4.235000e+04
Chile                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Iceland                0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Malaysia               0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Italy                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Russia                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Turkey                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00

AP pillar                    Total
Funder Country_split
EU                    4.527810e+08
United States         3.178609e+08
Denmark               1.661546e+08
United Kingdom        1.545517e+08
Netherlands           9.488457e+07
Germany               8.500092e+07
Singapore             8.313929e+07
Finland               7.776410e+07
Canada                6.281281e+07
Norway                5.935346e+07
Sweden                5.263569e+07
Spain                 3.522711e+07
France                3.237181e+07
South Korea           3.109875e+07
Switzerland           2.829096e+07
New Zealand           2.800436e+07
Israel                2.745611e+07
Japan                 1.737572e+07
Belgium               1.584524e+07
Poland                1.462682e+07
Portugal              7.514905e+06
Australia             7.346265e+06
Ireland               5.945907e+06
Austria               5.210601e+06
Estonia               4.631669e+06
Czechia               4.318810e+06
China                 3.735259e+06
Global                3.338193e+06
Brazil                1.888285e+06
South Africa          5.599000e+05
Slovakia              5.371710e+05
Uruguay               5.327980e+05
Serbia                1.499950e+05
Croatia               1.312388e+05
Latvia                4.235000e+04
Chile                 0.000000e+00
Iceland               0.000000e+00
Malaysia              0.000000e+00
Italy                 0.000000e+00
Russia                0.000000e+00
Turkey                0.000000e+00

### 4a. Total funding by country x AP pillar excl. non-profit funding

Same breakdown as 4, restricted to the same non-profit/NGO-excluded set as 3b (see 3b's note for
exactly which `'Funder type'` values are dropped and which are kept). Reuses 3b's
`country_split_np`, so **3b must have been run first**.

In [28]:
# Same pivot as 4, but off 3b's non-profit-excluded split rather than re-deriving the filter -
# guarantees 4a and 3b always agree on which grants are in scope. `country_split_np` already
# carries the weighted_funding column, so this is a pure re-pivot.
# NOTE: *_np naming again on purpose - analyses 6 and 9 below read 3a's `country_split`.
country_pillar_np = country_split_np.pivot_table(
    index='Funder Country_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
country_pillar_np['Total'] = country_pillar_np.sum(axis=1)
country_pillar_np = country_pillar_np.sort_values('Total', ascending=False)

# Reindex onto 4's country list so 4a has the SAME rows in the same order-ish as 4, making the two
# CSVs directly comparable side by side in the template. A country whose funding was entirely
# non-profit drops out of country_split_np and would otherwise vanish from this table; showing it
# as an explicit 0 row says "assessed, nothing left" rather than silently omitting it.
# In the current data that applies to 'Global' only. ('Chile', 'Iceland', 'Malaysia', 'Italy',
# 'Russia' and 'Turkey' also read 0 here, but they are already 0 in 4 - grants with no funding
# amount recorded, not an artefact of this filter.)
country_pillar_np = country_pillar_np.reindex(
    country_pillar.index.union(country_pillar_np.index, sort=False), fill_value=0
).fillna(0).sort_values('Total', ascending=False)

save(country_pillar_np, '4a_funding_by_country_and_pillar_excl_nonprofit')
print(country_pillar_np)

Saved 4a_funding_by_country_and_pillar_excl_nonprofit -> data_output\analysis\260727_0922_4a_funding_by_country_and_pillar_excl_nonprofit.csv
AP pillar             Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder Country_split
EU                     3.877506e+07  3.108022e+07  1.853421e+08  1.975836e+08
United States          1.375888e+07  3.313243e+07  1.170682e+08  3.558181e+07
United Kingdom         4.169018e+07  2.754722e+07  4.065543e+07  4.312279e+07
Netherlands            6.164645e+07  1.452487e+07  2.305151e+06  1.640810e+07
Germany                4.181583e+06  9.593932e+06  7.620307e+06  6.360510e+07
Singapore              1.285894e+07  1.798270e+07  3.960247e+07  1.269518e+07
Finland                3.858689e+07  4.899000e+05  2.682890e+07  1.179841e+07
Norway                 1.689705e+07  1.606977e+06  1.082230e+07  3.002714e+07
Canada                 3.339732e+05  8.602979e+06  1.379242e+06  4.902932e+07
Sweden                 1.064234e+06  2.549047e+05  5.963613e+06  4.535294e+07
Denmark                2.842624e+06  5.991436e+05  7.810452e+06  3.420155e+07
Spain                  8.428214e+06  1.020059e+07  3.845675e+06  1.275263e+07
France                 0.000000e+00  0.000000e+00  3.000000e+06  2.937181e+07
South Korea            0.000000e+00  3.109875e+07  0.000000e+00  0.000000e+00
New Zealand            6.712255e+06  5.954930e+06  5.152576e+06  1.018460e+07
Switzerland            2.663368e+06  4.187049e+06  2.938837e+06  1.767838e+07
Israel                 9.491092e+06  1.713622e+07  4.557900e+05  0.000000e+00
Japan                  1.068329e+06  1.295055e+07  4.502100e+04  3.281080e+06
Belgium                0.000000e+00  3.600000e+06  0.000000e+00  1.224524e+07
Poland                 1.017403e+05  4.189125e+06  2.040675e+05  1.013188e+07
Portugal               3.859768e+06  1.008026e+06  3.497930e+05  2.297318e+06
Australia              3.580585e+06  3.159440e+05  6.817100e+05  2.768026e+06
Ireland                7.725970e+05  0.000000e+00  0.000000e+00  5.173310e+06
Austria                8.979060e+05  0.000000e+00  3.200000e+06  1.112695e+06
Estonia                0.000000e+00  0.000000e+00  2.602796e+06  2.004573e+06
Czechia                0.000000e+00  5.873048e+05  0.000000e+00  3.731505e+06
China                  2.559000e+06  8.008800e+04  4.004400e+04  1.056127e+06
Brazil                 4.465736e+05  1.441711e+06  0.000000e+00  0.000000e+00
South Africa           0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00
Slovakia               0.000000e+00  0.000000e+00  3.000000e+05  2.371710e+05
Uruguay                0.000000e+00  0.000000e+00  0.000000e+00  5.327980e+05
Serbia                 0.000000e+00  1.499950e+05  0.000000e+00  0.000000e+00
Croatia                0.000000e+00  0.000000e+00  0.000000e+00  1.312388e+05
Latvia                 0.000000e+00  0.000000e+00  0.000000e+00  4.235000e+04
Global                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Chile                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Iceland                0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Malaysia               0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Italy                  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Russia                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Turkey                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00

AP pillar                    Total
Funder Country_split
EU                    4.527810e+08
United States         1.995413e+08
United Kingdom        1.530156e+08
Netherlands           9.488457e+07
Germany               8.500092e+07
Singapore             8.313929e+07
Finland               7.770410e+07
Norway                5.935346e+07
Canada                5.934552e+07
Sweden                5.263569e+07
Denmark               4.545377e+07
Spain                 3.522711e+07
France                3.237181e+07
South Korea           3.109875e+07
New Zealand           2.800436e+07
Switzerland           2.746764e+07
Israel                2.708310e+07
Japan                 1.734498e+07
Belgium               1.584524e+07
Poland                1.462682e+07
Portugal              7.514905e+06
Australia             7.346265e+06
Ireland               5.945907e+06
Austria               5.210601e+06
Estonia               4.607369e+06
Czechia               4.318810e+06
China                 3.735259e+06
Brazil                1.888285e+06
South Africa          5.599000e+05
Slovakia              5.371710e+05
Uruguay               5.327980e+05
Serbia                1.499950e+05
Croatia               1.312388e+05
Latvia                4.235000e+04
Global                0.000000e+00
Chile                 0.000000e+00
Iceland               0.000000e+00
Malaysia              0.000000e+00
Italy                 0.000000e+00
Russia                0.000000e+00
Turkey                0.000000e+00

### 4b. Total funding by region x AP pillar (2020-2025), and by EU / EU+ / Europe x AP pillar

In [19]:
region_pillar = region_split.pivot_table(
    index='Funder region_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
region_pillar['Total'] = region_pillar.sum(axis=1)
region_pillar = region_pillar.sort_values('Total', ascending=False)
save(region_pillar, '4b_funding_by_region_and_pillar')
print(region_pillar)

tier_pillar = tier_split.pivot_table(
    index='_tiers', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
tier_pillar['Total'] = tier_pillar.sum(axis=1)
save(tier_pillar, '4b_funding_by_eu_tier_and_pillar')
print()
print(tier_pillar)

Saved 4b_funding_by_region_and_pillar -> data_output\analysis\260727_0922_4b_funding_by_region_and_pillar.csv
AP pillar            Cross-cutting    Cultivated  Fermentation   Plant-based  \
Funder region_split
Europe                2.257344e+08  1.119103e+08  3.607699e+08  5.995560e+08
North America         9.504176e+07  5.044035e+07  1.355070e+08  9.968469e+07
Asia/Asia Pacific     2.677911e+07  6.841370e+07  4.552182e+07  2.998501e+07
Middle East           9.491092e+06  1.750923e+07  4.557900e+05  0.000000e+00
Global                0.000000e+00  1.880443e+06  6.630000e+05  7.947500e+05
South America         4.465736e+05  1.441711e+06  0.000000e+00  5.327980e+05
Africa                0.000000e+00  0.000000e+00  5.599000e+05  0.000000e+00

AP pillar                   Total
Funder region_split
Europe               1.297971e+09
North America        3.806738e+08
Asia/Asia Pacific    1.706996e+08
Middle East          2.745611e+07
Global               3.338193e+06
South America        2.421083e+06
Africa               5.599000e+05
Saved 4b_funding_by_eu_tier_and_pillar -> data_output\analysis\260727_0922_4b_funding_by_eu_tier_and_pillar.csv

AP pillar  Cross-cutting    Cultivated  Fermentation   Plant-based  \
_tiers
EU          1.644838e+08  7.841910e+07  3.060532e+08  5.066684e+08
EU+         2.257344e+08  1.117603e+08  3.607699e+08  5.995560e+08
Europe      2.257344e+08  1.119103e+08  3.607699e+08  5.995560e+08

AP pillar         Total
_tiers
EU         1.055625e+09
EU+        1.297821e+09
Europe     1.297971e+09

### 4c. Total funding by region x AP pillar excl. non-profit funding, and by EU / EU+ / Europe x AP pillar

Region- and tier-level twins of 4a, on the same non-profit/NGO-excluded set as 3b (see 3b's note for
which `'Funder type'` values are dropped). Also defines `region_split_np` / `tier_split_np`, which 9c
reuses - so **3b must have been run first**, and this cell before 9c.

In [ ]:
# Region/tier equivalents of 4a. Built from `df_np` (defined once in 3b) rather than re-deriving the
# funder-type filter, so 3b, 4a, 4c and 9c can never disagree about which grants are in scope.
# NOTE: *_np naming again - analyses 5-9 read the unfiltered `region_split` / `tier_split`.
region_split_np = split_multi_value(df_np, 'Funder region', delimiter=',')
region_split_np['weighted_funding'] = region_split_np[FUNDING_COL] * region_split_np['_weight']

tier_split_np = europe_tier_split(df_np)
tier_split_np['weighted_funding'] = tier_split_np[FUNDING_COL] * tier_split_np['_weight']

region_pillar_np = region_split_np.pivot_table(
    index='Funder region_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
region_pillar_np['Total'] = region_pillar_np.sum(axis=1)
# Reindexed onto 4b's region list for the same reason 4a is reindexed onto 4's - keeps the two CSVs
# row-for-row comparable in the template. 'Global' funding is 100% non-profit, so it appears here as
# an explicit 0 row rather than silently vanishing.
region_pillar_np = region_pillar_np.reindex(
    region_pillar.index.union(region_pillar_np.index, sort=False), fill_value=0
).fillna(0).sort_values('Total', ascending=False)
save(region_pillar_np, '4c_funding_by_region_and_pillar_excl_nonprofit')
print(region_pillar_np)

tier_pillar_np = tier_split_np.pivot_table(
    index='_tiers', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
).reindex(['EU', 'EU+', 'Europe'])
tier_pillar_np['Total'] = tier_pillar_np.sum(axis=1)
save(tier_pillar_np, '4c_funding_by_eu_tier_and_pillar_excl_nonprofit')
print()
print(tier_pillar_np)

### 5. Top 20 funder institutions, with yearly split (no pillar split)

In [20]:
# Yearly breakdown by START year, not the funding-year spread - same default as everywhere
# else except 1b. 'Total' is the funder's sum across the 2020-2025 window: since Filter 3 now
# scopes `df` to that window globally, this Total is window-scoped too (it previously spanned
# all start years). Only NSERC was affected in the current data: 137,862 -> 96,985 EUR.
by_funder_year = df[df['Year project started'].between(2020, 2025)].pivot_table(
    index='Funder name', columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
by_funder_year.columns = by_funder_year.columns.astype(int)
by_funder_year = by_funder_year[sorted(by_funder_year.columns)]
by_funder_year['Total'] = df.groupby('Funder name')[FUNDING_COL].sum()
by_funder_year = by_funder_year.fillna(0)
top20_funders = by_funder_year.sort_values('Total', ascending=False).head(20)
save(top20_funders, '5_top20_funders')
print(top20_funders)

Saved 5_top20_funders -> data_output\analysis\260727_0922_5_top20_funders.csv
Year project started                                        2020  \
Funder name
European Commission                                 3.741279e+07
UK Research and Innovation (UKRI)                   3.111053e+06
Novo Nordisk Foundation                             3.345500e+04
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    3.272000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          1.022493e+07
"Agency for Science, Technology, and Research (...  0.000000e+00
Federal Ministry of Food and Agriculture (BMEL)     1.552889e+06
Protein Industries Canada                           1.955580e+07
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  8.730389e+06
NSF                                                 3.020116e+06
Israel Innovation Authority's Generic Technolog...  0.000000e+00
National Institute of Food and Agriculture          1.207839e+06
Federal Ministry for Economic Affairs and Energ...  8.166190e+05
USDA NIFA                                           2.413582e+05
Singapore Food Agency                               0.000000e+00
Danish Ministry of Food, Agriculture and Fisheries  4.346060e+06

Year project started                                        2021  \
Funder name
European Commission                                 2.500890e+07
UK Research and Innovation (UKRI)                   7.417615e+06
Novo Nordisk Foundation                             1.356960e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    1.017000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          2.488350e+07
"Agency for Science, Technology, and Research (...  4.218251e+07
Federal Ministry of Food and Agriculture (BMEL)     8.060830e+05
Protein Industries Canada                           7.631638e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  3.662148e+06
NSF                                                 0.000000e+00
Israel Innovation Authority's Generic Technolog...  8.149300e+06
National Institute of Food and Agriculture          8.462400e+06
Federal Ministry for Economic Affairs and Energ...  2.195042e+06
USDA NIFA                                           1.074179e+07
Singapore Food Agency                               0.000000e+00
Danish Ministry of Food, Agriculture and Fisheries  4.841415e+06

Year project started                                        2022  \
Funder name
European Commission                                 1.012906e+08
UK Research and Innovation (UKRI)                   1.274546e+07
Novo Nordisk Foundation                             3.514565e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    5.766000e+06
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        0.000000e+00
Research Council of Norway                          9.229815e+05
"Agency for Science, Technology, and Research (...  0.000000e+00
Federal Ministry of Food and Agriculture (BMEL)     3.488063e+06
Protein Industries Canada                           3.795336e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  4.040993e+06
NSF                                                 1.255051e+06
Israel Innovation Authority's Generic Technolog...  1.666206e+07
National Institute of Food and Agriculture          8.765550e+05
Federal Ministry for Economic Affairs and Energ...  5.622825e+06
USDA NIFA                                           4.726362e+06
Singapore Food Agency                               0.000000e+00
Danish Ministry of Food, Agriculture and Fisheries  2.595590e+05

Year project started                                        2023  \
Funder name
European Commission                                 9.079888e+07
UK Research and Innovation (UKRI)                   4.356962e+07
Novo Nordisk Foundation                             2.027661e+07
Bezos Earth Fund (BEF)                              0.000000e+00
Business Finland                                    4.882900e+06
Dutch National Growth Fund                          6.000000e+07
Department of Commerce (DoC)                        4.718300e+05
Research Council of Norway                          2.239901e+06
"Agency for Science, Technology, and Research (...  3.188250e+05
Federal Ministry of Food and Agriculture (BMEL)     2.129174e+07
Protein Industries Canada                           3.029490e+06
Defense Advanced Research Projects Agency (DARPA)   3.708478e+07
Swedish Research Council for Environment Agricu...  4.121009e+06
NSF                                                 5.426400e+05
Israel Innovation Authority's Generic Technolog...  1.341792e+06
National Institute of Food and Agriculture          4.382728e+06
Federal Ministry for Economic Affairs and Energ...  6.906378e+06
USDA NIFA                                           4.110818e+06
Singapore Food Agency                               0.000000e+00
Danish Ministry of Food, Agriculture and Fisheries  4.106737e+06

Year project started                                        2024  \
Funder name
European Commission                                 8.056789e+07
UK Research and Innovation (UKRI)                   6.771888e+07
Novo Nordisk Foundation                             2.180884e+07
Bezos Earth Fund (BEF)                              8.077890e+07
Business Finland                                    4.678500e+07
Dutch National Growth Fund                          0.000000e+00
Department of Commerce (DoC)                        4.746417e+07
Research Council of Norway                          5.253050e+05
"Agency for Science, Technology, and Research (...  0.000000e+00
Federal Ministry of Food and Agriculture (BMEL)     9.741771e+06
Protein Industries Canada                           3.838650e+06
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00
Swedish Research Council for Environment Agricu...  6.989658e+06
NSF                                                 1.747786e+07
Israel Innovation Authority's Generic Technolog...  0.000000e+00
National Institute of Food and Agriculture          5.713368e+06
Federal Ministry for Economic Affairs and Energ...  4.720504e+06
USDA NIFA                                           2.663786e+05
Singapore Food Agency                               0.000000e+00
Danish Ministry of Food, Agriculture and Fisheries  5.808920e+05

Year project started                                        2025         Total
Funder name
European Commission                                 1.294472e+08  4.645262e+08
UK Research and Innovation (UKRI)                   4.680803e+06  1.392434e+08
Novo Nordisk Foundation                             2.398031e+07  1.148145e+08
Bezos Earth Fund (BEF)                              3.841188e+06  8.462009e+07
Business Finland                                    1.123707e+07  7.295997e+07
Dutch National Growth Fund                          0.000000e+00  6.000000e+07
Department of Commerce (DoC)                        0.000000e+00  4.793600e+07
Research Council of Norway                          6.259273e+06  4.505590e+07
"Agency for Science, Technology, and Research (...  0.000000e+00  4.250134e+07
Federal Ministry of Food and Agriculture (BMEL)     4.592222e+06  4.147277e+07
Protein Industries Canada                           2.758304e+06  4.060921e+07
Defense Advanced Research Projects Agency (DARPA)   0.000000e+00  3.708478e+07
Swedish Research Council for Environment Agricu...  5.333470e+06  3.287767e+07
NSF                                                 3.882711e+06  2.617838e+07
Israel Innovation Authority's Generic Technolog...  0.000000e+00  2.615315e+07
National Institute of Food and Agriculture          3.407436e+06  2.405033e+07
Federal Ministry for Economic Affairs and Energ...  3.078532e+06  2.333990e+07
USDA NIFA                                           1.559508e+06  2.164621e+07
Singapore Food Agency                               2.025035e+07  2.025035e+07
Danish Ministry of Food, Agriculture and Fisheries  3.001019e+06  1.713568e+07

### 6. Top 20 country rankings per year, 2020-2025 (non-cumulative)

Two shapes: (a) rank 1-20 x year, country name per cell (for a table); (b) country x year, rank
number per cell (for graphing a ranked-line/bump chart). Distinct from analysis #8's cumulative
ranking below - confirmed via the template these are two different things, not variants of one.

In [29]:
# By START year (2020-2025), not the funding-year spread - same default as everywhere else in
# this notebook except 1b.
annual_country = country_split[country_split['Year project started'].between(2020, 2025)]
year_country_totals = {}
for y in range(2020, 2026):
    year_country_totals[y] = annual_country[annual_country['Year project started'] == y].groupby(
        'Funder Country_split'
    )['weighted_funding'].sum().sort_values(ascending=False)

# Shape A: rank (1-20) x year, country name per cell
rank_table = pd.DataFrame({y: year_country_totals[y].head(20).index.tolist() for y in range(2020, 2026)})
rank_table.index = pd.RangeIndex(1, 21, name='Rank')
save(rank_table, '6a_country_rank_table')
print(rank_table)

# Shape B: country x year, rank number per cell (for graphing)
all_countries_ranked = sorted(set().union(*[year_country_totals[y].head(10).index for y in range(2020, 2026)]))
country_rank_grid = pd.DataFrame(index=all_countries_ranked, columns=range(2020, 2026), dtype='float')
for y in range(2020, 2026):
    ranks = {c: i + 1 for i, c in enumerate(year_country_totals[y].index)}
    for c in all_countries_ranked:
        country_rank_grid.loc[c, y] = ranks.get(c, np.nan)
save(country_rank_grid, '6b_country_rank_grid')
print()
print(country_rank_grid)

Saved 6a_country_rank_table -> data_output\analysis\260727_0922_6a_country_rank_table.csv
                2020            2021            2022            2023  \
Rank
1                 EU       Singapore              EU              EU
2             Canada          Norway         Denmark     Netherlands
3             Norway   United States   United States   United States
4            Germany              EU  United Kingdom  United Kingdom
5             Sweden         Denmark          Israel         Germany
6      United States           Spain     South Korea         Denmark
7        New Zealand          Canada         Germany          France
8            Denmark          Israel           Spain          Canada
9            Belgium  United Kingdom         Finland           Japan
10           Finland          Sweden     Switzerland           Spain
11    United Kingdom       Australia          Sweden          Sweden
12           Ireland         Germany          Canada     New Zealand
13             Japan     Switzerland     Netherlands     Switzerland
14             China     Netherlands          France         Belgium
15             Spain         Finland       Australia         Finland
16       Switzerland        Portugal          Norway         Austria
17            Global           Japan          Global         Ireland
18           Estonia          Global           Japan          Israel
19       Netherlands           China         Austria          Norway
20           Croatia          Poland           China          Brazil

                2024            2025
Rank
1      United States              EU
2                 EU         Denmark
3     United Kingdom   United States
4            Finland       Singapore
5            Denmark          Sweden
6            Germany         Finland
7             Poland     Netherlands
8        Netherlands         Germany
9          Singapore     South Korea
10            Sweden          Norway
11       South Korea     New Zealand
12            Canada  United Kingdom
13           Belgium     Switzerland
14       New Zealand        Portugal
15            France          Canada
16             Spain         Czechia
17       Switzerland         Austria
18           Estonia          France
19           Czechia           Spain
20            Norway           Japan
Saved 6b_country_rank_grid -> data_output\analysis\260727_0922_6b_country_rank_grid.csv

                2020  2021  2022  2023  2024  2025
Belgium          9.0  26.0  28.0  14.0  13.0  29.0
Canada           2.0   7.0  12.0   8.0  12.0  15.0
Denmark          8.0   5.0   2.0   6.0   5.0   2.0
EU               1.0   4.0   1.0   1.0   2.0   1.0
Finland         10.0  15.0   9.0  15.0   4.0   6.0
France           NaN   NaN  14.0   7.0  15.0  18.0
Germany          4.0  12.0   7.0   5.0   6.0   8.0
Israel           NaN   8.0   5.0  18.0   NaN  23.0
Japan           13.0  17.0  18.0   9.0  21.0  20.0
Netherlands     19.0  14.0  13.0   2.0   8.0   7.0
New Zealand      7.0   NaN  24.0  12.0  14.0  11.0
Norway           3.0   2.0  16.0  19.0  20.0  10.0
Poland          21.0  20.0  21.0  24.0   7.0  27.0
Singapore        NaN   1.0   NaN  23.0   9.0   4.0
South Korea     31.0   NaN   6.0  34.0  11.0   9.0
Spain           15.0   6.0   8.0  10.0  16.0  19.0
Sweden           5.0  10.0  11.0  11.0  10.0   5.0
Switzerland     16.0  13.0  10.0  13.0  17.0  13.0
United Kingdom  11.0   9.0   4.0   4.0   3.0  12.0
United States    6.0   3.0   3.0   3.0   1.0   3.0

### 7. Total funding 2020-2025 by AP pillar x End product type, plus a separate Dairy sub-split

In [22]:
ep_split = split_multi_value(df, 'End product type', delimiter=';')
ep_split['weighted_funding'] = ep_split[FUNDING_COL] * ep_split['_weight']
pillar_end_product = ep_split.pivot_table(
    index='End product type_split', columns='AP pillar', values='weighted_funding', aggfunc='sum', fill_value=0
)
pillar_end_product['Total'] = pillar_end_product.sum(axis=1)
save(pillar_end_product, '7a_funding_by_pillar_and_end_product')
print(pillar_end_product)

# Dairy's own constituents, not cross-tabulated with pillar. Starts from ep_split's Dairy share
# (not df directly) so a 'Meat; Dairy' grant contributes the same weighted share here as it does
# to 7a's Dairy total, then splits that share further across sub-end products. 'sub-end product'
# is exclusively populated for Dairy rows (confirmed: no non-Dairy row has one) - Dairy rows
# missing a sub-end product are labelled 'Agnostic' here, for this breakdown only, so their
# funding isn't silently dropped. Not written back to the underlying data: 'Agnostic' is already a
# distinct End product type value, and reusing it as a sub-end product value there would be confusing.
dairy_ep = ep_split[ep_split['End product type_split'] == 'Dairy'].copy()
dairy_ep['sub-end product'] = dairy_ep['sub-end product'].fillna('Agnostic')
dairy_ep = dairy_ep.rename(columns={'weighted_funding': 'dairy_weighted_funding'})
sub_ep_split = split_multi_value(dairy_ep, 'sub-end product', delimiter=';')
sub_ep_split['weighted_funding'] = sub_ep_split['dairy_weighted_funding'] * sub_ep_split['_weight']
dairy_breakdown = sub_ep_split.groupby('sub-end product_split')['weighted_funding'].sum().sort_values(ascending=False)
dairy_breakdown.name = 'Total funding (2020-2025, EUR)'
save(dairy_breakdown, '7b_dairy_sub_breakdown')
print()
print(dairy_breakdown)

Saved 7a_funding_by_pillar_and_end_product -> data_output\analysis\260727_0922_7a_funding_by_pillar_and_end_product.csv
AP pillar                               Cross-cutting    Cultivated  \
End product type_split
Agnostic                                 3.166280e+08  5.911432e+07
Chocolate, desserts, and confectionery   0.000000e+00  3.597543e+05
Dairy                                    5.628772e+06  1.185138e+06
Eggs and egg proteins                    1.484131e+06  0.000000e+00
Fish and seafood                         1.600180e+05  2.656016e+07
Meat                                     3.359196e+07  1.643764e+08
Spreads, sauces, and condiments          0.000000e+00  0.000000e+00

AP pillar                               Fermentation   Plant-based  \
End product type_split
Agnostic                                4.613802e+08  5.238315e+08
Chocolate, desserts, and confectionery  1.053143e+06  6.477531e+06
Dairy                                   3.293387e+07  6.371087e+07
Eggs and egg proteins                   7.166210e+06  7.911941e+06
Fish and seafood                        8.217224e+06  2.018518e+07
Meat                                    2.524319e+07  1.076132e+08
Spreads, sauces, and condiments         7.483568e+06  8.230304e+05

AP pillar                                      Total
End product type_split
Agnostic                                1.360954e+09
Chocolate, desserts, and confectionery  7.890428e+06
Dairy                                   1.034586e+08
Eggs and egg proteins                   1.656228e+07
Fish and seafood                        5.512258e+07
Meat                                    3.308247e+08
Spreads, sauces, and condiments         8.306598e+06
Saved 7b_dairy_sub_breakdown -> data_output\analysis\260727_0922_7b_dairy_sub_breakdown.csv

sub-end product_split
Milk and milk proteins         2.903665e+07
Cheese                         2.870888e+07
Agnostic                       2.246005e+07
Yoghurt and fermented dairy    1.844889e+07
Infant formula                 3.700140e+06
Cream and ice cream            1.104044e+06
Name: Total funding (2020-2025, EUR), dtype: float64

### 8. Investment and cumulative investment by country, 2020-2025, with cumulative rank

Reuses `year_country_totals` computed for analysis #6 above.

In [32]:
investment_by_year = pd.DataFrame({y: year_country_totals[y] for y in range(2020, 2026)}).fillna(0)
save(investment_by_year, '8a_investment_by_country_and_year')

cumulative_by_year = investment_by_year.cumsum(axis=1)
save(cumulative_by_year, '8b_cumulative_investment_by_country_and_year')

# Rank 1 = highest cumulative total-to-date that year
cumulative_rank = cumulative_by_year.rank(axis=0, ascending=False, method='min')
save(cumulative_rank, '8c_cumulative_investment_rank')

print(investment_by_year.head(10))
print()
print(cumulative_by_year.head(10))
print()
print(cumulative_rank.head(10))

Saved 8a_investment_by_country_and_year -> data_output\analysis\260727_0922_8a_investment_by_country_and_year.csv
Saved 8b_cumulative_investment_by_country_and_year -> data_output\analysis\260727_0922_8b_cumulative_investment_by_country_and_year.csv
Saved 8c_cumulative_investment_rank -> data_output\analysis\260727_0922_8c_cumulative_investment_rank.csv
                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.828994e+06  1.328364e+06  6.063202e+05
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.200000e+06
Belgium               3.600000e+06  0.000000e+00  0.000000e+00  5.995271e+06
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.346367e+07  9.627245e+06  5.676812e+06  1.334143e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.328890e+05  4.717510e+05  3.254220e+05
Croatia               1.312388e+05  0.000000e+00  0.000000e+00  0.000000e+00
Czechia               0.000000e+00  3.755200e+04  0.000000e+00  0.000000e+00
Denmark               4.621640e+06  2.212959e+07  3.844566e+07  2.934713e+07

                              2024          2025
Funder Country_split
Australia             1.279530e+05  4.340292e+05
Austria               0.000000e+00  1.345167e+06
Belgium               6.249971e+06  0.000000e+00
Brazil                0.000000e+00  4.144000e+05
Canada                6.939440e+06  3.764216e+06
Chile                 0.000000e+00  0.000000e+00
China                 0.000000e+00  0.000000e+00
Croatia               0.000000e+00  0.000000e+00
Czechia               1.689872e+06  2.591386e+06
Denmark               3.500198e+07  3.660860e+07

                              2020          2021          2022          2023  \
Funder Country_split
Australia             2.060400e+04  4.849598e+06  6.177962e+06  6.784282e+06
Austria               0.000000e+00  0.000000e+00  6.654340e+05  3.865434e+06
Belgium               3.600000e+06  3.600000e+06  3.600000e+06  9.595271e+06
Brazil                0.000000e+00  0.000000e+00  0.000000e+00  1.473885e+06
Canada                2.346367e+07  3.309092e+07  3.876773e+07  5.210916e+07
Chile                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
China                 2.705197e+06  2.938086e+06  3.409837e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05  1.312388e+05  1.312388e+05
Czechia               0.000000e+00  3.755200e+04  3.755200e+04  3.755200e+04
Denmark               4.621640e+06  2.675123e+07  6.519690e+07  9.454403e+07

                              2024          2025
Funder Country_split
Australia             6.912235e+06  7.346265e+06
Austria               3.865434e+06  5.210601e+06
Belgium               1.584524e+07  1.584524e+07
Brazil                1.473885e+06  1.888285e+06
Canada                5.904859e+07  6.281281e+07
Chile                 0.000000e+00  0.000000e+00
China                 3.735259e+06  3.735259e+06
Croatia               1.312388e+05  1.312388e+05
Czechia               1.727424e+06  4.318810e+06
Denmark               1.295460e+08  1.661546e+08

                      2020  2021  2022  2023  2024  2025
Funder Country_split
Australia             22.0  14.0  17.0  20.0  21.0  22.0
Austria               24.0  28.0  26.0  22.0  24.0  24.0
Belgium                9.0  17.0  19.0  19.0  19.0  19.0
Brazil                24.0  28.0  31.0  27.0  29.0  29.0
Canada                 2.0   5.0   6.0   8.0   9.0   9.0
Chile                 24.0  28.0  31.0  35.0  36.0  36.0
China                 14.0  20.0  20.0  23.0  25.0  27.0
Croatia               20.0  25.0  28.0  33.0  34.0  34.0
Czechia               24.0  26.0  30.0  34.0  28.0  26.0
Denmark                8.0   6.0   3.0   3.0   4.0   3.0

### 9a. Research category as a % of total funding, by region (+ EU / EU+ / Europe) - overall, and by AP pillar

`'Research category'` is multi-value like `'Funder Country'`/`'Funder region'`, so it gets the
same fractional split - a grant tagged with 3 categories has each get 1/3 of its (region- or
country-weighted) share. Grants with no `'Research category'` at all are excluded entirely, so
`'Total (EUR)'` here is the classified-funding total, not the full region/country total from
1c/3 - percentages are a share of classified funding only.

In [24]:
def category_pct_table(base_split, index_col, weighted_col_name):
    # Grants with no Research category are dropped entirely (not labelled 'Unclassified') -
    # percentages here are a share of classified funding only, so Total (EUR) will be less than
    # the region/country's true total wherever some grants lack a category.
    base = base_split.rename(columns={'weighted_funding': weighted_col_name}).copy()
    exploded = split_multi_value(base, 'Research category', delimiter=',')
    exploded['weighted_funding'] = exploded[weighted_col_name] * exploded['_weight']
    eur = exploded.pivot_table(
        index=index_col, columns='Research category_split', values='weighted_funding', aggfunc='sum', fill_value=0
    )
    eur['Total (EUR)'] = eur.sum(axis=1)
    pct = eur.drop(columns='Total (EUR)').div(eur['Total (EUR)'], axis=0) * 100
    pct['Total (EUR)'] = eur['Total (EUR)']
    return pct.sort_values('Total (EUR)', ascending=False)


def category_pct_by_pillar(base_split, index_col, weighted_col_name):
    pillars = sorted(base_split['AP pillar'].dropna().unique())
    return pd.concat(
        {p: category_pct_table(base_split[base_split['AP pillar'] == p], index_col, weighted_col_name) for p in pillars},
        names=['AP pillar']
    )

In [25]:
region_category_pct = category_pct_table(region_split, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct, '9a_research_category_pct_by_region')
print(region_category_pct)

region_category_pct_by_pillar = category_pct_by_pillar(region_split, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_by_pillar, '9a_research_category_pct_by_region_and_pillar')
print()
print(region_category_pct_by_pillar)

Saved 9a_research_category_pct_by_region -> data_output\analysis\260727_0922_9a_research_category_pct_by_region.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder region_split
Europe                           10.455913            2.348816
North America                     4.952989            2.362732
Asia/Asia Pacific                21.548814            7.814260
Middle East                       0.000000            0.000000
Global                           26.362429           12.716364
South America                     0.000000            0.000000
Africa                           20.000000            0.000000

Research category_split  Cell line development  Consumer & market research  \
Funder region_split
Europe                                1.319316                    5.563653
North America                         1.611055                    0.881481
Asia/Asia Pacific                     3.207925                    4.458708
Middle East                           0.000000                    0.000000
Global                                5.077501                    0.000000
South America                        17.116310                    0.672323
Africa                                0.000000                    0.000000

Research category_split  Crop development  End product formulation  \
Funder region_split
Europe                           4.651376                11.865027
North America                    3.433184                 8.469097
Asia/Asia Pacific                0.205808                 8.176913
Middle East                      0.000000                 1.416843
Global                           0.000000                14.025801
South America                    1.379376                28.038862
Africa                           0.000000                20.000000

Research category_split  Feedstocks  Food safety & quality  \
Funder region_split
Europe                     5.211380               3.411531
North America              7.030999               0.948064
Asia/Asia Pacific          3.314921               6.258798
Middle East                0.000000               0.553356
Global                     0.000000               0.000000
South America              0.000000               0.779978
Africa                     0.000000               0.000000

Research category_split  Health & nutrition  Impact Assessments  \
Funder region_split
Europe                             6.731913            6.301635
North America                      2.610619            1.320206
Asia/Asia Pacific                  6.189963            1.663867
Middle East                        0.000000            0.000000
Global                             0.000000            3.942926
South America                      1.522586            1.184904
Africa                             0.000000            0.000000

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder region_split
Europe                                 17.627659  12.297021     1.585894
North America                           9.552548  48.463038     2.374694
Asia/Asia Pacific                       8.644866  18.725918     2.117082
Middle East                             0.000000  96.612958     0.863487
Global                                 19.436663   9.523116     4.437976
South America                           5.307491  42.431886     0.000000
Africa                                 20.000000   0.000000     0.000000

Research category_split  Strain development  Target molecule selection  \
Funder region_split
Europe                             5.984842                   1.852729
North America                      3.193419                   0.574007
Asia/Asia Pacific                  3.458858                   3.458858
Middle East                        0.000000                   0.000000
Global                             0.000000                   0.000000
South America                      0.778853                   0.000000
Africa                            20.000000                  20.000000

Research category_split  Texturization methods   Total (EUR)
Funder region_split
Europe                                2.791295  1.297971e+09
North America                         2.221866  3.806738e+08
Asia/Asia Pacific                     0.754441  1.706996e+08
Middle East                           0.553356  2.745611e+07
Global                                4.477223  3.338193e+06
South America                         0.787433  2.421083e+06
Africa                                0.000000  5.599000e+05
Saved 9a_research_category_pct_by_region_and_pillar -> data_output\analysis\260727_0922_9a_research_category_pct_by_region_and_pillar.csv

Research category_split            Bioprocess design  Cell culture media  \
AP pillar     Funder region_split
Cross-cutting Europe                        6.962628            1.936759
              North America                 1.409992            0.883320
              Asia/Asia Pacific             2.789063            2.437754
              Middle East                   0.000000            0.000000
              South America                 0.000000            0.000000
Cultivated    Europe                       23.464128           23.335654
              Asia/Asia Pacific            35.649223           18.543223
              North America                12.755241           16.167172
              Middle East                   0.000000            0.000000
              Global                       41.148748           22.574296
              South America                 0.000000            0.000000
Fermentation  Europe                       25.982999                 NaN
              North America                 8.177337                 NaN
              Asia/Asia Pacific            25.587533                 NaN
              Global                       16.025641                 NaN
              Africa                       20.000000                 NaN
              Middle East                   0.000000                 NaN
              South America                      NaN                 NaN
Plant-based   Europe                             NaN                 NaN
              North America                      NaN                 NaN
              Asia/Asia Pacific                  NaN                 NaN
              Global                             NaN                 NaN
              South America                      NaN                 NaN

Research category_split            Cell line development  \
AP pillar     Funder region_split
Cross-cutting Europe                            1.936759
              North America                     0.464250
              Asia/Asia Pacific                 0.000000
              Middle East                       0.000000
              South America                     0.000000
Cultivated    Europe                           11.395196
              Asia/Asia Pacific                 8.004123
              North America                    11.283890
              Middle East                       0.000000
              Global                            9.013663
              South America                    28.743625
Fermentation  Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              Global                                 NaN
              Africa                                 NaN
              Middle East                            NaN
              South America                          NaN
Plant-based   Europe                                 NaN
              North America                          NaN
              Asia/Asia Pacific                      NaN
              Global                                 NaN
              South America                          NaN

Research category_split            Consumer & market research  \
AP pillar     Funder region_split
Cross-cutting Europe                                 1.760203
              North America                          0.323891
              Asia/Asia Pacific                      8.672965
              Middle East                            0.000000
              South America                          0.000000
Cultivated    Europe                                 3.066365
              Asia/Asia Pacific                      2.900851
              North America                          4.579190
              Middle East                            0.000000
              Global                                 0.000000
              South America                          0.000000
Fermentation  Europe                                 2.626053
              North America                          0.145464
              Asia/Asia Pacific                      0.000000
              Global                                 0.000000
              Africa                                 0.000000
              Middle East                            0.000000
              South America                               NaN
Plant-based   Europe                                 9.229432
              North America                          0.542573
              Asia/Asia Pacific                     11.018424
              Global                                 0.000000
              South America                          3.055098

Research category_split            Crop development  End product formulation  \
AP pillar     Funder region_split
Cross-cutting Europe                       0.707728                 3.292093
              North America                0.337592                 0.856361
              Asia/Asia Pacific            0.000000                15.772638
              Middle East                  0.000000                 0.000000
              South America                0.000000               100.000000
Cultivated    Europe                            NaN                 7.665799
              Asia/Asia Pacific                 NaN                 5.455115
              North America                     NaN                 8.997553
              Middle East                       NaN                 1.354029
              Global                            NaN                 0.000000
              South America                     NaN                 0.000000
Fermentation  Europe                            NaN                 8.827430
              North America                     NaN                 3.308521
              Asia/Asia Pacific                 NaN                 2.965663
              Global                            NaN                26.709402
              Africa                            NaN                20.000000
              Middle East                       NaN                33.333333
              South America                     NaN                      NaN
Plant-based   Europe                       9.803240                17.704375
              North America               12.788701                22.474922
              Asia/Asia Pacific            1.171632                15.514813
              Global                       0.000000                36.631016
              South America                6.268010                43.594458

Research category_split            Feedstocks  Food safety & quality  \
AP pillar     Funder region_split
Cross-cutting Europe                 4.906779               5.627252
              North America          0.640067               0.276549
              Asia/Asia Pacific      1.278930              13.042929
              Middle East            0.000000               0.000000
              South America          0.000000               0.000000
Cultivated    Europe                      NaN               4.155607
              Asia/Asia Pacific           NaN               8.521238
              North America               NaN               3.121175
              Middle East                 NaN               0.000000
              Global                      NaN               0.000000
              South America               NaN               0.000000
Fermentation  Europe                15.679217               1.579505
              North America         19.302947               0.342643
              Asia/Asia Pacific     11.678075               2.780309
              Global                 0.000000               0.000000
              Africa                 0.000000               0.000000
              Middle East            0.000000              33.333333
              South America               NaN                    NaN
Plant-based   Europe                      NaN               3.540802
              North America               NaN               1.311694
              Asia/Asia Pacific           NaN               0.318909
              Global                      NaN               0.000000
              South America               NaN               3.544289

Research category_split            Health & nutrition  Impact Assessments  \
AP pillar     Funder region_split
Cross-cutting Europe                         3.576738            3.564251
              North America                  0.483633            0.878540
              Asia/Asia Pacific              2.909170            0.477809
              Middle East                    0.000000            0.000000
              South America                  0.000000            0.000000
Cultivated    Europe                         0.300807            8.927284
              Asia/Asia Pacific              1.862986            0.000000
              North America                  0.325015            5.776236
              Middle East                    0.000000            0.000000
              Global                         0.000000            2.479336
              South America                  0.000000            0.000000
Fermentation  Europe                         2.624289            6.262300
              North America                  2.078380            0.239060
              Asia/Asia Pacific              4.976129            0.000000
              Global                         0.000000            0.000000
              Africa                         0.000000            0.000000
              Middle East                    0.000000            0.000000
              South America                       NaN                 NaN
Plant-based   Europe                        11.591919            6.865846
              North America                  6.518554            0.956215
              Asia/Asia Pacific             20.835182            9.045395
              Global                         0.000000           10.695187
              South America                  6.918770            5.384311

Research category_split            Ingredient optimisation       Other  \
AP pillar     Funder region_split
Cross-cutting Europe                              5.071415   52.761791
              North America                       0.941440   89.575569
              Asia/Asia Pacific                   2.212083   47.502305
              Middle East                         0.000000  100.000000
              South America                       0.000000    0.000000
Cultivated    Europe                                   NaN    3.077687
              Asia/Asia Pacific                        NaN   14.234489
              North America                            NaN   20.326350
              Middle East                              NaN   97.291942
              Global                                   NaN   16.905590
              South America                            NaN   71.256375
Fermentation  Europe                             11.861266    3.590655
              North America                       4.475349   52.671283
              Asia/Asia Pacific                   6.961881   20.479191
              Global                             46.581197    0.000000
              Africa                             20.000000    0.000000
              Middle East                         0.000000    0.000000
              South America                            NaN         NaN
Plant-based   Europe                             29.115217    4.021637
              North America                      29.497885   17.782005
              Asia/Asia Pacific                  36.669001    0.612102
              Global                             42.780749    0.000000
              South America                      24.117721    0.000000

Research category_split            Scaffolding  Strain development  \
AP pillar     Funder region_split
Cross-cutting Europe                  1.875077            3.213388
              North America           0.665340            1.055032
              Asia/Asia Pacific       1.158823            0.581843
              Middle East             0.000000            0.000000
              South America           0.000000            0.000000
Cultivated    Europe                 14.611474                 NaN
              Asia/Asia Pacific       4.828753                 NaN
              North America          16.668178                 NaN
              Middle East             1.354029                 NaN
              Global                  7.878367                 NaN
              South America           0.000000                 NaN
Fermentation  Europe                       NaN           13.363377
              North America                NaN            7.023641
              Asia/Asia Pacific            NaN           12.285610
              Global                       NaN            0.000000
              Africa                       NaN           20.000000
              Middle East                  NaN            0.000000
              South America                NaN                 NaN
Plant-based   Europe                       NaN            3.705530
              North America                NaN            1.641440
              Asia/Asia Pacific            NaN            0.519635
              Global                       NaN            0.000000
              South America                NaN            3.539177

Research category_split            Target molecule selection  \
AP pillar     Funder region_split
Cross-cutting Europe                                1.369058
              North America                         0.878032
              Asia/Asia Pacific                     1.163687
              Middle East                           0.000000
              South America                         0.000000
Cultivated    Europe                                     NaN
              Asia/Asia Pacific                          NaN
              North America                              NaN
              Middle East                                NaN
              Global                                     NaN
              South America                              NaN
Fermentation  Europe                                5.809088
              North America                         0.996700
              Asia/Asia Pacific                    12.285610
              Global                                0.000000
              Africa                               20.000000
              Middle East                           0.000000
              South America                              NaN
Plant-based   Europe                                     NaN
              North America                              NaN
              Asia/Asia Pacific                          NaN
              Global                                     NaN
              South America                              NaN

Research category_split            Texturization methods   Total (EUR)
AP pillar     Funder region_split
Cross-cutting Europe                            1.438083  2.257344e+08
              North America                     0.330391  9.504176e+07

In [26]:
tier_category_pct = category_pct_table(tier_split, '_tiers', 'tier_weighted_funding').reindex(['EU', 'EU+', 'Europe'])
save(tier_category_pct, '9a_research_category_pct_by_eu_tier')
print(tier_category_pct)

tier_category_pct_by_pillar = category_pct_by_pillar(tier_split, '_tiers', 'tier_weighted_funding')
save(tier_category_pct_by_pillar, '9a_research_category_pct_by_eu_tier_and_pillar')
print()
print(tier_category_pct_by_pillar)

Saved 9a_research_category_pct_by_eu_tier -> data_output\analysis\260727_0922_9a_research_category_pct_by_eu_tier.csv
Research category_split  Bioprocess design  Cell culture media  \
_tiers
EU                               10.218250            1.552240
EU+                              10.457121            2.337530
Europe                           10.455913            2.348816

Research category_split  Cell line development  Consumer & market research  \
_tiers
EU                                    0.908419                    5.457232
EU+                                   1.319468                    5.564296
Europe                                1.319316                    5.563653

Research category_split  Crop development  End product formulation  \
_tiers
EU                               4.514109                12.534197
EU+                              4.651914                11.866398
Europe                           4.651376                11.865027

Research category_split  Feedstocks  Food safety & quality  \
_tiers
EU                         5.036759               3.364292
EU+                        5.211983               3.411925
Europe                     5.211380               3.411531

Research category_split  Health & nutrition  Impact Assessments  \
_tiers
EU                                 6.252336            6.820767
EU+                                6.732691            6.302364
Europe                             6.731913            6.301635

Research category_split  Ingredient optimisation      Other  Scaffolding  \
_tiers
EU                                     18.497750  14.240915     1.057147
EU+                                    17.629696  12.298442     1.586078
Europe                                 17.627659  12.297021     1.585894

Research category_split  Strain development  Target molecule selection  \
_tiers
EU                                 5.645846                   1.471951
EU+                                5.985534                   1.852943
Europe                             5.984842                   1.852729

Research category_split  Texturization methods   Total (EUR)
_tiers
EU                                    2.427792  1.055625e+09
EU+                                   2.791618  1.297821e+09
Europe                                2.791295  1.297971e+09
Saved 9a_research_category_pct_by_eu_tier_and_pillar -> data_output\analysis\260727_0922_9a_research_category_pct_by_eu_tier_and_pillar.csv

Research category_split  Bioprocess design  Cell culture media  \
AP pillar     _tiers
Cross-cutting EU+                 6.962628            1.936759
              Europe              6.962628            1.936759
              EU                  4.726281            0.107775
Cultivated    Europe             23.464128           23.335654
              EU+                23.495620           23.232762
              EU                 20.730703           20.669134
Fermentation  EU+                25.982999                 NaN
              Europe             25.982999                 NaN
              EU                 27.392476                 NaN
Plant-based   EU+                      NaN                 NaN
              Europe                   NaN                 NaN
              EU                       NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
AP pillar     _tiers
Cross-cutting EU+                     1.936759                    1.760203
              Europe                  1.936759                    1.760203
              EU                      0.107775                    0.177901
Cultivated    Europe                 11.395196                    3.066365
              EU+                    11.410490                    3.070480
              EU                     12.002464                    4.224199
Fermentation  EU+                          NaN                    2.626053
              Europe                       NaN                    2.626053
              EU                           NaN                    2.984019
Plant-based   EU+                          NaN                    9.229432
              Europe                       NaN                    9.229432
              EU                           NaN                    8.855890

Research category_split  Crop development  End product formulation  \
AP pillar     _tiers
Cross-cutting EU+                0.707728                 3.292093
              Europe             0.707728                 3.292093
              EU                 0.008418                 3.092169
Cultivated    Europe                  NaN                 7.665799
              EU+                     NaN                 7.676087
              EU                      NaN                 9.455414
Fermentation  EU+                     NaN                 8.827430
              Europe                  NaN                 8.827430
              EU                      NaN                 8.929384
Plant-based   EU+                9.803240                17.704375
              Europe             9.803240                17.704375
              EU                 9.402242                18.253441

Research category_split  Feedstocks  Food safety & quality  \
AP pillar     _tiers
Cross-cutting EU+          4.906779               5.627252
              Europe       4.906779               5.627252
              EU           2.056585               4.678550
Cultivated    Europe            NaN               4.155607
              EU+               NaN               4.161184
              EU                NaN               4.327686
Fermentation  EU+         15.679217               1.579505
              Europe      15.679217               1.579505
              EU          16.267275               1.767508
Plant-based   EU+               NaN               3.540802
              Europe            NaN               3.540802
              EU                NaN               3.753064

Research category_split  Health & nutrition  Impact Assessments  \
AP pillar     _tiers
Cross-cutting EU+                  3.576738            3.564251
              Europe               3.576738            3.564251
              EU                   3.604575            4.602429
Cultivated    Europe               0.300807            8.927284
              EU+                  0.301210            8.939265
              EU                   0.429275           10.434632
Fermentation  EU+                  2.624289            6.262300
              Europe               2.624289            6.262300
              EU                   2.030968            7.138215
Plant-based   EU+                 11.591919            6.865846
              Europe              11.591919            6.865846
              EU                  10.563076            6.789835

Research category_split  Ingredient optimisation      Other  Scaffolding  \
AP pillar     _tiers
Cross-cutting EU+                       5.071415  52.761791     1.875077
              Europe                    5.071415  52.761791     1.875077
              EU                        3.698753  69.516337     0.199433
Cultivated    Europe                         NaN   3.077687    14.611474
              EU+                            NaN   3.081818    14.631085
              EU                             NaN   3.914214    13.812279
Fermentation  EU+                      11.861266   3.590655          NaN
              Europe                   11.861266   3.590655          NaN
              EU                       12.173547   3.822232          NaN
Plant-based   EU+                      29.115217   4.021637          NaN
              Europe                   29.115217   4.021637          NaN
              EU                       29.985173   4.188130          NaN

Research category_split  Strain development  Target molecule selection  \
AP pillar     _tiers
Cross-cutting EU+                  3.213388                   1.369058
              Europe               3.213388                   1.369058
              EU                   1.732265                   0.666375
Cultivated    Europe                    NaN                        NaN
              EU+                       NaN                        NaN
              EU                        NaN                        NaN
Fermentation  EU+                 13.363377                   5.809088
              Europe              13.363377                   5.809088
              EU                  11.730972                   4.718851
Plant-based   EU+                  3.705530                        NaN
              Europe               3.705530                        NaN
              EU                   4.114450                        NaN

Research category_split  Texturization methods   Total (EUR)
AP pillar     _tiers
Cross-cutting EU+                     1.438083  2.257344e+08
              Europe                  1.438083  2.257344e+08
              EU                      1.024379  1.644838e+08
Cultivated    Europe                       NaN  1.119103e+08
              EU+                          NaN  1.117603e+08
              EU                           NaN  7.841910e+07
Fermentation  EU+                     1.793821  3.607699e+08
              Europe                  1.793821  3.607699e+08
              EU                      1.044553  3.060532e+08
Plant-based   EU+                     4.422001  5.995560e+08
              Europe                  4.422001  5.995560e+08
              EU                      4.094698  5.066684e+08

### 9b. Research category as a % of total funding, by country - overall, and by AP pillar

In [27]:
country_category_pct = category_pct_table(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct, '9b_research_category_pct_by_country')
print(country_category_pct)

country_category_pct_by_pillar = category_pct_by_pillar(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_by_pillar, '9b_research_category_pct_by_country_and_pillar')
print()
print(country_category_pct_by_pillar)

Saved 9b_research_category_pct_by_country -> data_output\analysis\260727_0922_9b_research_category_pct_by_country.csv
Research category_split  Bioprocess design  Cell culture media  \
Funder Country_split
EU                               12.863224            1.738614
United States                     5.410358            2.254821
Denmark                          12.516476            0.516037
United Kingdom                   12.404175            8.325029
Netherlands                       4.777105            2.669911
Germany                           4.881928            0.685060
Singapore                        15.089249            3.764120
Finland                          14.454670            0.314991
Canada                            2.638501            2.908811
Norway                           10.121437            1.736356
Sweden                            1.863944            0.222507
Spain                             6.700209            4.362627
France                            3.089107            0.000000
South Korea                      51.654005            6.013103
Switzerland                       9.437793            0.191084
New Zealand                       7.295102            8.140037
Israel                            0.000000            0.000000
Japan                            35.059919           34.875596
Belgium                           4.543951            4.543951
Poland                           10.064336            9.434726
Portugal                          6.809871            2.055218
Australia                         0.000000            0.000000
Ireland                          12.993763            0.000000
Austria                          17.272480            0.000000
Estonia                           4.029116            0.000000
Czechia                           0.000000            8.967859
China                             1.072054            0.000000
Global                           26.362429           12.716364
Brazil                            0.000000            0.000000
South Africa                     20.000000            0.000000
Slovakia                          0.000000            0.000000
Uruguay                           0.000000            0.000000
Serbia                            0.000000          100.000000
Croatia                           0.000000            0.000000
Latvia                            0.000000            0.000000
Chile                                  NaN                 NaN
Iceland                                NaN                 NaN
Malaysia                               NaN                 NaN
Italy                                  NaN                 NaN
Russia                                 NaN                 NaN
Turkey                                 NaN                 NaN

Research category_split  Cell line development  Consumer & market research  \
Funder Country_split
EU                                    0.353102                    6.834610
United States                         1.500104                    1.007146
Denmark                               0.438324                    3.144721
United Kingdom                        4.646946                    3.220764
Netherlands                           3.462910                    3.809717
Germany                               1.650716                    4.474306
Singapore                             2.256169                    2.803278
Finland                               0.314991                    2.767671
Canada                                2.172519                    0.245561
Norway                                0.594575                   10.206345
Sweden                                0.000000                    9.432012
Spain                                 4.127878                    1.003633
France                                0.000000                    5.902362
South Korea                           6.013103                    0.000000
Switzerland                           0.000000                   12.622892
New Zealand                           5.808940                   15.247091
Israel                                0.000000                    0.000000
Japan                                 0.364610                    4.115990
Belgium                               4.543951                    9.459103
Poland                                0.000000                    0.695574
Portugal                              2.055218                    1.161203
Australia                             0.000000                    4.020274
Ireland                               0.000000                   12.613720
Austria                               0.000000                    0.000000
Estonia                               0.000000                    0.000000
Czechia                               0.000000                   50.939958
China                                 1.072054                    0.000000
Global                                5.077501                    0.000000
Brazil                               21.945844                    0.000000
South Africa                          0.000000                    0.000000
Slovakia                              0.000000                    0.000000
Uruguay                               0.000000                    3.055098
Serbia                                0.000000                    0.000000
Croatia                               0.000000                    0.000000
Latvia                                0.000000                    0.000000
Chile                                      NaN                         NaN
Iceland                                    NaN                         NaN
Malaysia                                   NaN                         NaN
Italy                                      NaN                         NaN
Russia                                     NaN                         NaN
Turkey                                     NaN                         NaN

Research category_split  Crop development  End product formulation  \
Funder Country_split
EU                               2.342163                13.440693
United States                    3.161116                 4.123045
Denmark                          4.500510                 9.935390
United Kingdom                   6.958591                 7.924872
Netherlands                      1.560073                 2.938007
Germany                         16.557347                13.226870
Singapore                        0.000000                 7.548412
Finland                          1.107567                10.068663
Canada                           4.809971                30.462066
Norway                           1.707581                 9.853148
Sweden                           4.549173                15.907489
Spain                            6.015823                11.463300
France                          19.383060                26.915754
South Korea                      0.000000                 6.013103
Switzerland                      3.369745                12.704765
New Zealand                      0.000000                 7.975960
Israel                           0.000000                 1.416843
Japan                            0.000000                 0.256768
Belgium                         11.618989                14.003054
Poland                           0.000000                41.847084
Portugal                         1.771524                16.177895
Australia                        4.782213                45.551112
Ireland                          0.000000                21.826909
Austria                          0.000000                 3.198607
Estonia                          0.000000                15.108344
Czechia                          9.062357                 1.861896
China                            0.000000                 5.025836
Global                           0.000000                14.025801
Brazil                           0.000000                23.649698
South Africa                     0.000000                20.000000
Slovakia                         0.000000                27.924069
Uruguay                          6.268010                43.594458
Serbia                           0.000000                 0.000000
Croatia                          0.000000                 0.000000
Latvia                           0.000000                33.333333
Chile                                 NaN                      NaN
Iceland                               NaN                      NaN
Malaysia                              NaN                      NaN
Italy                                 NaN                      NaN
Russia                                NaN                      NaN
Turkey                                NaN                      NaN

Research category_split  Feedstocks  Food safety & quality  \
Funder Country_split
EU                         6.630876               4.312052
United States              8.329690               1.099380
Denmark                   11.212780               3.302497
United Kingdom             5.313215               2.788588
Netherlands                0.269622               1.765040
Germany                    0.634172               1.755637
Singapore                  4.280558              11.002779
Finland                    1.835021               0.727166
Canada                     0.459044               0.182339
Norway                     9.847553               6.336612
Sweden                     2.478974               3.884166
Spain                      2.105408               3.528531
France                     0.000000               0.000000
South Korea                0.000000               0.000000
Switzerland                1.471831               2.458602
New Zealand                4.902813               3.279324
Israel                     0.000000               0.553356
Japan                      0.259103               3.087097
Belgium                    0.000000              16.205855
Poland                     0.367135               0.367135
Portugal                   0.132627               3.324087
Australia                  9.279682               0.000000
Ireland                    0.000000               0.000000
Austria                    0.000000               0.000000
Estonia                    0.719683              13.016388
Czechia                    0.000000               0.000000
China                      0.000000               2.178042
Global                     0.000000               0.000000
Brazil                     0.000000               0.000000
South Africa               0.000000               0.000000
Slovakia                  27.924069               1.613515
Uruguay                    0.000000               3.544289
Serbia                     0.000000               0.000000
Croatia                    0.000000               0.000000
Latvia                     0.000000               0.000000
Chile                           NaN                    NaN
Iceland                         NaN                    NaN
Malaysia                        NaN                    NaN
Italy                           NaN                    NaN
Russia                          NaN                    NaN
Turkey                          NaN                    NaN

Research category_split  Health & nutrition  Impact Assessments  \
Funder Country_split
EU                                 7.382722           12.343731
United States                      2.549780            1.487633
Denmark                            6.739791            3.138014
United Kingdom                     7.833064            3.139465
Netherlands                        2.790457            2.218842
Germany                            2.698861            1.632381
Singapore                          7.811373            0.000000
Finland                            1.465537            1.509929
Canada                             2.918490            0.472948
Norway                            12.516152            2.963911
Sweden                            12.584737            5.683277
Spain                              4.823575            1.015817
France                            10.401849            0.000000
South Korea                        0.000000            0.000000
Switzerland                        6.511487           11.241806
New Zealand                       14.284079            7.416242
Israel                             0.000000            0.000000
Japan                              0.217870            0.000000
Belgium                           11.618989            9.459103
Poland                             2.378054            0.000000
Portugal                           0.332586            6.097294
Australia                          0.000000           10.390926
Ireland                           21.131753            0.000000
Austria                            0.000000           17.272480
Estonia                            0.000000            0.524649
Czechia                            1.861896            0.000000
China                              0.907648            0.000000
Global                             0.000000            3.942926
Brazil                             0.000000            0.000000
South Africa                       0.000000            0.000000
Slovakia                           1.613515            0.000000
Uruguay                            6.918770            5.384311
Serbia                             0.000000            0.000000
Croatia                           33.333333            0.000000
Latvia                             0.000000            0.000000
Chile                                   NaN                 NaN
Iceland                                 NaN                 NaN
Malaysia                                NaN                 NaN
Italy                                   NaN                 NaN
Russia                                  NaN                 NaN
Turkey                                  NaN                 NaN

Research category_split  Ingredient optimisation      Other  Scaffolding  \
Funder Country_split
EU                                     20.624397   3.459315     0.629792
United States                           5.066759  55.864949     2.369562
Denmark                                20.159794   1.646187     0.438324
United Kingdom                         10.476884   5.323727     4.953231
Netherlands                             3.038857  63.637390     3.751927
Germany                                30.737811   8.231671     1.738204
Singapore                               7.017653  22.885570     3.103563
Finland                                10.230779  46.079953     0.000000
Canada                                 32.252650  11.006056     2.400669
Norway                                 22.218513   1.774488     0.105977
Sweden                                 20.634282  16.810224     0.286426
Spain                                  11.197963  31.019262     4.308401
France                                 20.035880   7.568625     0.000000
South Korea                             0.000000  30.306684     0.000000
Switzerland                            14.688059   0.000000     6.032805
New Zealand                            14.732951   0.000000     3.049145
Israel                                  0.000000  96.612958     0.863487
Japan                                  16.429602   3.541378     1.034072
Belgium                                 9.459103   0.000000     4.543951
Poland                                 34.442129   0.000000     0.000000
Portugal                                5.452568  52.452666     2.044617
Australia                              18.409355   4.612358     0.000000
Ireland                                22.023787   0.000000     0.000000
Austria                                 3.198607  38.586739     0.000000
Estonia                                18.809321   0.000000     0.000000
Czechia                                12.901331  12.542807     0.000000
China                                  15.776644  68.509306     0.000000
Global                                 19.436663   9.523116     4.437976
Brazil                                  0.000000  54.404458     0.000000
South Africa                           20.000000   0.000000     0.000000
Slovakia                               40.924833   0.000000     0.000000
Uruguay                                24.117721   0.000000     0.000000
Serbia                                  0.000000   0.000000     0.000000
Croatia                                33.333333   0.000000     0.000000
Latvia                                 33.333333   0.000000     0.000000
Chile                                        NaN        NaN          NaN
Iceland                                      NaN        NaN          NaN
Malaysia                                     NaN        NaN          NaN
Italy                                        NaN        NaN          NaN
Russia                                       NaN        NaN          NaN
Turkey                                       NaN        NaN          NaN

Research category_split  Strain development  Target molecule selection  \
Funder Country_split
EU                                 4.485651                   1.336092
United States                      3.355490                   0.660480
Denmark                           14.458068                   2.208061
United Kingdom                     9.298111                   3.832248
Netherlands                        2.676339                   0.280498
Germany                            4.122775                   0.769292
Singapore                          5.838059                   5.838059
Finland                            4.448731                   3.891194
Canada                             2.373267                   0.136418
Norway                             5.037609                   4.358296
Sweden                             2.058467                   0.657643
Spain                              3.233172                   0.646502
France                             0.000000                   3.089107
South Korea                        0.000000                   0.000000
Switzerland                        2.552681                   0.000000
New Zealand                        3.679838                   3.679838
Israel                             0.000000                   0.000000
Japan                              0.000000                   0.000000
Belgium                            0.000000                   0.000000
Poland                             0.293754                   0.000000
Portugal                           0.132627                   0.000000
Australia                          0.000000                   0.000000
Ireland                            9.410068                   0.000000
Austria                           17.272480                   0.000000
Estonia                           41.099986                   6.477147
Czechia                            1.861896                   0.000000
China                              0.536027                   0.536027
Global                             0.000000                   0.000000
Brazil                             0.000000                   0.000000
South Africa                      20.000000                  20.000000
Slovakia                           0.000000                   0.000000
Uruguay                            3.539177                   0.000000
Serbia                             0.000000                   0.000000
Croatia                           33.333333                   0.000000
Latvia                             0.000000                   0.000000
Chile                                   NaN                        NaN
Iceland                                 NaN                        NaN
Malaysia                                NaN                        NaN
Italy                                   NaN                        NaN

### 9c. Research category as a % of total funding, excl. non-profit funding

Non-profit-excluded twin of 9a/9b, for region, EU / EU+ / Europe, and country. Reuses
`region_split_np` / `tier_split_np` from 4c and `country_split_np` from 3b.

Named **9c**, not 9b - `9b_*` is already the by-country cut of the unfiltered analysis above.

Unlike 4a/4c these tables are **not** reindexed onto 9a/9b's row list. Every figure here is a
percentage of that row's own classified total, and a row left with no funding has no meaningful
percentage (0/0); a row that disappears did so because 100% of its money was non-profit. In the
current data that is `'Global'` in the region cut.

In [ ]:
region_category_pct_np = category_pct_table(region_split_np, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_np, '9c_research_category_pct_by_region_excl_nonprofit')
print(region_category_pct_np)

region_category_pct_by_pillar_np = category_pct_by_pillar(region_split_np, 'Funder region_split', 'region_weighted_funding')
save(region_category_pct_by_pillar_np, '9c_research_category_pct_by_region_and_pillar_excl_nonprofit')
print()
print(region_category_pct_by_pillar_np)

In [ ]:
tier_category_pct_np = category_pct_table(tier_split_np, '_tiers', 'tier_weighted_funding').reindex(['EU', 'EU+', 'Europe'])
save(tier_category_pct_np, '9c_research_category_pct_by_eu_tier_excl_nonprofit')
print(tier_category_pct_np)

tier_category_pct_by_pillar_np = category_pct_by_pillar(tier_split_np, '_tiers', 'tier_weighted_funding')
save(tier_category_pct_by_pillar_np, '9c_research_category_pct_by_eu_tier_and_pillar_excl_nonprofit')
print()
print(tier_category_pct_by_pillar_np)

In [ ]:
country_category_pct_np = category_pct_table(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_np, '9c_research_category_pct_by_country_excl_nonprofit')
print(country_category_pct_np)

country_category_pct_by_pillar_np = category_pct_by_pillar(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_pct_by_pillar_np, '9c_research_category_pct_by_country_and_pillar_excl_nonprofit')
print()
print(country_category_pct_by_pillar_np)

### 9d. Research category by country in EUR (2020-2025)

Same split as 9b, in absolute amounts instead of row percentages. Five CSVs: one overall, plus one
per AP pillar carrying only the categories that occur in that pillar, and every country funded in it.

In [34]:
def category_eur_table(base_split, index_col, weighted_col_name):
    """EUR twin of category_pct_table - identical split logic, absolute amounts instead of row shares."""
    base = base_split.rename(columns={'weighted_funding': weighted_col_name}).copy()
    exploded = split_multi_value(base, 'Research category', delimiter=',')
    exploded['weighted_funding'] = exploded[weighted_col_name] * exploded['_weight']
    eur = exploded.pivot_table(
        index=index_col, columns='Research category_split', values='weighted_funding', aggfunc='sum', fill_value=0
    )
    eur = eur.loc[:, eur.sum() > 0]  # drop categories with no funding in this slice
    eur['Total (EUR)'] = eur.sum(axis=1)
    return eur.sort_values('Total (EUR)', ascending=False)


country_category_eur = category_eur_table(country_split, 'Funder Country_split', 'country_weighted_funding')
save(country_category_eur, '9d_research_category_eur_by_country')
print(country_category_eur.to_string(float_format=lambda v: f'{v:,.0f}'))

# One CSV per AP pillar. Subsetting BEFORE the pivot is what keeps each file to the categories that
# actually occur in that pillar - pivoting first and filtering after would leave all-zero columns.
for pillar in sorted(country_split['AP pillar'].dropna().unique()):
    pillar_eur = category_eur_table(
        country_split[country_split['AP pillar'] == pillar],
        'Funder Country_split', 'country_weighted_funding',
    )
    slug = re.sub(r'[^a-z0-9]+', '-', pillar.lower()).strip('-')
    save(pillar_eur, f'9d_research_category_eur_by_country_{slug}')
    print(f"\n--- {pillar}: {len(pillar_eur)} countries x {len(pillar_eur.columns) - 1} categories, "
          f"EUR {pillar_eur['Total (EUR)'].sum():,.0f} ---")
    print(pillar_eur.to_string(float_format=lambda v: f'{v:,.0f}'))

Saved 9d_research_category_eur_by_country -> data_output\analysis\260727_0922_9d_research_category_eur_by_country.csv
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation       Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
EU                              58,242,233           7,872,114              1,598,781                  30,945,817        10,604,867               60,856,900  30,023,344             19,524,150          33,427,562          55,890,068               93,383,350  15,663,122    2,851,577          20,310,176                  6,049,571              5,537,357  452,780,989
United States                   17,197,415           7,167,195              4,768,245                   3,201,324        10,047,952               13,105,551  26,476,830              3,494,499           8,104,756           4,728,605               16,105,249 177,572,854    7,531,911          10,665,791                  2,099,408              5,593,361  317,860,947
Denmark                         20,796,702             857,419                728,295                   5,225,099         7,477,805               16,508,109  18,630,551              5,487,251          11,198,474           5,213,955               33,496,427   2,735,215      728,295          24,022,746                  3,668,796              9,379,472  166,154,613
United Kingdom                  19,170,868          12,866,478              7,181,936                   4,977,747        10,754,624               12,248,028   8,211,667              4,309,811          12,106,137           4,852,097               16,192,207   8,227,912    7,655,305          14,370,392                  5,922,806              5,503,728  154,551,743
Netherlands                      4,532,735           2,533,333              3,285,767                   3,614,833         1,480,268                2,787,715     255,830              1,674,751           2,647,713           2,105,339                2,883,406  60,382,061    3,560,000           2,539,432                    266,150                335,232   94,884,566
Germany                          4,149,684             582,307              1,403,124                   3,803,202        14,073,898               11,242,961     539,052              1,492,308           2,294,057           1,387,539               26,127,423   6,996,996    1,477,489           3,504,397                    653,906              5,272,579   85,000,923
Singapore                       12,545,095           3,129,462              1,875,762                   2,330,625                 0                6,275,696   3,558,826              9,147,632           6,494,320                   0                5,834,427  19,026,900    2,580,280           4,853,721                  4,853,721                632,824   83,139,290
Finland                         11,240,544             244,950                244,950                   2,152,254           861,289                7,829,805   1,426,987                565,474           1,139,661           1,174,183                7,955,873  35,833,659            0           3,459,515                  3,025,952                609,000   77,764,097
Canada                           1,657,317           1,827,106              1,364,620                     154,244         3,021,278               19,134,080     288,338                114,532           1,833,185             297,072               20,258,796   6,913,213    1,507,928           1,490,716                     85,688              2,864,698   62,812,811
Norway                           6,007,423           1,030,587                352,901                   6,057,819         1,013,508                5,848,185   5,844,864              3,760,999           7,428,770           1,759,184               13,187,457   1,053,220       62,901           2,989,995                  2,586,800                368,850   59,353,463
Sweden                             981,100             117,118                      0                   4,964,605         2,394,489                8,373,017   1,304,825              2,044,458           6,624,063           2,991,432               10,860,997   8,848,177      150,762           1,083,488                    346,155              1,551,005   52,635,690
Spain                            2,360,290           1,536,827              1,454,132                     353,551         2,119,200                4,038,189     741,674              1,242,999           1,699,206             357,843                3,944,718  10,927,189    1,517,725           1,138,953                    227,744              1,566,866   35,227,108
France                           1,000,000                   0                      0                   1,910,702         6,274,648                8,713,118           0                      0           3,367,267                   0                6,485,978   2,450,101            0                   0                  1,000,000              1,170,000   32,371,813
South Korea                     16,063,750           1,870,000              1,870,000                           0                 0                1,870,000           0                      0                   0                   0                        0   9,425,000            0                   0                          0                      0   31,098,750
Switzerland                      2,670,042              54,060                      0                   3,571,137           953,333                3,594,299     416,395                695,562           1,842,162           3,180,414                4,155,392           0    1,706,738             722,178                          0              4,729,244   28,290,956
New Zealand                      2,042,947           2,279,565              1,626,756                   4,269,850                 0                2,233,617   1,373,001                918,354           4,000,165           2,076,871                4,125,869           0      853,894           1,030,515                  1,030,515                142,441   28,004,360
Israel                                   0                   0                      0                           0                 0                  389,010           0                151,930                   0                   0                        0  26,526,158      237,080                   0                          0                151,930   27,456,108
Japan                            6,091,914           6,059,886                 63,354                     715,183                 0                   44,615      45,021                536,405              37,856                   0                2,854,762     615,340      179,677                   0                          0                131,707   17,375,722
Belgium                            720,000             720,000                720,000                   1,498,818         1,841,057                2,218,818           0              2,567,857           1,841,057           1,498,818                1,498,818           0      720,000                   0                          0                      0   15,845,242
Poland                           1,472,092           1,380,000                      0                     101,740                 0                6,120,896      53,700                 53,700             347,834                   0                5,037,787           0            0              42,967                          0                 16,100   14,626,815
Portugal                           511,755             154,448                154,448                      87,263           133,128                1,215,753       9,967                249,802              24,994             458,206                  409,755   3,941,768      153,651               9,967                          0                      0    7,514,905
Australia                                0                   0                      0                     295,340           351,314                3,346,305     681,710                      0                   0             763,345                1,352,400     338,836            0                   0                          0                217,015    7,346,265
Ireland                            772,597                   0                      0                     750,000                 0                1,297,808           0                      0           1,256,474                   0                1,309,514           0            0             559,514                          0                      0    5,945,907
Austria                            900,000                   0                      0                           0                 0                  166,667           0                      0                   0             900,000                  166,667   2,010,601            0             900,000                          0                166,667    5,210,601
Estonia                            186,615                   0                      0                           0                 0                  699,768      33,333                602,876                   0              24,300                  871,186           0            0           1,903,615                    300,000                  9,975    4,631,669
Czechia                                  0             387,305                      0                   2,200,000           391,386                   80,412           0                      0              80,412                   0                  557,184     541,700            0              80,412                          0                      0    4,318,810
China                               40,044                   0                 40,044                           0                 0                  187,728           0                 81,356              33,903                   0                  589,298   2,559,000            0              20,022                     20,022                163,842    3,735,259
Global                             880,029             424,497                169,497                           0                 0                  468,208           0                      0                   0             131,622                  648,833     317,900      148,148                   0                          0                149,458    3,338,193
Brazil                                   0                   0                414,400                           0                 0                  446,574           0                      0                   0                   0                        0   1,027,311            0                   0                          0                      0    1,888,285
South Africa                       111,980                   0                      0                           0                 0                  111,980           0                      0                   0                   0                  111,980           0            0             111,980                    111,980                      0      559,900
Slovakia                                 0                   0                      0                           0                 0                  150,000     150,000                  8,667               8,667                   0                  219,836           0            0                   0                          0                      0      537,171
Uruguay                                  0                   0                      0                      16,278            33,396                  232,270           0                 18,884              36,863              28,688                  128,499           0            0              18,857                          0                 19,064      532,798
Serbia                                   0             149,995                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0      149,995
Croatia                                  0                   0                      0                           0                 0                        0           0                      0              43,746                   0                   43,746           0            0              43,746                          0                      0      131,239
Latvia                                   0                   0                      0                           0                 0                   14,117           0                      0                   0                   0                   14,117           0            0                   0                          0                 14,117       42,350
Chile                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Iceland                                  0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Malaysia                                 0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Italy                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Russia                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Turkey                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0           0            0                   0                          0                      0            0
Saved 9d_research_category_eur_by_country_cross-cutting -> data_output\analysis\260727_0922_9d_research_category_eur_by_country_cross-cutting.csv

--- Cross-cutting: 29 countries x 16 categories, EUR 357,492,916 ---
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
United States                    1,340,081             839,523                441,232                     274,312           320,853                  797,784     608,331                262,837             384,250             822,722                  828,818 85,019,577      632,351             986,605                    834,497                314,010   94,707,783
Netherlands                        266,150                   0                      0                           0                 0                  266,150           0                266,150             266,150                   0                  266,150 60,049,554            0                   0                    266,150                      0   61,646,452
United Kingdom                   4,410,911           3,904,657              3,904,657                   1,351,081         1,583,739                2,008,501   3,963,383              1,755,553           1,894,603             233,807                1,923,922  3,718,234    3,904,657           3,963,383                  1,704,355              1,464,739   41,690,184
EU                               1,565,059                   0                      0                           0                 0                2,390,008   1,565,059              6,701,490           5,280,243           6,999,521                3,861,255  8,847,362            0           1,565,059                          0                      0   38,775,058
Finland                          3,828,954                   0                      0                      18,000                 0                  756,050     838,954                      0                   0             546,429                  765,050 30,000,000            0           1,063,525                    829,929                      0   38,646,890
Norway                           3,242,344             290,000                290,000                   2,088,000                 0                  101,414   3,343,758              2,858,906               8,700                   0                3,053,758  1,040,170            0             290,000                    290,000                      0   16,897,050
Singapore                                0                   0                      0                           0                 0                        0           0              2,531,294                   0                   0                  155,812  9,704,400            0             155,812                    311,625                      0   12,858,944
Israel                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0  9,491,092            0                   0                          0                      0    9,491,092
Spain                               71,354                   0                      0                      43,438                 0                  253,294     139,688                119,738             191,429                   0                  239,341  7,240,850            0              43,438                          0                 85,645    8,428,214
New Zealand                        746,886             652,809                      0                   1,701,956                 0                1,089,373     342,486                652,809             779,050                   0                  436,564          0      310,323                   0                          0                      0    6,712,255

### 9e. Research category by country in EUR, excl. non-profit funding (2020-2025)

9d with non-profit/NGO funders removed - i.e. government money only. Reuses `country_split_np` from
3b and `category_eur_table` from 9d, so both must have been run. Five CSVs, same shapes as 9d.

In [36]:
country_category_eur_np = category_eur_table(country_split_np, 'Funder Country_split', 'country_weighted_funding')
save(country_category_eur_np, '9e_research_category_eur_by_country_excl_nonprofit')
print(country_category_eur_np.to_string(float_format=lambda v: f'{v:,.0f}'))

# Pillar list taken from country_split (not country_split_np) so the same four files are always
# written even if a pillar's funding were entirely non-profit in some future dataset.
for pillar in sorted(country_split['AP pillar'].dropna().unique()):
    pillar_eur_np = category_eur_table(
        country_split_np[country_split_np['AP pillar'] == pillar],
        'Funder Country_split', 'country_weighted_funding',
    )
    slug = re.sub(r'[^a-z0-9]+', '-', pillar.lower()).strip('-')
    save(pillar_eur_np, f'9e_research_category_eur_by_country_{slug}_excl_nonprofit')
    print(f"\n--- {pillar}: {len(pillar_eur_np)} countries x {len(pillar_eur_np.columns) - 1} categories, "
          f"EUR {pillar_eur_np['Total (EUR)'].sum():,.0f} ---")
    print(pillar_eur_np.to_string(float_format=lambda v: f'{v:,.0f}'))

assert country_category_eur_np['Total (EUR)'].sum() <= country_category_eur['Total (EUR)'].sum() + 1

Saved 9e_research_category_eur_by_country_excl_nonprofit -> data_output\analysis\260727_0922_9e_research_category_eur_by_country_excl_nonprofit.csv
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
EU                              58,242,233           7,872,114              1,598,781                  30,945,817        10,604,867               60,856,900  30,023,344             19,524,150          33,427,562          55,890,068               93,383,350 15,663,122    2,851,577          20,310,176                  6,049,571              5,537,357  452,780,989
United States                   13,953,078           4,732,644              3,542,795                   3,201,324         7,461,649                9,628,578  15,113,207              3,141,040           6,624,225           4,522,223               12,396,582 92,659,685    5,848,784          10,361,764                  1,928,386              4,425,309  199,541,272
United Kingdom                  19,170,868          12,866,478              7,181,936                   4,419,273        10,714,957               12,248,028   8,211,667              4,309,811          12,066,471           4,293,624               16,152,541  7,927,740    7,655,305          14,370,392                  5,922,806              5,503,728  153,015,624
Netherlands                      4,532,735           2,533,333              3,285,767                   3,614,833         1,480,268                2,787,715     255,830              1,674,751           2,647,713           2,105,339                2,883,406 60,382,061    3,560,000           2,539,432                    266,150                335,232   94,884,566
Germany                          4,149,684             582,307              1,403,124                   3,803,202        14,073,898               11,242,961     539,052              1,492,308           2,294,057           1,387,539               26,127,423  6,996,996    1,477,489           3,504,397                    653,906              5,272,579   85,000,923
Singapore                       12,545,095           3,129,462              1,875,762                   2,330,625                 0                6,275,696   3,558,826              9,147,632           6,494,320                   0                5,834,427 19,026,900    2,580,280           4,853,721                  4,853,721                632,824   83,139,290
Finland                         11,240,544             244,950                244,950                   2,134,254           861,289                7,829,805   1,426,987                565,474           1,139,661           1,132,183                7,955,873 35,833,659            0           3,459,515                  3,025,952                609,000   77,704,097
Norway                           6,007,423           1,030,587                352,901                   6,057,819         1,013,508                5,848,185   5,844,864              3,760,999           7,428,770           1,759,184               13,187,457  1,053,220       62,901           2,989,995                  2,586,800                368,850   59,353,463
Canada                           1,657,317           1,827,106              1,364,620                     154,244         2,101,843               18,214,645     288,338                114,532           1,805,122             297,072               20,181,855  6,309,228    1,507,928           1,490,716                     85,688              1,945,263   59,345,518
Sweden                             981,100             117,118                      0                   4,964,605         2,394,489                8,373,017   1,304,825              2,044,458           6,624,063           2,991,432               10,860,997  8,848,177      150,762           1,083,488                    346,155              1,551,005   52,635,690
Denmark                          2,461,243             221,929                 92,805                   2,336,210         1,297,459                8,728,982   2,310,509              1,323,567           6,578,133             700,067               12,167,907  2,714,580       92,805           1,968,993                    383,540              2,075,044   45,453,770
Spain                            2,360,290           1,536,827              1,454,132                     353,551         2,119,200                4,038,189     741,674              1,242,999           1,699,206             357,843                3,944,718 10,927,189    1,517,725           1,138,953                    227,744              1,566,866   35,227,108
France                           1,000,000                   0                      0                   1,910,702         6,274,648                8,713,118           0                      0           3,367,267                   0                6,485,978  2,450,101            0                   0                  1,000,000              1,170,000   32,371,813
South Korea                     16,063,750           1,870,000              1,870,000                           0                 0                1,870,000           0                      0                   0                   0                        0  9,425,000            0                   0                          0                      0   31,098,750
New Zealand                      2,042,947           2,279,565              1,626,756                   4,269,850                 0                2,233,617   1,373,001                918,354           4,000,165           2,076,871                4,125,869          0      853,894           1,030,515                  1,030,515                142,441   28,004,360
Switzerland                      2,670,042              54,060                      0                   3,571,137           240,750                3,594,299     416,395                695,562           1,842,162           3,180,414                4,044,655          0    1,706,738             722,178                          0              4,729,244   27,467,636
Israel                                   0                   0                      0                           0                 0                  389,010           0                151,930                   0                   0                        0 26,153,152      237,080                   0                          0                151,930   27,083,102
Japan                            6,091,914           6,059,886                 32,611                     715,183                 0                   44,615      45,021                536,405              37,856                   0                2,854,762    615,340      179,677                   0                          0                131,707   17,344,979
Belgium                            720,000             720,000                720,000                   1,498,818         1,841,057                2,218,818           0              2,567,857           1,841,057           1,498,818                1,498,818          0      720,000                   0                          0                      0   15,845,242
Poland                           1,472,092           1,380,000                      0                     101,740                 0                6,120,896      53,700                 53,700             347,834                   0                5,037,787          0            0              42,967                          0                 16,100   14,626,815
Portugal                           511,755             154,448                154,448                      87,263           133,128                1,215,753       9,967                249,802              24,994             458,206                  409,755  3,941,768      153,651               9,967                          0                      0    7,514,905
Australia                                0                   0                      0                     295,340           351,314                3,346,305     681,710                      0                   0             763,345                1,352,400    338,836            0                   0                          0                217,015    7,346,265
Ireland                            772,597                   0                      0                     750,000                 0                1,297,808           0                      0           1,256,474                   0                1,309,514          0            0             559,514                          0                      0    5,945,907
Austria                            900,000                   0                      0                           0                 0                  166,667           0                      0                   0             900,000                  166,667  2,010,601            0             900,000                          0                166,667    5,210,601
Estonia                            186,615                   0                      0                           0                 0                  699,768      33,333                602,876                   0                   0                  871,186          0            0           1,903,615                    300,000                  9,975    4,607,369
Czechia                                  0             387,305                      0                   2,200,000           391,386                   80,412           0                      0              80,412                   0                  557,184    541,700            0              80,412                          0                      0    4,318,810
China                               40,044                   0                 40,044                           0                 0                  187,728           0                 81,356              33,903                   0                  589,298  2,559,000            0              20,022                     20,022                163,842    3,735,259
Brazil                                   0                   0                414,400                           0                 0                  446,574           0                      0                   0                   0                        0  1,027,311            0                   0                          0                      0    1,888,285
South Africa                       111,980                   0                      0                           0                 0                  111,980           0                      0                   0                   0                  111,980          0            0             111,980                    111,980                      0      559,900
Slovakia                                 0                   0                      0                           0                 0                  150,000     150,000                  8,667               8,667                   0                  219,836          0            0                   0                          0                      0      537,171
Uruguay                                  0                   0                      0                      16,278            33,396                  232,270           0                 18,884              36,863              28,688                  128,499          0            0              18,857                          0                 19,064      532,798
Serbia                                   0             149,995                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0      149,995
Croatia                                  0                   0                      0                           0                 0                        0           0                      0              43,746                   0                   43,746          0            0              43,746                          0                      0      131,239
Latvia                                   0                   0                      0                           0                 0                   14,117           0                      0                   0                   0                   14,117          0            0                   0                          0                 14,117       42,350
Chile                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Iceland                                  0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Malaysia                                 0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Italy                                    0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Russia                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Turkey                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0          0            0                   0                          0                      0            0
Saved 9e_research_category_eur_by_country_cross-cutting_excl_nonprofit -> data_output\analysis\260727_0922_9e_research_category_eur_by_country_cross-cutting_excl_nonprofit.csv

--- Cross-cutting: 28 countries x 16 categories, EUR 273,217,303 ---
Research category_split  Bioprocess design  Cell culture media  Cell line development  Consumer & market research  Crop development  End product formulation  Feedstocks  Food safety & quality  Health & nutrition  Impact Assessments  Ingredient optimisation      Other  Scaffolding  Strain development  Target molecule selection  Texturization methods  Total (EUR)
Funder Country_split
Netherlands                        266,150                   0                      0                           0                 0                  266,150           0                266,150             266,150                   0                  266,150 60,049,554            0                   0                    266,150                      0   61,646,452
United Kingdom                   4,410,911           3,904,657              3,904,657                   1,351,081         1,583,739                2,008,501   3,963,383              1,755,553           1,894,603             233,807                1,923,922  3,718,234    3,904,657           3,963,383                  1,704,355              1,464,739   41,690,184
EU                               1,565,059                   0                      0                           0                 0                2,390,008   1,565,059              6,701,490           5,280,243           6,999,521                3,861,255  8,847,362            0           1,565,059                          0                      0   38,775,058
Finland                          3,828,954                   0                      0                           0                 0                  756,050     838,954                      0                   0             504,429                  765,050 30,000,000            0           1,063,525                    829,929                      0   38,586,890
Norway                           3,242,344             290,000                290,000                   2,088,000                 0                  101,414   3,343,758              2,858,906               8,700                   0                3,053,758  1,040,170            0             290,000                    290,000                      0   16,897,050
United States                    1,340,081             839,523                441,232                     274,312           320,853                  797,784     608,331                262,837             384,250             822,722                  828,818  4,070,677      632,351             986,605                    834,497                314,010   13,758,883
Singapore                                0                   0                      0                           0                 0                        0           0              2,531,294                   0                   0                  155,812  9,704,400            0             155,812                    311,625                      0   12,858,944
Israel                                   0                   0                      0                           0                 0                        0           0                      0                   0                   0                        0  9,491,092            0                   0                          0                      0    9,491,092
Spain                               71,354                   0                      0                      43,438                 0                  253,294     139,688                119,738             191,429                   0                  239,341  7,240,850            0              43,438                          0                 85,645    8,428,214
New Zealand                        746,886             652,809                      0                   1,701,956                 0                1,089,373     342,486                652,809             779,050                   0                  436,564          0      310,323                   0                          0                      0    6,712,255
Germany                                  0                   0                      0                           0            13,846                        0           0                      0              13,846                   0                  774,780  2,107,853            0                   0                          0              1,271,257    4,181,583

### 10. Total funding by sub-production pillar (2020-2025)

Total funding per `'Sub-production pillar'` value, across all AP pillars. Mutually exclusive rows
summing to the grand total, with `(no sub-pillar assigned)` shown explicitly since it is the
majority of funding (Cultivated has no sub-pillar scheme, and most Plant-based grants have none).

In [30]:
SUBPILLAR_COL = 'Sub-production pillar'
total_funding = df[FUNDING_COL].sum()

# Single-valued today, so a plain groupby is correct - no split_multi_value weighting needed.
# Guard in case curation starts packing two values into one cell.
_multi = df[SUBPILLAR_COL].dropna().astype(str).str.contains(r'[;,]')
if _multi.any():
    print(f"WARNING: {_multi.sum()} '{SUBPILLAR_COL}' cells contain ';' or ',' - this analysis "
          f"assumes one value per grant. Switch to split_multi_value before trusting these totals.")

subpillar = df[SUBPILLAR_COL].astype(str).str.strip().where(df[SUBPILLAR_COL].notna())
subpillar_np = df_np[SUBPILLAR_COL].astype(str).str.strip().where(df_np[SUBPILLAR_COL].notna())

by_subpillar = pd.DataFrame({
    'Grants': df.groupby(subpillar)[FUNDING_COL].size(),
    'Total funding (2020-2025, EUR)': df.groupby(subpillar)[FUNDING_COL].sum(),
})
# excl. non-profit column comes from 3b's df_np - run 3b first. Derived from df_np's own column,
# NOT by reindexing a df-based mask: 3b resets df_np's index, so the labels don't line up.
by_subpillar['Total funding excl. non-profit (EUR)'] = df_np.groupby(subpillar_np)[FUNDING_COL].sum()
by_subpillar['% of all funding'] = 100 * by_subpillar['Total funding (2020-2025, EUR)'] / total_funding
by_subpillar = by_subpillar.sort_values('Total funding (2020-2025, EUR)', ascending=False)
by_subpillar.index.name = SUBPILLAR_COL

_blank, _blank_np = df[SUBPILLAR_COL].isna(), df_np[SUBPILLAR_COL].isna()
by_subpillar.loc['(no sub-pillar assigned)'] = [
    int(_blank.sum()), df.loc[_blank, FUNDING_COL].sum(),
    df_np.loc[_blank_np, FUNDING_COL].sum(),
    100 * df.loc[_blank, FUNDING_COL].sum() / total_funding,
]
by_subpillar.loc['ALL GRANTS'] = [len(df), total_funding, df_np[FUNDING_COL].sum(), 100.0]

save(by_subpillar, '10a_funding_by_subpillar')
print(by_subpillar.to_string(float_format=lambda v: f'{v:,.1f}'))

Saved 10a_funding_by_subpillar -> data_output\analysis\260727_0922_10a_funding_by_subpillar.csv
                          Grants  Total funding (2020-2025, EUR)  Total funding excl. non-profit (EUR)  % of all funding
Sub-production pillar
Broad R&D                   98.0                   233,417,114.0                         205,197,114.0              12.4
BF                         232.0                   227,488,164.2                         206,856,495.1              12.1
Mixed                       69.0                   221,846,799.7                         178,011,891.7              11.8
PF                         124.0                    92,893,972.9                          83,186,966.9               4.9
TF                         107.0                    71,483,801.4                          62,743,398.7               3.8
Socioeconomic               62.0                    16,977,725.4                          16,893,425.4               0.9
Technical research          26.0                     9,636,317.6                           8,343,904.7               0.5
(no sub-pillar assigned) 1,704.0                 1,009,375,455.7                         873,212,662.9              53.6
ALL GRANTS               2,422.0                 1,883,119,351.0                       1,634,445,859.4             100.0

### 11. Fermentation-pillar funding by start year x sub-pillar (2020-2025)

Fermentation-pillar grants only, split by `BF` / `PF` / `Mixed`. By START year, same as 1a/2a.

In [33]:
ferment = df[df['AP pillar'] == 'Fermentation']

ferment_year_subpillar = ferment.pivot_table(
    index=SUBPILLAR_COL, columns='Year project started', values=FUNDING_COL, aggfunc='sum', fill_value=0
)
ferment_year_subpillar.columns = ferment_year_subpillar.columns.astype(int)
ferment_year_subpillar = ferment_year_subpillar[sorted(ferment_year_subpillar.columns)]
ferment_year_subpillar.loc['Total'] = ferment_year_subpillar.sum()

save(ferment_year_subpillar, '11_funding_fermentation_by_year_and_subpillar')
print(ferment_year_subpillar.to_string(float_format=lambda v: f'{v:,.0f}'))

# pivot_table drops rows with a blank sub-pillar, so the table total falls short of the pillar total.
_gap = ferment[ferment[SUBPILLAR_COL].isna()]
print(f"\nFermentation pillar total: EUR {ferment[FUNDING_COL].sum():,.0f}. Table covers "
      f"EUR {ferment_year_subpillar.loc['Total'].sum():,.0f}; {len(_gap)} grants "
      f"(EUR {_gap[FUNDING_COL].sum():,.0f}) have no sub-pillar and are excluded.")

Saved 11_funding_fermentation_by_year_and_subpillar -> data_output\analysis\260727_0922_11_funding_fermentation_by_year_and_subpillar.csv
Year project started        2020       2021       2022        2023        2024        2025
Sub-production pillar
BF                    10,304,279 25,600,180 38,092,226  56,856,521  17,766,953  78,868,006
Mixed                  9,940,951 14,324,124  2,573,474  41,001,060 115,445,366  38,561,825
PF                     1,506,957  2,744,946  6,454,392  18,389,218  32,023,500  31,774,959
Total                 21,752,187 42,669,250 47,120,092 116,246,798 165,235,818 149,204,791

Fermentation pillar total: EUR 543,477,406. Table covers EUR 542,228,937; 7 grants (EUR 1,248,469) have no sub-pillar and are excluded.

### 12. Funding by start year x AP pillar x country, for a fixed country set (2020-2025)

Same methodology and growth-rate formula as 2c/2d, with a (Country, AP pillar) row index instead of
region. Country set = EU-27 + Norway / UK / Switzerland (EU+), plus US, Canada, Australia,
New Zealand, Brazil, Israel, Japan, South Korea, Singapore, `Global`, and `EU` (supranational
EU-level funding, kept as its own row - it is the largest single funder value in the data).

Every requested country gets a row per pillar even at zero, so the row set is stable across reruns
and pastes into a fixed template. Nine EU-27 members currently have no funding at all
(Bulgaria, Cyprus, Greece, Hungary, Lithuania, Luxembourg, Malta, Romania, Slovenia), as does Italy.

In [35]:
from Funding_analysis_helpers import EU_27

# 'EU' = supranational EU-level funding, kept as its own row (not folded into the member states) -
# same treatment europe_tier_split gives it.
REPORT_COUNTRIES = sorted(EU_27) + [
    'Norway', 'United Kingdom', 'Switzerland',
    'United States', 'Canada', 'Australia', 'New Zealand', 'Brazil',
    'Israel', 'Japan', 'South Korea', 'Singapore',
    'EU', 'Global',
]
YEARS = list(range(2020, 2026))
AP_PILLARS = sorted(df['AP pillar'].dropna().unique())

_unknown = [c for c in REPORT_COUNTRIES if c not in set(country_split['Funder Country_split'])]
if _unknown:
    print(f"No funding found for: {_unknown} - kept as zero rows. Check spelling against "
          f"'Funder Country' if any of these were expected to have grants.")

country_pillar_year = country_split[country_split['Funder Country_split'].isin(REPORT_COUNTRIES)].pivot_table(
    index=['Funder Country_split', 'AP pillar'], columns='Year project started',
    values='weighted_funding', aggfunc='sum', fill_value=0,
)
country_pillar_year.columns = country_pillar_year.columns.astype(int)

# Reindex onto the full (country x pillar) grid so absent combinations read as 0 rather than vanishing.
_grid = pd.MultiIndex.from_product([REPORT_COUNTRIES, AP_PILLARS], names=['Funder Country', 'AP pillar'])
country_pillar_year = country_pillar_year.reindex(index=_grid, columns=YEARS, fill_value=0).fillna(0)
country_pillar_year['Total'] = country_pillar_year[YEARS].sum(axis=1)

save(country_pillar_year, '12a_funding_by_year_country_and_pillar')
print(country_pillar_year.to_string(float_format=lambda v: f'{v:,.0f}'))

# Growth rates, same formula as 2b/2d. yoy_growth needs the year columns only, not 'Total'.
growth_country_pillar = country_pillar_year[YEARS].apply(yoy_growth, axis=1)
growth_country_pillar['Average growth rate (2021-2025)'] = growth_country_pillar.iloc[:, 1:].mean(axis=1)
save(growth_country_pillar, '12b_growth_rates_by_country_and_pillar')
print()
print(growth_country_pillar.to_string(float_format=lambda v: f'{v:,.2f}'))

print(f"\nTable covers EUR {country_pillar_year['Total'].sum():,.0f} of "
      f"EUR {country_split['weighted_funding'].sum():,.0f} total "
      f"({100 * country_pillar_year['Total'].sum() / country_split['weighted_funding'].sum():.1f}%) - "
      f"the remainder sits in countries outside REPORT_COUNTRIES.")

No funding found for: ['Bulgaria', 'Cyprus', 'Greece', 'Hungary', 'Lithuania', 'Luxembourg', 'Malta', 'Romania', 'Slovenia'] - kept as zero rows. Check spelling against 'Funder Country' if any of these were expected to have grants.
Saved 12a_funding_by_year_country_and_pillar -> data_output\analysis\260727_0922_12a_funding_by_year_country_and_pillar.csv
Year project started               2020       2021       2022       2023       2024       2025       Total
Funder Country AP pillar
Austria        Cross-cutting          0          0          0          0          0    897,906     897,906
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0  3,200,000          0          0   3,200,000
               Plant-based            0          0    665,434          0          0    447,261   1,112,695
Belgium        Cross-cutting          0          0          0          0          0          0           0
               Cultivated     3,600,000          0          0          0          0          0   3,600,000
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0  5,995,271  6,249,971          0  12,245,242
Bulgaria       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Croatia        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based      131,239          0          0          0          0          0     131,239
Cyprus         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Czechia        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0     37,552          0          0    549,753          0     587,305
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0  1,140,119  2,591,386   3,731,505
Denmark        Cross-cutting          0  1,292,413  1,950,000  2,373,887    343,008    125,729   6,085,037
               Cultivated             0          0          0  2,890,231          0          0   2,890,231
               Fermentation     964,149  4,984,719  1,178,426 15,850,480 20,742,871 20,770,189  64,490,833
               Plant-based    3,657,491 15,852,462 35,317,239  8,232,533 13,916,103 15,712,683  92,688,512
Estonia        Cross-cutting          0          0          0          0     24,300          0      24,300
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0      6,000    759,846  1,817,000     19,950   2,602,796
               Plant-based    1,091,457     49,620    181,978     56,376    526,526     98,616   2,004,573
Finland        Cross-cutting     36,000     36,100  1,266,000     56,000 36,521,000    731,790  38,646,890
               Cultivated             0          0          0    489,900          0          0     489,900
               Fermentation     800,000    944,900  4,500,000          0  9,346,927 11,237,070  26,828,897
               Plant-based    2,436,000    735,814  2,416,526  4,393,000    917,070    900,000  11,798,410
France         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0  3,000,000          0   3,000,000
               Plant-based            0          0  3,302,803 22,943,999  2,340,000    785,011  29,371,813
Germany        Cross-cutting  2,273,642    549,500          0     45,645          0  1,312,796   4,181,583
               Cultivated     1,251,942    226,812  1,748,286  6,366,892          0          0   9,593,932
               Fermentation     934,702     57,525  1,244,760  2,530,964  1,882,916    969,440   7,620,307
               Plant-based    5,298,483  3,806,425  9,610,991 23,361,358 12,959,358  8,568,486  63,605,101
Greece         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Hungary        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Ireland        Cross-cutting          0          0          0    772,597          0          0     772,597
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based    3,000,000          0          0  2,173,310          0          0   5,173,310
Italy          Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Latvia         Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0     42,350          0      42,350
Lithuania      Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Luxembourg     Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Malta          Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Netherlands    Cross-cutting          0          0  1,596,898 60,000,000          0     49,554  61,646,452
               Cultivated             0          0  1,280,000  3,750,000  7,900,000  1,594,867  14,524,867
               Fermentation           0          0          0    720,194     49,978  1,534,979   2,305,151
               Plant-based      958,406  2,166,950  1,028,663    839,762  3,735,695  7,678,620  16,408,096
Poland         Cross-cutting          0    101,740          0          0          0          0     101,740
               Cultivated             0          0          0          0  4,189,125          0   4,189,125
               Fermentation           0          0          0    204,068          0          0     204,068
               Plant-based       44,629    124,586    344,609    449,758  9,120,000     48,300  10,131,883
Portugal       Cross-cutting          0          0          0          0          0  3,859,768   3,859,768
               Cultivated             0          0     45,427    497,610    164,000    300,989   1,008,026
               Fermentation           0          0    249,991     49,834          0     49,968     349,793
               Plant-based            0  1,194,205      4,000    799,552          0    299,561   2,297,318
Romania        Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Slovakia       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0    300,000     300,000
               Plant-based            0          0          0    211,169          0     26,002     237,171
Slovenia       Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0          0          0          0          0           0
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Spain          Cross-cutting    243,174    199,307    111,758  7,000,000    873,975          0   8,428,214
               Cultivated             0  5,521,700  3,615,350    154,515    909,026          0  10,200,591
               Fermentation     450,445  1,277,964    722,874    541,250    383,142    470,000   3,845,675
               Plant-based    1,261,850  3,679,976  4,342,395  1,159,682  2,308,725          0  12,752,628
Sweden         Cross-cutting          0    162,257          0    772,568    129,409          0   1,064,234
               Cultivated             0          0      1,287     27,300    226,318          0     254,905
               Fermentation     512,913    112,930  1,202,058  1,585,192    474,494  2,076,026   5,963,613
               Plant-based    9,088,049  7,002,557  5,028,372  5,554,098  7,855,104 10,824,758  45,352,938
Norway         Cross-cutting      8,700 12,475,794          0  2,020,313    304,243  2,088,000  16,897,050
               Cultivated             0          0          0          0          0  1,606,977   1,606,977
               Fermentation   8,963,974     43,500    442,830          0    323,647  1,048,349  10,822,300
               Plant-based    1,298,734 23,799,834    480,152    232,874    658,055  3,557,488  30,027,137
United Kingdom Cross-cutting          0    119,000  4,201,830 15,628,955 20,308,830  1,431,569  41,690,184
               Cultivated       772,680  3,952,365  3,275,443 11,071,815  6,078,099  2,396,823  27,547,224
               Fermentation     724,398    577,667  4,675,561  6,751,092 26,367,126  1,859,754  40,955,599
               Plant-based    1,647,560  2,914,392  4,910,908 15,095,069 19,049,004    741,803  44,358,736
Switzerland    Cross-cutting          0          0  1,721,954          0          0    941,414   2,663,368
               Cultivated             0    611,394          0  3,413,477    162,179          0   4,187,049
               Fermentation           0          0    462,352    328,447          0  2,148,038   2,938,837
               Plant-based    1,903,055  1,860,276  4,291,153  3,480,264  3,921,369  3,045,586  18,501,702
United States  Cross-cutting    241,358    260,526    312,888  3,218,605 85,825,457  4,848,948  94,707,783
               Cultivated     5,147,022 20,501,318  3,356,120  4,121,446  4,327,248  3,780,236  41,233,389
               Fermentation     905,398  4,370,162 12,176,573 39,742,145 62,654,125 14,279,317 134,127,718
               Plant-based    3,155,025  9,316,069 17,090,147  7,793,417  3,621,664  6,815,736  47,792,057
Canada         Cross-cutting     12,258     50,728     14,387    147,485     99,655      9,460     333,973
               Cultivated        41,060    213,229    143,290  7,586,393    244,293    978,700   9,206,964
               Fermentation     152,077    488,691     28,055    327,893    382,526          0   1,379,242
               Plant-based   23,258,275  8,874,597  5,491,080  5,279,657  6,212,966  2,776,056  51,892,631
Australia      Cross-cutting          0  3,134,400          0    318,232    127,953          0   3,580,585
               Cultivated        20,604          0    295,340          0          0          0     315,944
               Fermentation           0          0    681,710          0          0          0     681,710
               Plant-based            0  1,694,594    351,314    288,088          0    434,029   2,768,026
New Zealand    Cross-cutting  5,160,642          0          0          0          0  1,551,613   6,712,255
               Cultivated             0          0          0  1,074,661  4,880,269          0   5,954,930
               Fermentation           0          0          0          0          0  5,152,576   5,152,576
               Plant-based    1,686,976          0    181,995  6,230,613    569,765  1,515,250  10,184,599
Brazil         Cross-cutting          0          0          0    446,574          0          0     446,574
               Cultivated             0          0          0  1,027,311          0    414,400   1,441,711
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Israel         Cross-cutting          0  8,149,300          0  1,341,792          0          0   9,491,092
               Cultivated             0          0 16,662,060    474,160          0    373,006  17,509,226
               Fermentation           0          0          0    455,790          0          0     455,790
               Plant-based            0          0          0          0          0          0           0
Japan          Cross-cutting          0    727,925     23,097     68,165     78,601    170,541   1,068,329
               Cultivated        93,799          0    538,136 12,054,230    222,438     72,689  12,981,292
               Fermentation      32,524          0          0     12,497          0          0      45,021
               Plant-based    2,747,742     28,363    109,047     46,307    155,721    193,900   3,281,080
South Korea    Cross-cutting          0          0          0          0          0          0           0
               Cultivated             0          0 14,193,750          0  7,480,000  9,425,000  31,098,750
               Fermentation           0          0          0          0          0          0           0
               Plant-based            0          0          0          0          0          0           0
Singapore      Cross-cutting          0 10,327,650          0          0          0  2,531,294  12,858,944
               Cultivated             0 12,127,125          0    792,985          0  5,062,588  17,982,698
               Fermentation           0 19,268,250          0          0 10,209,040 10,125,176  39,602,466
               Plant-based            0 10,163,888          0          0          0  2,531,294  12,695,182
EU             Cross-cutting    293,854          0 26,973,875  3,498,858  1,008,950  6,999,521  38,775,058
               Cultivated     7,131,192  4,065,712  2,818,811  1,477,162 13,920,674  1,666,667  31,080,219
               Fermentation   7,311,607 10,542,943 19,128,777 42,806,039 27,602,026 77,950,678 185,342,069
               Plant-based   22,676,135 10,400,243 52,369,143 37,521,546 31,786,270 42,830,306 197,583,643
Global         Cross-cutting          0          0          0          0          0          0           0
               Cultivated       812,156    602,494    258,145    207,648          0          0   1,880,443
               Fermentation           0          0    425,000    238,000          0          0     663,000
               Plant-based      497,250          0    212,500     85,000          0          0     794,750
Saved 12b_growth_rates_by_country_and_pillar -> data_output\analysis\260727_0922_12b_growth_rates_by_country_and_pillar.csv

Year project started          2020     2021  2022   2023   2024  2025  Average growth rate (2021-2025)
Funder Country AP pillar
Austria        Cross-cutting   NaN      NaN   NaN    NaN    NaN   inf                              inf
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    inf  -1.00   NaN                              inf
               Plant-based     NaN      NaN   inf  -1.00    NaN   inf                              inf
Belgium        Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN    -1.00   NaN    NaN    NaN   NaN                            -1.00
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN      NaN   NaN    inf   0.04 -1.00                              inf
Bulgaria       Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN      NaN   NaN    NaN    NaN   NaN                              NaN
Croatia        Cross-cutting   NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Cultivated      NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Fermentation    NaN      NaN   NaN    NaN    NaN   NaN                              NaN
               Plant-based     NaN    -1.00   NaN    NaN    NaN   NaN                            -1.00

### 13. Research Question No. 18

Evaluate how public R&I grants act as a catalyst for private investment by correlating specific public grants to private investment data. This analysis aims to build on the previous section by describing the link between public support and downstream private capital investment and IP generation activity. Depending on data availability, it will also analyse the degree to which not receiving public funding support has been a hindrance to companies in relation to intellectual property generation and commercial activity.

In [41]:
# Read in private investment data that was collected by other GFI colleagues
# private investment was collected by year of deal
private2025 = pd.read_csv('data_output/private_investment_2025.csv')
private2024 = pd.read_csv('data_output/private_investment_2024.csv')
private2023 = pd.read_csv('data_output/private_investment_2023.csv')
private2022 = pd.read_csv('data_output/private_investment_2022.csv')
private2021 = pd.read_csv('data_output/private_investment_2021.csv')
private2020 = pd.read_csv('data_output/private_investment_2020.csv')

In [42]:
# combine all private investment tables in one
private = pd.concat([private2025, private2024, private2023, private2022, private2021, private2020])
private = private[private["Net0i Organisation ID"].notna()]
private["Net0i Organisation ID"] = private["Net0i Organisation ID"].astype(int)

In [43]:
# Check whether the names and organisation ID's match (= if one ID corresponds to one name only)
private.drop_duplicates(['Organisation name', 'Net0i Organisation ID'])['Net0i Organisation ID'].value_counts()

# after cleaning up some names, all ID's are unique except for two ID's that correspond to companies that changed their name
# Nutrumami -> SUMM Ingredients (ID: 153164); Re:Meat -> Curve (ID: 124873)

Net0i Organisation ID
153164    2
124873    2
31814     1
486       1
55931     1
         ..
179082    1
496       1
128227    1
43723     1
73048     1
Name: count, Length: 279, dtype: int64

In [20]:
df_np

,Title,Abstract,Original title,Database,Total amount,Gov & NP contribution,Currency,Total amount (USD),Gov & NP contribution (USD),Total amount (EUR),...,2028,2029,2030,2031,2032,2033,2034,2035,lrd_row_id,date_curated
0,"Precision Technology: Biotechnology, smart sen...",The project has three sub-goals:\n\nDeveloping...,NaN,airtable,64200000,64200000,NOK,7524240.0,7524240.0,5.585400e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,260727.0
1,National Alternative Proteins Innovation and K...,"To secure a continued supply of safe, tasty, ...",NAPIC: National Alternative Protein Innovation...,airtable,38000000,16001352,GBP,48859450.0,18697500.0,4.522000e+07,...,3173601.480,3173601.480,NaN,NaN,NaN,NaN,NaN,NaN,5,260727.0
2,Green technology for plant-based food (GreenPl...,To maintain national food self-sufficiency and...,GreenPlantFood - Green technology for plant-ba...,airtable,27600000,27600000,NOK,2604048.0,2604048.0,2.401200e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,260727.0
3,SYLPLANT,"Arbiom, an agricultural-biotech company develo...",NaN,airtable,23000000,14000000,EUR,25829000.0,15722000.0,2.300000e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,260727.0
4,University of Bath Cellular Agriculture Manufa...,Imagine being able to manufacture food anywher...,Cellular Agriculture Manufacturing Hub,airtable,21214469,12302109,GBP,26130285.0,15655848.0,2.524522e+07,...,1829938.714,1829938.714,1829938.714,NaN,NaN,NaN,NaN,NaN,10,260727.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2204,SBEP-IMPROVED VALORIZATION OF MARINE SOURCES &...,Impact-oriented utilization pathways for new s...,SBEP-IMPROVED VALORIZATION OF MARINE SOURCES &...,Dimensions,3419996,3419996,NOK,340451.0,340451.0,3.042428e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2205,Control and functionalization of protein nanof...,This research program seeks a better understan...,NaN,airtable,24000,24000,CAD,18200.0,18200.0,2.567660e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUAL_3,260727.0
2206,Control and functionalization of protein nanof...,This research program seeks a better understan...,NaN,airtable,24000,24000,CAD,18967.0,18967.0,1.520040e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUAL_4,260727.0
2207,Control and functionalization of protein nanof...,This research program seeks a better understan...,NaN,airtable,24000,24000,CAD,18275.0,18275.0,1.521576e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUAL_5,260727.0
2208,Control and functionalization of protein nanof...,This research program seeks a better understan...,NaN,airtable,24000,24000,CAD,17706.0,17706.0,1.521576e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUAL_6,260727.0

#### 13a. Normalise organisation names and generate match candidates

Matches **from** the curated private-investment company list **into** the funding data's
organisation text, rather than trying to resolve every funding org name into a canonical entity -
201 targeted lookups instead of ~1,200 messy names, and every candidate stays reviewable.

Matching and fractional weighting are deliberately decoupled: matching searches the *unsplit* text
(so a name shredded by a comma inside it is still found), while the recipient split is used only
for the 1/n denominator.

Tiers: `exact` (normalised equal, or equal ignoring spaces) and `contains` on a multi-token name
are auto-accepted; `contains` on a **single-token** name and anything `fuzzy` go to a review file.
Single-token names are the false-positive risk - 95 of the 201 companies have one-word names, and
e.g. `Multus` legitimately matches `Multus Biotechnology Limited` but not `Multus Media`.

The review file is written **without a run timestamp** so hand edits survive re-runs. Edit the
`accept` column (True/False) and re-run 13b to pick the decisions up.

In [55]:
import unicodedata
from rapidfuzz import fuzz

REVIEW_FILE = Path('data_output/company_match_review.csv')  # deliberately NOT timestamped
FUZZ_MIN = 88

# LEGAL FORMS ONLY. Descriptive words ('technologies', 'labs', 'group') are deliberately NOT
# stripped: removing them reduced 'Roslin Technologies' to the generic token 'roslin', which then
# matched 'Instytut Genetyki Roslin Polskiej Akademii Nauk'.
LEGAL_FORMS = (r'(ltd|limited|inc|incorporated|llc|plc|gmbh|mbh|ug|ag|bv|nv|ab|oyj|oy|as|asa|aps|'
               r'sa|sl|slu|srl|sas|sarl|spa|kg|kft|doo|ou|ehf|sia|pte|pty|co|corp|corporation|company)')


def normalise_org(name):
    """Lowercase, de-accent, drop parentheticals/punctuation, strip legal forms. '' if unusable."""
    if pd.isna(name):
        return ''
    s = str(name).replace('&amp;', '&').replace('&', ' and ')
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()  # 'Sophie’s' -> "sophie's"
    s = s.lower()
    s = re.sub(r'\(.*?\)', ' ', s)
    s = re.sub(r'[^a-z0-9]+', ' ', s)
    for _ in range(2):  # handles stacked forms like 'foo bv ltd'
        s = re.sub(rf'\b{LEGAL_FORMS}\b', ' ', s)
    s = re.sub(r'\bthe\b', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()


def _despace(s):
    return s.replace(' ', '')  # 'onego bio' == 'onegobio'


def split_collaborators(value):
    """Best-effort split of 'Collaborator institutions'. Delimiters are inconsistent (';' 109 rows,
    ',' 159, ' and ' 72, '&' 26) and commas also occur INSIDE names, so prefer ';' when present and
    only fall back to ','. Used for the 1/n denominator only - never for matching."""
    if pd.isna(value):
        return []
    t = str(value).replace('&amp;', '&')
    if ';' in t or '\n' in t:
        parts = re.split(r';|\n', t)
    elif ',' in t:
        parts = re.split(r',', t)
    else:
        parts = re.split(r'\s+and\s+|\s*/\s*', t)
    return [x.strip() for x in parts if x.strip()]


# --- recipients per grant, from df_np (non-profit funders already excluded) ---
# 'Multiple organisation recipients' is NOT used as a gate: it is 2,166 NaN / 133 No / 104 Yes plus
# ~19 rows holding country lists, and 396 grants list collaborators while it is not 'Yes'.
_recip_rows = []
for _idx, _r in df_np.iterrows():
    _pi = _r['PI organisation']
    _raw_collab = _r['Collaborator institutions']
    _recips = ([_pi] if pd.notna(_pi) else []) + split_collaborators(_raw_collab)
    # norm_blob is built from the UNSPLIT text on purpose - it is the fallback that catches a name
    # the split damaged, so it must not itself go through the split. Rejoining the split parts would
    # nearly work (delimiters collapse to spaces either way), but the ' and ' / '/' fallback branch
    # CONSUMES its delimiter: 'Flour Milling and Baking Research Association' loses its 'and', so a
    # company whose real name contains 'and' could not be recovered here. 6 grants differ.
    _blob_parts = ([str(_pi)] if pd.notna(_pi) else []) + ([str(_raw_collab)] if pd.notna(_raw_collab) else [])
    _recip_rows.append({
        'grant_idx': _idx,
        'recipients': _recips,
        'norm_recipients': [normalise_org(x) for x in _recips],
        'norm_blob': normalise_org(' ; '.join(_blob_parts)),
        'n_recipients': max(len(_recips), 1),
    })
grant_recipients = pd.DataFrame(_recip_rows)
print(f"{len(grant_recipients)} grants; {(grant_recipients['recipients'].map(len) > 0).sum()} name at "
      f"least one recipient. Recipients per grant: median "
      f"{int(grant_recipients['n_recipients'].median())}, max {grant_recipients['n_recipients'].max()}.")

# --- fuzzy engine: rapidfuzz if available, stdlib difflib otherwise (different scores, same tiers) ---

def _ratio(a, b): return fuzz.token_set_ratio(a, b)
FUZZ_ENGINE = 'rapidfuzz.token_set_ratio'

print(f'Fuzzy engine: {FUZZ_ENGINE}')

# --- company search list: EVERY name an ID has ever carried, not one row per ID ---
# Companies get renamed (e.g. 124873 Re:Meat -> Curve, 153164 Nutrumami -> SUMM Ingredients) and in
# both of those cases only the OLD name appears in the funding data - the grant predates the rename.
# Searching just the current name loses the match, so every (id, name) pair is searched and results
# attributed back to the id. 13b de-duplicates on (org_id, grant_idx), so an alias cannot double-count.
companies = (private[['Net0i Organisation ID', 'Organisation name']]
             .drop_duplicates()
             .rename(columns={'Net0i Organisation ID': 'org_id', 'Organisation name': 'org_name'}))
companies['org_norm'] = companies['org_name'].map(normalise_org)
companies['n_tokens'] = companies['org_norm'].str.split().str.len()
companies = (companies[companies['org_norm'] != '']
             .drop_duplicates(['org_id', 'org_norm']).reset_index(drop=True))
_n_ids = companies['org_id'].nunique()
_aliases = len(companies) - _n_ids
print(f"{_n_ids} private-investment companies searched under {len(companies)} name variants "
      f"({_aliases} renamed/alias); {(companies['n_tokens'] == 1).sum()} variants are single-token "
      f"(never auto-accepted).")

_cands = []
for _c in companies.itertuples(index=False):
    _cn, _cd = _c.org_norm, _despace(_c.org_norm)
    _pat = re.compile(rf'(?<![a-z0-9]){re.escape(_cn)}(?![a-z0-9])')
    for _g in grant_recipients.itertuples(index=False):
        _best = None
        for _rn, _raw in zip(_g.norm_recipients, _g.recipients):
            if not _rn:
                continue
            if _rn == _cn or _despace(_rn) == _cd:
                _best = ('exact', 100.0, _raw)
                break
            if _best is None and _pat.search(_rn):
                _best = ('contains', 100.0, _raw)
        if _best is None and _pat.search(_g.norm_blob):
            # name survived only in the unsplit text - a comma inside it shredded the split
            _best = ('contains_blob', 100.0, ' ; '.join(str(x) for x in _g.recipients)[:140])
        if _best is None:
            for _rn, _raw in zip(_g.norm_recipients, _g.recipients):
                if not _rn:
                    continue
                _sc = _ratio(_cn, _rn)
                if _sc >= FUZZ_MIN and (_best is None or _sc > _best[1]):
                    _best = ('fuzzy', _sc, _raw)
        if _best:
            _tier, _score, _matched = _best
            _cands.append({
                'org_id': _c.org_id, 'org_name': _c.org_name, 'org_norm': _cn,
                'n_tokens': _c.n_tokens, 'grant_idx': _g.grant_idx, 'tier': _tier,
                'score': round(_score, 1), 'matched_text': _matched,
                'n_recipients': _g.n_recipients,
                'accept': _tier == 'exact' or (_tier in ('contains', 'contains_blob') and _c.n_tokens >= 2),
            })

match_candidates = pd.DataFrame(_cands)
match_candidates['needs_review'] = ~match_candidates['accept']
print()
print(match_candidates.groupby(['tier', 'accept']).size().to_string())
print(f"\n{match_candidates['org_id'].nunique()} of {_n_ids} companies have at least one "
      f"candidate; {match_candidates.loc[match_candidates['accept'], 'org_id'].nunique()} are "
      f"auto-accepted. {int(match_candidates['needs_review'].sum())} pairs need review.")

if REVIEW_FILE.exists():
    print(f"\n{REVIEW_FILE} already exists - NOT overwritten. Delete it to regenerate from scratch.")
else:
    match_candidates.to_csv(REVIEW_FILE, index=False)
    print(f"\nWrote {REVIEW_FILE}. Edit the 'accept' column for the rows where needs_review is True, "
          f"then re-run 13b.")

print()
print(match_candidates[match_candidates['needs_review']]
      [['org_name', 'n_tokens', 'tier', 'score', 'matched_text']].to_string())

2209 grants; 2070 name at least one recipient. Recipients per grant: median 1, max 159.
Fuzzy engine: rapidfuzz.token_set_ratio
279 private-investment companies searched under 281 name variants (2 renamed/alias); 129 variants are single-token (never auto-accepted).

tier      accept
contains  False      28
          True       15
exact     True      169
fuzzy     False      26

105 of 279 companies have at least one candidate; 85 are auto-accepted. 54 pairs need review.

Wrote data_output\company_match_review.csv. Edit the 'accept' column for the rows where needs_review is True, then re-run 13b.

                       org_name  n_tokens      tier  score                                                                                                                                                                                            matched_text
26          Roslin Technologies         2     fuzzy  100.0                                                                                                                                                                                                  Roslin
32                       Mewery         1  contains  100.0                                                                                                                                                                                           Mewery s.r.o.
33         Finnish Food Factory         3     fuzzy  100.0                                                                                                                                                                                                   "Food
34                 Vanetta Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food
35                     Uncommon         1  contains  100.0                                                                                                                                                                                        Uncommon Bio Ltd
40                  Quorn Foods         2     fuzzy  100.0                                                                                                                                                                                                   Quorn
41                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
42                       Multus         1  contains  100.0                                                                                                                                                                                            Multus Media
43                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
44                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
45                       Multus         1  contains  100.0                                                                                                                                                                            MULTUS BIOTECHNOLOGY LIMITED
46                       Multus         1  contains  100.0                                                                                                                                                                            Multus Biotechnology Limited
47                       Multus         1  contains  100.0                                                                                                                                               University College London; Multus\n Biotechnology Limited
48                       Multus         1  contains  100.0                                                                                                                                                                                Multus Biotechnology Ltd
50                       Multus         1  contains  100.0                                                                                                                                                                                Multus Biotechnology Ltd
60             Clean Food Group         3     fuzzy  100.0                                                                                                                                                                                                   "Food
66                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
67                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
68                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
69                 Planet Foods         2     fuzzy   88.0                                                                                                                                                                                        Planted Foods AG
74                    Poseidona         1     fuzzy   90.0                                                                                                                                                                                          POSEIDONADA SL
90                        Formo         1  contains  100.0                                                                                                                                                                                          Formo Bio GmbH
91                        Formo         1  contains  100.0                                                                                                                                                                                        Formo Foods GmbH
102                  Greenforce         1  contains  100.0                                                                                                                                                                               GREENFORCE FUTURE FOOD AG
112              Ironic Biotech         2     fuzzy  100.0                                                                                                                                                                                               IRONIC AB
117                    Novameat         1  contains  100.0                                                                                                                                                                                        NOVAMEAT TECH SL
119                    Novameat         1  contains  100.0                                                                                                                                 Hooked Foods AB / Novameat / Sunny side / Solymeyea / ITC MURSKA SOBOTA
120                    Novameat         1  contains  100.0                                                                                                                                                                                     NOVAMEAT TECH, S.L.
122  The Mediterranean Food Lab         3     fuzzy  100.0                                                                                                                                                                                                   "Food
126                    Meatable         1  contains  100.0  National University of Singapore, A*STAR, Singapore Food Agency, TissUse, United States Food and Drug Administration (US-FDA), Meatable, Vireo Advisors, Asia-Pacific Society for Cellular Agriculture
129                   Planetary         1     fuzzy   90.0                                                                                                                                                                                         PlanetDairy ApS
130                   Planetary         1     fuzzy   90.0                                                                                                                                                                                         PlanetDairy ApS
131               Innocent Meat         2     fuzzy  100.0                                                                                                                                                                                            Innocent Ltd
134               Innocent Meat         2     fuzzy  100.0                                                                                                                                                                                        INNOCENT LIMITED
135                   Cultimate         1  contains  100.0                                                                                                                                                                                      CULTIMATE FOODS UG
139            The Very Food Co         2     fuzzy  100.0                                                                                                                                                                                                   "Food
143                       Vacka         1  contains  100.0                                                                                                                                                                                       VACKA QUESERIA SL
149                      Innomy         1  contains  100.0                                                                                                                                                                                       INNOMY BIOTECH SL
151                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
152                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
153                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
154                     Planted         1  contains  100.0                                                                                                                                                                                        Planted Foods AG
167                  Renew Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food
195                   Havredals         1  contains  100.0                                                                                                                                                                                 Havredals Biodevelop Ab
197                BLUU Seafood         2     fuzzy  100.0                                                                                                                                                                                               Bluu GmbH
198                BLUU Seafood         2     fuzzy  100.0                                                                                                                                                                                               Bluu GmbH
200        The Vegan Food Group         3     fuzzy  100.0                                                                                                                                                                                                   "Food
201                       Oatly         1  contains  100.0                                                                                                                                                                                                Oatly UK
202                       Oatly         1  contains  100.0                                                                                                                                                                                                Oatly UK
204                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                          Matr Foods ApS
205                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                              Matr Foods
206                  Mati Foods         2     fuzzy   90.0                                                                                                                                                                                          Matr Foods ApS
226               BioTech Foods         2     fuzzy  100.0                                                                                                                                                              NEW WAVE BIOTECH LTD; FORMIDABLE FOODS LTD
234                  Gosh! Food         2     fuzzy  100.0                                                                                                                                                                                                   "Food

#### 13b. Public funding per matched company, by year

Applies the accepted matches with fractional counting: a grant's amount is split evenly across its
recipients (`1 / n_recipients`), and the matched company takes one share. If a company matched a
grant more than once (e.g. named as both PI and collaborator) it is de-duplicated to one share.

Reads `company_match_review.csv` if it exists so hand decisions win; otherwise falls back to the
auto-accepted tiers.

In [56]:
if REVIEW_FILE.exists():
    _decisions = pd.read_csv(REVIEW_FILE)
    _decisions['accept'] = _decisions['accept'].astype(str).str.strip().str.lower().isin(['true', '1', 'yes'])
    print(f'Using hand-reviewed decisions from {REVIEW_FILE}.')
else:
    _decisions = match_candidates.copy()
    print('No review file found - using auto-accepted tiers only.')

# Canonical name per Net0i ID, taken from the most recent deal. Two IDs carry two names because the
# company was renamed (Re:Meat -> Curve, Nutrumami -> SUMM Ingredients), so org_id is the ONLY safe
# join key - joining on the name as well would split those companies into separate rows.
ORG_NAME = (private.sort_values('Deal year')
            .drop_duplicates('Net0i Organisation ID', keep='last')
            .set_index('Net0i Organisation ID')['Organisation name'])


def _org_attribute(column):
    """Per-COMPANY lookup of a company-level attribute, from the most recent deal that records one.
    HQ country/continent belong to the company, not to a (company, year) pair, so a year in which a
    company has public funding but no private deal must still carry them - carrying them through the
    groupby alone leaves those rows NA (e.g. Bruno Cell: Italy on its 2020 deal, blank on its 2024
    grant-only row)."""
    have = private[private[column].notna()]
    return (have.sort_values('Deal year')
            .drop_duplicates('Net0i Organisation ID', keep='last')
            .set_index('Net0i Organisation ID')[column])


ORG_COUNTRY = _org_attribute('Organisation HQ country')
ORG_CONTINENT = _org_attribute('Organisation continent')

accepted = _decisions[_decisions['accept']].copy()
# One share per (company, grant): a company named as both PI and collaborator must not double-count.
accepted = accepted.drop_duplicates(['org_id', 'grant_idx'])
print(f"{len(accepted)} accepted (company, grant) pairs covering "
      f"{accepted['org_id'].nunique()} companies and {accepted['grant_idx'].nunique()} grants.")

_grant_cols = df_np[[FUNDING_COL, 'Year project started']].copy()
public_matched = accepted.merge(_grant_cols, left_on='grant_idx', right_index=True, how='left')
public_matched['company_share_eur'] = public_matched[FUNDING_COL] / public_matched['n_recipients']
public_matched['Year'] = public_matched['Year project started'].astype(int)

public_by_company_year = (public_matched.groupby(['org_id', 'Year'])
                          .agg(public_funding_eur=('company_share_eur', 'sum'),
                               grants=('grant_idx', 'nunique'))
                          .reset_index())
print(f"\nPublic funding attributed to matched companies: "
      f"EUR {public_by_company_year['public_funding_eur'].sum():,.0f} "
      f"({100 * public_by_company_year['public_funding_eur'].sum() / df_np[FUNDING_COL].sum():.1f}% of df_np).")
print(public_by_company_year.assign(org_name=lambda d: d['org_id'].map(ORG_NAME))
      .sort_values('public_funding_eur', ascending=False).head(15).to_string(index=False))

Using hand-reviewed decisions from data_output\company_match_review.csv.
222 accepted (company, grant) pairs covering 98 companies and 181 grants.

Public funding attributed to matched companies: EUR 136,654,988 (8.4% of df_np).
 org_id  Year  public_funding_eur  grants                     org_name
  93799  2025        1.279995e+07       3                  Solar Foods
  18170  2024        7.600000e+06       1                     Meatable
  93799  2023        5.338836e+06       2                  Solar Foods
  56928  2022        4.615091e+06       2                    Onego Bio
  29755  2023        4.408183e+06       6                       Multus
 165558  2024        4.140000e+06       2                      Labfarm
   8777  2022        3.521315e+06       3                BioTech Foods
   8777  2020        3.200972e+06       2                BioTech Foods
  56605  2024        3.024694e+06       2                  Melt&Marble
  88542  2024        3.000000e+06       1             Standing Ovation
  40415  2025        2.531294e+06       1 Cellular Agriculture Limited
  41778  2020        2.500000e+06       1                 ORF Genetics
  56928  2025        2.499999e+06       1                    Onego Bio
  56605  2025        2.485840e+06       1                  Melt&Marble
 124762  2024        2.441250e+06       1                       Millow

In [47]:
public_by_company_year

     org_id  Year  public_funding_eur  grants
0       486  2021        3.977884e+05       1
1       486  2022        2.853573e+05       1
2       486  2023        1.000000e+06       1
3       489  2020        1.154560e+05       1
4       489  2021        1.250000e+05       1
..      ...   ...                 ...     ...
160  124873  2023        2.730000e+04       1
161  127895  2024        4.100000e+04       1
162  153164  2025        1.011261e+05       1
163  153339  2024        2.730000e+04       1
164  165558  2024        4.140000e+06       2

[165 rows x 4 columns]

#### 13c. Public vs private investment by company and year

Private deal amounts are USD; converted to EUR with a year-end rate per deal year (same
Frankfurter source as 3a). Deals with no recorded amount are counted in `deals` but contribute 0 to
`private_investment_eur` - check the coverage line before using the ratio.

Rows are the union of (company, year) seen in either dataset, so a company with public funding but
no private deal that year appears with a zero, and vice versa.

In [57]:
# --- private side: USD -> EUR per deal year ---
private_deals = private.copy()
def _to_number(series):
    return pd.to_numeric(series.astype(str).str.replace(',', '', regex=False), errors='coerce')

private_deals['deal_amount_usd'] = _to_number(private_deals['Deal amount USD'])
private_deals['deal_amount_orig'] = _to_number(private_deals['Deal amount original currency'])
private_deals['Year'] = private_deals['Deal year'].astype(int)

# A deal already denominated in EUR is taken at its ORIGINAL amount - no conversion. The vendor's
# USD figure was converted at the deal-date rate (implied USD/EUR ranges 1.09-1.22 within 2020
# alone), so round-tripping it back through one year-end rate would inject error into a number that
# is already exact. Everything else converts from USD at a year-end rate, as elsewhere in this
# notebook.
_orig_ccy = private_deals['Deal original currency'].astype(str).str.strip().str.upper()
_is_eur = _orig_ccy.eq('EUR') & private_deals['deal_amount_orig'].notna()

_rates = {int(y): fetch_usd_to_eur_rate(f'{int(y)}-12-29') for y in sorted(private_deals['Year'].unique())}
print('USD->EUR year-end rates (used only for non-EUR deals):', _rates)

private_deals['deal_amount_eur'] = np.where(
    _is_eur,
    private_deals['deal_amount_orig'],
    private_deals['deal_amount_usd'] * private_deals['Year'].map(_rates),
)
private_deals['amount_source'] = np.where(
    _is_eur, 'original EUR',
    np.where(private_deals['deal_amount_usd'].notna(), 'converted from USD', 'no amount'))

print(private_deals['amount_source'].value_counts().to_string())
_missing = (private_deals['amount_source'] == 'no amount').sum()
print(f"{_missing} of {len(private_deals)} deals ({100 * _missing / len(private_deals):.0f}%) have no "
      f"recorded amount and contribute 0 EUR - treat the ratio as a lower bound on private capital.")

private_by_company_year = (private_deals.groupby(['Net0i Organisation ID', 'Year', 'Organisation HQ country', 'Organisation continent'])
                           .agg(private_investment_eur=('deal_amount_eur', 'sum'),
                                deals=('Net0i Organisation ID', 'size'),
                                deals_with_amount=('deal_amount_eur', 'count'))
                           .reset_index()
                           .rename(columns={'Net0i Organisation ID': 'org_id', 
                                            'Organisation HQ country': 'country',
                                            'Organisation continent': 'continent'}))

# Outer join on org_id + Year ONLY (see ORG_NAME note in 13b), so public-only and private-only
# (company, year) rows both survive; the name is attached afterwards.
public_vs_private = (public_by_company_year
                     .merge(private_by_company_year, on=['org_id', 'Year'], how='outer')
                     .fillna({'public_funding_eur': 0, 'grants': 0,
                              'private_investment_eur': 0, 'deals': 0, 'deals_with_amount': 0}))
public_vs_private.insert(1, 'org_name', public_vs_private['org_id'].map(ORG_NAME))
# Backfill company-level attributes on rows that came only from the public side (no deal that year).
for _col, _lookup in (('country', ORG_COUNTRY), ('continent', ORG_CONTINENT)):
    _before = public_vs_private[_col].isna().sum()
    public_vs_private[_col] = public_vs_private[_col].fillna(public_vs_private['org_id'].map(_lookup))
    _after = public_vs_private[_col].isna().sum()
    print(f"{_col}: filled {_before - _after} of {_before} blank rows from the company's other rows"
          f"{f'; {_after} still blank' if _after else ''}.")
public_vs_private[['grants', 'deals', 'deals_with_amount']] = \
    public_vs_private[['grants', 'deals', 'deals_with_amount']].astype(int)
public_vs_private = public_vs_private.sort_values(['org_name', 'Year']).reset_index(drop=True)

assert public_vs_private['org_name'].notna().all(), 'org_id present in funding matches but not in private data'
assert not public_vs_private.duplicated(['org_id', 'Year']).any(), 'duplicate (company, year) rows'

save(public_vs_private, 'Q18_public_vs_private_by_company_and_year', index=False)
print()
print(public_vs_private.to_string(index=False, float_format=lambda v: f'{v:,.0f}'))

_yr = public_vs_private.groupby('Year')[['public_funding_eur', 'private_investment_eur']].sum()
_yr['private_per_public_eur'] = _yr['private_investment_eur'] / _yr['public_funding_eur']
print()
_pub_yrs = sorted(public_by_company_year['Year'].unique())
_prv_yrs = sorted(private_by_company_year['Year'].unique())
print(f'Year totals across matched companies. NOT a causal ratio - public and private are')
print(f'contemporaneous here, with no lag applied. Public years {_pub_yrs[0]}-{_pub_yrs[-1]}, '
      f'private years {_prv_yrs[0]}-{_prv_yrs[-1]};')
print(f'any year present in only one of the two gives a meaningless ratio.')
print(_yr.to_string(float_format=lambda v: f'{v:,.2f}'))

USD->EUR year-end rates (used only for non-EUR deals): {2020: 0.81573, 2021: 0.88472, 2022: 0.93906, 2023: 0.90498, 2024: 0.95831, 2025: 0.84991}
amount_source
no amount             468
original EUR          347
converted from USD    275
468 of 1090 deals (43%) have no recorded amount and contribute 0 EUR - treat the ratio as a lower bound on private capital.
country: filled 44 of 44 blank rows from the company's other rows.
continent: filled 44 of 44 blank rows from the company's other rows.
Saved Q18_public_vs_private_by_company_and_year -> data_output\analysis\260727_0922_Q18_public_vs_private_by_company_and_year.csv

 org_id                       org_name  Year  public_funding_eur  grants        country continent  private_investment_eur  deals  deals_with_amount
  68536                       21St.Bio  2021                   0       0        Denmark    Europe              86,000,000      1                  1
 179045                          5Yes!  2021                   0       0         Russia    Europe                       0      1                  0
 179046                            Aak  2021                   0       0         Sweden    Europe             400,000,000      1                  1
 179046                            Aak  2022                   0       0         Sweden    Europe             253,990,741      3                  3
  42893                        Aberyne  2022                   0       0         France    Europe                       0      1                  0
  88658                    Adamo Foods  2022             389,989       1 United Kingdom    Europe                 950,713      3                  2
  88658                    Adamo Foods  2023             507,572       2 United Kingdom    Europe               2,495,281      6                  3
  88658                    Adamo Foods  2024           1,729,803       2 United Kingdom    Europe               2,466,864      2                  1
  88658                    Adamo Foods  2025             266,423       1 United Kingdom    Europe                 359,813      2                  1
  97369                            Aio  2022                   0       0        Estonia    Europe                 210,000      3                  2
  97369                            Aio  2023                   0       0        Estonia    Europe               1,180,000      4                  3
  97369                            Aio  2024                   0       0        Estonia    Europe              12,500,000      6                  4
  97369                            Aio  2025                   0       0        Estonia    Europe               2,200,000      2                  2
  31768                         Algama  2020                   0       0         France    Europe                       0      1                  0
  31768                         Algama  2021           1,429,699       2         France    Europe               2,000,000      2                  1
  31768                         Algama  2023                   0       0         France    Europe              13,000,000      1                  1
 110921                      Alt Atlas  2022                   0       0 United Kingdom    Europe                       0      2                  0
 110921                      Alt Atlas  2023                   0       0 United Kingdom    Europe                       0      2                  0
 111102        Apollo Roslinny Qurczak  2020                   0       0         Poland    Europe                       0      1                  0
 110927                         Arivia  2020                   0       0         Greece    Europe             500,000,000      1                  1
  57032                         Arkeon  2022                   0       0        Austria    Europe               9,756,240      2                  2
  57032                         Arkeon  2023                   0       0        Austria    Europe               2,750,000      1                  1
 179066                    Awevo Foods  2023                   0       0          Spain    Europe                       0      1                  0
  41330                   BLUU Seafood  2021                   0       0        Germany    Europe               7,000,000      2                  1
  41330                   BLUU Seafood  2023           1,746,639       4        Germany    Europe              16,000,000      1                  1
  55628                      Bene Meat  2023                   0       0 Czech Republic    Europe                       0      1                  0
  39666                      BettaF!sh  2020                   0       0        Germany    Europe                       0      1                  0
  39666                      BettaF!sh  2021                   0       0        Germany    Europe                       0      2                  0
  39666                      BettaF!sh  2023                   0       0        Germany    Europe                       0      1                  0
  39666                      BettaF!sh  2024             248,563       1        Germany    Europe                       0      4                  0
  39666                      BettaF!sh  2025                   0       0        Germany    Europe                 248,562      2                  1
  31611                   Better Dairy  2020                   0       0 United Kingdom    Europe               1,774,498      3                  1
  31611                   Better Dairy  2022                   0       0 United Kingdom    Europe              20,683,089      1                  1
  31611                   Better Dairy  2024             737,948       3 United Kingdom    Europe                       0      1                  0
 109256         BioCraft Pet Nutrition  2021                   0       0        Austria    Europe                       0      1                  0
 133326                         BioGNR  2022                   0       0      Lithuania    Europe                  20,000      1                  1
   8777                  BioTech Foods  2020           3,200,972       2          Spain    Europe               1,906,961      1                  1
   8777                  BioTech Foods  2021             649,478       2          Spain    Europe              41,200,000      2                  2
   8777                  BioTech Foods  2022           3,521,315       3          Spain    Europe                 753,000      1                  1
   8777                  BioTech Foods  2023              71,820       1          Spain    Europe                       0      0                  0
   8777                  BioTech Foods  2024             909,026       1          Spain    Europe                       0      0                  0
 110938                         Biolab  2025                   0       0          Italy    Europe                       0      1                  0
 101359                         Bluana  2022                   0       0        Romania    Europe                 317,382      4                  2
 101359                         Bluana  2023                   0       0        Romania    Europe                       0      2                  0
 101359                         Bluana  2024                   0       0        Romania    Europe                 100,000      2                  2
 101359                         Bluana  2025                   0       0        Romania    Europe                       0      2                  0
  42545                      Blue Farm  2020                   0       0        Germany    Europe                       0      1                  0
  42545                      Blue Farm  2021                   0       0        Germany    Europe                       0      2                  0
  42545                      Blue Farm  2022                   0       0        Germany    Europe               3,000,000      1                  1
  42545                      Blue Farm  2023                   0       0        Germany    Europe                       0      1                  0
  42545                      Blue Farm  2025                   0       0        Germany    Europe               1,334,070      1                  1
 110942                   Bolder Foods  2022                   0       0        Belgium    Europe                       0      1                  0
 110942                   Bolder Foods  2023                   0       0        Belgium    Europe                       0      1                  0
  60154                     Bon Vivant  2022                   0       0         France    Europe               5,500,000      2                  2
  60154                     Bon Vivant  2023                   0       0         France    Europe              15,000,000      1                  1
  60154                     Bon Vivant  2024                   0       0         France    Europe              10,000,000      6                  2
  55667                   Bosque Foods  2021                   0       0        Germany    Europe                 442,360      3                  1
  55667                   Bosque Foods  2022                   0       0        Germany    Europe               2,817,180      2                  1
  55667                   Bosque Foods  2023             460,573       1        Germany    Europe                   5,000      2                  1
  55667                   Bosque Foods  2024                   0       0        Germany    Europe                       0      2                  0
 192677                     Brew Bites  2025                   0       0        Germany    Europe                 254,973      2                  1
  72243                 Bright Biotech  2021                   0       0 United Kingdom    Europe                  12,452      2                  1
  72243                 Bright Biotech  2022                   0       0 United Kingdom    Europe               6,187,034      3                  2
  72243                 Bright Biotech  2025                   0       0 United Kingdom    Europe               1,143,692      1                  1
  26553                     Bruno Cell  2020                   0       0          Italy    Europe                       0      1                  0
  26553                     Bruno Cell  2024             218,732       1          Italy    Europe                       0      0                  0
 179082                   Bunte Burger  2020                   0       0        Germany    Europe                       0      1                  0
  31823              Bute Island Foods  2021                   0       0 United Kingdom    Europe             135,738,467      1                  1
  84466                   Calidris Bio  2022             292,675       1        Belgium    Europe                       0      1                  0
  84466                   Calidris Bio  2023             107,115       1        Belgium    Europe                       0      0                  0
 172465                      Catchfree  2023                   0       0    Switzerland    Europe                  34,274      2                  2
 172465                      Catchfree  2024                   0       0    Switzerland    Europe                       0      2                  0
 172465                      Catchfree  2025                   0       0    Switzerland    Europe               1,247,745      2                  2
  45908                     Cell Craft  2020                   0       0 United Kingdom    Europe                       0      1                  0
  45908                     Cell Craft  2021                   0       0 United Kingdom    Europe                 176,944      2                  1
  45908                     Cell Craft  2023             193,375       1 United Kingdom    Europe                 504,270      2                  1
  45908                     Cell Craft  2024             415,970       1 United Kingdom    Europe                 423,131      1                  1
 127895                      Cell4Food  2022                   0       0       Portugal    Europe                       0      1                  0
 127895                      Cell4Food  2024              41,000       1       Portugal    Europe                       0      2                  0
 127895                      Cell4Food  2025                   0       0       Portugal    Europe               1,500,000      3                  1
 110949                        CellRev  2020                   0       0 United Kingdom    Europe                  90,862      1                  1
 110949                        CellRev  2021                   0       0 United Kingdom    Europe               1,227,445      2                  1
 110949                        CellRev  2022                   0       0 United Kingdom    Europe               2,223,977      2                  1
 110949                        CellRev  2024                   0       0 United Kingdom    Europe                       0      1                  0
  40415   Cellular Agriculture Limited  2020              29,750       1 United Kingdom    Europe                  44,865      1                  1
  40415   Cellular Agriculture Limited  2021                   0       0 United Kingdom    Europe                 176,944      2                  2
  40415   Cellular Agriculture Limited  2022              56,828       3 United Kingdom    Europe                       0      1                  0
  40415   Cellular Agriculture Limited  2023           2,252,794       4 United Kingdom    Europe                 794,868      2                  2
  40415   Cellular Agriculture Limited  2024             218,732       1 United Kingdom    Europe                       0      0                  0
  40415   Cellular Agriculture Limited  2025           2,531,294       1 United Kingdom    Europe                       0      0                  0
  73048                    Chunk Foods  2020                   0       0         Turkey    Europe                       0      1                  0
  89432               Clean Food Group  2022                   0       0 United Kingdom    Europe               1,855,290      2                  1
  89432               Clean Food Group  2023           1,103,369       2 United Kingdom    Europe               3,253,976      2                  2
  89432               Clean Food Group  2024                   0       0 United Kingdom    Europe               3,050,278      2                  1
  89432               Clean Food Group  2025                   0       0 United Kingdom    Europe                       0      1                  0
  47781          Cocuus System Iberica  2021                   0       0          Spain    Europe                       0      1                  0
  47781          Cocuus System Iberica  2022             381,845       1          Spain    Europe               2,500,000      1                  1
 103324                Connectomix Bio  2022                   0       0     Luxembourg    Europe                       0      1                  0
   8746                    Cubiq Foods  2020                   0       0          Spain    Europe               5,000,000      1                  1
   8746                    Cubiq Foods  2022           1,011,206       1          Spain    Europe               5,750,000      1                  1
   8746                    Cubiq Foods  2023                   0       0          Spain    Europe               2,262,450      1                  1
  88766                      Cultimate  2022                   0       0        Germany    Europe                 900,000      4                  2
  88766                      Cultimate  2023                   0       0        Germany    Europe                       0      2                  0
  88766                      Cultimate  2024             218,732       1        Germany    Europe               4,600,000      2                  2
  84645         Cultivated Biosciences  2021                   0       0    Switzerland    Europe                   9,643      3                  1
  84645         Cultivated Biosciences  2022                   0       0    Switzerland    Europe               1,641,067      5                  5
  84645         Cultivated Biosciences  2023                   0       0    Switzerland    Europe                       0      2                  0
  84645         Cultivated Biosciences  2024                   0       0    Switzerland    Europe               9,583,100      6                  2
 124609                 Cultured Foods  2021             216,485       1         Poland    Europe                       0      0                  0
 124609                 Cultured Foods  2023                   0       0         Poland    Europe                 484,164      1                  1
 124609                 Cultured Foods  2024             119,759       1         Poland    Europe                       0      0                  0
 124873                          Curve  2023              27,300       1         Sweden    Europe                 284,042      3                  2
 124873                          Curve  2024                   0       0         Sweden    Europe                 322,742     10                  4
 124873                          Curve  2025                   0       0         Sweden    Europe               1,001,254      2                  2
  30602                           DRYK  2021                   0       0        Denmark    Europe                       0      1                  0
  30602                           DRYK  2022                   0       0        Denmark    Europe                       0      1                  0
 113569                   DUG Foodtech  2020                   0       0         Sweden    Europe                       0      1                  0
 113569                   DUG Foodtech  2022                   0       0         Sweden    Europe               1,497,825      1                  1
 113569                   DUG Foodtech  2023                   0       0         Sweden    Europe               1,487,359      1                  1
 113569                   DUG Foodtech  2024                   0       0         Sweden    Europe                 324,208      2                  2
  39907             Devon Garden Foods  2020                   0       0 United Kingdom    Europe                  20,000      1                  1
  31884                   Dr. Mannah's  2023                   0       0        Germany    Europe                       0      1                  0
 124265                      Dreamfarm  2023                   0       0          Italy    Europe               5,000,000      1                  1
  17980                         DryGro  2020                   0       0 United Kingdom    Europe               3,833,931      1                  1
  17980                         DryGro  2021                   0       0 United Kingdom    Europe               1,431,074      1                  1
 179099 Dutch Structuring Technologies  2023                   0       0    Netherlands    Europe                       0      1                  0
  33917              Dutch Weed Burger  2021                   0       0    Netherlands    Europe                       0      1                  0
 113282                       Econutri  2023                   0       0        Austria    Europe                 100,000      1                  1
 113282                       Econutri  2024                   0       0        Austria    Europe                       0      2                  0

In [58]:
public_vs_private

,org_id,org_name,Year,public_funding_eur,grants,country,continent,private_investment_eur,deals,deals_with_amount
0,68536,21St.Bio,2021,0.0,0,Denmark,Europe,8.600000e+07,1,1
1,179045,5Yes!,2021,0.0,0,Russia,Europe,0.000000e+00,1,0
2,179046,Aak,2021,0.0,0,Sweden,Europe,4.000000e+08,1,1
3,179046,Aak,2022,0.0,0,Sweden,Europe,2.539907e+08,3,3
4,42893,Aberyne,2022,0.0,0,France,Europe,0.000000e+00,1,0
...,...,...,...,...,...,...,...,...,...,...
663,102467,YOFI,2021,0.0,0,France,Europe,1.105900e+05,1,1
664,128294,Yeastup,2022,0.0,0,Switzerland,Europe,8.188603e+05,1,1
665,128294,Yeastup,2024,0.0,0,Switzerland,Europe,1.916627e+07,2,2
666,12254,Yumgo,2022,0.0,0,France,Europe,1.500000e+06,1,1
667,12254,Yumgo,2024,0.0,0,France,Europe,6.000000e+06,2,2